rule example_23_7_1:
    input:
        "Calculations/example_23_7_1/results.csv"

rule example_23_7_1_matlab:
    input:
        "Calculations/example_22_5_1/cum_age_dist_fcn.csv",
        "Calculations/example_23_7_1/example_23_7_1.m"
    output:
        "Calculations/example_23_7_1/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_23_7_1');example_23_7_1;exit"
        """
