project:
  type: book

book:
  title: "Reaction Engineering Basics"
  author: "Carl R. F. Lund"
  date: today
  date-format: long
  cover-image: 'Graphics/RE_Basics_Cover.png'
  reader-mode: true
  favicon: Graphics/BuffaloBadger_16_16.png
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "Graphics/Banner.png"
    logo-href: http://buffalobadger.github.io
    search: true
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: http://buffalobadger.github.io/SCoRE
      - text: "ToTaL Engineering"
        href: http://buffalobadger.github.io/ToTaL_Engineering
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html 
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
       - section_1_intro_safety_ethics.qmd
       - section_1_rxns_reactors.qmd
       - section_1_reaction_progress.qmd
    - part: "Rate Expressions"
      chapters:
        - section_2_rates_and_expressions.qmd
        - section_2_mechanisms.qmd
    - part: "Reaction Engineering Analysis"
      chapters:
        - section_3_react_eng_models.qmd
        - section_3_reaction_engineering_tasks.qmd 
        - section_3_formulating_calcs.qmd
    - part: "Modeling Ideal Reactors"
      chapters:
        - section_4_bstr_analysis.qmd
        - section_4_sbstr_analysis.qmd
        - section_4_non_continuous_design.qmd
        - section_4_cstr_analysis.qmd
        - section_4_pfr_analysis.qmd
        - section_4_continuous_design.qmd
    - part: "Modeling Ideal Reactor Systems"
      chapters:
       - section_5_reactor_networks.qmd
       - section_5_thermally_backmixed_pfr.qmd
       - section_5_recycle_pfr.qmd
    - part: "Kinetics Data Analysis"
      chapters:
        - section_6_data_generation.qmd
        - section_6_bstr_data_analysis.qmd
        - section_6_cstr_data_analysis.qmd
        - section_6_pfr_data_analysis.qmd
    - part: "Modeling Non-Ideal Reactors"
      chapters:
        - section_7_age_function.qmd
        - section_7_segregated_flow_model.qmd
        - section_7_axial_dispersion_model.qmd
        - section_7_zoned_model.qmd
    - references.qmd
  appendices:
    - apndx_prereq_knowledge.qmd
    - apndx_nomenclature.qmd
    - apndx_reaction_thermo.qmd
    - apndx_kinetics_theories.qmd
    - apndx_derivations.qmd
    - apndx_mathematics.qmd
    - apndx_useful_eqns.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



