project:
  type: book

book:
  title: "Reaction Engineering Basics"
  author: "Carl R. F. Lund"
  date: "8/27/2022"
  cover-image: 'Graphics/RE_Basics_Cover.png'
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "Graphics/Banner.png"
    logo-href: buffalobadger.github.io
    search: true
    left:
      - text: "ToTaL PS"
        href: buffalobadger.github.io/total_ps.html
      - text: "Reaction Engineering Basics"
        href: "index.html"
#      - text: "SCoRE"
#        href: doh
#      - text: "The Sett"
#        href: doh
      - text: "About"
        href: buffalobadger.github.io/about.html
  chapters:
    - index.qmd
    - part: section_1_intro.qmd
      chapters: 
       - reactions-reactors-reaction-eng.qmd
       - reaction-eng-safety-ethics.qmd
       - reaction-progress.qmd
    - part: rate-expressions.qmd
      chapters:
        - reaction-rates-expressions.qmd
        - mechanisms-mechanistic-rate-expressions.qmd
    - part: reactor-response-models.qmd
      chapters: 
        - modeling-ideal-reactors.qmd
        - structure-of-response-models.qmd
    - part: kinetics-data-analysis.qmd
      chapters:
      - kinetics-data-generation.qmd
      - analysis-bstr-kinetics-data.qmd
      - analysis-cstr-kinetics-data.qmd
      - analysis-pfr-kinetics-data.qmd
    - part: model-isolated-ideal-reactors.qmd
      chapters:
        - response-optimization-design.qmd
        - bstr-analysis.qmd
        - sbstr-analysis.qmd
        - design-non-continuous-reactors.qmd
        - cstr-analysis.qmd
        - pfr-analysis.qmd
        - design-continuous-reactors.qmd
    - part: model-ideal-systems.qmd
      chapters:
       - reactor-networks.qmd
       - thermally-backmixed-pfrs.qmd
       - recycle-pfrs.qmd
    - part: model-isolated-non-ideal-reactors.qmd
      chapters:
        - axial-dispersion-model.qmd
        - segregated-flow-model.qmd
        - zoned-model.qmd
    - references.qmd
  appendices:
    - prerequisite-knowledge.qmd
    - nomenclature.qmd
    - reaction-thermo.qmd
    - reactor-heat-exchange.qmd
    - collision-theory.qmd
    - transition-state-theory.qmd
    - ideal-reactor-models.qmd
    - numerical-solution-ates.qmd
    - numerical-solution-ivodes.qmd
    - numerical-parameter-estimation.qmd
    - numerical-solution-bvodes.qmd
    - numerical-solution-daes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{cancel}



