project:
  type: book

book:
  title: "Reaction Engineering Basics"
  author: "Carl R. F. Lund"
  date: today
  date-format: long
  cover-image: 'Graphics/RE_Basics_Cover.png'
  reader-mode: true
  favicon: Graphics/BuffaloBadger_16_16.png
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "Graphics/Banner.png"
    logo-href: http://buffalobadger.github.io
    search: true
    left:
      - text: "REB, The Book"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "REB, The Course"
        href: http://buffalobadger.github.io/RE_Basics_Course
      - text: "REB, The Design"
        href: http://buffalobadger.github.io/RE_Basics_Design
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html 
  chapters:
    - index.qmd
    - rxn_eng_ethics_safety.qmd
    - rxns_stoichiometry.qmd
    - rates_rate_expressions.qmd
    - mech_rate_expressions.qmd
    - reactor_analysis.qmd
    - cstr_analysis.qmd
    - bstr_analysis.qmd
    - sbstr_analysis.qmd
    - pfr_analysis.qmd
    - design_reactors.qmd
    - gen_anal_kin_data.qmd
    - reactor_networks.qmd
    - empir_non_ideal_reactors.qmd
    - references.qmd
  appendices:
    - apx_notation_terminology.qmd
    - apx_kinetics_theories.qmd
    - apx_reactor_design_eqns.qmd
    - apx_numerical_methods.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3



