project:
  type: book

book:
  title: "Reaction Engineering Basics"
  author: "Carl R. F. Lund"
  date: "8/27/2022"
  cover-image: 'Graphics/RE_Basics_Cover.png'
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "Graphics/Banner.png"
    logo-href: buffalobadger.github.io
    search: true
    left:
      - text: "ToTaL PS"
        href: buffalobadger.github.io/total_ps.html
      - text: "Reaction Engineering Basics"
        href: "index.html"
#      - text: "SCoRE"
#        href: doh
#      - text: "The Sett"
#        href: doh
      - text: "About"
        href: buffalobadger.github.io/about.html
  chapters:
    - index.qmd
    - part: section_1_intro.qmd
      chapters: 
       - section_1_intro_and_defs.qmd
       - section_1_safety_and_ethics.qmd
       - section_1_reaction_progress.qmd
    - part: section_2_intro.qmd
      chapters:
        - section_2_rates_and_expressions.qmd
        - section_2_mechanisms.qmd
    - part: section_3_intro.qmd
      chapters: 
        - section_3_design_equations.qmd
        - section_3_response_function.qmd
    - part: section_4_intro.qmd
      chapters:
      - section_4_data_generation.qmd
      - section_4_bstr_data_analysis.qmd
      - section_4_cstr_data_analysis.qmd
      - section_4_pfr_data_analysis.qmd
    - part: section_5_intro.qmd
      chapters:
        - response-optimization-design.qmd
        - bstr-analysis.qmd
        - sbstr-analysis.qmd
        - design-non-continuous-reactors.qmd
        - cstr-analysis.qmd
        - pfr-analysis.qmd
        - design-continuous-reactors.qmd
    - part: section_6_intro.qmd
      chapters:
       - reactor-networks.qmd
       - thermally-backmixed-pfrs.qmd
       - recycle-pfrs.qmd
    - part: section_7_intro.qmd
      chapters:
        - axial-dispersion-model.qmd
        - segregated-flow-model.qmd
        - zoned-model.qmd
    - references.qmd
  appendices:
    - apndx_prereq_knowledge.qmd
    - apndx_nomenclature.qmd
    - apndx_reaction_thermo.qmd
    - apndx_heat_exchange.qmd
    - apndx_collision_theory.qmd
    - apndx_transition_state_theory.qmd
    - apndx_ideal_reactor_models.qmd
    - apndx_solve_ates.qmd
    - apndx_solve_ivodes.qmd
    - apndx_estimate_parameters.qmd
    - apndx_solve_bvodes.qmd
    - apndx_solve_daes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{cancel}



