project:
  type: book

book:
  title: "Reaction Engineering Basics"
  author: "Carl R. F. Lund"
  date: "8/11/2023"
  cover-image: 'Graphics/RE_Basics_Cover.png'
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: "Graphics/Banner.png"
    logo-href: http://buffalobadger.github.io
    search: true
    left:
      - text: "ToTaL PS"
        href: http://buffalobadger.github.io/total_ps.html
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
#      - text: "SCoRE"
#        href: doh
#      - text: "The Sett"
#        href: doh
      - text: "About"
        href: http://buffalobadger.github.io/about.html
  chapters:
    - index.qmd
    - part: section_1_intro.qmd
      chapters: 
       - section_1_intro_and_defs.qmd
       - section_1_safety_and_ethics.qmd
       - section_1_reaction_progress.qmd
    - part: section_2_intro.qmd
      chapters:
        - section_2_rates_and_expressions.qmd
        - section_2_mechanisms.qmd
    - part: section_3_intro.qmd
      chapters: 
        - section_3_design_equations.qmd
        - section_3_response_function.qmd
    - part: section_4_intro.qmd
      chapters:
      - section_4_data_generation.qmd
      - section_4_bstr_data_analysis.qmd
      - section_4_pfr_data_analysis.qmd
      - section_4_cstr_data_analysis.qmd
    - part: section_5_intro.qmd
      chapters:
        - section_5_reaction_engineering_tasks.qmd
        - section_5_bstr_analysis.qmd
        - section_5_sbstr_analysis.qmd
        - section_5_non_continuous_design.qmd
        - section_5_cstr_analysis.qmd
        - section_5_pfr_analysis.qmd
        - section_5_continuous_design.qmd
    - part: section_6_intro.qmd
      chapters:
       - section_6_reactor_networks.qmd
       - section_6_thermally_backmixed_pfr.qmd
       - section_6_recycle_pfr.qmd
    - part: section_7_intro.qmd
      chapters:
        - section_7_axial_dispersion_model.qmd
        - section_7_segregated_flow_model.qmd
        - section_7_zoned_model.qmd
    - references.qmd
  appendices:
    - apndx_prereq_knowledge.qmd
    - apndx_nomenclature.qmd
    - apndx_reaction_thermo.qmd
    - apndx_heat_exchange.qmd
    - apndx_collision_theory.qmd
    - apndx_transition_state_theory.qmd
    - apndx_ideal_reactor_models.qmd
    - apndx_solve_ates.qmd
    - apndx_solve_ivodes.qmd
    - apndx_estimate_parameters.qmd
    - apndx_solve_bvodes.qmd
    - apndx_solve_daes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



