# Reaction Thermodynamics {#sec-reaction-thermo}

This appendix provides an abbreviated overview of the calculation of heats of reaction, equilibrium constants and equilibrium composition.

## Heats of Reaction

The heat of reaction appears in the energy balances for the ideal reactors considered in *Reaction Engineering Basics*. The heat of reaction also changes with temperature. As such, it is essential that students know how to calculate the heat of reaction at any given temperature.

The heat, $\Delta H_j$, of an arbitrary reaction, $j$, is defined as the change in enthalpy when stoichiometric amounts of the reactants in reaction $j$ are **completely** converted to stoichiometric amounts of the products of the reaction. This is true, even if the equilibrium conversion for reaction $j$ is less than 100%. The heat of reaction does not depend upon the conversion, it is defined in terms of complete conversion.

If heat is released when reaction $j$ occurs, reaction $j$ is said to be an *exothermic* reaction, and $\Delta H_j$ will be negative. Conversely, if heat is consumed when reaction $j$ occurs, reaction $j$ is said to be an *endothermic* reaction, and $\Delta H_j$ will be positive.

The units of the heat of reaction are energy per mole. The "mole" in the units is a mole of extent of reaction for the reaction, as written.

Typically, the calculation of the heat of reaction proceeds in two steps. First, the standard heat of reaction at 298 K is calculated. Then that result is used to calculate the heat of reaction at any other temperature. The next two sub-sections describe these two steps.

### The Standard Heat of Reaction at 298 K

The *standard heat of formation* at 298 K of some species, $i$, $\Delta H_{f,i}^0 \Bigr\rvert_{T=298K}$, is the heat of the reaction in which one mole of species $i$ (in its standard state) is synthesized at 298 K from the elements that it comprises (in their standard states). Standard heats of formation of many reagents at 298 K are tabulated in various handbooks; selected lists often appear in thermodynamics textbooks, too. Tables of this type should indicate the standard state that has been used for species $i$ and each of the elements.

The widespread availability of tables containing standard heats of formation is important because the standard heat of any reaction, $j$, at 298 K can be calculated from the standard heats of formation of the reactants and products in reaction $j$. Specifically, @eq-deltaH-298-form is used to calculate the standard heat of reaction $j$ from the standard heats of formation of its reactants and products. @eq-deltaH-298-form uses the *Reaction Engineering Basics* sign convention wherein the stoichiometric coefficients of reactants are negative and the stoichiometric coefficients of products are positive.

$$
\Delta H_j^0\Bigr\rvert_{T=298K} = \sum_i \left( \nu_{i,j} \Delta H_{f,i}^0\Bigr\rvert_{T=298K} \right)
$$ {#eq-deltaH-298-form}

An alternative to using standard heats of formation is to use the *standard heat of combustion* of the reactants and products at 298 K. The standard heat of combustion at 298 K of some species $i$, $\Delta H_{c,i}^0 \biggr\rvert_{T=298K}$, is the heat of the reaction in which species $i$ is completely oxidized by O~2~ at 298 K, usually producing CO~2~ and H~2~O~(l)~, and with all species in their standard states. Standard heats of combustion are tabulated in handbooks and textbooks, just as standard heats of formation are. Standard heats of combustion are particularly convenient for use with hydrocarbons. If reagent $i$ contains elements other than C, O and H, the table providing the value of the standard heat of combustion should indicate the additional combustion products and their standard states. @eq-deltaH-298-comb is used to calculate the standard heat of reaction $j$ from the standard heats of combustion of its reactants and products.

$$
\Delta H_j^0\Bigr\rvert_{T=298K} = \sum_i \left( -\nu_{i,j} \Delta H_{c,i}^0\Bigr\rvert_{T=298K} \right)
$$ {#eq-deltaH-298-comb}

### The Standard Heat of Reaction at Temperature T

*Assuming none of the reactants and products in reaction $j$ undergo a phase change between 298 K and T*, the standard heat of reaction $j$ at arbitrary temperature, $T$, can be calculated using @eq-deltaH-T. If one of the reagents does undergo a phase change, the latent heat for that phase change would need to be included in the equation.

$$
\Delta H_j^0 = \Delta H_j^0\Bigr\rvert_{T=298K} + \sum_i \left( \nu_{i,j} \int_{298\text{ K}}^T \hat C_{p,i}dT \right)
$$ {#eq-deltaH-T}

## Adiabatic Temperature

Consider an exothermic chemical reaction that takes place adiabatically in a system with no shafts or moving boundaries. Since there are no shafts or moving boundaries, no energy enters or leaves the system in the form of work. As the exothermic reaction takes place, the standard heat of reaction is released. It cannot leave the system because it is an adiabatic process. Consequently, the heat released by the exothermic reaction is converted into internal molecular energy. From a macroscopic perspective the result is that the temperature of the system increases. That is, the heat released by the reaction is used to raise the temperature of the reacting system. This assumes that no phase changes occur as the reaction takes place.

When the reaction process ends, the system will be at a new temperature that is sometimes referred to as the adiabatic temperature. In the case of an exothermic reaction, this temperature will be greater than the starting temperature, and the change in temperature is referred to as the adiabatic temperature rise. For an endothermic reaction the system temperature would decrease, resulting in an adiabatic temperature drop. For the remainder of this discussion, we can generalize by simply referring to the adiabatic temperature change, noting that if the reaction is exothermic it will be a rise and if the reaction is endothermic it will be a drop.

Notice that one doesn’t need to know anything about the container holding the system, i. e. the reactor, other than it operates adiabatically and without any shafts or moving boundaries. The adiabatic temperature can be computed using only thermodynamic quantities. Typically in reaction engineering, the goal is to calculate the adiabatic temperature change given the starting composition and temperature and the final composition. Knowing the initial and final amounts of the reagents, it is possible to calculate the apparent extents (see @sec-reaction-progress) of a complete mathematically independent subset of the reactions occurring in the system. The essential concept when calculating the adiabatic temperature is that the heat released or absorbed by reaction must just equal the change in the sensible heat of the reagents.

Enthalpy is a state function, so it is not necessary to perform the calculations using the exact path followed by the reacting system. Any path that starts at the same initial conditions and ends at the same final conditions can be used. For analysis purposes, it is convenient to use a pathway where the reactions first occur isothermally at the initial temperature and then the resulting product mix is heated (or cooled) to the final temperature. The net $\Delta H$ for the two steps is then set equal to zero, giving an implicit equation for the final, adiabatic temperature as shown in @eq-adiabatic_temperature which assumes that no phase changes occur as the reaction takes place.

$$
\sum_{j^\prime} \xi_{j^\prime}\left( - \Delta H_{j^\prime}\Big \vert_{T_0} \right) = \sum_i \int_{T_0}^{T_{ad}} \hat C_{p,i} \left( n_{i,0} + \nu_{i,j^\prime} \xi_{j^\prime} \right)dT
$$ {#eq-adiabatic_temperature}

| $\qquad$ where $j^\prime$ indexes the reactions in a complete, mathematically
| $\qquad \qquad$ independent subset of the reactions ocurring in the system.

Given only the initial amounts of the reagents and the requisite thermodynamic data, @eq-adiabatic_temperature provides a relationship between the final temperature and the extents of reaction.

## Equilibrium Constants

Equilibrium constants can appear in rate expressions, and their value changes with temperature. As such, it is important that students know how to calculate equilibrium constants at any given temperature. The calculation of an equilibrium constant at temperature, $T$, proceeds in four steps.

To calculate the equilibrium constant for reaction $j$, it is first necessary to calculate the standard Gibbs free energy change of reaction $j$ at 298 K, $\Delta G_j^0 \Bigr\rvert_{T=298K}$. Like standard heats of formation at 298 K, standard Gibbs free energies of formation at 298 K, $\Delta G_{f,i}^0 \Bigr\rvert_{T=298K}$, of many reagents, $i$, are tabulated in various handbooks and textbooks. They can be used to calculate the Gibbs free energy change for reaction $j$ at 298 K using @eq-deltaG-298.

$$
\Delta G_j^0\Bigr\rvert_{T=298K} = \sum_i \left( \nu_{i,j} \Delta G_{f,i}^0\Bigr\rvert_{T=298K} \right)
$$ {#eq-deltaG-298}

Knowing the standard Gibbs free energy of reaction $j$ at 298K, the equilibrium constant *at 298 K* for reaction $j$ can be calculated using @eq-K-298.

$$
K_j \Bigr\rvert_{T=298K} = \exp{ \left( \frac{-\Delta G_j^0\Bigr\rvert_{T=298K}}{R(298\text{ K})} \right)}
$$ {#eq-K-298}

To calculate the equilibrium constant at any other temperature, an expression for the standard heat of reaction $j$ as a function of temperature must next be generated. This can be done using @eq-deltaH-298-form or @eq-deltaH-298-comb together with @eq-deltaH-T as described above.

The equilibrium constant for reaction $j$ at any temperature then can be calculated using @eq-K-T.

$$
K_j  = K_j \Bigr\rvert_{T=298K} \exp{\left\{ \frac{1}{R} \int_{298K}^T\frac{\Delta H_j^0}{T^2}dT \right\}}
$$ {#eq-K-T}

## Equilibrium Composition

Knowing the initial composition of a system, the reactions taking place, the final temperature and, for gases, the final pressure, the equilibrium composition of the system can be calculated. Doing this won't be necessary in *Reaction Engineering Basics*, but it is an important skill that a reaction engineer needs. It can be important in the early stages of designing a reactor system and whenever reaction engineering tasks involve reversible reactions.

The reactions taking place in the system may not be mathematically independent. The first step in calculating the equilibrium composition of a system is to identify a complete, mathematically independent subset of the reactions taking place. [Appendix -@sec-pre-knowledge] includes a section that describes how to do so. Here, for convenience, the reactions in the complete mathematically independent subset of the reactions taking place will simply be referred to as "the independent reactions."

Having identified the independent reactions, an equilibrium expression, @eq-equil-expr, can be written for each of them.

$$
K_{j^\prime} = \prod_i a_i^{\nu_{i,j^\prime}}
$$ {#eq-equil-expr}

| $\qquad$ where $j^\prime$ indexes the reactions in a complete, mathematically
| $\qquad \qquad$ independent subset of the reactions ocurring in the system.

The thermodynamic activity, $a_i$, of each species, $i$,  in the equilibrium expressions can be related to the composition. For an ideal liquid solution, the activity is simply equal to the mole fraction, @eq-liq-activity. For an ideal gas, the activity is the partial pressure divided by the standard state of 1 atm, @eq-gas-activity.

$$
a_i = x_i \quad \text{(ideal liquid solution)}
$$ {#eq-liq-activity}

$$
a_i = \frac{P_i}{1 \text{ atm}} = \frac{y_iP}{1 \text{ atm}} \quad \text{(ideal gas)}
$$ {#eq-gas-activity}

Finally, the mole fractions can be expressed in terms of the apparent extents of the independent reactions. For example the gas phase mole fraction of reagent $i$ in a closed system would be written as shown in @eq-y-in-terms-of-xi. Similar equations are used for liquid phase systems (where $x_i$ is used instead of $y_i$) and for open, steady-state systems (where $\dot n_i$, $\dot n_{i,in}$ and $\dot \xi$ are used instead of $n_i$, $n_{i,0}$ and $\xi$).

$$
y_i = \frac{n_i}{\displaystyle \sum_i n_i} = \frac{n_{i,0} + \displaystyle \sum_{j^\prime}\nu_{i,j^\prime}\xi_{j^\prime}}{\displaystyle \sum_i \left( n_{i,0} + \sum_{j^\prime}\nu_{i,j^\prime}\xi_{j^\prime}\right)}
$$ {#eq-y-in-terms-of-xi}

| $\qquad$ where $j^\prime$ indexes the reactions in a complete, mathematically
| $\qquad \qquad$ independent subset of the reactions ocurring in the system.

If $N$ is the number of independent reactions, then after substitution for the activities and mole fractions as just described, @eq-equil-expr can be used to write a set of $N$ equilibrium expressions containing $N$ unknown apparent extents of reaction. Those equations can be solved to find the equilibrium extents of reaction which, in turn, can be used to calculate the equilibrium mole fractions or any other measure of the equilibrium composition.

## Symbols Used in this Appendix

| Symbol | Meaning |
|:-------|:--------|
| $a_i$ | Thermodynamic activity of reagent $i$. |
| $i$ | as a subscript, denotes a specific reagent present in the system.\
as a summation or continuous product index, indexes all reagents present in the system. |
| $j$ | subscript denoting a specific reaction occurring in the system. |
| $j^\prime$ | As a subscript, denotes a specific reaction from a complete, mathematically independent subset of the reactions occurring in the system.\
As a summation or continuous product index, indexes the reactions that constitute a complete, mathematically independent subset of the reactions occurring in the system. |
| $n_i$ | Moles of reagent $i$; an additional subscripted $0$ indicates the initial moles of reagent $i$. |
| $\dot n_i$ | Molar flow rate of reagent $i$; an additional subscripted $in$ indicates the inlet molar flow rate of reagent $i$. |
| $x_i$ | Liquid phase mole fraction of reagent $i$. |
| $y_i$ | Gas phase mole fraction of reagent $i$. |
| $\hat C_{p,i}$ | Molar heat capacity at constant pressure of reagent $i$. |
| $K_j$ | Equilibrium constant for reaction $j$. |
| $P$ | Pressure. |
| $P_i$ | Partial pressure of reagent $i$. |
| $R$ | Ideal gas constant. |
| $T$ | Temperature. |
| $\nu _{i,j}$ | Stoichiometric coefficient of reagent $i$ in reaction $j$. |
| $\xi _j$ | Apparent extent of reaction $j$. |
| $\dot \xi _j$ | Apparent extent of reaction $j$ in an open steady-state system. |
| $\Delta G_{f,i}^0$ | Standard Gibbs free energy of formation of reagent $i$. |
| $\Delta G_j^0$ | Standard Gibbs free energy change for reaction $j$. |
| $\Delta H_{c,i}^0$ | Stardard heat of combustion of reagent $i$. |
| $\Delta H_{f,i}^0$ | Standard heat of formation of reagent $i$. |
| $\Delta H_j$ | Heat of reaction $j$; a superscripted $0$  indicates the standard heat of reaction. |

: {tbl-colwidths="[20,80]"}
