# Prerequisite Knowledge {#sec-apndx_pre_knowledge}

*Reaction Engineering Basics* assumes that students have acquired certain knowledge and skills previously and have the ability to do the things listed here.

## General Problem-Solving

* Identify *intensive* quantities. These are quantities that do not fix the size of the system. Examples inlcude pressure, partial pressure, mole fraction, concentration, temperature, etc.
* Identify *extensive* quantities. These are quantities that fix the size of the system. Examples include moles, molar flow rate, mass, mass flow rate, volume, volumetric flow rate, etc.
* Know that if a problem provides *only* intensive quantities, the value of one extensive variable may be choses as a *basis for the calculations*.

## Algebra

* Rearrange equations using the basic rules and properties of algebra.
* Factor, reduce and add algebraic fractions.
* Manipulate logarithms and exponentials.
* Combine two equations by elimination of a variable common to both.
* When it is possible, analytically solve $N$ equations to obtain expressions for $N$ unknowns.
* Numerically solve sets of algebraic-transcendental equations.
    * A brief overview of the numerical solution of sets of algebraic-transcendental equations is presented in [Appendix -@sec-solving-ates].

## Calculus

* Evaluate definite and indefinite integrals analytically and numerically (see below for a brief overview of numerical integration).
* Differentiate a function analytically and numerically (see below for a brief overview of numerical differentiation).

### Numerical Integration

* Given a vector containing $N$ values of the independent variable, $x$
* The trapezoid rule is one of several ways to numerically integrate a function, $f\left(x\right)$, over the interval from $x_1$ to $x_N$.

$$\int_{x_1}^{x_N} f(x)dx \approx \sum_{k=1}^{N-1} \left[ \frac{1}{2} \left( f_k + f_{k+1} \right) \left( x_{k+1} - x_k \right) \right]$$

### Numerical Differentiation

* Given
    * A vector containing $N$ values of the independent variable, $x$
    * A vector containing the corresponding $N$ values of the dependent variable, $y$
* The derivative, $\frac{dy}{dx}$ corresponding to the $k^{th}$ element in the vectors can be approximated numerically using
    * Backward differences: $\frac{dy}{dx}\Bigr\rvert_{k} \approx \frac{y_{k} - y_{k-1}}{x_{k} - x_{k-1}}$
    * Forward differences: $\frac{dy}{dx}\Bigr\rvert_{k} \approx \frac{y_{k+1} - y_{k}}{x_{k+1} - x_{k}}$
    * Central differences: $\frac{dy}{dx}\Bigr\rvert_{k} \approx \frac{1}{2} \left( \frac{y_{k+1} - y_{k}}{x_{k+1} - x_{k}} + \frac{y_{k} - y_{k-1}}{x_{k} - x_{k-1}} \right)$

## Differential Equations

* Understand what it means to "solve" a differential equation.
* Understand what initial conditions and boundary conditions are.
* Analytically solve a first order, initial-value ODE by separation of variables.
* Numerically solve a set of coupled, initial-value ODEs.
    * A brief overview of the numerical solution of sets of coupled, initial-value ODEs is presented in [Appendix -@sec-solving-ivodes].
* Numerically solve a non-singular set of coupled, boundary-value ODEs.
    * A brief overview of the numerical solution of sets of non-singular, coupled, boundary-value ODEs is presented in [Appendix -@sec-solving-bvodes].

## Linear Algebra

* Know the difference between linear and non-linear equations.
* Write equations in vector and matrix form.
* Multiply scalars, vectors and matrices.
* Understand what the rank of a matrix is.
* Given a set of reactions or linear equations, identify a complete mathematically independent subset of those reactions or equations (see below for a brief overview of identifying mathematically independent linear equations).

### Identifying Mathematically Independent Linear Equations.

In a *mathematically independent set of linear equations*, none of the equations in the set can be expressed as a linear combination of the other equations in the set.

Given a set of equations (or chemical reactions), one or more *complete, mathematically independent subsets* can be identified such that **none** of the equations/reactions **in** the subset can be expressed as a linear combination of the other equations in the subset, *and* **all** of the equations **not in** the subset can be expressed as a linear combination of the equations/reactions in the subset.

A complete, mathematically independent subset of a set of chemical reactions can be found as follows.

* Create an empty *working* matrix where each row will represents a reagent that appears either as a reactant or as a product in the reaction set.
* Add the first reaction in the full set of reactions to the working matrix by creating a column for that reaction. In each row in that column, insert the stoichiometric coefficient of the species corresponding to that row.
* Successively for each remaining reaction:
    * Create a *test* matrix by adding an additional column for the next remaining reaction to the working matrix.
    * Calculate the rank of the test matrix
    * If the rank of the test matrix equals the number of reactions (columns) in the test matrix, use the test matrix as the new working matrix, otherwise discard the test matrix.
* After all reactions have been processed, the columns in the resulting working matrix will correspond to a complete, mathematically independent subset.
    * There could be other complete, mathematically independent subsets.

## Statistics and Probability

* Understand what means, standard deviations and 95% confidence intervals are and be able to calculate them.
* Understand what probabilities are.
* Calculate expectation values using a probability density function (see below for a brief overview).

### Probability Density Functions

* A probability density function, $p_X\left(z\right)$, for a random variable, $X$, spans the range of possible values of that variable.
* At any value of $z$, the value of the probability density function, $p_X \left(z\right)$, when multiplied by a differential portion of the range, $dz$, equals the probability that a single observation of $X$ will fall in the range between $z$ and $z + dz$.
* A probability density function must satisfy two conditions
    $$p_X\left(z\right) >0 \quad \text{for} \quad -\infty \lt z \lt \infty$$
    $$\int_{-\infty }^{\infty } p_X(z)dz = 1$$
* The average (expectation) value of any quantity, $a$, that is functionally dependent upon the random variable, $X$, can be calculated using the probability density function.
    $$a=f(X) \text{ and } X\sim p_X(z) \quad \Rightarrow \quad \left\langle a \right\rangle = \int_{-\infty}^{\infty}f(z)p_X(z)dz$$

## Fluids and Fluid Mixtures

* Understand and use the ideal gas and ideal liquid equations of state.
* Understand and use composition variables such as mole fractions, concentrations and partial pressures.
* Understand fluid flow and pressure drop in pipes.

## Reaction Thermodynamics

* Understand the meaning of and difference between latent and sensible heats and be able to calculate them.
* Understand heat of reaction and be able to generate and use an equation to calculate it.
    * A brief overview of calculating heats of reaction is presented in [Appendix -@sec-reaction-thermo].
* Understand chemical reaction equilibrium and be able to generate and use equations to calculate equilibrium constants and equilibrium composition at any temperature.
    * A brief overview of equilibrium calculations is presented in [Appendix -@sec-reaction-thermo].
    
## Heat Transfer

* Understand heat transfer coefficients and heat transfer area and be able to use them to calculate the rate of heat transfer.
    * A brief overview of selected ways to transfer heat to or from chemical reactors is presented in [Appendix -@sec-reactor-heat-transfer].

## Chemical Processes

* Know how to write and use mass and energy balances on components of simple chemical processes including
    * flow stream splitting points
    * flow stream mixing points
    * heat exchangers
* Know how to use mass and energy balance equations on the components of a simple chemical process to model that process.

### Classification of Chemical Processes

There are a number of different ways to classify or describe chemical processes. Students should be familiar with the following terms used to describe chemical processes.

* Adiabatic - no energy is added to or removed from the system while the process occurs, other than that associated with input and output material flow streams.
* Isothermal - the temperature throughout the system is uniform (the same everywhere) and constant while the process occurs.
* Isobaric - the pressure throughout the system is uniform and constant while the process occurs.
* Isochoric - the system volume is constant while the process occurs.
* Steady-state - the temperature, pressure and chemical composition are all constant over time at each location in the system.
* Transient - the temperature, pressure or chemical composition vary with time at one or more locations in the system.

## Computation

Students using *Reaction Engineering Basics* should have access to and be able to use software for numerical computation to perform the tasks listed below.

* Routine calculations.
* Reading data from files or entering data manually.
* Displaying data on screen as text, printing it or saving it to a file.
* Plotting data.
* Performing parameter estimation with non-linear models.
    * A brief overview of parameter estimation and model assessment is presented in [Appendix -@sec-parameter-est].
* Solving algebraic-transcendental equations.
    * A brief overview of the numerical solution of sets of algebraic-transcendental equations is presented in [Appendix -@sec-solving-ates].
* Solving initial value ordinary differential equations.
    * A brief overview of the numerical solution of  sets of coupled, initial-value ODEs is presented in [Appendix -@sec-solving-ivodes].
* Solving boundary value ordinary differential equations
    * A brief overview of the numerical solution of sets of non-singular, coupled, boundary-value ODEs is presented in [Appendix -@sec-solving-bvodes].

## Symbols Used in this Appendix

With one exception, all of the symbols used in this appendix have no special meaning and won't be listed here. For example, in this chapter $f\left( x \right)$ is used to denote some generic function, $f$, that is functionally dependent on the generic variable, $x$. Neither $f$ nor $x$ has any special meaning attached to it. The one exception is the probability density function.

| Symbol | Meaning |
|:-------|:--------|
| $p_X\left(z\right)$ | Probability density function for the random variable, $X$.  |

: {tbl-colwidths="[20,80]"}

