# Design of Reactors {#sec-ch10}











[Chapter -@sec-3_react_eng_tasks] describes and differentiates between response, optimization, and design tasks. @sec-4_bstr_analysis and @sec-4_sbstr_analysis examine the modeling of two kinds of non-continuous, ideal reactors: BSTRs and SBSTRs. They illustrate the use of the reactor design equations for those non-continuous reactors to complete reaction engineering assignments involving response and optimization tasks. This chapter introduces design tasks for non-continuous ideal reactors.

Reactor design is an advanced aspect of reaction engineering. This chapter is a very basic introduction to reactor design. Its intent is to make the reader aware that many reaction engineering assignments are open-ended and do not have a single "correct" answer like those considered in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis]. Unlike those assignments, reactor design assignments can provide opportunities for a reaction engineer to be very creative and not simply follow some "cookie-cutter" approach to completing assignments. They can lead to discovery of innovative ways to operate reactors and the invention of new kinds of reactors.

## Design Principles and Scale

Design assignments can vary in scale from design of a single reactor to design of an entire process. There are principles that should guide the design no matter the scale. Among the more important principles, the process should be safe to operate, it should comply with all governmental regulations, it should not have unfavorable or unjust environmental and societal impacts, and it should be profitable.

Chemical reactors are virtually always one part of a larger process. At the largest scale, reactive process design starts with a decision to build a process from scratch. The decision to do this would be informed by some number of preliminary analyses of the market for the products from the process, the economic potential of the process, the technical feasibility of the process, etc. Full reactive process design will involve a team comprising members with expertise in finance, planning, procurement, law, construction, chemistry, engineering, safety, etc. The members with engineering expertise would include a reaction engineer among other engineering specializations such as process design, separations, control, heating and cooling, etc.

Some of the economic factors that must be evaluated as part of the process design are capital costs (one time expenses to purchase the necessary equipment, etc.), operating costs (including labor, utilities, feedstock costs, waste disposal, etc.), maintenance costs, licensing costs (e. g. royalties for use of patented technology), income the process will generate and the return on investment. Business and legal activities include choosing the site for the process, securing necessary permits, licensing any necessary technology, identifying all regulatory restrictions that apply to the process, purchasing the equipment as specified by the design engineers, and others. The engineering team lays out the piping and processing equipment and designs the individual components, making sure that they are all properly and efficiently integrated. Specific tasks that a reaction engineer would be involved in include selecting the type of reactor(s) to be used, sizing the reactor(s) and specifying operational prameters (heating and cooling, feed temperature and composition, etc.), specifying turn-around tasks and timing for non-continuous processes, and developing procedures for start-up, operation, shut-down, and various possible emergencies.

Participation in a full reactive process design of the kind just described requires much deeper knowledge of reaction engineering and much more reaction engineering experience than most readers of this book are likely to possess. **Preliminary design involves a more limited scope**. A preliminary reactor design might be one of the factors that go into the decision to build the full process. This chapter considers preliminary design that only includes the reactor.

## Preliminary Reactor Design

A review of the examples in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] will reveal that simply analyzing a reactor requires a relatively shallow level of understanding of reactor performance and a relatively low level of thinking. That is, if one learns how to generate and simplify the reactor design equations for a given system along with some important definitions, modeling the reactor always follows the same general steps. (Write and simplify the design equations, specify the initial and final values, write ancillary equations needed to evaluate the derivatives at the start of an integration step, write ancillary equations to calculate the initial and final values, solve the reactor design equations, and write ancillary equations and use them to calculate any other quantities of interest.) When one has that minimum level of knowledge and knows the steps to follow to solve the design equations, response and optimization tasks can be completed without too much additional thought or understanding.

Looking at the discussion that follows many of the examples in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis], and particularly at the qualitative analyses, reveals a deeper level of understanding and a higher level of thinking. At that level, physical explanations for observed phenomena are sought and developed. That is, those discussions seek to *explain* in physical (not mathematical) terms why a graph has a given shape or passes through a minimum or maximum, or why increasing the inlet temperature or inlet flow rate affects the output in the way that it does. It requires deeper knowledge (e. g. what factors can cause temperature or reaction rate to change) and higher level of thinking (e. g. which of those factors are at play or important at a given point in the process; how will the importance of those factors change over the course of processing; how are those factors related to the reactor inputs).

It can be argued that reactor design requires an even deeper level of understanding of reactor performance and an eveh higher level of thinking. During reactor design the reaction engineer isn't trying to explain an observed reactor response. Rather, the engineer needs to *predict* how to cause a desired reactor response by altering the reactor, what goes into it, and how it is operated. When a reaction engineer lacks an appropriate level of understanding or has not learned to think at an appropriate level, their design strategy can devolve to the point of trial and error which is at best inefficient and at worst, ineffective.

### Design Task Characteristics

The aspect of design tasks that differentiates them from response and optimization tasks is that a design task begins with an **underspecifed reactor process**. For BSTRs and SBSTRs the reactor design equations are a set of IVODEs with time as the independent variable. As explained in @sec-apndx_solve_ivodes, a set of IVODEs can be solved either to find the values of the dependent variables over time or the value of an unknown constant together with the values of the dependent variables over time. Quite simply, an underspecified reactor process does not provide enough information to solve the reactor design equations.

Recall from @sec-apndx_solve_ivodes that when a set of IVODEs is solved to find the values of the dependent variables over time the following must be known: the initial values of the independent and dependent variables, the final value of one variable, and the value of every other quantity that appears in the design equations. When the set of IVODEs is solved for the value of an unknown constant, together with the values of the dependent variables over time, a second final value must be known.

The quantities that must be known when solving the IVODEs can be referred to collectively as the reactor model parameters. From this perspective, the distinguishing characteristic of a design assignment is that some of the reactor model parameters are not known, and the purpose of the design assignment is to find the "best" values for those parameters.

### Choice of the Reactor Type

As already mentioned, reactor design tasks begin with an underspecified reactor. In almost all cases, the assignment identifies the chemical to be produced, but very often it **does not specify the type of reactor** to be used. If the type of reactor to use is not specified, that is the first decision a design engineer needs to make. This chapter only considers the design of non-continuous reactors, so the choice boils down to a BSTR or an SBSTR. This choice was discussed in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis]. @sec-4_sbstr_analysis identified three situations where an SBSTR can offer a clear advantage over a BSTR: fast, highly exothermic reactions, reactions where the selectivity is strongly affected by the relative amounts of the reactants, and reversible reactions where a product can be selectivity removed. If one of these situations clearly pertains, the choice to use an SBSTR is obvious.

When the choice between a BSTR and an SBSTR isn't clear, the engineer might initially select a BSTR and begin the design process. The operation of a BSTR is slightly less detailed than an SBSTR because it isn't necessary to start, control and stop flow going into the reactor. As such, using a BSTR simplifies operation slightly and perhaps reduces labor costs compared to an SBSTR. As the design calculations proceed, the engineer may find that an SBSTR would be more appropriate, in which case the use of a BSTR can be abandoned, and replaced with design of an SBSTR. If the engineer had initially selected an SBSTR and successfully completed a preliminary design for it, they wouldn't know whether a BSTR could accomplish the same task more easily or economically.

### Reactor Metrics as Economic Indicators

The reactor design equations needed to model the reactor, and therefore identity of the reactor model parameters, are known once the type of reactor has been specified. The design assignment will specify some, but not all, of the values of the reactor model parameters. The design engineer must specify all of the missing reactor model parameters to create a fully specified reactor model. Before considering ways of doing that, it is helpful to understand how the fully specified reactor model will be used.

One of the primary goals of process design is to arrive at a fully specified reactor that will yield greatest rate of financial profit while satisfying the specifications included in the design assignment. At the preliminary design stage there are still too many unknowns for that sort of financial analysis. Instead, reactor metrics (reactor parameters and outputs) that are related to profit are used to assess and compare fully specified reactors. 

For example, the capital and operating costs for a reactor often scale with its volume. In that case, one of the goals of the preliminary design would be to minimize the reactor volume while satisfying the specifications in the design assignment. Similarly, the use of steam or another medium for heating and the use of chilled water or another coolant have associated costs, and the amount of each heat exchange fluid used can serve as a cost indicator. The selling price of the product may depend upon its purity, and production of hazardous wastes can add to operating costs. In both of these cases, conversion and selectivity may be important metrics that are related to process profit. Any reactor design assignment is likely to have several metrics that are related to the economics of the reactor process.

Typically the engineer will choose any one of the metrics as the key metric. The key metric would be the one that the engineer thinks will have the greatest effect upon the economics of the process. The engineer then would specify the missing reactor model parameters such that the fully specified model represents an optimization task where the key metric will be minimized or maximized, as appropriate.

### Specification of the Missing Reactor Model Parameters

In order to solve the reactor design equations and calculate the important reactor metrics, all of the missing reactor model parameters must be specified. As mentioned above, one reactor metric can be identified as the key metric. The key metric could be a reactor model parameter, such as the reactor volume, or it could be the final value of a variable, such as the final value of the amount of reactant from which the conversion could be calculated. In either case, the key metric will be maximized (or minimized, as appropriate). Thus, if the key metric is one of the missing reactor model parameters, it would be specified by saying it has the largest (or smallest) value possible.

The second way in which a missing reactor model parameter can be specified is by saying it is an optimization parameter. This means that its value is the value that results in key metric having the largest (or smallest) value possible. In other words, the key metric will be maximized or minimized with respect to the optimization parameters. Often, the optimization parameters are also economically important reactor metrics. Clearly, the engineer must have an understanding of reaction engineering that allows them to identify which of the missing reactor model parameters can significanly affect the key metric in order to use this type of specification effectively.

:::{.callout-note collapse="false"}
## Note

There can only be one key metric that is being maximized or minimized. The optimization tasks illustrated in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] involved minimizing or maximizing a key metric with respect to a single optimization parameter and possibly a single constraint. However computer functions are readily available for maximizing or minimizing the key metric with respect to **multiple optimization parameters** and subject to multiple constraints (see below).

:::

The other way of specifying a missing reactor model parameter is to assign a fixed value to it. Once all of the missing reactor model parameters have been specified, the key metric can be minimized or maximized using the fully specified reactor model. Doing so will yield the final values of the variables and the values of the key metric and the optimization paramters. At this point all of the economically important reactor metrics will be known or can be calculated.

### Comparing Fully Specified Reactors

As just described, all of the economically important reactor metrics will be known or can be calculated after the missing reactor model parameters are specified and the key metric is maximized or minimized. In the simplest design assignments, this might be all that is needed.

It may happen that when the key metric is minimized, one or more of the other economically important metrics has a large and unfavorable value. In design assignments, a trade-off between the economically important metrics is often observed. That is, as one important metric is optimized, another important metric changes in an unfavorable way. Sometime in this situation, the engineer might decide to analyze the same fully specified reactor system multiple times, maximizing a different metric each time. This can provide useful insight into the magnitude of the coupling between the important metrics.

At this point, guided by insight, knowledge and intuition, the engineer might elect to specify the missing reactor model parameters in a totally different way and see how the important metrics change and how they compare to the first fully specified reactor. The results might inspire or suggest yet more ways to specify the missing reactor model parameters. 

Ultimately the engineer selects one of the fully specified reactors as the one that is most preferred. A few of the other fully specified reactors may be designated as alternatives, pointing out the trade-offs between the economically important reactor metrics. The quantity or quantities chosen as key metrics, the other quantities identified as economically important metrics, and the different ways the engineer specified the missing reactor model parameters leading up to the selection of the preferred and alternative reactor systems can be referred to as that engineer's **design strategy**.

### Preliminary Design Constraints

The engineer may not have complete freedom when specifying the missing reactor model parameters. Other considerations may constrain their freedom. For example, there may be temperature limits on various process streams. These might include a maximum allowed reaction temperature (to prevent undesired reactions, phase changes in the reactor, or catalyst deactivation), a maximum outlet temperature on chilled water, or a maximum final temperature for a batch process. Safety can also impose other constraints such as a maximum temperature and/or pressure that feed and product piping can withstand, composition limits to avoid danger of explosion, etc. If anything is being discharged to the atmosphere or waterways, regulations may restrict composition.

The design specifications often set the net production rate (see @eq-bstr_net_rate) or equivalently, the total volume to be processed and the total time during which that must happen. For a non-continuous process, this establishes a relationship between the volume per batch (i. e. the reactor volume) and the total time per batch. Specifically, both the volume per batch and the time per batch are related to the number of batches, @eq-vol_and_time_per_batch. 

$$
N_{batches} = \frac{V_{total}}{V_{batch}} = \frac{t_{total}}{t_{batch}} 
$$ {#eq-vol_and_time_per_batch}

If the design assignment specifies the net production rate, but does not fix either the volume per batch or the time per batch, then the design engineer can specify one or the other. If the reaction engineer specifies the volume per batch, the time per batch is constrained as shown in @eq-time_per_batch_constraint, and if the engineer specifies the time per batch, the volume per batch is constrained as shonw in @eq-volume_per_batch_constraint. Equations [-@eq-vol_and_time_per_batch], [-@eq-time_per_batch_constraint], and [-@eq-volume_per_batch_constraint] are written in terms of the volume being processed, but any measure of the amount to be processed could be used.

$$
N_{batches} = \frac{V_{total}}{V_{batch}} \qquad \Rightarrow \qquad t_{batch} \le \frac{t_{total}}{N_{batches}}
$${#eq-time_per_batch_constraint}

$$
N_{batches} = \frac{t_{total}}{t_{batch}} \qquad \Rightarrow \qquad V_{batch} \ge \frac{V_{total}}{N_{batches}}
$${#eq-volume_per_batch_constraint}

Constraints often do not apply directly to the specifications that the engineer adds to the design specifications. Instead, they indirectly limit the choices the engineer can make. That is, after the engineer specifies the missing reactor model parameters, the reactor model equations must be solved in order to determine whether any of the constraints are violated. Computer functions that perform constrained, multi-parameter optimization are available in many software packages.

## Example {#sec-example_11}

Readers who have assimilated the knowledge and skills from Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] are capable of non-continuous reactor analysis. This chapter emphasizes design strategy, not analysis. More specifically, the focus is on choosing the reactor type, identifying a key reactor metric and other economically important metrics, and specifying the missing reactor model parameters.

For this reason, the example provided here does not include any calculations. Instead, it focuses on the engineer's thought processes and the resulting design strategy the engineer develops. The engineer may revise or expand their design strategy as they proceed through the analyses, but since analysis is not included in these examples, that aspect of the design process is not illustrated.

Even though it is quite simple, the following example describes one engineer's thinking and the design strategy that engineer develops based on that thinking. A different engineer might think differently and develop a different design strategy. Assuming they are competent, both engineers will arrive at a preliminary design that satisfies the design specifications, but their preliminary designs may be different from each other. It is critially important for readers to recognize that **this example is [not]{.underline} a "cook book" for what [you]{.underline} should be thinking while developing [your]{.underline} design strategy**, but rather an example of what one engineer [might]{.underline} be thinking as they develop [their]{.underline} design strategy. Since the engineer's thinking is the essence of this example the usual "Click Here to See What an Expert Might be Thinking at this Point" callouts are not used.

### Preliminary Reactor Design for an Autocatalytic Reaction

**Background**: A specialty chemical company is considering producing reagent Z in a non-continuous process. A preliminary marketing study suggests yearly sales of 30,000 gal per year might be expected if the purity is 99% or greater. The proposed process would produce Z three times per year with each production period lasting four-weeks. The reactor would be used for other purposes the rest of the time. Chilled water at 18 °C is available as is saturated steam at 50 psi. Storage tanks will be used to hold the 99% pure product between the time it is produced and the time it is sold.

Z can be produced from reagent A which is available in essentially pure form at ambient temperature (20 °C). The irreversible, exothermic, autocatalytic reaction, $A + Z \rightarrow 2Z$, is first order in A and in Z. In the absence of Z, the rate is very small. When both A and Z are present, the rate is measurable at 20 °C. The reaction is moderately exothermic. Reagents A and Z are liquids and form an ideal solution. The product, Z, has the lower boiling point, 96 °C.  A rate expression and all necessary thermochemical data are available.

**Assignment**: Perform a preliminary design of a reactor that can be used as described above.

---

#### Design Strategy

As the engineer who was given this assignment, here's what I'm thinking:

* For this non-continuous process, I could use either a BSTR or an SBSTR.
    * The reaction is exothermic, so if the temperature cannot be safely controlled, I will have to use an SBSTR.
    * I'll start my analysis assuming the reactor operates as a BSTR.
* I'll use one week as the basis for my calculations.
    * 30,000 gal must be processed over 12 weeks or 2500 gal per week.
* I'll assume that capital and operating costs scale with the reactor volume, in which case I'll want to minimize the volume of the reactor.
    * The resulting volume will impose an upper limit constraint on the processing time, @eq-time_per_batch_constraint.
* I want the rate to be as large as possible at all times.
* Having some Z present initially is essential for an acceptable rate.
    * This suggests that during turnaround the reactor should not be emptied completely.
* The reaction is exothermic; the temperature will rise continually if no cooling is provided.
    * I'll assume that some cooling will be necessary, but I'd like to use as little cooling water as possible to reduce operating costs.
    * Since the reaction rate is "measurable" at ambient conditions, I'll assume no heating is necessary.
* The conversion must be at least 99%.
* To provide a margin of safety and keep the product from boiling (at 96 °C), I’ll specify a maximum temperature of 90 °C.
* The product that is left in the reactor during turnaround will be hot and the A that is added to it will be at 20 °C (ambient temperature)
    * The initial temperature will depend upon the relative amounts of A and Z.
* For cooling I'll assume the reactor is jacketed and that the jacket volume and heat transfer area are geometrically related to the volume.
    * I'll assume that I can determine that relationship along with the heat transfer coefficient from stirred tank vendor literature.
* If the temperature cannot be controlled below 90 °C, I'll switch to using an SBSTR.
    
Based upon my thinking above, here is my **design strategy**.

1. Assume the reactor is a jacketed BSTR with a volume, $V$.
    a. Use stirred tank manufacturer's literature to estimate the jacket volume, heat transfer area and heat transfer coefficient.
    b. Assume that chilled water flows into the jacket at 18 °C with a flow rate of $\dot{m}_{ex}$.
2. At the end of processing $X$% of the reactor contents are removed and transferred to storage.
    a. the turnaround time needed for this can be estimated.
3. To start a batch, a sufficient amount of pure A at 20 °C to fill the reactor is added instantaneously.
    a. Assuming perfect mixing, the initial temperature and molar amounts of A and Z can be calculated.
4. The processing ends when the conversion of A reaches 99%.

Using the reactor design equations for this system, the reactor volume can be minimized with respect to $\dot{m}_{ex}$ and $X$ subject to the constraints that the temperature is below 90 °C at all times and that the processing time satisfies @eq-time_per_batch_constraint.

The reactor volume is the key metric to be minimized. The coolant flow rate is also an economically important metric that should be as small as possible.

It may not prove possible to meet the design specifications and satisfy the constraints using my initial specifications for the missing reactor model parameters. Whether or not it is possible, the following modifications of the system should be analyzed.

* During turnaround, partially cool the fluid that is not removed from the reactor prior to adding the fresh feed and starting the next batch.
* Drain the jacket during turnaround and initially operate the reactor adiabatically, starting the coolant flow when the temperature reaches $T_1$, with $T_1$ as an additional optimization parameter.
* Operate as an SBSTR, adding the fresh feed at a steady rate, $V_{in}$, with $V_{in}$ as an additional optimization parameter.

The minimized volumes for each system should be compared and the one with the smalles $V$ should be reported as the preferred design. If any of the other designs have a volume close to the volume of the preferred design, but with a coolant usage much smaller than the preferred design, they should be reported as alternative designs.

#### Discussion

This was a very simple example, and many details were not included in the design strategy. One thing to note is that by minimizing with respect to the coolant flow rate, the possibliity that no cooling is necessary is included. In that case the optimim coolant flow rate would be essentially zero.

The total volume to be processed per week in this example is 2500 gal. It is important to recognize that the minimized volume, $V$ that is found using the design equations is the total reactor volume. However, at the start of the process $X$% of that volume was not fresh feed. Also, the time per batch is the processing time plus the turnaround time. As a result, the constraint on the processing time is given by equation (1).

$$
t_{batch} \le \frac{t_{total}}{N_{batches}}
$$

$$
N_{batches} = \frac{2500\text{ gal}}{\left(1 - \frac{X}{100}\right)V}
$$

$$
t_{turnaround} + t_{processing} \le \frac{1\text{ week}}{2500\text{ gal}}\left(1 - \frac{X}{100}\right)V
$$

$$
t_{processing} \le \frac{1\text{ week}}{2500\text{ gal}}\left(1 - \frac{X}{100}\right)V - t_{turnaround} \tag{1}
$$

There are a lot of "what-if's" associated this assignment. For example, what if, with no cooling, the heat of reaction only caused the temperature to rise to 50 °C? In that case, it might be beneficial to use heat to raise the initial temperature. That would lead to a higher rate, and consequently a smaller reactor. (Of course the costs associated with the heating would need to be offset by the lower capital and operating costs due to a smaller volume.) A good design engineer is constantly asking *and answering* these what-if's as one means of refining and improving their design strategy.

## Symbols Used in @sec-4_non_continuous_design

| Symbol | Meaning |
|:-------|:--------|
| $t_{batch}$ | Total time (processing plus turnaround) per batch. |
| $t_{total}$ | Total time available for processing the total volume of feed. |
| $N_{batches}$ | Number of batches. |
| $V_{batch}$ | Volume of feed to be processsed per batch. |
| $V_{total}$ | Total volume of feed to be processsed. |

: {tbl-colwidths="[20,80]"}

Effectively, this chapter is a continuation of @sec-4_non_continuous_design. That chapter only considered the design of non-continuous reactor processes. It presented important design principles and described different levels of design before identifying preliminary design as being an appropriate level of design for the purposes of *Reaction Engineering Basics*.

Briefly, preliminary design begins with an underspecified reactor process to which the design engineer adds sufficient specifications to enable modeling and analysis of the process. It uses reactor performance metrics as indicators of process economics. Often a single key reactor performance metric is minimized or maximized with respect to one or more reactor process parameters to be specified by the design engineer. Some process parameters or reactor outputs may be subject to constraints imposed by safety, operability, or regulatory considerations.

All of the discussion in @sec-4_non_continuous_design applies equally in the present chapter, but it won't be duplicated here. Chapters 12 and 13 illustrated the modeling and analysis of two types of continuous reactors, namely the CSTR and the PFR. With that knowledge as background, this chapter considers two additional aspects of preliminary design. Specifically this chapter builds upon @sec-4_non_continuous_design by adding sections on the choice between non-continuous and continuous processes and on the choice bewteen CSTRs and PFRs in continuous processes.

## The Choice Between Non-Continuous and Continuous Processes

Most of the criteria used when choosing between a continuous process and a non-continuus process have already been mentioned in previous chapters. This section simply gathers them together in one place. The most important criterion, perhaps, is the anticipated amount of the product to be produced anually. If the product is a commodity that is going to be produced and sold in large volumes, a continuous process is most likely preferred. The profit margin on commodity chemicals is often small, and production costs need to be minimized because they cannot be passed on to the consumer easily. Generally the additional labor and logistics of a non-continuous process lead to a larger production cost per pound of product compared to a continuous process.

In contrast, when a small annual production is anticipated, but the profit margin is large, a non-continuous process may be preferred. A non-continuous process allows production of value-added products on demand. This can reduce the costs associated with storing the products during seasons of low demand while allowing for ramping up production when demand is greater.

Another important factor is the number of different reactor operating conditions required to produce the product. If the "recipe" for making the product involves multiple reactive steps at different temperatures and of different durations, a non-continuous process will likely be preferred. For example if the reactive processing requires holding at one temperature for some period of time, then adding a reagent and holding at a different temperature for a different amount of time, a non-continuous process would probably be preferred. It is simply easier to follow this kind of recipe using a non-continuous process.

Similarly, if the reaction must be run at conditions where the reaction rate is very low, a non-continuous process may be the better choice. For processes where the rate is much faster, where additional reagents do not need to be added part way through the reaction process, and where multiple reaction temperatures are not required, a continuous process can be advantageous.

Flexibility is another consideration when deciding between a continuous and a non-continuous process. A non-continuous process may be more suitable if the same reactor will be used to produce different products at different times. That is, it may be more challenging to use the same feed and product piping to conduct one chemical processes part of the time and a different reaction at other times in a continuous reactor system. Generally continuous processes are best when they can be started up and allowed to operate at steady state for extended periods of time.

In the final analysis, though, none of these criteria are definitive. Ultimately the choice between using a non-continuous process or a continuous process comes down to economics.

## The Choice Between CSTRs and PFRs in Continuous Processes

In some instances the choice between a CSTR and a PFR is an easy one, but under other circumstances it is not clear at all. The most significant difference between the two reactor types is how the temperature and composition vary during the reaction time. In continuous reactors, the reaction time is the length of time that the reacting fluid spends in the reactor.

The choice between a CSTR and a PFR is easiest when only one reaction is taking place and the reactor is **isothermal**. For typical reaction kinetics a high rate is favored by large reactant concentrations and, if the reaction is reversible, by small product concentrations. In an isothermal CSTR the concentrations are the outlet values and they do not vary during the reaction time. The reactant concentrations are smaller than in the feed, the product concentrations are larger than in the feed, and the reaction rate does not change during the reaction time.

In an isothermal PFR the concentrations change monotonically during the reaction time. The reactant concentrations start at their feed values and decrease steadily to their outlet values during the reaction time. The product concentrations start at their feed values and increase steadily to their outlet values. Based on those variations the rate of a typical reaction decreases steadily during the reaction time in a PFR.

Comparing equal feeds at equal conversions, the rate will be constant during the reaction time in a CSTR. When comparing at equal conversions, the outlet composition from a PFR will equal the CSTR composition. Therefore rate in a PFR will become equal to the CSTR rate at the end of the reaction time. Except at the very end of the reaction time, the rate in the PFR will be greater than the rate in the CSTR, so a PFR volume smaller than the CSTR volume is needed to reach the same final conversion.

Comparing equal feeds at equal space times means the reaction times for the reactors are the same, but the conversions differ. Again, the CSTR rate will be constant during the reaction time. Because the initial rate in the PFR is higher, the PFR will reach the same conversion as the CSTR in less reaction time than the CSTR. the PFR fluid will continue to react for the remainder of the reaction time, so its final conversion will be greater than the CSTR conversion.

Thus the choice between a CSTR and a PFR for a slngle, isothermal reaction is quite straightforward, but few commercial reactors operate isothermally. When the reactors are **adiabatic**, the composition effects are the same as in isothermal reactors, but temperature effects must also be considered. In a CSTR, the temperature does not change during the reaction time. The temperature and composition in the CSTR are constant and equal to their outlet values.

The temperature will change during the reaction time in a PFR, and the effect of that change can either reinforce the effect of composition change or it can oppose it. If the reaction is **endothermic** the temperature decreases steadily during the reaction time. Taken alone, this change decreases the rate and so it reinforces the effect of decreasing reactant concentration. If the reaction is exothermic, the temperature increases during the reaction time. Taken alone, this increases the rate, so for an exothermic reaction the effect of changing temperature during the reaction time opposes the effect of composition. This results in three possible rate behaviors in an adiabatic PFR with an **exothermic** reaction.

* The rate increases steadily during the reaction time as would happen if the temperature effect was stronger than the composition effect over the reactor's entire conversion range.
* The rate increases, passes through a maximum, and then decreases during the reaction time as would happen if the temperature effect predominated at early reaction times and the concentration effect predominated at later reaction times.
* The rate decreases steadily during the reaction time as would happen if the concentration effect was stronger than the temperature effect over the reactor's entire conversion range. (As noted above, this rate behavior also occurs when the reaction is endothermic.)

Comparing equal feeds at equil conversions as above, the rate will not change during the reaction time in a CSTR, and because the conversions are equal, the rate in a PFR will become equal to the CSTR rate at the end of the PFR reaction time. If the rate in the PFR increases steadily during the reaction time (first rate behavior above) the required PFR volume will be larger than the CSTR. This is because the rate only become equal to the CSTR rate at the very end of the reaction time; prior to that the PFR rate is lower than the CSTR rate so the required volume is larger. Conversely, if the rate in the PFR decreases steadily (third rate behavior above) the required PFR volume will be smaller than the CSTR. If the PFR rate increases, passes through a maximum, and then decreases during the reaction time, the required PFR volume could be smaller or larger than the CSTR volume.

Comparing equal feeds at equil space times for a single reaction in adiabatic reactors, the rate again will not change during the reaction time in the CSTR. The reaction time in the PFR will equal the reaction time in the CSTR. If the PFR rate increases steadily during the reaction time, the conversion will be smaller in the PFR than in the CSTR. If the PFR rate decreases steadily during the reaction time, the conversion will be larger in the PFR than in the CSTR. Not surprisingly, if the PFR rate increases, passes through a maximum, and then decreases during the reaction time, the conversion in the PFR could be either larger or smaller than that in the CSTR.

Some reactors are neither isothermal nor adiabatic, and in these cases the variation of the rate during the reaction time will differ from the rate behaviors described above. When more than one reaction is taking place the selectivity may be just as important as the reaction rate. The effects of temperature and composition upon the selectivity may be different from their effects upon the rate. This can lead to trade-offs between conversion and selectivity.

In summary, for a single reaction in an isothermal reactor the choice between a CSTR and a PFR is straightforward. For single reactions in adiabatic reactors it is straighforward if the reaction is endothermic. When the reaction is exothermic it won't be known which of the three rate behaviors applies without performing at least a few preliminary calculations.

Furthermore, all of the preceding qualitative analysis assumed typical kinetics. For atypical kinetics (autocatalytic reactions, reactant-inhibitie reactions, etc.) a similar analysis can be used. As was found for typical kinetics, in some cases the choice between a CSTR and a PFR will be straightforward while in others it won't.

In the simplest of situations it may be possible to make a choice between a CSTR and a PFR on the basis of a qualitative analysis. In many other situations preliminary modeling of both reactor types may be needed to inform the choice of which reactor type to use. Finally, CSTRs are not well-suited to reactions that require a solid catalyst, in which case the use of a PFR is obvious.

## Examples

The example presented in @sec-4_non_continuous_design describes possible design strategies an engineer might use when tasked with designing a non-continuous reactor for an auto-catalytic reaction. It focuses more upon selecting a key metric (the reactor volume) and identifying the operating parameters that can be varied to minimize that metric than on choosing the type of reactor to use.

The examples presented here focus upon initially choosing to use a CSTR, to use a PFR, or to analyze both reactor types before choosing one of them. Once that choice is made, design strategies analogous to the one presented in [Example -@sec-example_11] can be developed for the chosen reactor type(s). As was the case in @sec-4_non_continuous_design, these examples describe one possible design strategy, but they do not include any analysis. The reader should have learned how to model and analyze CSTRs and PFRs in @sec-4_cstr_analysis and @sec-4_pfr_analysis.

As was true in @sec-4_non_continuous_design, the engineer's thinking is the essence of these examples, the usual "Click Here T\to See What an Expert Might be Thinking" callouts are not used.

### Preliminary Design of a Continuous Reactor for an Exothermic Autocatalytic Reaction {#sec-example_14_3_1}

**Background**: A chemical company is considering construction of a new plant to produce 15 million pounds of reagent Z per year. This will be the first time the company will produce Z. It is produced from reagent A in an irreversible, autocatalytic, exothermic reaction, equation (1). The rate expression is shown in equation (2) where the rate coefficient $k_2$ is much, much smaller than $k_1$. Kinetics and thermodynamic data are available for the system. The product, Z, must be at least 95% pure, and the reacting fluid temperature cannot exceed 115 °C. A small steam generator and a chilled water plant will be built to support the process. 

$$
A \rightarrow Z \tag{1}
$$

$$
r_1 = k_1C_AC_Z + k_2C_A \tag{2}
$$

**Assignment**: Perform a preliminary design for the reactor to be used in the new plant.

#### Design Strategy

The annual production is large, so the process will be continuous. There isn't an existing plant that I can use for reference, so I'll need to decide whether to use a CSTR or a PFR. Some qualitative reasoning may help me make that choice. 
If I use a CSTR, it will operate at the final conditions where the temperature will be as high as allowed and the composition will consist of 95% Z and 5% A. Both of these factors favor a high rate, and consequently a small volume. (The reaction is auto-catalytic, so the rate remians high despite a lower reactant concentration and higher product concentration.) If I use a PFR, near the inlet the composition will be almost all A and the temperature will be low. This will lead to a very low rate near the inlet, a lower average rate, and consequently a large reactor. Based on this reasoning, it seems clear that a CSTR should be used.

I'd like the reactor to be as small as possible which means I'd like the rate to be as large as possible. I can't exceed 115 °C, so to provide a margin of safety, I'll set the outlet temperature to be 100 °C. For the rate to be as large as possible, and knowing the conversion must equal 95%, that fixes the outlet composition and temperature. 

I'll assume two weeks of down time per year, which fixes the outlet flow rate of Z at 1.5 x 10^6^ lb per 50 weeks. I can convert that to a molar outlet flow rate, then, knowing the conversion, I can calculate the inlet molar flow rate of A. Then, knowing the rate and the inlet flow rates, I can calculate the reactor volume.

I'm not sure whether the heat of reaction is sufficiently high to operate adiabatically. I might need to add heat or I might need to remove it so that the outlet temperature is 100 °C. I'll need to calculate the necessary heat transfer area and exchange fluid temperature. I'll assume that steam and cooling water will be available at the same temperatures as in other plants the company operations for the purposes of this preliminary design. If the design proceeds to a larger scale, the design of the steam and chilled water plants will need to be integrated into the reactor design.

Since the reactor volume is essentially fixed by the specified production rate, the costs that scale with the reactor volume are also fixed. I expect that the steam and/or chilled water will be the next most significant contributors to the operating costs. If I need cooling, I can minimize the amount of coolant used by adjusting the heat transfer area.

Even if I don't need steam for steady-state operation, I will likely want to supply heat during process start-up. I'll need to devise a start-up procedure and calculate its heat exchange requirements. If the steady-state process also requires steam, I'll need to design the reactor for the more demanding of the two operating modes. I'll assume that any steam used will be saturated, and adjust the heat transfer area to minimize the steam flow rate. I'll assume that only 85% of the steam condenses to provide a margin of error.

#### Discussion

In this assignment, the choice between a CSTR and a PFR was quite easy. The kinetics were such that high product concentration favors a high rate, and the reaction was exothermic, so adiabatic operation would give a high temperature, which also favors a high rate. The choice of a CSTR could be made on the basis of a qualitative analysis without requiring any computational analysis of a PFR.

In [Example -@sec-example_11], the reactor volume was used as the key metric affecting the operating costs for the process. Here the reactor volume was effectively established by the specified production rate, product purity, and maximum temperature. Thus, the coolant and steam flow rates could be used as the key metrics affecting operating costs. Further, if both cooling (during steady-state operation) and heating (during start-up) were required, they could both be minimized because they would not be used simultaneously. The cooling could be minimized for steady-state operation and the heating for start-up.

### Preliminary Design of a Continuous Reactor for an Endothermic Reaction {#sec-example_14_3_2}

**Background**: Z is the monomer used to produce a commodity polymer. Typically Z is produced from A via the endothermic, irreversible dehydrogenation reaction (1). The gas-phase dehydrogenation reaction is second order in A. A company wants to build a process to produce 10,000 tons of Z per year. The feed A will be avialable at 200 °C and 10 atm. The reactor must operate at 98% conversion, and its temperature must be kept below 800 °C.

$$
A \rightarrow Z + H_2 \tag{1}
$$

**Assignment**: Perform a preliminary design of a reactor for use in this process.

#### Design Strategy

The amount of Z to be produced per year is very large, so I'll design a continuous reactor. It is likely that I'll need to heat the reactor whichever type I choose. If I choose a CSTR, it will operate at the outlet composition where the concentration of A will be very small, leading to a low rate of reaction, and therefore requiring a large reactor. Additionally, because the reacting fluid is a gas, it might be challenging to design the agitation so that mixing is perfect. So, it seems clear that I need to use a PFR.

Having chosen the reactor, most of the operational details are fixed. The conversion and outlet flow rates are set by the given process specifications, and knowing the conversion, I can calculate the feed flow rate. I want the reactor to be as small as possible because I expect operating costs to scale with the reactor volume. I could simply design the reactor to operate close to the maximum allowed temperature, leaving an appropriate margin of error.

However, I don't really know whether it is necessary to operate right at the limit. The rate may be sufficiently large at lower temperatures. Clearly there will be a trade-off between reactor volume and heating demand where using less heat will result in a larger volume. I also don't know what the heat exchange fluid is going to be. It might be saturated steam, but depending upon the temperature, a molten salt might be preferred.

For the purposes of this preliminary design, I'll assume that the temperature of the heat exchange fluid will be constant, and I'll create a graph showing the reactor volume as a function of the heat exchange fluid temperature. That may prove helpful for choosing what to use as a heat exchange fluid as the design moves forward. That is, for a given volume it will show the necessary exchange fluid temperature, and that can be used to estimate the associated costs for various heat exchange fluids.

#### Discussion

In this example, the choice of the type of reactor to use was unequivocal. The remaining available specifications were insufficient to go too far with the preliminary design. In situations like this it can be useful to explore the trade-offs between different operating parameters instead of choosing a key metric and minimizing it. In this way, preliminary choices can be made to more fully specify the nature of the system, after which a preliminary optimization can be performed.

For this system, the engineer would really need more details about the metals to be used for the reactor (what temperatures can it withstand, at what temperature might hydrogen embrittlement become an issue) and its compatibility with different heat exchange fluids. A very preliminary calculation of reactor volume versus heat exchange temperature like the one described above can inform decisions about the metallurgy, heat transfer medium, etc. Then a slightly improved preliminary design can be undertaken.

### Preliminary Design of a Continuous Reactor for an Exothermic Reaction {#sec-example_14_3_3}

**Background**: The liquid-phase, exothermic reactions of A and B, equations (1) and (2), are exothermic, irreversible, first order in A and first order in B. D is the desired product because its value is significantly greater than U. The activation energy for reaction (1) is smaller than the activation energy for reaction (2) while their pre-exponential factors are comparable. The kinetics and thermodynamics of the reactions are well-documented.

$$
A + B \rightarrow D + Z \tag{1}
$$

$$
A + B \rightarrow U + Z \tag{2}
$$

**Assignment**: For a proposed process to manufacture D, separate streams of A and B will br available at 30 °C where they will react at a modest rate when combined. The adiabatic temperature rise for the reactions at these feed conditions is approximately 60 °C. Chilled water will also be available at 25 °C. Perform a preliminary design of a continuous reactor for the conversion of A and B.

#### Design Strategy

The assignment doesn't specify a production rate, so I'll choose a feed rate as a basis in my analysis. There are two important performance metrics in this system, the reactor volume and the yield of D. Based upon the information given in the assignment, the reactor could operate adiabatically, but it might be preferrable to cool it because lower temperature will favor the production of D (because the activation energy is smaller).

The choice of reactor is not clear-cut. If a CSTR is used, it will operate at higher temperature and lower reactant concentrations. Those factors have opposing effects upon the reaction rates, and by extension the reactor volume. If a PFR is used, the temperature at the inlet will be smaller, and the concentrations of the reactants will be larger. As the fluid progresses through the reactor, the temperature will rise, tending to increase the rate, while the reactant concentrations will decrease, tending to decrease the rate. Depending upon the conversion, it is possible that the average rate in the PFR will be close to the rate in the CSTR, and consequently, their volumes will be comparable. Because the temperature will vary in the PFR, it also isn't clear which reactor will offer the better selectivity.

Given those uncertainties, it would not be prudent to choose the reactor type without performing any analysis. Instead, I will evaluate both reactor types and, if possible, choose the preferred reactor based upon a comparison of their performance. For either reactor type, I'm also not sure which of the performance metrics is most important, the reactor volume or the yield of D. That is, it might result that when the reactor volume is minimized, the yield of D is very small, or vice versa.

In light of the uncertainties described above, my design strategy for each of the two reactors will be as follows:

1. Choose a range of reactor volumes.
    a. for each volume, maximize the yield of D with respect to the coolant flow rate and heat transfer area.
    b. plot the maximum yield of D as a function of the reactor volume.
2. Choose a range of values of the yield of D.
    a. for each yield of D, minimize the reactor volume with respect to the coolant flow rate and heat transfer area.
    b. plot the minimum reactor volume as a function of the yield of D.

This will generate four graphs, two for the CSTR and two for the PFR. These graphs should make any trade-offs between reactor volume and yield apparent, and they may also show that one of the two reactor types is clearly superior. In any case, these graphs should be useful for refining the the design specifications.

#### Discussion

In this assignment it wasn't possible to select the reactor type on the basis of a qualitative analysis. This is often the case, especially if the reactor is being heated or cooled. It is better to do at least an initial computational analysis of both reactors and use the results to inform future design decisions.
