## Preface {.unnumbered}

*Reaction Engineering Basics* is an introductory textbook on chemical kinetics and reaction engineering. It complements the online, *Self-study Course on Reaction Engineering* (*SCoRE*[as link]). Both *Reaction Engineering Basics* and *SCoRE* present the subject at the level of a first undergraduate chemical engineering course on reactions and reactors.

There are many excellent introductory kinetics and reaction engineering textbooks. Like many other textbooks, *Reaction Engineering Basics*, limits kinetics data analysis problems to isothermal systems with a single reaction taking place (though it does not limit the analysis to systems where linear least squares can be used). However, as it moves into the area of reaction engineering, *Reaction Engineering Basics* is different from many other textbooks in two respects. First, *Reaction Engineering Basics* does not start with systems with single reactions taking place in isothermal reactors and then introduce systems with multiple reactions or systems requiring an energy balance in subsequent chapters. The reaction engineering section of *Reaction Engineering Basics* **starts** with systems that require mole **and** energy balances and that feature multiple reactions. Second, *Reaction Engineering Basics* differs from many other introductory kinetics and reaction engineering textbooks by using numerical methods to solve almost all of the problems it presents. The one exception is that analytic algebra is used when generating rate expressions for non-elementary reactions from proposed mechanisms for those reactions.

*Reaction Engineering Basics* was written for use in an undergraduate chemical engineering curriculum. The intended audience is students who have completed approximately two years of a four-year chemical engineering degree program. While very brief overviews of important topics are included, generally *Reaction Engineering Basics* assumes that readers have completed two semesters of general chemistry, a course on chemical engineering mass and energy balances and, ideally, a course on chemical engineering thermodynamics. Proficiency in algebra, calculus and differential equations is also assumed. [Appendix -@sec-pre-knowledge] provides a few more specifics on prerequisite knowledge.

## Practice Problems and Numerical Methods

Each chapter of *Reaction Engineering Basics* includes illustrative example problems with solutions. Beyond showing *what to do* to solve the problem, the solutions attempt to expose expert thinking by describing *how an expert knows to do those things*. The solutions describe in detail how to solve the problems, in most cases using numerical methods. They also present and discuss the results from solving the problem. However, the solutions in *Reaction Engineering Basics* **do not** include actual computer code used to solve the problems.

Instead, the solutions are written in a way that should make it easy for students to implement the calculations using computational tools they are familiar with, that are available to them or, if using this textbook as part of a formal course, that are required by the course instructor. In this way, *Reaction Engineering Basics* is not tied to any one brand of software or computational tool.

However, video solutions to most *Reaction Engineering Basics* example problems are available in *SCoRE*[as link]. *SCoRE* provides Python and Matlab utility functions for the essential numerical methods used in *Reaction Engineering Basics*, and it illustrates their use. Python was chosen because it is freely available online; Matlab was chosen because it is licensed by many universities (including the author's) for instructional use. As part of presenting solutions to *Reaction Engineering Basics* example problems, the video solutions that are included in *SCoRE* **do** describe how to write and execute the necessary code. 

*Reaction Engineering Basics* does not include end-of-chapter practice problems. Once again, many practice problems, with solutions, are available in *SCoRE*. Instructors thinking about using *Reaction Engineering Basics* may be dismayed by the absence of practice problems that do not include solutions. The reason for not including them is discussed elsewhere [add ref to CEE paper], but even if problems without solutions were available, it would not take long for the solutions to those problems to appear elsewhere online.

## Acknowledgements

I could use any number of clichés here, but instead I'll just say that my wife, Deb, has been unbelievably supportive of me in my career, and particularly as I wrote this book. I owe her a debt that I can't hope to repay, but at the very least, I can thank and acknowledge her for all she has done and continues to do. So thanks, Deb, you're the best!

I was fortunate and blessed to receive a fantastic formal eduction. From grade school through graduate school I've been taught by many outstanding educators, and I thank them all. Two in particular stand out. Jim Dumesic, "the Boss," is one. When he became my PhD advisor, I expected it to be a 4 to 5 year deal. It wasn't. Jim has been my mentor, trusted advisor and true friend ever since that day. For over forty years, he's always been there for me, and I can't thank him enough. The other standout is Phil Wankat. Without going into the details, I was ready to change majors after my first undergraduate chemical engineering course. It didn't happen because Phil Wankat taught the second chemical engineering course I took, one on stagewise separations. He is the best teacher I ever had, and his teaching and personality are directly responsible for me being a chemical engineer today. 

The [University at Buffalo](https://www.buffalo.edu/), its [School of Engineering and Applied Sciences](https://engineering.buffalo.edu) and its [Department of Chemical and Biological Engineering](https://engineering.buffalo.edu/chemical-biological.html) have been my professional home since 1986. They have provided an environment that is equally supportive of educational innovation and, in my case, catalysis and reaction engineering research. I appreciate that educational innovation is not only supported, it is recognized and rewarded.

Personally, I believe there is a God who blessed me with the ability, circumstances and perseverence to write this book.

## About the Author

Carl Lund is a Professor in the [Department of Chemical and Biological Engineering](https://engineering.buffalo.edu/chemical-biological.html) at the [University at Buffalo](https://www.buffalo.edu/). He earned a B. S. in chemical engineering from [Purdue University](https://engineering.purdue.edu/ChE) in 1976 and a Ph. D. in chemical engineering from the [University of Wisconsin - Madison](https://engineering.wisc.edu/departments/chemical-biological-engineering) in 1981. He worked in the Exxon Corporate Research Laboratories from 1981 to 1986, after which he joined the faculty at the University at Buffalo. He is a fellow of the AIChE.  He started teaching undergraduate kinetics and reaction engineering in 1986, and has taught it every year since, except for 1998, 1999 and 2000. His current research activity centers on pedagogy for problem-solving courses.

## License

This website is licensed under the [Creative Commons Attribution-Non-Commercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/) License (CC BY-NC-ND 4.0).