# Kinetics Data Analysis

The first section of *Reaction Engineering Basics* introduced the field of reaction engineering and reviewed basic facts about chemical reactions. The second section of *Reaction Engineering Basics* described and defined chemical reaction rates and rate expressions. It presented empirical and theoretical ways to propose the mathematical form of a rate expression.

When rate expressions are being generated, they must be validated using experimental kinetics data. That requires mathematical models for the reactors used in the experiments. So the third section of *Reaction Engineering Basics* examined the equations that are used to model four types of ideal reactors and the numerical solution of those equations.

This fourth section of *Reaction Engineering Basics* explores the generation and analysis of kinetics data. The design of experiments for gathering kinetics data is presented first. That is followed by three chapters that explain how to analyzed data that were generated using three of the four ideal reactor types from @sec-modeling-ideal-reactors.

## Chapters in this Section

@sec-kin-data-gen Generation and Analysis of Kinetics Data

@sec-bstr-data-analysis Analysis of Kinetics Data from a BSTR

@sec-cstr-data-analysis Analysis of Kinetics Data from a CSTR

@sec-pfr-data-analysis Analysis of Kinetics Data from a PFR
