# Reaction Mechanisms and Mechanistic Rate Expressions {#sec-mechanisms}

During a non-elementary reaction, the involved bonds do not break and form simultaneously. As a result, intermediate species are formed that are not observed at the macroscopic level. Thus, what appears to be a single reaction event at the macroscopic level actually occurs as two or more elementary reactions at the microscopic level. The set of elementary reaction events that actually takes place at the molecular level is known as the **reaction mechanism**. Because it appears from a macroscopic perspective that only the non-elementary reaction is taking place, it is desirable to have an expression for the apparent rate of that non-elementary reaction. The focus of this chapter is the generation of apparent rate expressions for non-elementary reactions from proposed mechanisms.

## Reaction Mechanisms

Understanding the mechanism of a non-elementary reaction can be useful in a number of ways. Often reaction mechanisms are studied with the intention of using that knowledge to modify the reactive process. Because the intermediate species in a reaction mechanism are not readily observable using typical analysis instruments, the experimental study of mechanisms is demanding. *Reaction Engineering Basics* does not touch upon the experimental study of reaction mechanisms. Its focus with respect to mechanisms is on generating apparent rate expressions for non-elementary reaction given either a proposed mechanism or a mechanism that is well-established by experimental study.

The species that participate in a reaction mechanism but do not appear in the reaction expression for the non-elementary reaction are called **reactive intermediates**. The concentrations of reactive intermediates are always very small. Otherwise they would be observed at the macroscopic level. The reason reactive intermediates have small concentrations is that they react quickly making their lifetimes very short. That’s why they are called *reactive* intermediates. (While their lifetimes are short relative to the reactants and products in the apparent non-elementary reaction, they are still much longer than the lifetime of an activated complex. As noted in [Chapter -@sec-react-eng-def] and [Appendix -@sec-transition-state-theory], some bonds in an activated complex are breaking at the same time others are forming, leading to lifetimes measured in nanoseconds.) The identification of reactive intermediates when solving problems involving mechanisms is illustrated in every example at the end of this chapter.

By definition, every reaction in a reaction mechanism is an elementary reaction. Consequently, the rate expression for each mechanistic step will have the functional form shown in @eq-net_rate_elem_rxn, or, for gases in @eq-net_rate_elem_rxn_part_press. Those equations include the equilibrium constant for the elementary step. Very often, in mechanistic steps, thermodynamic data are not available for the reactive intermediates. In those cases, the equilibrium constant for the mechanistic step won’t be known. For this reason, in this chapter the rate expressions for elementary mechanistic steps will be written as shown in @eq-rate_mech_step. The square brackets in that equation can represent concentrations or (if the reagents are gases) partial pressures. When writing the rate expressions in this way, it is important to remember that the forward and reverse rate coefficients *must* be consistent with thermodynamics. The use of @eq-rate_mech_step when solving problems involving mechanisms is illustrated every example at the end of this chapter.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$ {#eq-rate_mech_step}

There are a few rules that all mechanisms must obey. There must be some linear combination of the mechanistic steps that exactly equals the apparent, non-elementary reaction. Being elementary reactions, every step in a reaction mechanism must be reversible. This is required by the principle of microscopic reversibility. In addition, the mechanistic steps must be consistent with all available experimental data including (isotopic effects, isotope distributions in products, spectroscopic measurements, etc.) and not just the reaction kinetics.

Reaction mechanisms are sometimes differentiated as having either an open sequence of steps or a closed sequence. Mechanisms with a closed sequence of steps are commonly referred to as **chain reaction mechanisms**. The distinguishing feature of a chain reaction mechanism is that it includes elementary steps known as **propagation steps**. A propagation step is a step wherein one reactive intermediate participates as a reactant and another reactive intermediate is formed as a product. The full set of propagation steps in the mechanism forms a closed sequence where each reactive intermediate is produced in one propagation step and consumed in a different propagation step. In a chain reaction mechanism, the apparent, non-elementary reaction is, in fact, a linear combination of the full set of propagation steps. As a consequence, propagation steps occur many, many more times than the other steps in the mechanism.

HBr synthesis, @eq-HBr_synthesis, is a non-elementary reaction. The HBr synthesis mechanism, Equations [-@eq-HBr_mech_step_1] through [-@eq-HBr_mech_step_4], is a classic example of a chain reaction mechanism. Notice that reactions [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] each consume one reactive intermediate and generate a different reactive intermediate. This makes reactions [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] propagation steps. More specifically, reaction [-@eq-HBr_mech_step_2] consumes a Br· reactive intermediate and generates an H· reactive intermediate. Then reaction [-@eq-HBr_mech_step_3] consumes an H· reactive intermediate and generates a Br· reactive intermediate. Adding just these two propagation steps together yields the apparent, non-elementary reaction [-@eq-HBr_synthesis].

$$
H_2 + Br_2 \rightleftarrows 2 HBr
$$ {#eq-HBr_synthesis}

$$
Br_2 \rightleftarrows 2 Br \cdot
$$ {#eq-HBr_mech_step_1}

$$
Br \cdot + H_2 \rightleftarrows HBr + H \cdot
$$ {#eq-HBr_mech_step_2}

$$
H \cdot + Br_2 \rightleftarrows HBr + Br \cdot
$$ {#eq-HBr_mech_step_3}

$$
2 H \cdot \rightleftarrows H_2
$$ {#eq-HBr_mech_step_4}

While the sum of the two propagation steps, [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3], equals the apparent non-elementary reaction, the other steps are still needed. This can be seen by noting that if neither reaction [-@eq-HBr_mech_step_1] nor reaction [-@eq-HBr_mech_step_4] ever occurred, then there would not be any reactive intermediates present, and that would mean that the propagation steps could not occur. In theory, either reaction [-@eq-HBr_mech_step_1], in the forward direction, or reaction [-@eq-HBr_mech_step_4], in the reverse direction, would need to occur at least one time in order to get the propagation sequence going. Steps [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] could then occur over and over until all of the Br~2~ or all of the H~2~ was used up. At that point, reaction [-@eq-HBr_mech_step_1], in the reverse direction, or reaction [-@eq-HBr_mech_step_4], in the forward direction, would need to occur one time to use up the reactive intermediates.

Reactions [-@eq-HBr_mech_step_1] and [-@eq-HBr_mech_step_4] are examples of two additional kinds of steps found in chain reaction mechanisms. These kinds of steps are known as **initiation steps** and **termination steps**. An elementary initiation step does not have a reactive intermediate as a reactant, but it generates one or more reactive intermediates as products. Similarly, termination steps consume reactive intermediates without producing any new ones. As noted above, even though initiation and termination steps only need to occur a small number of times compared to the propagation steps they are still a necessary kind of elementary reaction step for a chain reaction mechanism.

It has already been noted that every elementary step must be reversible. As such, the definitions just given for initiation and termination steps don’t make much sense because the reverse of any initiation step will be a termination step by definition, and similarly, the reverse of any termination step will be an initiation step. It is perhaps better to refer to them as initiation/termination steps. Usually, when one says that a step is an initiation step, what is meant is that the step in the forward direction, as written, is an initiation step. Commonly, the mechanistic steps corresponding to an apparent, non-elementary reaction will be written so that the reactants in the initiation step are also reactants in the apparent, non-elementary reaction reaction.

**Chain transfer steps** can also appear in chain reaction mechanisms. These steps are common in free radical polymerization mechanisms. In free radical polymerization, a very long hydrocarbon molecule (the so-called chain) has a free radical at one end. Monomer molecules react with the free radical end of the growing polymer chain, with the net result that the chain is longer by one monomer unit and still has a free radical at the end. In a chain transfer step, a monomer adds to the end of a growing polymer chain, but the free radical transfers to a different molecule. That is, a chain transfer step terminates one growing chain and starts a new one.

Yet another type of step in chain reactions is known as a **chain branching step**. Chain branching steps must be kept under control; if they are not controlled, they can lead to explosions. In an elementary chain branching step, one reactive intermediate is consumed, but two new reactive intermediates are generated. Clearly if these steps get out of control, the number of reactive intermediates will increase geometrically. This, coupled with the fact that reactive intermediates are so highly reactive, is why explosions can result from uncontrolled chain branching steps.

If it is not possible to identify propagation steps in a reaction mechanism, then the mechanism consists of an open sequence of reaction steps. **Open sequence mechanisms** are a little less common than closed sequences. The reason has to do with the energy required for a reaction to take place. If, for example, in a chain reaction mechanism, the initiation step requires a significant energy input, but the propagation steps do not, the apparent, non-elementary reaction is able to proceed with relative ease because the initiation step only needs to occur a small number of times. In contrast, if one step in an open sequence of steps requires a significant energy input, that amount of energy will be required every time the apparent, non-elementary reaction takes place.

Reagents participate in a chemical reaction according to a fixed stoichiometry. For example every time one H~2~ molecule participates in reaction [-@eq-HBr_synthesis], one Br~2~ molecules also participates and two HBr molecules are produced. The propagation steps in a chain reaction mechanism, and all of the steps in an open sequence reaction mechanism, must obey a similar kind of stoichiometry. For example, each time the apparent, non-elementary HBr synthesis reaction occurs, each of the propagation steps, [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3], must occur one time. The  **stoichiometric number**, $\sigma_e$, of mechanistic step $e$ (not to be confused with the stoichiometric coefficient, $\nu_{i,j}$, of reagent $i$ in reaction $j$) is defined as the number of times mechanistic step $e$ must occur when the apparent, non-elementary reaction, $j$ occurs one time. Put differently, in the linear combination of the mechanistic steps that equals the apparent, non-elementary reaction, the coefficient that multiplies each mechanistic step is the stoichiometric number of that step. Thus, the stoichiometric numbers of steps [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] are each equal to 1. For some steps in a reaction mechanism, it is not possible to assign a unique stoichiometric number. For example, the initiation and terminations steps above, reactions [-@eq-HBr_mech_step_1] and [-@eq-HBr_mech_step_4], do not have unique stoichiometric numbers.

Identifying the types of reactions in a chain reaction mechanism and ensuring that the mechanism satisfies the rule that there must be some linear combination of the mechanistic steps that exactly equals the apparent, non-elementary reaction is illustrated in [Example -@sec-example_5_1].

## Generating Rate Expressions from Mechanisms

Once a proposed mechanism has been checked to make sure it obeys the rules given above, it can be used to generate an expression for the apparent rate of generation of a reactant or product in the corresponding non-elementary reaction. Specifically, the net rate of generation of species $i$ in the overall macroscopically observed reaction, $j$, will be the sum of its rates of generation in each of the mechanistic steps. That is, the apparent rate of generation of $i$ via the non-elementary reaction, $j$, is given by @eq-gen_rate_from_mech, where $i$ is a reactant or product in the apparent, non-elementary reaction, $j$. Because the steps are elementary, their rates are given by @eq-rate_mech_step, leading to @eq-gen_rate_expr_from_mech as the expression for the apparent rate of generation of $i$ via non-elementary reaction $j$. In *Reaction Engineering Basics*, such rate expressions are referred to as **mechanistic rate expressions**. Examples [-@sec-example_5_1], [-@sec-example_5_2], [-@sec-example_5_4], and [-@sec-example_5_5] illustrate the use of Equations [-@eq-gen_rate_from_mech] and [-@eq-gen_rate_expr_from_mech] in problems involving the generation of a rate expression from a mechanism.

$$
r_{i,j} =\sum_e\nu_{i,e}r_e
$$ {#eq-gen_rate_from_mech}

$$
r_{i,j} = \sum_e\nu_{i,e} \left(k_{e,f} \prod_{n_r}\left[ n_r \right]^{-\nu_{n_r,e}} - k_{e,r}\prod_{n_p}\left[ n_p \right]^{\nu_{n_p,e}} \right)
$$ {#eq-gen_rate_expr_from_mech}

Generally @eq-gen_rate_expr_from_mech leads to a mechanistic rate expression that is not very useful for reaction engineering purposes. Specifically, the resulting mechanistic rate expression will contain several terms, and it will include concentrations of reactive intermediates. The latter are present in a real system in very small concentrations. These concentrations are typically unknown, and they are very difficult to measure accurately. That makes it difficult to use a mechanistic rate expression in its initial form and makes it desirable to simplify it. Simplification is accomplished by making different assumptions. Of course, the resulting simplified rate expression will only be valid if the assumptions are valid and if the underlying mechanism is correct.

It is sometimes observed that the rate of one particular mechanistic step has virtually no effect upon the apparent rate of the macroscopically observed reaction. Steps of this kind can be referred to as **kinetically insignificant steps**. This leads to an assumption that can be used to simplify a mechanistic rate expression. If a mechanistic step is assumed to be kinetically insignificant, its rate can be set equal to zero as shown in @eq-kin_insignificant_step. Example [-@sec-example_5_2] shows the use of @eq-kin_insignificant_step during the generation of mechanistic rate expression.

$$
r_{e,\text{insignificant}} = 0
$$ {#eq-kin_insignificant_step}

Similarly, it is sometimes observed that the rate in the reverse direction of a particular step is very small compared to its forward rate or that the step is thermodynamically able to go essentially to completion. In other words, it is an **effectively irreversible step**. If a mechanistic step is assumed to be effectively irreversible, the term corresponding to its rate in the reverse direction in @eq-rate_mech_step, is set equal to zero as shown in @eq-effectively_irreversible_step. Examples [-@sec-example_5_1], [-@sec-example_5_4], and [-@sec-example_5_5] illustrate the use of @eq-effectively_irreversible_step.

$$
r_{e,\text{irreversible}} = k_{e,f} \prod_{i_r} \left[ i_r \right]^{-\nu_{i_r,e}}
$$ {#eq-effectively_irreversible_step}

### The Bodenstein Steady State Approximation

@bodenstein_m_geschwindigkeit_1907 suggested an assumption related to reactive intermediates appearing in a reaction mechanism. As noted previously, reactive intermediates will be present at very low concentrations. This is a consequence of their high reactivity. As the reaction begins, the concentration of these species increases, but because they are so reactive, those intermediates formed undergo subsequent reaction very rapidly. In this way a steady state is quickly established whereby the rate at which reactive intermediates are being formed equals the rate at which they are undergoing subsequent reaction. Hence their concentration becomes constant and the overall rate of generation of the reactive intermediates becomes equal to zero. When the concentration of a species does not change over time, that concentration is said to be at steady state. For reactive intermediates, one can assume that this steady state condition always exists, ignoring the brief time required for the concentrations of the reactive intermediates to build up to their steady state values. This is known as the **Bodenstein steady state approximation**. To apply the steady state approximation, the expression for the overall rate of generation of each reactive intermediate is extracted from the reaction mechanism and set equal to zero, as shown in @eq-bodenstein_ss_approx. Examples [-@sec-example_5_1], [-@sec-example_5_2], [-@sec-example_5_4], and [-@sec-example_5_5] illustrate the use the Bodenstein steady state approximation in problems involving the generation of a rate expression from a mechanism.

$$
0 = \sum_e\nu_{RI,e}r_e
$$ {#eq-bodenstein_ss_approx}

If there are $N$ reactive intermediates in the mechanism, then @eq-bodenstein_ss_approx can be used once for each intermediate. This results in a set of $N$ algebraic equations. This set of $N$ equations can be solved for the concentrations of the $N$ reactive intermediates in terms of the rate coefficients in the mechanism and the concentrations of stable species such as the reactants and products of the apparent, non-elementary reaction. The resulting expressions for the concentrations of the reactive intermediates can be substituted back into the mechanistic rate espression from @eq-gen_rate_expr_from_mech. After doing so, the mechanistic rate expression for the apparent, non-elementary reaction will no longer contain concentrations of reactive intermediates, and it will be much more useful for reaction engineering purposes. This process is illustrated in Examples [-@sec-example_5_4] and [-@sec-example_5_5].

### Rate Determining Step

Sometimes one step in the mechanism is much more difficult or demanding than any of the other steps. This step introduces a bottleneck in the reaction kinetics; if the rate of this one step were somehow increased, the net rates of all the other steps and the observed overall rate would increase proportionally. This kind of step is referred to as a **rate-determining step** or a rate-limiting step. In situations where there is a rate-determining step, the rate expression can often be simplified considerably by making the assumption that the apparent rate of the non-elementary reaction, $r_j$ is equal to the rate of the rate- determining step, $r_{e_\text{rds}}$, as shown in @eq-rds_rate_expr. Note that $r_j$ in @eq-rds_rate_expr is the apparent *general* rate of the apparent non-elementary reaction; it is *not* a species generation rate. It is important to recognize that not all mechanisms have a rate-determining step. The assumption of a rate-determining step during the generation of a rate expression from a mechanism is illustrated in Examples [-@sec-example_5_3], [-@sec-example_5_6], and [-@sec-example_5_7].

$$
r_j = r_{e_\text{rds}} = k_{e_\text{rds},f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e_\text{rds}}} - k_{e_\text{rds},r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e_\text{rds}}}
$$ {#eq-rds_rate_expr}

It is often stated that the rate determining step is the slowest step in the mechanism, but this is not an accurate statement. When the steps all have the same stoichiometric number (see above), then every step in the mechanism proceeds at the same net rate. If the rate determining step was much slower than the steps before it, then the concentrations of the reactants of the rate-determining step would continually build up. Eventually, the concentrations of the reactants of the rate-determining step would become sufficiently large to be observed macroscopically. At that point, it would no longer appear from a macroscopic perspective, that only the non-elementary reaction was taking place. It is more accurate to say that the rate-determining step is the kinetic bottleneck or that it is the most demanding step, than to incorrectly state that it is the slowest step. Its rate *determines* the rates of all the other mechanistic steps.

The concept of one step being more difficult or demanding can be put in more scientific terms. Recall that multiplying each mechanistic step by its stoichiometric number and summing yields the apparent, non-elementary reaction. Since free energy is a state function, the sum of the free energy change for each mechanistic step multiplied by the stoichiometric number of that step is equal to the free energy change for the apparent, non-elementary reaction, as expressed in @eq-delta_G_from_steps. If there is one mechanistic step, $e_{\text{rds}}$, wherein essentially all of the overall free energy change takes place, that one step is the rate-determining step, @eq-delta_G_from_rds. Since essentially all of the free energy change occurs in the rate-determining step, the free energy change for the other steps is essentially zero, @eq-delta_G_not_rds. Note, again, that there does not have to be a rate-determining step in a reaction mechanism.

$$
\Delta G_j = \sum_e \sigma_e \Delta G_e
$$ {#eq-delta_G_from_steps}

$$
\Delta G_j = \sigma_{e_{\text{rds}}} \Delta G_{e,\text{rds}}
$$ {#eq-delta_G_from_rds}

$$
\Delta G_{e,nrds} \approx 0
$$ {#eq-delta_G_not_rds}

If a rate-determining step exists for a particular reaction mechanism, there is another consequence. Since the free energy changes for all steps other than the rate-determining step are essentially zero, it may be assumed that all steps other than the rate- determining step reach a state of quasi-equilibrium. (Recall from thermodynamics that by definition the free energy change for a process at thermodynamic equilibrium is equal to zero.) This is expressed in @eq-quasi_equilibrium.

$$
K_{eq,e} = \prod_i \left[i\right]^{\nu_{i,e,nrds}}
$$ {#eq-quasi_equilibrium}

Note that the rate expression that results from the application of @eq-rds_rate_expr is likely to include the concentration of one or more reactive intermediates, and if it does, it is not suitable for many reaction engineering purposes. In those cases, however, the quasi-equilibration assumption, @eq-quasi_equilibrium, can be applied to all other steps. The resulting equilibrium expressions can be solved for the concentrations of the reactive intermediates in terms of the concentrations of the reactants, products and the equilibrium constants for the steps other than the rate-determining step. Upon substitution into @eq-rds_rate_expr, a rate expression more suitable for reaction engineering purposes results. The use of the assumption that steps other than the rate-determining step are quasi-equilibrated is illustrated in Examples [-@sec-example_5_3], [-@sec-example_5_6], and [-@sec-example_5_7].

Rate expressions that are derived with the assumption of a rate-determining step will only apply for environmental conditions that are far from equilibrium. Recall that the free energy change due to the rate-determining step is equal to the overall free energy change. However, as the system approaches thermodynamic equilibrium the overall free energy change approaches zero (by definition) and the free energy change for every step approaches zero (according to the principle of microscopic reversibility). Thus, as the system approaches thermodynamic equilibrium it is no longer possible to identify a rate-determining step, and as a consequence, rate expressions that are derived with the assumption of a rate-determining step will only apply for environmental conditions that are far from equilibrium.

### Homogeneous Catalytic and Enzymatic Reaction Mechanisms

Recall that a catalyst is a material that causes the rate of one or more chemical reactions to increase, but the catalyst itself is not a reactant or product of the apparent non-elementary reaction. In some cases, the catalyst is present within the same phase as the reacting fluid. In this case the catalyst is referred to as a **homogeneous catalyst**. For present purposes, an **enzyme** may be considered to be a homogeneous catalyst for biological reactions, and for the remainder of this sub-section any discussion concerning catalysts also applies to enzymes unless noted otherwise. 

In mechanisms for catalytic reactions, the catalyst appears in several different chemical forms. That is, some of the catalyst will be free (not bonded to anything), while some catalyst will be complexed (chemically bound) with reactants, products, or other species. Each of the chemical forms of the catalyst can be treated as a reactive intermediate because it appears in the reaction mechanism, but not in the apparent, non-elementary reaction. The concentrations of the various chemical forms of the catalyst can be difficult to measure, making it desirable to eliminate them from mechanistic rate expressions using either the steady-state approximation or, when there is rate-determining step in the mechanism, quasi-equilibrium assumptions.

The presence of a catalyst leads to an additional complication when simplifying a mechanistic rate expression. When the Bodenstein steady state approximation is applied to each of the chemical forms of the catalyst, it is found that the resulting equations cannot be solved to obtain expressions for the concentrations of the reactive intermediates as is done for non-catalytic mechanisms. The reason is that when the free catalyst and all the complexes it forms are treated as a reactive intermediates, the equations generated using the Bodenstein steady state approximation are not mathematically independent. One of the Bodenstein steady state equations must be replaced.

The equation that replaces one of the Bodenstein steady state equations is an expression for the **conservation of catalyst**. While the concentrations of the various chemical forms of the catalyst aren’t known, the total amount of catalyst originally added to the system usually is known, and it is a constant. Since catalyst is not generated nor consumed by reaction, the sum of the concentrations of all forms of the catalyst (free, reactant-complexed, intermediate-complexed, and product-complexed) must equal the known total concentration of catalyst. This is expressed in @eq-cat_conservation where $\kappa_i$ is the number of catalyst species in the form originally added to the system that are needed to create one complex of the catalyst with species $i$. When one of the Bodenstein steady state equations is replaced by @eq-cat_conservation, the resulting set of equations is mathematically independent. They can be solved to obtain expressions for the concentrations of each reactive intermediate in terms of only rate coefficients, concentrations of stable species and the total concentration of the catalyst in its initial form, $C_{0,cat}$. The use of @eq-cat_conservation is illustrated in Examples [-@sec-example_5_4] and [-@sec-example_5_5]

$$
C_{0,cat} = C_{cat,free} + \sum_{ic}\kappa_{ic}C_{ic}
$$ {#eq-cat_conservation}

A similar complication can arise for either catalytic or non-catalytic reactions if the mechanism involves ionic species. In that case, instead of requiring the total amount of catalyst to be conserved, **charge conservation** must be enforced. If the reacting solution is uncharged, this means that the sum of the amounts of all positively charged species multiplied by their respective charges must equal the sum of the amounts of all negatively charged species multiplied by their respective charges, as expressed in @eq-charge_conservation. That equation can then be used to replace one of the Bodenstein steady state equations, leading to a mathematically independent set of equations.

$$
0 = \sum_{i_+} C_{i_+}q_{i_+} + \sum_{i_-} C_{i_-}q_{i_-}
$$ {#eq-charge_conservation}

While enzyme catalysis and homogeneous chemical catalysis are the same in many respects, there are some differences. The term “substrate” is typically used instead of "reactant". In catalytic systems, a reagent that binds with the catalyst and renders it catalytically inactive is called a **catalyst poision**. The equivalent in an enzymatic reaction is called an **enzyme inhibitor**. Typically an enzyme is a large molecule that has many twists and folds in its structure, and the catalysis associated with the enzyme takes place when the substrate binds to one particular location within the overall structure. Inhibitors are often molecules that also bind to the particular location where the catalysis takes place. When an inhibitor molecule is bound in this way, the enzyme becomes catalytically inactive until such time that the inhibitor releases from it. In addition to inhibition, some enzymes require **cofactor** molecules. A cofactor molecule is often a relatively small inorganic molecule that has the effect of activating an enzyme when it binds to it. That is, the enzyme alone is not active, but when a cofactor binds to it, it becomes catalytically active.

In terms of simplifying mechanistic rate expressions, the concentrations of poisons, inhibitors, and cofactors that are not complexed with a catalyst or enzyme is often easily measured. In this case, it is acceptable for reaction engineering purposes for the concentrations of uncomplexed poisons, inhibitors, and cofactors to appear in the rate expression for the apparent, non-elementary reaction. If, for some reason, the presence of these concentration in the rate expression was undesirable, the poision, inhibitor, or cofactor could be treated as a conserved species. Doing so would lead to their total concentration appearing in the rate expression instead of the concentration of the uncomplexed form. Generation of a mechanistic rate expression when the mechanism includes an inhibitor is illustrated in Example [-@sec-example_5_5].

### Heterogeneous Catalytic Reaction Mechanisms

Many industrial processes utilize **heterogeneous catalysts**; they are a separate phase that is in contact with the reacting fluid. Most typically the catalyst is solid while the reagents are in a gaseous or liquid phase. The reaction actually takes place on the surface of the catalyst at specific locations called **active sites**. When writing a mechanistic step that involves an active site, it is common to use some type of star to represent the site, e. g. $\ast$. Reactants, intermediates and products can bond to these sites in much the same way as they can form complexes with homogeneous catalysts or enzymes. In heterogeneous catalysis, the bonding of a species in the reacting fluid phase to an active site on the surface of the catalyst is a process referred to as **adsorption**, and the surface complexes that are generated are called adsorbed species. The reverse process, where a species leaves the surface and enters the fluid phase is called **desorption**.

In simple situations, it is usually safe to assume that the total surface area of the heterogeneous catalyst remains constant during the course of the reaction. It can also be safely assumed that the number (and therefore the concentration) of active sites, $C_{sites}$, remains constant. Note that this is a two- dimensional concentration (sites per surface area) not a three dimensional one (sites per volume). In heterogeneous catalytic kinetics, the concentration of an adsorbed species, $i$, is usually expressed in terms of the fraction of the total sites that it covers, $\theta_i$. This quantity is then referred to as the **fractional coverage** or the surface coverage of species $i$. When this is done, the concentration, $C_{i_{surf}}$ of any surface species, $i_{surf}$, that adsorbs on a single site is given by @eq-surf_conc_to_coverage.

$$
C_{i_{surf}} = C_{sites} \theta_i
$$ {#eq-surf_conc_to_coverage}

Transition state theory can be used to derive the mathematical form of rate expressions for an elementary surface reaction. When this is done, the concentration of sites, $C_{sites}$, can be combined with the pre-exponential factor of the rate coefficient. After doing so, the resulting rate expression for an elementary surface reaction, $j$, is given in @eq-elem_surf_reaction_rate.

$$
r_j = k_{j,f}\prod_{i_{r}}\left[ i_{r} \right]^{- \nu_{i_{r},j} } \prod_{i_{rs}}\theta_{i_{rs}}^{- \nu_{i_{rs},j} } - k_{j,r}\prod_{i_{p}}\left[ i_{p} \right]^{ \nu_{i_p,j} }\prod_{i_{ps}}\theta_{i_{ps}}^{ \nu_{i_{ps},j}}
$$ {#eq-elem_surf_reaction_rate}

For reaction engineering purposes, it is not desirable to have a rate expression that contains surface coverages because they are typically unknown and difficult to measure. Therefore, the mechanistic rate expression is simplified using the Bodenstein steady state approximation or other valid assumptions. Similar to homogeneous and enzymatic catalysis, the heterogeneous catalytic sites are conserved, and one Bodenstein steady state equation must be replaced by an expression for the conservation of catalytic sites. In the case of heterogeneous catalysis, the conservation of catalytic sites takes the form shown in @eq-cons_surf_sites.

$$
\theta_{\text{vacant}} + \sum_{i_s} \theta_{i_s} = 1
$$ {#eq-cons_surf_sites}

The generation of a mechanistic rate expression from a heterogeneous catalytic reaction mechanism is illustrated in Examples [-@sec-example_5_6] and [-@sec-example_5_7].

### Most Abundant Intermediate

Catalytic reaction mechanisms (homogeneous, enzymatic or heterogeneous) are subtly different from non-catalytic reaction mechanisms. During non-catalytic reactions, the amount of every reactive intermediate is small. This makes their concentration difficult to measure, leading to the necessity to eliminate those concentrations from rate expressions for the non-elementary reaction. During catalytic reactions the total number of reactive intermediates is not necessarily small, it is determined by the amount of catalyst present. As a result, some of the intermediates in catalytic reactions will be present in significant amounts. Nonetheless, measuring the concentrations of those intermediates is still very difficult, so it is common to eliminate their concentrations from mechanistic rate expressions. That is, even though their concentration may be greater than reactive intermediates in non-catalytic reactions, the non-complexed catalyst and each complexed form of a catalyst or enzyme is treated as a reactive intermediate. This also applies to vacant sites and each adsorbed surface species in a heterogeneous catalytic reaction mechanism.

As a consequence of the larger concentrations of catalytic intermediates, it is possible that during reaction, most of the catalyst, enzyme or catalyst sites are complexed with one reagent. If so, that complex is called the **most abundant intermediate**. Mathematically, when there is a most abundant intermediate, @eq-fluid_mai applies for a homogeneous catalytic or enzymatic mechanism and @eq-surf_mai applies for a heterogeneous catalytic reaction mechanism. These inequalities can sometimes lead to additional simplification of the apparent rate expression for the non-elementary reaction. This happens when the apparent rate expression has a denominator with several terms. When there is a most-abundant intermediate, some of the terms in these denominators may be much smaller than others and so can be deleted without affecting the accuracy of the rate expression. The simplification of a mechanistic rate expression when there is a most abundant intermediate in the mechanism is illustrated in [Example -@sec-example_5_7].

$$
C_{i,ma} \gg C_{i,nma}
$$ {#eq-fluid_mai}

$$
\theta_{i,ma} \gg \theta_{i,nma}
$$ {#eq-surf_mai}

## Examples

### Validity, Classification of Steps and Mechanistic Rate Expression for a Chain Reaction Mechanism {#sec-example_5_1}

{{< include ../RE_Basics_Examples/reb_5_1/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

This is clearly a mechanistic rate expression problem. In general, to solve mechanism problems like this it will be necessary to identify the reactive intermediates. I prefer to do that first. The reactive intermediates are the reagents that appear in one or more mechanistic steps, but they do not appear in the apparent, non-elementary reaction.

Once I've done that, the problem asks me to classify each step in the mechanism. I can do that knowing that initiation steps have no reactive intermediates as reactants and one or more reactive intermediates as products, while termination steps have one or more reactive intermediates as reactants and no reactive intermediates as products. Propagation steps have one reactive intermediate among the reactants and a different reactive intermediate among the products. Chain branching steps have one reactive intermediate among the reactants and two reactive intermediates among the products. Chain transfer steps are usually found in polymerization reactions, so I don't expect to find any chain transfer steps in this mechanism.

The problem next asks me to show that there is a linear combination of the steps that equals the apparent, non-elementary reaction. I know that in chain mechanisms that linear combination usually involves only the propagation steps. For simple mechanisms like those considered in *Reaction Engineering Basics*, the necessary linear combination can usually be found by inspection.

Finally, the problem asks me to write the generalized rate expression predicted by the mechanism. Since no step is identified as rate-determining, I know I will need to choose a reactant or a product in the apparent, non-elementary reaction and sum the rates at which it is generated in each of the mechanistic steps. That will yield the generation rate for the reagent I choose, so finally I'll need to convert the result to a general reaction rate expression.

:::

**Reactive Intermediates**: $N \cdot$, $O \cdot$

**Initiation/Termination Steps**: Steps (2) and (5)

**Propagation Steps**: Steps (3) and (4)

By inspection it can be seen that adding steps (3) and (4) yields the apparent, non-elementary reaction, reaction (1).

The apparent rate of generation of any reactant or product in the apparent, non-elementary reaction can be found using @eq-gen_rate_from_mech.

$$
r_{i,j} = \sum_e\nu_{i,e}r_e
$$

In the case of NO, it does not appear in steps (2) or (5) and its stoichiometric coefficient in both step (3) and step (4) is 1. Substituting these values and expanding the sum leads to equation (6) for the apparent rate of generation of NO via reaction (1).

$$
r_{NO,1} = r_3 + r_4 \tag{6}
$$

All steps in a reaction mechanism are elementary. As a consequence, the mathematical form of $r_3$ and $r_4$ is given by @eq-rate_mech_step.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$

Applying this expression to reactions $r_3$ and $r_4$ yields equations (7) and (8).

$$
r_3 = k_{3,f} \left[ O \cdot \right] \left[ N_2 \right] - k_{3,r} \left[ NO \right] \left[ N \cdot \right] \tag{7}
$$

$$
r_4 = k_{4,f} \left[ N \cdot \right] \left[ O_2 \right] - k_{3,r} \left[ NO \right] \left[ O \cdot \right] \tag{8}
$$

The problem asks for the reaction rate, not the rate of generation of NO. They are related by definition.

$$
r_{i,j} = \nu_{i,j} r_j \quad \Rightarrow \quad r_j = \frac{r_{i,j}}{\nu_{i,j}}
$$

$$
r_1 = \frac{r_{NO,1}}{\nu_{NO,1}} = \frac{r_{NO,1}}{2} \tag{9}
$$

**Calculations**

1. Substitute equation (6) into equation (9).
2. Substitute equations (7) and (8) into the resulting equation.

**Final Answer and Discussion**

$$
\begin{align}
r_1 =&\, 0.5k_{3,f} \left[ O \cdot \right] \left[ N_2 \right] - 0.5k_{3,r} \left[ NO \right] \left[ N \cdot \right] \\
& + 0.5k_{4,f} \left[ N \cdot \right] \left[ O_2 \right] - 0.5k_{3,r} \left[ NO \right] \left[ O \cdot \right] 
\end{align} \tag{10}
$$

It will be seen in later chapters of *Reaction Engineering Basics*, that a reaction engineer will commonly use the rate expression by substituting it into mole and energy balances on a reactor (see [Appendix -@sec-ideal-reactor-models]). When writing those mole and energy balances, the reaction engineer will not know the reaction mechanism; the reaction engineer will only know that reaction (1) takes place and that equation (10) is the rate expression for reaction (1).

The mole and energy balances will include variables for the amounts of N~2~, O~2~, and NO, but they will *not* include variables for the amounts of N∙ and O∙. Furthermore, there is no way to calculate the concentrations of N∙ and O∙ because they are not stoichiometrically related to the concentrations of N~2~, O~2~, and NO. Without concentrations of N∙ and O∙, it is not possible to evaluate the reaction rate, and consequently the reaction engineer will not be able to solve the mole and energy balances on the reactor.

For this reason, the initial form of rate expressions generated from mechanisms is not useful for reaction engineering purposes. In order to perform reaction engineering tasks, the rate expression must be simplified so that it does not contain concentrations of reactive intermediates.

:::{.callout-note collapse="false"}
## Note

The reaction engineer could use an alternative approach if the mechanism was known. Instead of assuming that only the apparent, non-elementary reaction takes place, the reaction engineer could assume that reactions (2) through (5) occur in the reactor. In that case, the mole and energy balances would include variables for the amounts of the reactive intermediates and it *would* be possible to evaluate the rates of the reactions.

However, that approach introduces a different problem. If the mechanistic reactions are used, the rate expressions for each of the mechanistic steps are needed. That means, for example, that experiments would need to be performed to find the values of $k_{3,f}$, and $k_{3,r}$ in equation (7). Performing those experiments would require setting and/or measuring the concentrations of N∙ and O∙. Because N∙ and O∙ are highly reactive, setting and measuring their concentrations is very difficult. In other words, the difficult and demanding task of estimating the values of the kinetics parameters in the mechanistic rate expressions would be necessary if the reaction engineer opted for this alternative approach.

:::

### Mechanistic Rate Expression for HBr Synthesis using the Bodenstein Steady State Approximation {#sec-example_5_2}

{{< include ../RE_Basics_Examples/reb_5_2/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

This problem involves generation of a mechanistic rate expression from the mechanism for an apparent, non-elementary reaction. The problem does not identify a rate-determining step and it instructs me to use the Bodenstein steady state approximation. From this I know that the solution will involve three steps. First, I need to generate an expression for the generation of a reagent, in this case, HBr, by summing its rate of generation in each of the mechanistic steps. That expression will contain concentrations of reactive intermediates. To eliminate them, the next thing I need to do is to write the Bodenstein steady state approximation for each reactive intermediate and solve the resulting set of equations to obtain expressions for the concentrations of the reactive intermediates. Finally, I need to substitute the expressions for the concentrations of the reactive intermediates into the expression for the rate of generation of HBr.

In order to accomplish these steps I need to identify the reactive intermediates and I need rate expressions for each of the mechanistic steps, so that is where I will start. The reactive intermediates are the species that appear in the reaction mechanism, but not in the apparent, non-elementary reaction (1).

:::

**Reactive Intermediates**: H∙ and Br∙

**Necessary Equations**

Each of the mechanistic steps is an elementary reaction, so the mathematical form of the rate expressions is known to take the form shown in @eq-rate_mech_step.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$

The problem says to assume step (4) is effectively irreversible, so the second term in the expression for the rate of step (4), which is the rate in the reverse direction, is set equal to zero. The problem also states that step (5) is kinetically insignificant, so its rate is set equal to zero. The resulting rate expressions for the mechanistic steps then take the forms shown in equations (6) through(9).

$$
r_2 = k_{2,f} \left[ Br_2 \right] - k_{2,r} \left[ Br \cdot \right]^2 \tag{6}
$$

$$
r_3 = k_{3,f} \left[ Br \cdot \right] \left[ H_2 \right] - k_{3,r} \left[ HBr \right] \left[ H \cdot \right] \tag{7}
$$

$$
r_4 = k_{4,f} \left[ H \cdot \right] \left[ Br_2 \right] \tag{8}
$$

$$
r_5 = 0 \tag{9}
$$

The apparent rate of generation of a reagent in the apparent, non-elementary reaction is equal to the sum of its rate of generation in each of the mechanistic steps as given in @eq-gen_rate_from_mech.

$$
r_{i,j} = \sum_e\nu_{i,e}r_e
$$

Applying that equation to HBr yields equation (10).

$$
r_{HBr,1} = r_3 + r_4 \tag{10}
$$

The rate expression that will result upon substitution of equations (6) through (9) into equation (10) will not be useful for reaction engineering purposes because it will contain concentrations of reactive intermediates. To eliminate the concentrations of the reactive intermediates, the Bodenstein steady state approximation, @eq-bodenstein_ss_approx, can be applied to each of them.

$$
0 = \sum_e\nu_{RI,e}r_e
$$

The resulting Bodenstein steady state equations are shown in equations (11) and (12). After substitution of equations (6) through (9), these equations can be solved simultaneously to obtain expressions for the concentrations of H∙ and Br∙. The resulting expressions can then be substituted into the rate expression.

$$
0 = 2r_2 - r_3 + r_4 \tag{11}
$$

$$
0 = r_3 - r_4 - 2r_5 \tag{12}
$$

**Calculations**

1. Substitute equations (6) through (9) into all other equations.
2. Simultaneously solve equations (11) and (12) to obtain expressions for [H∙] and [Br∙].
3. Substitute the results from step 2 into the version of equation (10) resulting from step 1.

**Results and Final Answer**

Solving the Bodenstein steady state equations yields equations (13) and (14) for the concentrations of H∙ and Br∙. Substitution of those results into the rate expression yields a mechanistic rate expression for the apparent rate of generation of HBr via non-elementary reaction (1), as shown in equation (15).

$$
\left[ Br \cdot \right] = \sqrt{\frac{k_{2,f}}{k_{2,r}}} \sqrt{\left[ Br_2 \right]} \tag{13}
$$

$$
\left[ H \cdot \right] = \frac{k_{3,f}\sqrt{\frac{k_{2,f}}{k_{2,r}}} \sqrt{\left[ Br_2 \right]}\left[ H_2\right]}{k_{3,r}\left[ HBr\right] + k_{4,f}\left[ Br_2 \right]} \tag{14}
$$

$$
r_{HBr,1} = 2\frac{k_{3,f}k_{4,f}\sqrt{\frac{k_{2,f}}{k_{2,r}}} \left[ Br_2 \right]^{3/2}\left[ H_2\right]}{k_{3,r}\left[ HBr\right] + k_{4,f}\left[ Br_2 \right]} \tag{15}
$$

Before the rate expression in equation (15) could be used, it would be necessary to estimate the values of the kinetics parameters appearing in it. Using experimental data where the concentrations or partial pressures of H~2~, Br~2~ and HBr were varied and the corresponding values of the rate were measured, it would not be possible to obtain unique values for each of the five rate coefficients. This can be seen most easily by dividing the numerator and denominator of equation (15) by $k_{4,f}$ as shown in equation (16).

$$
r_{HBr,1} = 2\frac{k_{3,f}\sqrt{\frac{k_{2,f}}{k_{2,r}}} \left[ Br_2 \right]^{3/2}\left[ H_2\right]}{\frac{k_{3,r}}{k_{4,f}}\left[ HBr\right] + \left[ Br_2 \right]} \tag{16}
$$

Notice that $k_{2,f}$, $k_{2,r}$, and $k_{3,f}$ do not appear individually in the rate expression. They only appear together as the term, $k$, shown in equation (17). Similarly, $k_{3,r}$ and $k_{4,f}$ do not appear individually, but only together as the term, $k^\prime$, shown in equation (18). Consequently, the rate expression can be written as shown in equation (19).

$$
k = k_{3,f}\sqrt{\frac{k_{2,f}}{k_{2,r}}} \tag{17}
$$

$$
k^\prime = \frac{k_{3,r}}{k_{4,f}} \tag{18}
$$

$$
r_{HBr,1} = 2\frac{k \left[ Br_2 \right]^{3/2}\left[ H_2\right]}{k^\prime\left[ HBr\right] + \left[ Br_2 \right]} \tag{19}
$$

Statistical parameter estimation methods can be employed to find unique "best" values for $k$ and $k^\prime$. Looking at equation (17), it can be seen that arbitrary values can be selected for any two of the three rate coefficients, $k_{2,f}$, $k_{2,r}$, and $k_{3,f}$. As long as the value of the third rate coefficient was chosen so that $k$ was equal to its "best" value, the rate expression in equation (16) would be equally accurate. Thus, $k_{2,f}$, $k_{2,r}$, and $k_{3,f}$ are coupled. An infinite number of sets of values could be used and the accuracy of the rate expression would not change. The rate coefficients, $k_{3,r}$ and $k_{4,f}$, are similarly coupled. Whenever possible, **coupled kinetics parameters** in mechanistic rate expressions should be combined into a single parameter for which a unique value can be estimated. Put differently, for reaction engineering purposes, rate expression (19) is preferred over rate expression (16).

:::{.callout-note collapse="false"}
## Note

The coupled rate coefficients in this problem appeared in a term where they were multiplied, divided and raised to a constant power (here, the power was 1/2 corresponding to the square root). When terms like these are combined, the combined parameters, $k$ and $k^\prime$ in this case, will display Arrhenius temperature dependence and long as the original rate coefficients did so.

If rate coefficients are added or subtracted, this will not be true. That is, if $k = k_1 + k_2$, the combined rate coefficient $k$ will **not** display Arrhenius temperature dependence, even if $k_1$ and $k_2$ each do display Arrhenius temperature dependence.

:::

### Mechanistic Rate Expression from a Mechanism with a Rate-Determining Step {#sec-example_5_3}

{{< include ../RE_Basics_Examples/reb_5_3/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

This problem provides an apparent, non-elementary reaction and a proposed mechanism for that reaction. It asks me to generate a mechanistic rate expression. For this type of problem I know that I'll have to do two things. I'll need to write an expression for the rate of the non-elementary reaction in terms of the rates of the mechanistic steps. The resulting expression for the rate of the non-elementary reaction will contain concentrations of reactive intermediates, so the second thing I'll need to do is to eliminate those reactive intermediate concentrations.

In all problems like this I know I need to identify the reactive intermediates and I need expressions for the rates of the mechanistic steps, so that is what I'll do first. The reactive intermediates are the reagents that appear in the mechansim, but not in the non-elementary reaction. The mechanistic steps are elementary reactions by definition, so the mathematical form of their rate expressions is known.

I know two ways to write an expression for the rate of the non-elementary reaction in terms of the rates of the mechanistic steps: 1. pick a reactant or product in the non-elementary reaction and sum its rate of generation in all of the mechanistic steps and 2. assume one mechanistic step to be rate-determining. This problem tells me to use the latter approach.

I also know two ways to eliminate the concentrations of reactive intermediates from the rate expression for the non-elementary reaction: 1. use the Bodenstein steady state approximation if there isn't a rate-determining step, or 2. assume all steps other than the rate-determining step are quasi-equilibrated. Here, since there is a rate determining step, I'll use the quasi-equilibrium approach.

:::

**Reactive Intermediates**: $C_3H_5 \cdot$ and $I \cdot$

**Necessary Equations**

The mechanistic steps are elementary reactions, so their rate expressions are given by @eq-rate_mech_step.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$

Applying that equation to reactions (2), (3), and (4) yields the rate expressions in equations (5), (6), and (7).

$$
r_2 = k_{2,f} \left[ C_3H_5I \right] - k_{2,r} \left[ C_3H_5 \cdot \right] \left[ I \cdot \right] \tag{5}
$$

$$
r_3 = k_{3,f} \left[ C_3H_5I \right] \left[ I \cdot \right] - k_{3,r} \left[ C_3H_5 \cdot \right] \left[ I_2 \right] \tag{6}
$$

$$
r_4 = k_{4,f} \left[ C_3H_5 \cdot \right]^2 - k_{4,r} \left[ C_6H_{10} \right] \tag{7}
$$

If reaction (2) is rate-determining, then the apparent rate of the non-elementary reaction can be set equal to the rate of reaction (2) as shown in equation (8). That rate expression contains concentrations of reactive intermediates. 

$$
r_1 = r_2 \tag{8}
$$

To eliminate the concentrations of reactive intermediates, steps (3) and (4) can be assumed to be quasi-equilibrated, @eq-quasi_equilibrium.

$$
K_{eq,e} = \prod_i \left[i\right]^{\nu_{i,e}}
$$

Using that equation to write equilibrium expressions for reactions (3) and (4) results in equations (9) and (10).

$$
K_3 = \frac{\left[ C_3H_5 \cdot \right] \left[ I_2 \right]}{\left[ C_3H_5I \right] \left[ I \cdot \right]} \tag{9}
$$

$$
K_4 = \frac{\left[ C_6H_{10} \right]}{\left[ C_3H_5 \cdot \right]^2} \tag{10}
$$

Equations (9) and (10) can be solved to obtain expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙. After substituting equation (5) into equation (8), those expressions can then be substituted into the resulting equation. This eliminates the reactive intermediate concentrations to produce an acceptable rate expression.

If reaction (3) is rate-determining, then the apparent rate of the non-elementary reaction can be set equal to the rate of reaction (3) as shown in equation (11). That rate expression contains concentrations of reactive intermediates. To eliminate them, steps (2) and (4) can be assumed to be quasi-equilibrated leading to the equilibrium expressions shown in equations (10) and (12).

$$
r_1 = r_3 \tag{11}
$$

$$
K_2 = \frac{\left[ C_3H_5 \cdot \right] \left[ I \cdot \right]}{\left[ C_3H_5I \right]} \tag{12}
$$

Equations (10) and (12) can be solved to obtain expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙. After substituting equation (6) into equation (11), those expressions can then be substituted into the resulting equation. This eliminates the reactive intermediate concentrations to produce an acceptable rate expression.

If reaction (4) is rate-determining, then the apparent rate of the non-elementary reaction can be set equal to the rate of reaction (4) as shown in equation (13). That rate expression contains concentrations of reactive intermediates. To eliminate them, steps (2) and (3) can be assumed to be quasi-equilibrated leading to the equilibrium expressions shown in equations (9) and (12).

$$
r_1 = r_4 \tag{13}
$$

Equations (9) and (12) can be solved to obtain expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙. After substituting equation (7) into equation (13), those expressions can then be substituted into the resulting equation. This eliminates the reactive intermediate concentrations to produce an acceptable rate expression.

**Calculations**

1. Substitute equations (5) through (7) in all remaining equations.
2. For the case where step (2) is rate determining:
    a. Solve equations (9) and (10) to obtain expressions for [C~3~H~5~∙] and [I∙].
    b. Substitute the results into the version of equation (8) resulting from step 1.
3. For the case where step (3) is rate determining:
    a. Solve equations (10) and (12) to obtain expressions for [C~3~H~5~∙] and [I∙].
    b. Substitute the results into the version of equation (11) resulting from step 1.
4. For the case where step (4) is rate determining:
    a. Solve equations (9) and (12) to obtain expressions for [C~3~H~5~∙] and [I∙].
    b. Substitute the results into the version of equation (13) resulting from step 1.

**Final Answer**

When step (2) is assumed to be rate-determining, the expressions for the concentrations of [C~3~H~5~∙] and [I∙] shown in equations (14) and (15) are obtained by solving equations (9) and (10). Substitution into equation (8) yields the expression for the apparent rate of non-elementary reaction (1) shown in equation (16).

$$
\left[ C_3H_5 \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}} \tag{14}
$$

$$
\left[ I \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right]}{K_3 \sqrt{K_4}\left[ C_3H_5I \right]} \tag{15}
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - \frac{k_{2,r}}{K_3 K_4} \frac{\left[ C_6H_{10} \right] \left[ I_2 \right]}{\left[ C_3H_5I \right]} \tag{16}
$$

When step (3) is assumed to be rate-determining, the expressions for the concentrations of [C~3~H~5~∙] and [I∙] shown in equations (17) and (18) are obtained by solving equations (10) and (12). Substitution into equation (11) yields the expression for the apparent rate of non-elementary reaction (1) shown in equation (19).

$$
\left[ C_3H_5 \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}} \tag{17}
$$

$$
\left[ I \cdot \right] = \frac{K_2 \sqrt{K_4} \left[ C_3H_5I \right]}{\sqrt{\left[ C_6H_{10} \right]}} \tag{18}
$$

$$
r_1 = k_{3,f} K_2 \sqrt{K_4} \frac{\left[ C_3H_5I \right]^2}{\sqrt{\left[ C_6H_{10} \right]}} - \frac{k_{3,r}}{\sqrt{K_4}}\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right] \tag{19}
$$

When step (4) is assumed to be rate-determining, the expressions for the concentrations of [C~3~H~5~∙] and [I∙] shown in equations (20) and (21) are obtained by solving equations (9) and (12). Substitution into equation (13) yields the expression for the apparent rate of non-elementary reaction (1) shown in equation (22).

$$
\left[ C_3H_5 \cdot \right] = \sqrt{K_2K_3}  \frac{\left[ C_3H_5I \right]}{\sqrt{\left[ I_2 \right]}} \tag{20}
$$

$$
\left[ I \cdot \right] = \frac{\sqrt{K_2}}{\sqrt{K_3}} \sqrt{\left[ I_2 \right]} \tag{21}
$$

$$
r_1 = \frac{k_{4,f}K_2K_3\left[ C_3H_5I \right]^2}{\left[ I_2 \right]} - k_{4,r} \left[ C_6H_{10} \right] \tag{22}
$$

:::{.callout-note collapse="false"}
## Note

If thermodynamic data for the mechanistic steps are not available and the equilibrium constants are treated as kinetics parameters, then the parameters in the second term of equation (16) are coupled as was the case in [Example -@sec-example_5_2]. That is, it would not be possible to estimate unique values for k~2,r~, K~3~ and K~4~ using experimental kinetics data. Grouping the parameters to define an apparent rate coefficient as shown in equation (23) allows the rate expression to be written as equation (24). The apparent rate coefficient will exhibit Arrhenius temperature dependence and it will be possible to estimate a unique value for it.

$$
k_r^\prime = \frac{k_{2,r}}{K_3 K_4} \tag{23}
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - k_r^\prime \frac{\left[ C_6H_{10} \right] \left[ I_2 \right]}{\left[ C_3H_5I \right]} \tag{24}
$$

Similar grouping of the kinetics parameters in rate expressions (19) and (22) leads to equations (25) and (26)

$$
r_1 = k_f^\prime \frac{\left[ C_3H_5I \right]^2}{\sqrt{\left[ C_6H_{10} \right]}} - k_r^\prime \sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right] \tag{25}
$$

$$
r_1 = k_f^\prime \frac{\left[ C_3H_5I \right]^2}{\left[ I_2 \right]} - k_{4,r} \left[ C_6H_{10} \right] \tag{22}
$$

:::

### Michaelis-Menten Rate Expression for an Enzymatic Reaction {#sec-example_5_4}

{{< include ../RE_Basics_Examples/reb_5_4/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

I can see that this problem involves generation of a mechanistic rate expression. It provides an apparent, non-elementary reaction and a proposed mechanism for it, and it asks me to generate an expression for the apparent rate of the non-elementary reaction. I know that solving problems of this type takes two steps: 1. write an expression for the rate of the non-elementary reaction in terms of the rates of the mechanistic steps, and 2. eliminate the concentrations of reactive intermediates from the resulting rate expression.

I know that when solving this type of problem it is always necessary to identify the reactive intermediates, so I do that first. The reactive intermediates are species that appear in the reaction mechanism but not in the non-elementary reaction.

I also know that to solve this type of problem you always need rate expressions for each of the mechanistic steps, so I write those next. The mechanistic steps are elementary reactions, so the mathematical form of their rate expressions is known from theory. In this case, one reaction is effective irreversible, so for that reaction I will set the term corresponding to the rate of the reverse reaction equal to zero.

This problem does not identify a rate-determining step, so I will choose a reagent in the non-elementary reaction and set the rate of generation of that reagent equal to the sum of the rates at which it is generated in each mechanistic step.

The resulting rate expression will contain concentrations of reactive intermediates. Since there isn't a rate-determining step, I will use the Bodenstein steady state approximation to eliminate those concentrations. However, I also know that because this mechanism involves a catalyst, one of the equations resulting from the application of the Bodenstein steady state approximation will be mathematically dependent on the others and will need to be replaced. I can use an expression for the conservation of catalyst to replace one of the Bodenstein steady state equations. This will give me a set of equations I can solve to get expressions for the concentrations of the reactive intermediates. Once those expressions are substituted into the rate expression, it will be acceptable and useful for reaction engineering purposes.

:::

**Reactive Intermediates**: E and E-S

**Necessary Equations**

The mechanistic steps, reactions (2) and (3), are elementary reaction by definition. As such their mathematical form is known from theory to be as shown in @eq-rate_mech_step.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$

Applying that equation to reactions (2) and (3) yields the rate expressions for the mechanistic steps shown in equations (4) and (5). In equation (5), the term for the rate of reaction (3) in the reverse direction was set equal to zero because the problem says to assume it is effectively irreversible.

$$
r_2 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] \tag{4}
$$

$$
r_3 = k_{3,f} \left[ E\!-\!S \right] \tag{5}
$$

The apparent rate of generation of any reagent appearing in the non-elementary reaction will equal the sum of its rates of generation in the mechanistic steps, @eq-gen_rate_from_mech.

$$
r_{i,j} = \sum_e\nu_{i,e}r_e
$$

The product, P, only appears in step (3), so the summation above reduces to a single term when writing an expression for the apparent rate of generation of the product, P, as shown in equation (6).

$$
r_{P,1} = r_3 \tag{6}
$$

When equation (5) is substituted into equation (6), the resulting rate expression will contain the concentration of a reactive intermediate, namely E-S. The Bodenstein steady state approximation, @eq-bodenstein_ss_approx, can be used to eliminate the concentrations of reactive intermediates from rate expressions generated from mechanisms without a rate-determining step.

$$
0 = \sum_e\nu_{RI,e}r_e
$$

The Bodenstein steady state equation can be written for each of the reactive intermediates, E and E-S. However, because the mechanism includes a catalyst, those equations will not be mathematically independent. Applying the Bodenstein steady state approximation to E-S yields equation (7).

$$
0 = r_2 - r_3 \tag{7}
$$

When equations (4) and (5) are substituted into equation (7) it will contain the concentrations of both reactive intermediates. It isn't possible to solve that one equation to get expressions for two unknowns. An additional equation is needed, but writing the Bodenstein steady state approximation for E won't work because the resulting equation would not be mathematically independent from equation (7). Instead an expression for the conservation of catalyst, @eq-cat_conservation, can be used.

$$
C_{0,cat} = C_{cat,free} + \sum_{ic}\kappa_{ic}C_{ic}
$$

Here E~0~ will be used to represent the total amount of enzyme originally added to the system, expressed as a concentration. The only complexed form of the enzyme is E-S. That complex contains one original enzyme unit, so $\kappa_{E\!-\!S} = 1$, leading to the expression for the conservation of catalyst shown in equation (8).

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] \tag{8}
$$

After substitution of equations (4) and (5) into equation (7), it can be solved simultaneously with equation (8) to obtain expressions for the concentrations of E and E-S. Those expressions can then be substituted into equation (6), after first substituting equation (5). The resulting expression for the apparent rate of generation of P via non-elementary reaction (1) will not contain concentrations of reactive intermediates, making it useful for reaction engineering purposes.

**Calculations**

1. Substitute equations (4) and (5) into all other equations.
2. Solve equations (7) and (8) to obtain expressions for [E] and [E-S].
3. Substitute the resulting expressions in the version of equation (6) resulting from step 1.

**Final Answer**

The expressions for the concentrations of E and E-S shown in equations (9) and (10) result from solving equations (7) and (8). Substitution of those expression into equation (6) yields the expression for the apparent rate of generation of P via non-elementary reaction (1) shown in equation (11).

$$
\left[ E \right] = \frac{E_0}{1 + \frac{k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]} \tag{9}
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} E_0 \left[ S \right]}{k_{2,r}+ k_{3,f} + k_{2,f}\left[ S \right]} \tag{10}
$$

$$
r_{P,1} = \frac{k_{2,f} k_{3,f} E_0 \left[ S \right]}{k_{2,r} + k_{3,f} + k_{2,f}\left[ S \right]} = \frac{k_{3,f} E_0 \left[ S \right]}{\frac{k_{2,r} + k_{3,f}}{k_{2,f}} + \left[ S \right]} \tag{11}
$$

:::{.callout-note collapse="false"}
## Note

1. Michaelis and Menten [-@michaelis_l_kinetik_1913] studied enzymatic conversion of a substrate to product and were the first to propose a mechanistic rate epxression of the form of equation (11). They defined two kinetics parameters, $V_{max}$ and $K_m$, as shown in equations (12) and (13). Substitution of those definitions in equation (11) yields the so-called **Michaelis-Menten rate expression**, equation (14).

$$
V_{max} = k_{3,f} E_0 \tag{12}
$$

$$
K_m = \frac{k_{2,r} + k_{3,f}}{k_{2,f}} \tag{13}
$$

$$
r_{P,1} = \frac{V_{max} \left[ S \right]}{K_m + \left[ S \right]} \tag{14}
$$

2. The Michaelis-Menten rate expression above is non-linear with respect to the kinetics parameters. The parameters, $V_{max}$ and $K_m$, can be estimated using experimental kinetics data together with software for fitting non-linear models to data. Notice, however, that if the reciprocals of the two sides of the equation are set equal to each other as shown in equation (15), a linear model results. Specifically, defining $y$ and $x$ as shown in equations (16) and (17), it can be seen that the model has the linear form shown in equation (18) where the slope, $m$, and intercept, $b$, are given in equations (19) and (20).

$$
\frac{1}{r_{P,1}} = \left( \frac{K_m}{V_{max}}  \right) \frac{1}{\left[ S \right]} + \frac{1}{V_{max}} \tag{15}
$$

$$
y = \frac{1}{r_{P,1}} \tag{16}
$$

$$
x = \frac{1}{\left[ S \right]} \tag{17}
$$

$$
y = mx + b \tag{18}
$$

$$
m = \frac{K_m}{V_{max}} \tag{19}
$$

$$
b = \frac{1}{V_{max}} \tag{20}
$$

As was the case when the Arrhenius expression was linearized (see the note at the end of [Example -@sec-example_4_4]), a spreadsheet program could be used to create a plot of $\frac{1}{r_{P,1}}$ *vs*. $\frac{1}{\left[ S \right]}$. A plot of this type was used by Lineweaver and Burk [-@lineweaver_h_determination_1934], and today plots of the type are commonly called **Lineweaver-Burk** plots. By adding a trendline to the Lineweaver-Burk plot, the best estimates for $m$ and $b$ will be obtained. As equation (20) shows, the best estimate for $V_{max}$ is equal to the reciprocal of the best estimate for $b$. Then, as equation (19) shows, the best estimate for $K_m$ is equal to the best estimate for $m$ multiplied by $V_{max}$.

It can be noted in equation (13) that $K_m$ includes the sum of two rate coefficients. As such, $K_m$ will not display Arrhenius temperature dependence if it is measured over a sufficiently broad range of temperatures. Fortunately, enzymes are often active only in a narrow range of temperatures, and this does not become a problem.

:::

### Mechanistic Rate Expression from an Enzymatic Mechanism with an Inhibitor {#sec-example_5_5}

{{< include ../RE_Basics_Examples/reb_5_5/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

This problem identifies a non-elementary reaction (reaction (1)), it provides a proposed mechanism for that reaction (reactions (2) through (4)), and it asks me to generate an expression for the apparent rate of the non-elementary reaction. I call problems with these characteristics "mechanism problems," and I know that generally there are two steps involved in solving them. The first step is to write an expression for the apparent rate of the non-elementary reaction in terms of the rates of the mechanistic steps and the second step is to eliminate concentrations of reactive intermediates from the resulting apparent rate expression.

I also know that in order to solve this type of problem I need to identify the reactive intermediates, so I do that first. The reactive intermediates are the reagents that appear in the mechanism, but not in the non-elementary reaction.

I also know that I will need rate expressions for at least one of the mechanistic steps. The mechanistic steps are elementary reactions, so the mathematical form of their rate expressions is known from theory. For this problem, I'll write the rate expressions for all three reactions next.

The first step in solving the problem is to write an expression for the apparent rate of the non-elementary reaction in terms of the rates of the mechanistic steps. Potentially there are two ways to do this, but one of them requires there to be a rate-determining step. The problem statement does not mention that any step is rate-determining, so I must use the other way to write the rate expression: set the apparent rate of generation of one of the reagents in the non-elementary reaction equal to the sum of its rates of generation in each of the mechanistic steps.

The second step is to eliminate the concentrations of reactive intermediates from the rate expression. Again, in general there are two ways to do this, but one of them only applies when there is a rate determining step. So again, I'll use the other way; I'll write the Bodenstein steady state approximation for each reactive intermediate in the system.

In this problem there are 3 reactive intermediations, so that will yield three equations. However, I know that if I try to solve those three equations to obtain expressions for the concentrations of the reactive intermediates it won't work. The reason is that this mechanism involves a catalyst. When a mechanism involves a catalyst, the Bodenstein steady state equations are not mathematically independent. I know I'll need to replace one of them, and when there is a catalyst, I know to use an expression for the conservation of catalyst to replace one of the Bodenstein steady state equations.

That will give me three equations that I can solve to get expressions for the concentrations of the three reactive intermediates. The latter can be substituted into the rate expression to eliminate the reactive intermediate concentrations from it.

:::

**Reactive Intermediates**: E, E-S, and E-I

**Necessary Equations**

The mechanistic reaction steps are elementary by definition. As a consequence, their mathematical form is known from theory as shown in @eq-rate_mech_step.

$$
r_e = k_{e,f} \prod_{i_r}\left[ i_r \right]^{-\nu_{i_r,e}} - k_{e,r}\prod_{i_p}\left[ i_p \right]^{\nu_{i_p,e}}
$$

That equation can be used here to write rate expressions for steps (2) through (4) as shown in equations (5) through (7). The second term in the rate expression for step (4), corresponding to the rate of the reaction in the reverse direction, is set equal to zero here because the problem states that step (4) is effectively irreversible.

$$
r_2 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] \tag{5}
$$

$$
r_3 = k_{3,f} \left[ E \right] \left[ I \right] - k_{3,r} \left[ E\!-\!I \right] \tag{6}
$$

$$
r_4 = k_{4,f} \left[ E\!-\!S \right] \tag{7}
$$

The apparent rate of generation of any reagent in the non-elementary reaction is the sum of its rate of generation in each of the mechanistic steps, @eq-gen_rate_from_mech. 

$$
r_{i,j} = \sum_e\nu_{i,e}r_e
$$

An expression for the apparent generation of either S or P can be written using that equation. A stoichiometrically consistent answer will be obtained whichever is chosen. Here the apparent rate of generation of P via reaction (1) was selected because P only appears in one mechanistic step. That reduces the summation above to a single term as shown in equation (8).

$$
r_{P,1} = r_4 \tag{8}
$$

Looking at equation (7) it can be seen that when the rate expression for step (4) is substituted into equation (8), the resulting rate expression will contain the concentration of the reactive intermediate, E-S. The Bodenstein steady state approximation, @eq-bodenstein_ss_approx, can be used to eliminate it from the rate expression.

$$
0 = \sum_e\nu_{RI,e}r_e
$$

The Bodenstein steady state equation above can be written for each of the three reactive intermediates, but only two of the three resulting equations will be mathematically independent. Hence, Bodenstein steady state expressions are only written for two of the intermediates. Here Bodenstein steady state equations have been written for E-S and E-I, equations (9) and (10).

$$
0 = r_2 - r_4 \tag{9}
$$

$$
0 = r_3 \tag{10}
$$

An expression for the conservation of catalyst, @eq-cat_conservation, can be used to replace the third Bodenstein steady state approximation.

$$
C_{0,cat} = C_{cat,free} + \sum_{ic}\kappa_{ic}C_{ic}
$$

In this problem, $E_0$ is used to represent the amount of catalyst (enzyme) originally added to the system, expressed as a concentration. There are two complexed forms of the enzyme, E-I and E-S. Each of these contains one original enzyme unit, so $\kappa_{E-S}$ and $\kappa_{E-I}$ are both equal to one. The resulting catalyst conservation equation then takes the form shown in equation (11).

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] + \left[ E\!-\!I \right] \tag{11}
$$

**Calculations**

1. Substitute equations (5) through (7) into all other equations.
2. Solve the resulting versions of equations (9) through (11) to obtain expressions for $\left[ E \right]$, $\left[ E\!-\!S \right]$, and $\left[ E\!-\!I \right]$.
3. Substitute the result into the version of equation (8) that resulted from step 1.

**Results and Final Answer**

Solving equations (9) through (11) yields the expressions for the concentrations of E, E-S, and E-I shown in equations (12) through (14). Substitution of equation (7) and these expressions into equation (8) then gives the rate expression shown in equation (15).

$$
\left[ E \right] = \frac{k_{3,r} \left( k_{2,r} + k_{4,f} \right) E_0}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{12}
$$

$$
\left[ E\!-\!I \right] = \frac{k_{3,f} \left( k_{2,r} + k_{4,f} \right) E_0 \left[ I \right]}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{13}
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} k_{3,r} E_0 \left[ S \right]}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{14}
$$

$$
r_{P,1} = \frac{k_{4,f} E_0 \left[ S \right]}{\left[ S \right] + \frac{k_{2,r} k_{3,f} + k_{3,f} k_{4,f}}{k_{2,f} k_{3,r}} \left[ I \right] + \frac{k_{2,r} k_{3,r} + k_{3,r} k_{4,f}}{k_{2,f} k_{3,r}}} \tag{15}
$$

The problem asks for "Michaelis-Menten type rate expression." In a manner analogous to the note at the end of [Example -@sec-example_5_4], The kinetics parameters, $V_{max}$, $K_m$, and $K_I$, can be defined as shown in equations (16) through (18). Substitution into equation (15) then yields the Michaelis-Menten type rate expression shown in equation (19).

$$
V_{max} = k_{4,f} E_0 \tag{16}
$$

$$
K_m = \frac{k_{2,r} k_{3,r} + k_{3,r} k_{4,f}}{k_{2,f} k_{3,r}} \tag{17}
$$

$$
K_I = \frac{k_{2,r} k_{3,f} + k_{3,f} k_{4,f}}{k_{2,f} k_{3,r}} \tag{18}
$$

$$
r_{P,1} = \frac{V_{max} \left[ S \right]}{K_m + K_I \left[ I \right] + \left[ S \right]} \tag{19}
$$

:::{.callout-note collapse="false"}
## Note

Because they contain sums of rate coefficients, $K_m$ and $K_I$ in equation (19) are not expected to exhibit Arrhenius temperature dependence over a wide range of temperatures. That said, enzymes often are stable only over a relatively narrow range of temperatures in which case this probably won't cause problems.

:::

### Langmuir-Hinshelwood Rate Expression for a Heterogeneous Catalytic Reaction {#sec-example_5_6}

{{< include ../RE_Basics_Examples/reb_5_6/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

Once again, I can see that this is a mechanism problem because it provides an apparent, non-elementary reaction and a mechanism for that reaction and it asks me to generate an expression for the apparent rate of the non-elementary reaction. As was the case in the other problems in this chapter, I know that I will need to identify the reactive intermediates (that is, the reagents that appear in the mechanism, but not in the non-elementary reaction) in order to solve it. So the first thing I will do is to identify the reactive intemediates.

In most of the previous examples in this chapter the next thing I did was to write rate expressions for each of the steps in the mechanism. I did this when there wasn't a rate-determining step in the problem, because I knew I would use those rate expressions in both the non-elementary reaction rate expression and in the Bodenstein steady state equations. It would not hurt to do it here, but I know that when the problem involves a rate-determining step, I'll only need the rate expression for that one step, so I'm not going to write all of them.

I also notice that this is a heterogeneous catalytic reaction. I know that when I write either rate expressions or equilbrium expressions for heterogeneous catalytic reactions I should use fraction coverages instead of concentrations for any surface species.

The first step when solving a mechanism problem is to write an expression for the rate of the apparent, non-elementary reaction in terms of the rates of the mechanistic steps. When the mechanism *does not* include a rate-determining that involves setting the rate of generation of a reactant or product in the non-elementary reaction equal to the sum of its rates of generation in each of the mechanistic steps. Here, the mechanism *does* include a rate-determining step, so I know to simply set the rate of the apparent, non-elementary reaction equal to the rate of the rate determining step.

The other step when solving a mechanism problem is to eliminate concentrations of reactive intermediates from the rate expression. Again, the way this is done depends upon whether or not there is a rate-determining step in the mechanism. Where there isn't a rate determining step, I can use the Bodenstein steady state approximation, noting that for a catalytic reaction like this I would need to replace one Bodenstein steady state equation with an expression for the conservation of catalytic sites. Here, however, there *is* a rate-determining step, so I know that to eliminate concentrations (or coverages) of reactive intermediates from the rate expression I will need to write equilibrium expressions for every step *other than* the rate-determining step. I also know that I may also need to use an expression for the conservation of catalyst sites.

:::

**Reactive Intermediates**: $\ast$, $A\!-\!\ast$, $B\!-\!\ast$, $C\!-\!\ast$, and $D\!-\!\ast$

**Necessary Equations**

The problem states that mechanistic step (4) is rate-determining. As a consequence, the apparent general rate of the non-elementary reaction (1) is equal to the rate of the rate-determining step. Like all steps in a reaction mechanism, the rate-determining step is, by definition, an elementary reaction. That means that the mathematical form of the rate expression for step (4) is known from theory, @eq-elem_surf_reaction_rate.

$$
r_j = k_{j,f}\prod_{i_{r}}\left[ i_{r} \right]^{- \nu_{i_{r},j} } \prod_{i_{rs}}\theta_{i_{rs}}^{- \nu_{i_{rs},j} } - k_{j,r}\prod_{i_{p}}\left[ i_{p} \right]^{ \nu_{i_p,j} }\prod_{i_{ps}}\theta_{i_{ps}}^{ \nu_{i_{ps},j}}
$$

Setting the rate of the non-elementary reaction equal to the rate of step (4) leads to the rate expression shown in equation (7). It clearly contains surface coverages of reactive intermediates that must be eliminated.

$$
r_1 = r_4 = k_{4,f} \theta_A \theta_B - k_{4,r} \theta_C \theta_D \tag{7}
$$

If step (4) is rate-determining, then the other steps in the mechanism, reactions (2), (3), (5), and (6), can be assumed to be quasi-equilibrated. That means that @eq-quasi_equilibrium can be used to write equilibrium expressions for them.

$$
K_{eq,e,nrds} = \prod_i \left[i\right]^{\nu_{i,e,nrds}}
$$

The equilibrium expressions that result from applying @eq-quasi_equilibrium to reactions (2), (3), (5), and (6) are shown in equations (8) through (11). 

$$
K_2 = \frac{\theta_A}{\left[ A \right] \theta_{\text{vacant}}} \tag{8}
$$

$$
K_3 = \frac{\theta_B}{\left[ B \right] \theta_{\text{vacant}}} \tag{9}
$$

$$
K_5 = \frac{\theta_C}{\left[ C \right] \theta_{\text{vacant}}} \tag{10}
$$

$$
K_6 = \frac{\theta_D}{\left[ D \right] \theta_{\text{vacant}}} \tag{11}
$$

There are four equilibrium expressions and five surface coverages, so an additional equation is needed. This is a catalytic reaction, so an expression for the conservation of catalysts can be used. In this case, the catalyst is heterogeneous, so the conservation of catalyst sites is written as in @eq-cons_surf_sites.

$$
\theta_{\text{vacant}} + \sum_{is} \theta_{is} = 1
$$

Applying that expression to the present problem yields equation (12).

$$
1 = \theta_{\text{vacant}} + \theta_A +\theta_B + \theta_D + \theta_D \tag{12}
$$

**Calculations**

1. Solve equations (8) through (12) to obtain expressions for $\theta_{\text{vacant}}$, $\theta_A$, $\theta_B$, $\theta_C$, and $\theta_D$.
2. Substitute the results into equation (7).

**Results and Final Answer**

Solving equations (8) through (12) for $\theta_{\text{vacant}}$, $\theta_A$, $\theta_B$, $\theta_C$, and $\theta_D$ yields equations (13) through (17).

$$
\theta_{\text{vacant}} = \frac{1}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right]} \tag{13}
$$

$$
\theta_A = \frac{K_2 \left[ A \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right]} \tag{14}
$$

$$
\theta_B = \frac{K_3 \left[ B \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right]} \tag{15}
$$

$$
\theta_C = \frac{K_5 \left[ C \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right]} \tag{16}
$$

$$
\theta_D = \frac{K_6 \left[ D \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right]} \tag{17}
$$

Substitution of equations (13) through (17) into equation (7) yields the requested rate expression, equation (18).

$$
r_1 = \frac{k_{4,f}K_2K_3\left[ A \right] \left[ B \right]}{\left( 1 + K_2 \left[ A \right] + K_3 \left[ B \right] + K_5 \left[ C \right] + K_6 \left[ D \right] \right)^2} \tag{18}
$$

:::{.callout-note collapse="false"}
## Note

The rate expressions for heterogeneous catalytic reactions that result when it is assumed that the adsorption and desorption steps are all equilibrated and a surface reaction step is controlling are known as Langmuir-Hinshelwood rate expressions. They are named for Irving Langmuir, who developed models for adsorption equilibrium [@langmuir_i_adsorption_1918], and Cyril Hinshelwood who used them to develop rate expressions for surface reactions.

Langmuir-Hinshelwood rate expressions for heterogeneous catalytic reactions, Michaelis-Menten rate expressions for enzymatic reactions and general rate expressions for homogeneous catalytic reactions often take the form of a fraction. The numerator is typically a single positive term when the apparent reaction is irreversible or the difference between two terms when the apparent reaction is reversible. The denominator is typically the sum of several terms. [Example -@sec-example_5_7] shows how the summation in the denominator in these rate expressions often reduces to a single term when the amount of one of the reactive intermediates is much greater than all the other reactiven intermediates. 

:::

### Mechanistic Rate Expression from a Mechanism with a Most Abundant Intermediate {#sec-example_5_7}

{{< include ../RE_Basics_Examples/reb_5_7/problem_statement.qmd >}}

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

The problem identifies an apparent, non-elementary reaction and proposes a mechanism for it. It then asks me to generate a rate expression for the rate of the non-elementary reaction. From these characteristics, I know that this is a mechanism problem, and I know that to solve it I will first need to write a rate expression for the rate of the apparent reaction in terms of the rates of the mechanistic steps and then eliminate concentrations of reactive intermediates from that expression. I always begin this type of problem by identifying the reactive intermediates. Generally, the reactive intermediates are reagents that appear in the mechanism, but not in the apparent reaction. For heterogeneous catalytic reactions like the one in this problem, I know that the reactive intermediates are the surface species and the fractional coverages of the surface species will need to be eliminated from the rate expression.

In this problem there is a rate-determining step, so I know that the rate expression for the apparent reaction will simply equal the rate expression for the rate-determining step. I also know that when there is a rate-determining step, the other steps can be assumed to be quasi-equilibrated. That means equilibrium expressions can be written for every step *except* the rate-determining step. I know that those expressions, together with an expression for the conservation of catalyst sites can then be solved to get expressions for the surface coverages. Substitution of the surface coverage expressions into the rate expression then eliminates the surface coverages from the rate expression.

In this problem I'm also told that there is a most abundant surface intermediate. I know that this means that the coverage for that intermediate is much, much greater than all the other coverages. From past experience, I expect that the rate expression will have a denominator that is the sum of several terms. I know that if I (1) write inequalities expressing that the coverage of the most abundant intermediate is much greater than each of the other intermediates and (2) simply the resulting inequalities they will show that one term in the denominator is much, much greater than all the others. That will mean that all the other terms are negligible and can be set equal to zero.

:::

**Reactive Intermediates**: $\ast$, $O_2\!-\!\ast$, $CO_3\!-\!\ast$, $O\!-\!\ast$, and $CO_2\!-\!\ast$.

**Necessary Equations**

The problem states that step (6) is rate-determining, so the rate of the apparent, non-elementary reaction can be set equal to the rate of step (6). In addition, every mechanistic step, including step (6), is an elementary reaction. The mathematical form of the rate expression for elementary steps is known from theory, @eq-elem_surf_reaction_rate.

$$
r_j = k_{j,f}\prod_{i_{r}}\left[ i_{r} \right]^{- \nu_{i_{r},j} } \prod_{i_{rs}}\theta_{i_{rs}}^{- \nu_{i_{rs},j} } - k_{j,r}\prod_{i_{p}}\left[ i_{p} \right]^{ \nu_{i_p,j} }\prod_{i_{ps}}\theta_{i_{ps}}^{ \nu_{i_{ps},j}}
$$

For this problem, this leads to equation (7) for the rate of the apparent, non-elementary reaction.

$$
r_1 = r_6 = k_{6,f} \theta_{CO_2} - k_{6,r} \left[ CO_2 \right] \theta_{\text{vacant}} \tag{7}
$$

The other steps, reactions (2) through (5), may then be assumed to be at quasi-equilibrium, and equilibrium expressions, @eq-quasi_equilibrium, can be written for each of them.

$$
K_{eq,e,nrds} = \prod_i \left[i\right]^{\nu_{i,e,nrds}}
$$

The equilibrium expressions that result for steps (2) thorough (5) are given in equations (8) through (11).

$$
K_2 = \frac{\theta_{O_2}}{ \left[ O_2 \right] \theta_{\text{vacant}}} \tag{8}
$$

$$
K_3 = \frac{\theta_{CO_3}}{ \left[ CO \right] \theta_{O_2}} \tag{9}
$$

$$
K_4 = \frac{ \left[ CO_2 \right] \theta_{O}}{ \theta_{CO_3}} \tag{10}
$$

$$
K_5 = \frac{\theta_{CO_2}}{ \left[ CO \right] \theta_O} \tag{11}
$$

There are only four equilibrium expressions while there are five intermediates. An expression for the conservation of catalyst sites, @eq-cons_surf_sites, provides the additional equation.

$$
\theta_{\text{vacant}} + \sum_{is }\theta_{is} = 1
$$

For this problem, the conservation of sites expression then takes the form shown in equation (12).

$$
1 = \theta_{\text{vacant}} + \theta_{O_2} + \theta_{CO_3} + \theta_O + \theta_{CO_2} \tag{12}
$$

Equations (8) through (12) can be solved to obtain expressions for each of the surface coverages. Those expressions can then be substituted into equation (7) to generate an expression for the apparent rate of the non-elementary reaction (1).

If $O\!-\!\ast$ is the most abundant surface intermediate, then its coverage is much greater than each of the other surface species, as expressed in equations (13) through (16). The expressions for the surface coverages can be substituted into these inequalities and simplified. The "Results and Final Answer" section, below, shows how the resulting inequalities allow simplification of the rate expression.

$$
\theta_{O} \gg \theta_{\text{vacant}} \tag{13}
$$

$$
\theta_{O} \gg \theta_{CO_2} \tag{14}
$$

$$
\theta_{O} \gg \theta_{CO_3} \tag{15}
$$

$$
\theta_{O} \gg \theta_{O_2} \tag{16}
$$

**Calculations**

1. Solve equations (8) through (12) to obtain expressions for $\theta_{\text{vacant}}$, $\theta_{O_2}$, $\theta_{CO_3}$, $\theta_{O}$, and $\theta_{CO_2}$.
2. Substitute the results into equation (7) to obtain the rate expression.
3. Substitute the results from step 1 into equations (13) through (16) and simplify (typically the expressions for the coverages will be fractions that all have the same denominator, if so, multiply both sides of the inequality by the denominator so that it cancels out).
4. See whether the resulting inequalities allow simplification of the rate expression.
    a. Typically the rate expression will have a denominator that contains a sum of several terms.
    b. If one of the inequalities shows that one term in the denominator is much much greater than another, delete the smaller term from the denominator.
    c. Repeat step 4.b for each inequality.

**Results and Final Answer**

Solving equations (8) through (12) leads to the expressions for the surface coverages shown in equations (17) through (21).

$$
\theta_{\text{vacant}} = \frac{1}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{17}
$$

$$
\theta_{O_2} = \frac{K_2 \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{18}
$$

$$
\theta_{CO_3} = \frac{K_2 K_3 \left[ CO \right] \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{19}
$$

$$
\theta_O = \frac{\frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{20}
$$

$$
\theta_{CO_2} = \frac{\frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{21}
$$

Substitution of equations (17) through (21) then leads to the expression for the apparent rate of non-elementary reaction (1) given in equation (22).

$$
\begin{align}
r_1 =&\,  \frac{\frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]} - k_{6,r} \left[ CO_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \\
& \\
&= \frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] - k_{6,r} \left[ CO_2 \right]^2}{\begin{pmatrix}\left[ CO_2 \right] + K_2 \left[ O_2 \right]\left[ CO_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right]\left[ CO_2 \right] \\ + K_2K_3K_4 \left[ CO \right] \left[O_2 \right] + K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] \end{pmatrix}}
\end{align} \tag{22}
$$

When equations (17) through (21) are substituted into the inequality expressions in equations (13) through (16), simplification leads to the inequalities shown in expressions (23) through (26).

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg \left[ CO_2 \right] \tag{23}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] \tag{24}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2 K_3 \left[ CO \right] \left[ O_2 \right]\left[ CO_2 \right] \tag{25}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2 \left[ O_2 \right]\left[ CO_2 \right] \tag{26}
$$

Expression (23) shows that the fourth term in the denominator of equation (22) is much, much greater than the first term. Put differently, expression (23) shows that the first term in the denominator of equation (22) is negligible compared to the fourth term, and so the first term can be set equal to zero. Expression (24) similarly shows that the last term in the denominator is negligible; expression (25) shows that the third term is negligible; and expression (26) shows that the second term is negligible. When all of the negligible terms are set equal to zero, equation (22) simplifies to equation (27).

$$
r_1 = \frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] - k_{6,r} \left[ CO_2 \right]^2}{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]} \tag{27}
$$

:::{.callout-note collapse="false"}
## Note

As often occurs in mechanistic rate expressions, several of the rate coefficients and equilibrium constants in the rate expression, equation (27), are coupled. It would not be possible to estimate unique values for each of them by fitting equation (27) to experimental rate data. Assuming that thermodynamic data are not available for the surface species so that the equilibrium constants are being treated as kinetics parameters, the rate coefficients and equilbrium constants can be combined as shown in equations (28) and (29), leading to the rate expression shown in equation (30).

$$
k_{1,f}^\prime = k_{6,f}K_5 \tag{28}
$$

$$
k_{1,r}^\prime = \frac{k_{6,r}}{K_2K_3K_4} \tag{29}
$$

$$
r_1 = k_{1,f}^\prime \left[ CO \right]  - k_{1,r}^\prime \frac{\left[ CO_2 \right]^2}{\left[ CO \right] \left[O_2 \right]} \tag{30}
$$

It is possible to estimate unique values for $k_{1,f}^\prime$ and $k_{1,r}^\prime$ using experimental data for the apparent rate of reaction (1) at varying concentrations of CO, O~2~, and CO~2~. The estimated apparent rate coefficients, $k_{1,f}^\prime$ and $k_{1,r}^\prime$, would be expected to exhibit Arrhenius temperature dependence.

:::

## Symbols Used @sec-mechanisms

| Symbol | Meaning |
|:-------|:--------|
| $e$ | As a subscript denotes a specific elementary mechanistic reaction step; an additional subscripted "rds" denotes it is the rate-determining step while an additional subscripted "nrds" denotes it is *not* the rate-determining step.\
As a summation or continuous product index, indexes all steps in the reaction mechanism under consideration. |
| $i$ | Subscript denoting a specific reagent that is present in the system. |
| $i_c$ | As a subscript, denotes a complexed form of the catalyst.\
As a summation or continuous product index, indexes all complexed forms of the catalyst. |
| $i_p$ | As a subscript, denotes a specific reagent that is a product in the reaction under consideration.\
As a summation or continuous product index, indexes all reagents present in the system that are products in the reaction under consideration. |
| $i_{ps}$ | As a subscript, denotes a specific reagent that is a *surface* product in the reaction under consideration.\
As a summation or continuous product index, indexes all surface reagents present in the system that are products in the reaction under consideration. |
| $i_r$ | As a subscript, denotes a specific reagent that is a reactant in the reaction under consideration.\
As a summation or continuous product index, indexes all reagents present in the system that are reactants in the reaction under consideration. |
| $i_{rs}$ | As a subscript, denotes a specific reagent that is a *surface* reactant in the reaction under consideration.\
As a summation or continuous product index, indexes all surface reagents present in the system that are reactants in the reaction under consideration. |
| $i_s$ | As subscript denotes a specific *surface* species that is present in the system.\
As a summation or continuous product index, indexes all *surface * reagents present in the system. |
| $i_+$ | As a subscript, denotes a specific, positively charged reagent present in the system. \
As a summation or continuous product index, indexes all positively charged reagents present in the system. |
| $i_-$ | As a subscript, denotes a specific, negatively charged reagent present in the system. \
As a summation or continuous product index, indexes all negatively charged reagents present in the system. |
| $j$ | Index or subscript denoting a reaction. |
| $k_e$ | Rate coefficient for elementary reaction $e$; an additional subscripted $f$ denotes the forward reaction, an additional subscripted $r$ denotes the reverse reaction. |
| $k_j$ | Rate coefficient for reaction $j$; an additional subscripted $f$ denotes the forward reaction, an additional subscripted $r$ denotes the reverse reaction. |
| $q_i$ | Net charge on reagent $i$; $i=p$ denotes a positively charged reagent and $i=n$ denotes a negatively charged reagent. |
| $r_e$ | Net rate of elementary reaction $e$; additional subscripted "insignificant" denotes a kinetically insignificant reaction and "irreversible" denotes an effectively irreversible reaction. |
| $r_{i,j}$ | Net rate (or apparent net rate) of generation of reagent $i$ via reaction $j$ |
| $r_j$ | Net rate of reaction $j$ |
| $C_{0,cat}$ | Equivalent concentration of catalyst initially added to the system. |
| $C_{cat,free}$ | Concentration of uncomplexed catalyst. |
| $C_i$ | Concentration of reagent $i$; an additional subscripted "surf" denotes concentration of a surface species, "ma" denotes the most-abundant intermediate, and "nma" denotes an intermediate that is not most abundant. |
| $C_{sites}$ | Surface concentration of sites on a heterogeneous catalytic surface. |
| $K_{eq,e}$ | Equilibrium constant for elementary reaction $e$. |
| $RI$ | Subscript denoting a reactive intermediate. |
| $\theta_i$ | Fractional coverage of the catalyst surface by reagent $i$. |
| $\theta_{\text{vacant}}$ | Fraction of the catalyst surface that is not covered by any reagent; an additional subscripted "ma" denotes the most abundant intermediate and "nma" denotes a surface species that is not most abundant. |
| $\kappa_ic$ | Number of catalyst moieties as originally added to the system that are part of catalyst complex $ic$. |
| $\nu_{i,e}$ | Stoichiometric coefficient of reagent $i$ in elementary reaction $e$. |
| $\nu_{i,j}$ | Stoichiometric coefficient of reagent $i$ in reaction $j$. |
| $\sigma_e$ | Stoichiometric number of mechanistic step $e$. |
| $\Delta G_e$ | Gibbs free energy change for elementary reaction $e$. |
| $\Delta G_j$ | Gibbs free energy change for reaction $j$. |
| $\left[\,\,\right]$ | Square brackets indicate the concentration or partial pressure of the reagent they contain. |

: {tbl-colwidths="[20,80]"}