# Mechanistic Rate Expressions {#sec-ch4}

[Chapter -@sec-ch3] defined reaction rates and examined rate expressions. It described theoretical rate expressions that can only be used when the reaction is elementary. It noted that empirical rate expressions, which have no theoretical basis, can be used for non-elementary reactions. This chapter examines the use of mechanistic rate expressions for non-elementary reactions.

## Reaction Mechanisms {#sec-ch4_rxn_mechansims}

In an elementary reaction all bond breaking and forming takes place simultaneously. In a non-elementary reaction it does not. As a result, intermediate species are formed that are not observed at the macroscopic level. What appears to be a single reaction event at the macroscopic level actually occurs as two or more elementary reactions at the molecular level. Another name for a non-elementary reaction is an apparent reaction because it appears from a macroscopic perspective that only the non-elementary reaction is taking place. The set of elementary reaction events that actually takes place at the molecular level is known as the reaction mechanism.

Understanding the mechanism of a non-elementary reaction can be useful in a number of ways. Often reaction mechanisms are studied with the intention of using that knowledge to modify the reactive process, in particular when a catalyst is involved. Because the intermediate species in a reaction mechanism are not readily observable using common analysis instruments, the experimental study of mechanisms is demanding. *Reaction Engineering Basics* does not touch upon the experimental study of reaction mechanisms. Its focus with respect to mechanisms is on generating expressions for the apparent rate of non-elementary reactions. This can be done using either a proposed mechanism or a mechanism that is well-established by experimental study.

Species that are formed and consumed in a reaction mechanism but do not appear as reactants or products in the non-elementary reaction are called *reactive intermediates*. The concentrations of reactive intermediates are always very small. Otherwise they would be observed at the macroscopic level. The reason why they are called "reactive" intermediates is that they react quickly. Their lifetimes very short, so their number never builds up to an easily observable level.

By definition, every reaction in a reaction mechanism is an elementary reaction. Consequently, the rate expression for each mechanistic step will have the functional form shown in @eq-net_rate_elem_rxn, or for gases, in @eq-net_rate_elem_rxn_part_press. The rate coefficients for the absolute rate in the reverse direction are not independent. They are related to the rate coefficients for the absolute rate in the forward direction and the equilibrium constant, @eq-k_relation_to_K. Very often, however, in the case of mechanistic steps, thermodynamic data are not available for the reactive intermediates. In those cases, the equilibrium constant for the mechanistic step won’t be known. For this reason, in this chapter the rate expressions for elementary mechanistic steps will be written as in [Equations -@eq-net_rate_elem_rxn] and -@eq-net_rate_elem_rxn_part_press, and the reverse rate coefficients treated as kinetics parameters. It is convenient to use square brackets in the rate expressions for mechanistic steps to represent either concentrations or partial pressures, as in @eq-rate_mech_step.

$$
r_j = k_{j,f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j}} - k_{j,r}\prod_{i_p} [ i_p ]^{\nu_{i_p,j}}
$$ {#eq-rate_mech_step}

There are a few rules that all mechanisms must obey. There must be some linear combination of the mechanistic steps that exactly equals the apparent, non-elementary reaction. Being elementary reactions, every step in a reaction mechanism must be reversible. This is required by the principle of microscopic reversibility. In addition, the mechanistic steps must be consistent with all available experimental data (e. g. isotopic effects, isotope distributions in products, spectroscopic measurements, etc.) and not just the reaction kinetics.

### Chain Reaction Mechanisms

Reaction mechanisms are sometimes differentiated as having either an open sequence of steps or a closed sequence. Mechanisms with a closed sequence of steps are commonly referred to as *chain reaction mechanisms*. The distinguishing feature of a chain reaction mechanism is that it includes elementary steps known as propagation steps. A propagation step is a step wherein one reactive intermediate participates as a reactant and another reactive intermediate is formed as a product. The full set of propagation steps in the mechanism forms a closed sequence where each reactive intermediate is produced in one propagation step and consumed in a different propagation step. In a chain reaction mechanism, the apparent, non-elementary reaction is, in fact, a linear combination of the full set of propagation steps. As a consequence, propagation steps occur many, many more times than the other steps in the mechanism.

HBr synthesis, @eq-HBr_synthesis, is a non-elementary reaction, and its mechanism, [Equations -@eq-HBr_mech_step_1] through [-@eq-HBr_mech_step_4], is a classic example of a chain reaction mechanism. Comparing the apparent reaction, [-@eq-HBr_synthesis], to the mechanistic steps, [-@eq-HBr_mech_step_1] through [-@eq-HBr_mech_step_4], shows that Br· and H· appear in the mechanistic steps, but not in the apparent, non-elementary reaction. Thus, Br· and H· are reactive intermediates.

Notice that reactions [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] each consume one reactive intermediate and generate a different reactive intermediate. This makes reactions [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] propagation steps. Adding just these two propagation steps together yields the apparent, non-elementary reaction [-@eq-HBr_synthesis].

$$
H_2 + Br_2 \rightleftarrows 2 H\!Br
$$ {#eq-HBr_synthesis}

$$
Br_2 \rightleftarrows 2 Br \!\cdot\!
$$ {#eq-HBr_mech_step_1}

$$
Br \!\cdot\! + H_2 \rightleftarrows H\!Br + H \!\cdot\!
$$ {#eq-HBr_mech_step_2}

$$
H \!\cdot\! + Br_2 \rightleftarrows H\!Br + Br \!\cdot\!
$$ {#eq-HBr_mech_step_3}

$$
2 H \!\cdot\! \rightleftarrows H_2
$$ {#eq-HBr_mech_step_4}

While the sum of the two propagation steps, [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3], equals the apparent non-elementary reaction, the other steps are still needed. This can be seen by noting that if neither reaction [-@eq-HBr_mech_step_1] nor reaction [-@eq-HBr_mech_step_4] ever occurred, then there would not be any reactive intermediates present, and that would mean that the propagation steps could not occur. In theory, either reaction [-@eq-HBr_mech_step_1], in the forward direction, or reaction [-@eq-HBr_mech_step_4], in the reverse direction, would need to occur at least one time in order to get the propagation sequence going. Steps [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] could then occur over and over until all of the Br~2~ or all of the H~2~ was used up. At that point, reaction [-@eq-HBr_mech_step_1], in the reverse direction, or reaction [-@eq-HBr_mech_step_4], in the forward direction, would need to occur one time to use up the reactive intermediates.

Reactions [-@eq-HBr_mech_step_1] and [-@eq-HBr_mech_step_4] are examples of two additional kinds of steps found in chain reaction mechanisms. These kinds of steps are known as initiation steps and termination steps. An elementary initiation step does not have a reactive intermediate as a reactant, but it generates one or more reactive intermediates as products. Similarly, termination steps consume reactive intermediates without producing any new ones. As noted above, even though initiation and termination steps only need to occur a small number of times compared to the propagation steps they are still an essential kind of elementary reaction step for a chain reaction mechanism.

It has already been noted that every elementary reaction must be reversible. As such, the definitions just given for initiation and termination steps don’t make much sense because the reverse of any initiation step will be a termination step by definition, and similarly, the reverse of any termination step will be an initiation step. It is perhaps better to refer to them as initiation/termination steps. Usually, when one says that a step is an initiation step, what is meant is that the step in the forward direction, as written, is an initiation step. Commonly, the mechanistic steps corresponding to an apparent, non-elementary reaction will be written so that the reactants in the initiation step are also reactants in the apparent, non-elementary reaction.

Chain transfer steps can also appear in chain reaction mechanisms. These steps are common in free radical polymerization mechanisms. In free radical polymerization, a very long hydrocarbon molecule (the so-called chain) has a free radical at one end. Monomer molecules react with the free radical end of the growing polymer chain, with the net result that the chain becomes longer by one monomer unit and still has a free radical at the end. In a chain transfer step, a monomer adds to the end of a growing polymer chain, but the free radical transfers to a different molecule. That is, a chain transfer step terminates one growing chain and starts a new one.

Yet another type of step in chain reactions is known as a chain branching step. Chain branching steps must be kept under control; if they are not controlled, they can lead to explosions. In an elementary chain branching step, one reactive intermediate is consumed, but two new reactive intermediates are generated. Clearly if these steps get out of control, the number of reactive intermediates will increase exponentially. This, coupled with the fact that reactive intermediates are so highly reactive, is why explosions can result from uncontrolled chain branching steps.

If it is not possible to identify propagation steps in a reaction mechanism, then the mechanism consists of an open sequence of reaction steps. *Open sequence mechanisms* are a little less common than closed sequences. The reason has to do with the energy required for a reaction to take place. If, for example, in a chain reaction mechanism, the initiation step requires a significant energy input, but the propagation steps do not, the apparent, non-elementary reaction is able to proceed with relative ease because the initiation step only needs to occur a small number of times. In contrast, if one step in an open sequence of steps requires a significant energy input, that amount of energy will be required every time the apparent, non-elementary reaction takes place.

Reagents participate in a chemical reaction according to a fixed stoichiometry as described in [Chapter -@sec-ch2_rxn_stoich]. The propagation steps in a chain reaction mechanism, and all of the steps in an open sequence reaction mechanism, must obey a similar kind of stoichiometry. For example, each time the apparent, non-elementary HBr synthesis reaction occurs, each of the propagation steps, [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3], must occur one time. The *stoichiometric number*, $\sigma_j$, of mechanistic step $j$ (not to be confused with the stoichiometric coefficient, $\nu_{i,j}$, of a reagent, $i$, in that step) is defined as the number of times mechanistic step $j$ must occur when the apparent, non-elementary reaction occurs one time. Put differently, in the linear combination of the mechanistic steps that equals the apparent, non-elementary reaction, the coefficient that multiplies each mechanistic step is the stoichiometric number of that step. Thus, the stoichiometric numbers of steps [-@eq-HBr_mech_step_2] and [-@eq-HBr_mech_step_3] are each equal to 1. For some steps in a reaction mechanism, it is not possible to assign a unique stoichiometric number. For example, the initiation and terminations steps above, reactions [-@eq-HBr_mech_step_1] and [-@eq-HBr_mech_step_4], do not have unique stoichiometric numbers.

## Net Rate of Reagent Generation {#sec-ch4_net_rate_reagent_gen}

It was noted in [Chapter -@sec-ch3_rxn_rates] that if multiple reactions are taking place, the overall net rate of generation of a reagent is the sum of its net rate of generation in each of the reactions. This forms the basis for using the reaction mechanism to write an expression for the apparent rate of generation of a reactant or product in a non-elementary reaction.

From a macroscopic perspective, the only reaction that appears to be taking place is the non-elementary reaction, and the only reagents that appear to be present are the reactants and products of that apparent reaction, along with any non-reactive species present in the system. Consequently, it is desirable to generate an expression for the apparent rate of the non-elementary reaction in terms of the concentrations or partial pressures of those macroscopically observable reagents.

To do so, an expression for the apparent rate of the non-elementary reaction in terms of the rates of the mechanistic steps is written, the concentrations of reactive intermediates are eliminated, and if possible, the expression is further simplified. In *Reaction Engineering Basics*, such rate expressions are referred to as *mechanistic rate expressions*.

The apparent net rate of generation of reagent $i$ via non-elementary reaction $j_{non}$ equals the sum of its rate of generation in each of the mechanistic steps as expressed in @eq-gen_rate_from_mech. Because the steps are elementary, their rates are given by @eq-rate_mech_step, leading to @eq-gen_rate_expr_from_mech as the expression for the apparent rate of generation of $i$ via non-elementary reaction $j_{non}$.

$$
r_{i,j_{non}} =\sum_{j_{step}}\nu_{i,j_{step}}r_{j_{step}}
$$ {#eq-gen_rate_from_mech}

$$
r_{i,j_{non}} = \sum_{j_{step}}\nu_{i,j_{step}} \left(k_{j_{step},f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j_{step}}} - k_{j_{step},r}\prod_{i_p}[ i_p ]^{\nu_{i_p,j_{step}}} \right)
$$ {#eq-gen_rate_expr_from_mech}

@eq-gen_rate_expr_from_mech typically yields a mechanistic rate expression that is not very useful for reaction engineering purposes. It will contain several terms, and it will include concentrations of reactive intermediates. Those concentrations are very difficult to measure accurately because the reactive intermediates are present in very small amounts. That makes it difficult to use a mechanistic rate expression in its initial form and makes it desirable to simplify it and eliminate concentrations of reactive intermediates from it. Simplification is accomplished by making different assumptions. Of course, the resulting simplified rate expression will only be valid if those assumptions are valid and if the underlying mechanism is correct.

It is sometimes observed that the rate of one particular mechanistic step has virtually no effect upon the apparent rate of the macroscopically observed reaction. Steps of this kind can be referred to as *kinetically insignificant steps*. This leads to an assumption that can be used to simplify a mechanistic rate expression. If a mechanistic step is assumed to be kinetically insignificant, its rate can be set equal to zero as shown in @eq-kin_insignificant_step.

$$
r_{j_\text{insig}} = 0
$$ {#eq-kin_insignificant_step}

Similarly, it is sometimes observed that the reverse rate of a particular step is very small compared to its forward rate or that the step is thermodynamically able to go essentially to completion. In other words, it is an *effectively irreversible step*. If a mechanistic step is assumed to be effectively irreversible, the term corresponding to its rate in the reverse direction in @eq-rate_mech_step, is set equal to zero as shown in @eq-effectively_irreversible_step.

$$
r_{j_{irrev}} = k_{j_{irrev},f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j_{irrev}}}
$$ {#eq-effectively_irreversible_step}

## The Bodenstein Steady-State Approximation {#sec-ch4_bodenstein}

@bodenstein_m_geschwindigkeit_1907 suggested an assumption related to reactive intermediates appearing in a reaction mechanism. As noted previously, reactive intermediates will be present at very low concentrations. This is a consequence of their high reactivity. As the reaction begins, the concentration of these species increases, but because they are so reactive, those intermediates formed undergo subsequent reaction very rapidly. In this way a steady state is quickly established whereby the rate at which reactive intermediates are being formed equals the rate at which they are undergoing subsequent reaction. Hence their concentration becomes constant and the overall rate of generation of the reactive intermediates becomes equal to zero.

When the concentration of a species does not change over time, that concentration is said to be at steady state. For reactive intermediates, one can assume that this steady-state condition always exists, ignoring the brief time required for the concentrations of the reactive intermediates to build up to their steady-state values. This is known as the *Bodenstein steady state approximation*. To apply the steady state approximation, the rate of generation of each reactive intermediate, $i_{RI}$, is set equal to zero, as shown in @eq-bodenstein_ss_approx.

$$
0 = \sum_{j_{step}}\nu_{i_{RI},j_{step}}r_{j_{step}}
$$ {#eq-bodenstein_ss_approx}

If there are $N$ reactive intermediates in the mechanism, then @eq-bodenstein_ss_approx can be used once for each intermediate. This results in a set of $N$ algebraic equations that can be solved for the concentrations of the $N$ reactive intermediates. Doing so will give equations for the concentrations of the reactive intermediates in terms of the rate coefficients for the mechanistic steps and the concentrations of stable species. The resulting expressions can be substituted back into the mechanistic rate expression from @eq-gen_rate_expr_from_mech. After doing so, the mechanistic rate expression for the apparent, non-elementary reaction will no longer contain concentrations of reactive intermediates, and it will be much more useful for reaction engineering purposes.

## Rate-Determining Step {#sec-ch4_rate_detg_step}

Sometimes one step in the mechanism is much more difficult or demanding than any of the other steps. This step introduces a bottleneck in the reaction kinetics; if the rate of this one step were somehow increased, the net rates of all the other steps and the apparent rate of the non-elementary reaction would increase proportionally. This kind of step is referred to as a *rate-determining step* or a rate-limiting step. In situations where there is a rate-determining step, the rate expression can often be simplified considerably by making the assumption that the apparent rate of the non-elementary reaction, $r_{j_{non}}$, is equal to the rate of the rate-determining step, $r_{j_{rds}}$, as shown in @eq-rds_rate_expr. Note that $r_{j_{non}}$ in @eq-rds_rate_expr is the apparent *general* rate of the non-elementary reaction, $j_{non}$; it is *not* a species generation rate. It is important to recognize that not all mechanisms have a rate-determining step.

$$
r_{j_{non}} = r_{j_{rds}} = k_{j_{rds},f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j_{rds}}} - k_{j_{rds},r}\prod_{i_p} [ i_p ]^{\nu_{i_p,j_{rds}}}
$$ {#eq-rds_rate_expr}

It is often stated that the rate determining step is the slowest step in the mechanism, but this is not an accurate statement. When the steps all have the same stoichiometric number (see above), then every step in the mechanism proceeds at the same net rate. If the rate determining step was much slower than the steps before it, then the concentrations of the reactants of the rate-determining step would continually build up. Eventually, the concentrations of the reactants of the rate-determining step would become sufficiently large to be observed macroscopically. At that point, it would no longer appear from a macroscopic perspective, that only the non-elementary reaction was taking place. It is more accurate to say that the rate-determining step is the kinetic bottleneck or that it is the most demanding step, than to incorrectly state that it is the slowest step. Its rate *determines* the rates of all the other mechanistic steps.

The concept of one step being more difficult or demanding can be put in more scientific terms. Recall that multiplying each mechanistic step by its stoichiometric number and summing yields the apparent, non-elementary reaction. Since free energy is a state function, the sum of the free energy change for each mechanistic step multiplied by the stoichiometric number of that step is equal to the free energy change for the apparent, non-elementary reaction, as expressed in @eq-delta_G_from_steps. If there is one mechanistic step wherein essentially all of the overall free energy change takes place, that one step is the rate-determining step, @eq-delta_G_from_rds. Since essentially all of the free energy change occurs in the rate-determining step, the free energy change for the other steps, $j_{nrd}$, is essentially zero, @eq-delta_G_not_rds. Note, again, that there does not have to be a rate-determining step in a reaction mechanism.

$$
\Delta G_{j_{non}} = \sum_{j_{step}} \sigma_{j_{step}} \Delta G_{j_{step}}
$$ {#eq-delta_G_from_steps}

$$
\Delta G_{j_{non}} = \sigma_{j_{rds}} \Delta G_{j_{rds}}
$$ {#eq-delta_G_from_rds}

$$
\Delta G_{j_{nrd}} \approx 0
$$ {#eq-delta_G_not_rds}

If a rate-determining step exists for a particular reaction mechanism, there is another consequence. Since the free energy changes for all steps other than the rate-determining step are essentially zero (@eq-delta_G_not_rds), it may be assumed that all steps other than the rate-determining step reach a state of *quasi-equilibrium*. (Recall from thermodynamics that by definition, the free energy change for a process at thermodynamic equilibrium is equal to zero.) This is expressed in @eq-quasi_equilibrium.

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$ {#eq-quasi_equilibrium}

Note that the rate expression that results from the application of @eq-rds_rate_expr is likely to include the concentration of one or more reactive intermediates, and if it does, it is not suitable for many reaction engineering purposes. In those cases, however, the quasi-equilibration assumption, @eq-quasi_equilibrium, can be applied to all other steps. The resulting equilibrium expressions can be solved for the concentrations of the reactive intermediates in terms of the concentrations of the reactants, products and the equilibrium constants for the steps other than the rate-determining step. Upon substitution into @eq-rds_rate_expr, a rate expression more suitable for reaction engineering purposes results.

Rate expressions that are derived with the assumption of a rate-determining step will only apply for reaction conditions that are far from equilibrium. Recall that the free energy change due to the rate-determining step is equal to the overall free energy change. However, as the system approaches thermodynamic equilibrium the overall free energy change approaches zero (by definition) and the free energy change for every step approaches zero (according to the principle of microscopic reversibility). Thus, as the system approaches thermodynamic equilibrium it is no longer possible to identify a rate-determining step, and as a consequence, rate expressions that are derived with the assumption of a rate-determining step will only apply for environmental conditions that are far from equilibrium.

## Catalyst and Charge Conservation {#sec-ch4_cat_charge_cons}

Recall that a catalyst is a material that causes the rate of one or more chemical reactions to increase, but the catalyst itself is not a reactant or product of the apparent non-elementary reaction. In some cases, the catalyst is present within the same phase as the reacting fluid. In this case the catalyst is referred to as a *homogeneous catalyst*. For present purposes, an *enzyme* may be considered to be a homogeneous catalyst for biological reactions, and for the remainder of this sub-section any discussion concerning homogeneous catalysts also applies to enzymes. 

In mechanisms for catalytic reactions, the catalyst appears in several different chemical forms. That is, some of the catalyst will be free (not bonded to anything), while some catalyst will be complexed (chemically bound) with reactants, products, or other species. Each of the chemical forms of the catalyst can be treated as a reactive intermediate because it appears in the reaction mechanism, but not in the apparent, non-elementary reaction. The concentrations of the various chemical forms of the catalyst can be difficult to measure, making it desirable to eliminate them from mechanistic rate expressions using either the steady-state approximation or, when there is rate-determining step in the mechanism, quasi-equilibrium assumptions.

The presence of a catalyst leads to an additional complication when simplifying a mechanistic rate expression. When the Bodenstein steady state approximation is applied to each of the chemical forms of the catalyst, it is found that the resulting equations cannot be solved to obtain expressions for the concentrations of the reactive intermediates as is done for non-catalytic mechanisms. The reason is that when the free catalyst and all the complexes it forms are treated as a reactive intermediates, the equations generated using the Bodenstein steady state approximation are not mathematically independent. One of the Bodenstein steady state equations must be replaced.

The equation that replaces one of the Bodenstein steady state equations is an expression for the *conservation of catalyst*. While the concentrations of the various chemical forms of the catalyst aren’t known, the total amount of catalyst originally added to the system usually is known, and it is a constant. Since catalyst is not generated nor consumed by reaction, the sum of the concentrations of all forms of the catalyst (free, reactant-complexed, intermediate-complexed, and product-complexed) must equal the known total concentration of catalyst. This is expressed in @eq-cat_conservation where $\kappa_{i_c}$ is the number of catalyst species in the form originally added to the system that are needed to create one complex of the catalyst with species $i_c$. When one of the Bodenstein steady state equations is replaced by @eq-cat_conservation, the resulting set of equations is mathematically independent. It can be solved to obtain expressions for the concentration of each reactive intermediate in terms of only rate coefficients, concentrations of stable species and the total concentration of the catalyst in its initial form, $C_{cat,0}$. The amount of catalyst originally added to the system, $C_{cat,0}$, is a known constant, so its presence in the rate expression is acceptable.

$$
C_{cat,0} = C_{cat,free} + \sum_{i_c}\kappa_{i_c}C_{i_c}
$$ {#eq-cat_conservation}

A similar complication can arise for either catalytic or non-catalytic reactions if the mechanism involves ionic species. In that case, similar to requiring the total amount of catalyst to be conserved, *charge conservation* must be enforced. If the reacting solution is uncharged, this means that the sum of the amounts of all positively charged species multiplied by their respective charges must equal the sum of the amounts of all negatively charged species multiplied by their respective charges, as expressed in @eq-charge_conservation. That equation can then be used to replace one of the Bodenstein steady state equations, leading to a mathematically independent set of equations.

$$
0 = \sum_{i_+} C_{i_+}q_{i_+} + \sum_{i_-} C_{i_-}q_{i_-}
$$ {#eq-charge_conservation}

While enzyme catalysis and homogeneous chemical catalysis are the same in many respects, there are some differences. The term “substrate” is typically used instead of "reactant". In catalytic systems, a reagent that binds with the catalyst and renders it catalytically inactive is called a *catalyst poision*. The equivalent in an enzymatic reaction is called an *enzyme inhibitor*. Typically an enzyme is a large molecule that has many twists and folds in its structure, and the catalysis associated with the enzyme takes place when the substrate binds to one particular location within the overall structure. Inhibitors are often molecules that also bind to the particular location where the catalysis takes place. When an inhibitor molecule is bound in this way, the enzyme becomes catalytically inactive until such time that the inhibitor releases from it. In addition to inhibition, some enzymes require *cofactor* molecules. A cofactor molecule is often a relatively small inorganic molecule that has the effect of activating an enzyme when it binds to it. That is, the enzyme alone is not active, but when a cofactor binds to it, it becomes catalytically active.

In terms of simplifying mechanistic rate expressions, the concentrations of poisons, inhibitors, and cofactors that are [not]{.underline} complexed with a catalyst or enzyme is often easily measured. In this case, it is acceptable for reaction engineering purposes for the concentrations of *uncomplexed* poisons, inhibitors, and cofactors to appear in the expression for the apparent rate of the non-elementary reaction. It is *not* acceptable for the concentration of a poison, inhibitor or cofactor that *is* complexed to the catalyst to appear in the rate expression for the non-elementary reaction.

### Heterogeneous Catalytic Reaction Mechanisms

Many industrial processes utilize *heterogeneous catalysts*; they are a separate phase that is in contact with the reacting fluid. Most typically the catalyst is solid while the reagents are in a gaseous or liquid phase. The reaction actually takes place on the surface of the catalyst at specific locations called *active sites*. When writing a mechanistic step that involves an active site, it is common to use some type of star to represent the site, e. g. $\ast$. Reactants, intermediates and products can bond to these sites in much the same way as they can form complexes with homogeneous catalysts or enzymes. In heterogeneous catalysis, the bonding of a species in the reacting fluid phase to an active site on the surface of the catalyst is a process referred to as *adsorption*, and the surface complexes that are generated are called adsorbed species. The reverse process, where a species leaves the surface and enters the fluid phase is called *desorption*.

If the total surface area of the heterogeneous catalyst remains constant during the course of the reaction, the number (and therefore the concentration) of active sites, $C_{\text{sites}}$, remains constant. Note that this is a two-dimensional concentration (sites per surface area), not a three-dimensional concentration (sites per volume). In heterogeneous catalytic kinetics, surface concentrations are usually expressed in terms of the fraction of the total surface sites, $\theta$ as shown in @eq-surf_conc_to_coverage. In that equation, $i_{surf}$ can represent vacant sites as well as adsorbed reagents. $\theta$ is also referred to as the fractional coverage or the surface coverage.

$$
C_{i_{surf}} = C_{\text{sites}} \theta_{i_{surf}}
$$ {#eq-surf_conc_to_coverage}

Transition state theory can be used to derive the mathematical form of rate expressions for an elementary *surface* reaction. When this is done, the concentration of sites, $C_{\text{sites}}$, can be combined with the pre-exponential factor of the rate coefficient. After doing so, the resulting rate expression for an elementary surface reaction is given in @eq-elem_surf_reaction_rate where $i_{surf}$ includes vacant sites.

$$
r_j = k_{j,f}\prod_{i_r}[ i_r ]^{- \nu_{i_r,j}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j}} - k_{j,r}\prod_{i_p}[ i_p ]^{ \nu_{i_p,j} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j}}
$$ {#eq-elem_surf_reaction_rate}

Note that because the rate expression for a heterogeneous catalytic mechanistic step is different than those for non-catalytic, catalytic and enzymatic mechanistic steps, if there is a rate-determining step (rds) in a heterogeneous catalytic reaction mechanism, @eq-surface_rds should be used in place of @eq-rds_rate_expr for the apparent rate of the non-elementary reaction $j$. Also, when equilibrium expressions are written for surface reactions, the fractional coverage of surface species replaces their concentration.

$$
\begin{align}
r_j &= r_{j_{rds}} \\
&= k_{j_{rds},f}\prod_{i_r}\left[ i_r  \right]^{- \nu_{i_r,j_{rds}}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j_{rds}}} \\
&- k_{j_{rds},r}\prod_{i_p}\left[ i_p \right]^{ \nu_{i_p,j_{rds}} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j_{rds}}}
\end{align}
$$ {#eq-surface_rds}

For reaction engineering purposes, it is not desirable to have a rate expression that contains surface coverages because they are typically unknown and difficult to measure. Therefore, the mechanistic rate expression is simplified using the Bodenstein steady state approximation or other valid assumptions. Similar to homogeneous and enzymatic catalysis, the heterogeneous catalytic sites are conserved, and one Bodenstein steady state equation must be replaced by an expression for the conservation of catalytic sites. In the case of heterogeneous catalysis, the conservation of catalytic sites takes the form shown in @eq-cons_surf_sites, where again, $i_{surf}$ includes vacant sites.

$$
1 = \sum_{i_{surf}} \theta_{i_{surf}}
$$ {#eq-cons_surf_sites}

## Further Simplification of Mechanistic Rate Expressions {#sec-ch4_lim_forms_rate_expr}

After concentrations of reactive intermediates have been eliminated, mechanistic rate expressions will contain rate coefficients (and possibly unknown equilibrium constants) for steps in the mechanism. As is true for all rate expressions, experimental studies are necessary to estimate the values of these parameters and to assess the accuracy of the resulting rate expression. Often it is not necessary to find the value of every rate coefficient or to include every term. The key requirement is that the rate expression accurately predicts the net reaction rate at all compositions and temperatures where it will be used.

### Apparent Rate Coefficients

It is very common for mechanistic rate expressions to include products of two or more rate coefficients and equilibrium constants, each raised to a constant power. The exponent may be positive or negative. In most situations, it is not necessary, and would be very difficult, to estimate the value of each individual rate coefficient and equilibrium constant. Instead, the entire group that forms the product can be replaced with an apparent rate coefficient. As long as the individual rate coefficients and equilbrium constants that make it up display Arrhenius temperature dependence, the apparent rate coefficient will do so also.

This is not true for sums or differences of rate coefficients. They will not display Arrhenius temperature dependence, and apparent rate coefficients containing sums or differences of rate coefficients should be avoided. The only exception to this is if the range of temperatures where the rate expression will be used is small enough that assuming Arrhenius temperature dependence for the apparent rate coefficient does not introduce significant inaccuracy. 

### Limiting Forms of Mechanistic Rate Expressions

Whenever a mechanistic rate expression contains terms that are added or subtracted, it is possible that one or more of the terms is very, very much smaller than the others. In this case, the very, very small terms can be dropped from the rate expression, leading to a simpler mathematical form. Of course it must be established experimentally that the resulting rate expression accurately represents the temperature, pressure, and composition dependence of the reaction rate.

### Most Abundant Intermediates

Catalytic reaction mechanisms (homogeneous, enzymatic or heterogeneous) are subtly different from non-catalytic reaction mechanisms. During *non-catalytic* reactions, the amount of every reactive intermediate is small. This makes their concentration difficult to measure, leading to the necessity to eliminate those concentrations from rate expressions for the non-elementary reaction. 

During *catalytic* reactions the total number of reactive intermediates is not necessarily small, it is determined by the total amount of catalyst present. As a result, some of the intermediates in catalytic reactions will be present in significant amounts. Nonetheless, measuring the concentrations of those intermediates is still very difficult, so it is common to eliminate their concentrations from mechanistic rate expressions. That is, even though their concentration may be greater than reactive intermediates in non-catalytic reactions, the non-complexed catalyst and each complexed form of a catalyst or enzyme is treated as a reactive intermediate. This also applies to vacant sites and each adsorbed surface species in a heterogeneous catalytic reaction mechanism.

As a consequence of the larger concentrations of catalytic intermediates, it is possible that during reaction, most of the catalyst, enzyme or catalyst sites are complexed with the same reagent. If so, that complex is called the *most abundant intermediate*. Mathematically, when there is a most abundant intermediate, $i_{ma}$, @eq-fluid_mai applies for a homogeneous catalytic or enzymatic mechanism and @eq-surf_mai applies for a heterogeneous catalytic reaction mechanism. In those inequalities, $i_{nma}$ denotes all of the other complexed or adsorbed intermediates. 

$$
C_{i_{ma}} \gg C_{i_{nma}}
$$ {#eq-fluid_mai}

$$
\theta_{i_{ma}} \gg \theta_{i_{nma}}
$$ {#eq-surf_mai}

These inequalities can sometimes lead to additional simplification of the apparent rate expression for the non-elementary reaction. Expressions for the concentrations or coverages of the complexed species can be substituted into [Inequality -@eq-fluid_mai] and [Inequality -@eq-surf_mai]. Doing so may reveal that a term in the rate expression can be dropped because it is added to a second term that is much, much larger.

## Summary: Generating Mechanistic Rate Expressions {#sec-ch4_gen_mech_rate_expr}

The process for generating an expression for the rate of a non-elementary reaction from its known or postulated mechanism proceeds as follows.

1. Identify the reactive intermediates and the macroscopically observed reagents.
2. Write an expression for the apparent net rate of the non-elementary reaction.
    a. If there is a rate-determining step, set the apparent *general rate* of the non-elementary reaction equal to the general rate of the rate-determining step.
    b. If there isn't a rate-determining step, choose a reactant or product of the non-elementary reaction and set its *net rate of generation* in the non-elementary reaction equal to the sum of its rates of generation in each of the mechanistic steps.
3. Eliminate the concentrations (partial pressures) of reagents that are not macroscopically observed.
    a. If there is a rate-determining step, write equilibrium expressions for all mechanistic steps other than the rate-determining step.
    b. If there isn't a rate-determining step, write the Bodenstein steady-state approximation for each of the mechanistic intermediates.
    c. If there are charged species, a catalyst, or an enzyme, write an expression for the conservation of charge or catalyst as appropriate.
        i. If Bodenstein steady-state approximations were written, eliminate one of them.
    d. Solve the equations resulting from step 3a through 3c to obtain expressions for the concentrations (partial pressures) of the reagents that are not macroscopically observable.
    e. Substitute the expressions for the concentrations (partial pressures) of the reagents that are not macroscopically observable into the rate expression from step 2.
4. Simplify the resulting rate expression as appropriate.
    a. Define apparent rate coefficients.
    b. Write limiting forms of the rate expression.
    c. If there is a most-abundant intermediate, use it to simplify the rate expression, if possible.

## Examples

```{r}
#| echo: false
#| output: false
library(tidyverse)
library(knitr)
library(kableExtra)
library(readxl)
source("code/fmt_tibble_col.R")
source("code/fmt_E_to_10.R")
```

Collectively, the examples that follow illustrate all of the steps listed in the general summary, above. This chapter is one of the few places in *Reaction Engineering Basics,* where calculations are performed analytically without use of numerical methods. By default, the algebraic details are hidden, but can be viewed by clicking on the callouts labeled "Click Here to See Where That Came From."

### Generation of a Rate Expression From a Chain Reaction Mechanism{#sec-ch4_ex1}

Suppose that nitrogen oxidation, equation (1), occurs via the chain reaction mechanism given in equations (2) through (5). Classify each of the mechanistic steps as initiation/termination, propagation, chain branching or chain transfer, and show that there is a linear combination the mechanistic steps that is equal to the apparent, non-elementary reaction. Then generate an expression for the rate of generation of NO assuming step (4) to be effectively irreversible and step (5) to be kinetically insignificant. Use combinations of true rate coefficients to define the minimum number of apparent rate coefficients in the rate expression.

$$
N_2 + O_2 \rightleftarrows 2 N\!O \tag{1}
$$

$$
O_2 \rightleftarrows 2 O \!\cdot\! \tag{2}
$$

$$
O \!\cdot\! + N_2 \rightleftarrows N\!O + N \!\cdot\! \tag{3}
$$

$$
N \!\cdot\! + O_2 \rightleftarrows N\!O + O \!\cdot\! \tag{4}
$$

$$
2 N \!\cdot\! \rightleftarrows N_2\tag{5}
$$


---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This assignment entails generating a rate expression from a mechanism. I know that the final rate expression should not contain concentrations of reactive intermediates. They are the reagents that appear in one or more mechanistic steps, but not in the apparent, non-elementary reaction. Therefore I'll begin by identifying the reactive intermediates. Here I can see that N~2~, O~2~, and NO appear in the apparent, non-elementary reaction, so they are not reactive intermediates. The only other reagents that I see in the mechanism are N∙ and O∙, so they are the reactive intermediates. I'll simply use the definitions for the different kinds of chain mechanism steps to classify steps (2) through (5). 

:::

**Macroscopically Observable Reagents:** N~2~, O~2~, and NO.

**Reactive Intermediates**: $N \!\cdot\!$ and $O \!\cdot\!$

Initiation steps have no reactive intermediates as reactants and one or more reactive intermediates as products, while termination steps have one or more reactive intermediates as reactants and no reactive intermediates as products. Thus, as written, reaction (2) is an initiation step and reaction (5) is a termination step.

Propagation steps have one reactive intermediate among the reactants and a different reactive intermediate among the products. In reaction (3) O∙ is a reactant while N∙ is a product, and in reaction (4) N∙ is a reactant while O∙ is a product. That means reactions (3) and (4) are both propagation steps. There are no chain branching or chain transfer steps in this mechanism.

There must be a linear combination of the mechanistic steps that equals the apparent, non-elementary reaction. In chain reaction mechanisms, the sum usually includes only the propagation steps, (3) and (4) in the present system. In this instance it is easy to see that adding steps (3) and (4) yields the apparent, non-elementary reaction, reaction (1).

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

The problem asks me to write an expression for the net rate of generation of NO. To do that all I need to do is add the net rates of generation of NO in each of the steps, @eq-gen_rate_expr_from_mech. The resulting mechanistic rate expression will contain concentrations of the reactive intermediates, $N \!\cdot\!$ and $O \!\cdot\!$. To eliminate them, I must write the Bodenstein steady-state approximation, @eq-bodenstein_ss_approx, for each, solve the equations to get expressions for $N \!\cdot\!$ and $O \!\cdot\!$, and substitute the results into the mechanistic rate expression.

:::

**Apparent Rate of NO Generation**

The net rate of NO generation equals the sum of its rate of generation in each of the mechanistic steps, equation (6). That rate expression is not acceptable because it contains the concentrations of the reactive intermediates, $N \!\cdot\!$ and $O \!\cdot\!$. Expressions for the concentrations of the reactive intermediates, equations (7) and (8) can be generated using the Bodenstein steady-state approximation, @eq-bodenstein_ss_approx. Substitution of equations (7) and (8) in equation (6) yields equation (9), the mechanistic rate expression for the generation of NO.

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] - k_{3,r} [ NO ] [ N \cdot ] + k_{4,f} [ N \cdot ] [ O_2 ] \tag{6}
$$

$$
\left[ O \cdot \right] = \sqrt{\frac{k_{2,f}}{k_{2,r}} \left[ O_2 \right]} \tag{7}
$$

$$
\left[ N \cdot \right] = \frac{k_{3,f} \sqrt{\frac{k_{2,f}}{k_{2,r}} \left[ O_2 \right]} \left[ N_2 \right]}{\left(k_{3,r} \left[ NO \right] + k_{4,f} \left[ O_2 \right]\right)} \tag{8}
$$

$$
r_{NO,1} =  \left(\frac{2k_{3,f}k_{4,f}  \sqrt{\frac{k_{2,f}}{k_{2,r}} } \left[ O_2 \right]^{\frac{3}{2}}[ N_2 ]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right) \tag{9}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

Start from @eq-gen_rate_from_mech.

$$
r_{i,j_{non}} =\sum_{j_{step}}\nu_{i,j_{step}}r_{j_{step}}
$$

Since the apparent rate of generation of NO is desired,  $i = NO$ and $j_{non} = 1$. In @eq-gen_rate_from_mech, $j_{step}$ indexes all of the steps in the mechanism (reactions (2) through (5)), so here $j_{step}$ includes 2, 3, 4, and 5.

$$
r_{NO,1} = \nu_{NO,2}r_2 + \nu_{NO,3}r_3 + \nu_{NO,4}r_4 + \nu_{NO,5}r_5 
$$

$$
r_{NO,1} = \left(0\right)r_2 + \left(1\right)r_3 + \left(1\right)r_4 + \left(0\right)r_5 
$$

$$
r_{NO,1} = r_3 + r_4
$$

Steps (3) and (4) are elementary reactions by definition, so their rates are given by @eq-rate_mech_step. Further, since step (4) is effectively irreversible, the term for its reverse rate can be set equal to zero. Substitution then gives the mechanistic rate expression shown in equation (6).

$$
r_3 = k_{3,f}  [O \cdot] [ N_2 ] - k_{3,r} [ NO ] [ N \cdot ]
$$

$$
r_4 = k_{4,f} [ N \cdot ] [ O_2 ]
$$

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] - k_{3,r} [ NO ] [ N \cdot ] + k_{4,f} [ N \cdot ] [ O_2 ] \tag{6}
$$

Next, I can write the Bodenstein steady-state approximation, @eq-bodenstein_ss_approx, for $O \cdot$.

$$
0 = \nu_{O \cdot,2}r_2 + \nu_{O \cdot,3}r_3 + \nu_{O \cdot,4}r_4 + \nu_{O \cdot,5}r_5 
$$

$$
0 = 2r_2 - r_3 + r_4 
$$

And in like manner I can write the Bodenstein steady-state approximation for $N \cdot$.

$$
0 = r_3 - r_4 - 2 r_5
$$

Adding those two equations, noting that $r_5$ is equal to zero since step (5) is kinetically insignificant, and substituting @eq-rate_mech_step for the rate of step (2) leads to equation (7) for the concentration of $O \cdot$.

$$
0 = 2r_2 - 2 \cancelto{0}{r_5}
$$

$$
0 = 2k_{2,f} [ O_2] - 2k_{2,r} [ O \cdot]^2
$$

$$
\left[ O \cdot \right] = \sqrt{\frac{k_{2,f}}{k_{2,r}} \left[ O_2 \right]} \tag{7}
$$

Substituting @eq-rate_mech_step into the Bodenstein steady-state approximation for $N \cdot$, and then substituting equation (7) for the concentration of $O \cdot$ gives the expression for the concentration of $N \cdot$, equation (8).

$$
0 = r_3 - r_4 - 2 \cancelto{0}{r_5}
$$

$$
0 = k_{3,f} [ O \cdot] [ N_2] - k_{3,r} [ NO ] [ N \cdot] - k_{4,f} [ N \cdot] [ O_2]
$$

$$
[ N \cdot]\left(k_{3,r} [ NO ] + k_{4,f}  [ O_2]\right) = k_{3,f} [ O \cdot] [ N_2] 
$$

$$
\left[ N \cdot \right] = \frac{k_{3,f} \sqrt{\frac{k_{2,f}}{k_{2,r}} \left[ O_2 \right]} \left[ N_2 \right]}{\left(k_{3,r} \left[ NO \right] + k_{4,f} \left[ O_2 \right]\right)} \tag{8}
$$

The concentration of $N \cdot$ can be eliminated from equation (6) by rearranging it and substituting equation (8).

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] - \left(k_{3,r} [ NO ]  - k_{4,f}  [ O_2 ]\right)[ N \cdot ]
$$

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] - \left(k_{3,r} [ NO ]  - k_{4,f}  [ O_2 ]\right)\frac{k_{3,f} [ O \cdot] [ N_2] }{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}
$$

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] \left(1 - \frac{k_{3,r} [ NO ]  - k_{4,f}  [ O_2 ]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right)
$$

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] \left(\frac{k_{3,r} [ NO ] + k_{4,f}  [ O_2] - k_{3,r} [ NO ]  + k_{4,f}  [ O_2 ]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right)
$$

$$
r_{NO,1} = k_{3,f}  [O \cdot] [ N_2 ] \left(\frac{2k_{4,f}  [ O_2]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right)
$$

Then the concentration of $O \cdot$ can be eliminated by substitution of equation (7), giving the mechanistic rate expression, equation (9).

$$
r_{NO,1} = k_{3,f} \sqrt{\frac{k_{2,f}}{k_{2,r}} \left[ O_2 \right]} [ N_2 ] \left(\frac{2k_{4,f}  [ O_2]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right)
$$

$$
r_{NO,1} =  \left(\frac{2k_{3,f}k_{4,f}  \sqrt{\frac{k_{2,f}}{k_{2,r}} } \left[ O_2 \right]^{\frac{3}{2}}[ N_2 ]}{k_{3,r} [ NO ] + k_{4,f}  [ O_2]}\right) \tag{9}
$$

:::

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

Finally, the assignment asks me to combine the rate coefficients into the minimum number of apparent rate coefficients. The rate expression is a fraction with one term in the numerator and two terms in the denominator. In this situation, the minimum number of apparent rate coefficients will be two. That is, two of the terms will contain rate coefficients while the third does not. There is a variety of ways to do this, and each is equally valid. I'll just divide both the numerator and the denominator by $k_{4,f}$.

:::

If two apparent rate coefficients, $k$ and $k^\prime$ are defined as in equations (10) and (11), the mechanistic rate expression takes the form shown in equation (12). Both apparent rate coefficients are expected to display Arrhenius temperature dependence.

$$
k =  2k_{3,f}  \sqrt{\frac{k_{2,f}}{k_{2,r}} } \tag{10}
$$

$$
k^\prime =  \frac{k_{3,r} }{k_{4,f}} \tag{11}
$$

$$
r_{NO,1} =  \frac{k\left[ O_2 \right]^{\frac{3}{2}}[ N_2 ]}{[ O_2] + k^\prime[ NO ]} \tag{12}
$$

<center>**Discussion**</center>

As written in equation (9), the mechanistic rate expression contains five rate coefficients, and each rate coefficient has a pre-exponential factor and an activation energy. It would be very difficult to estimate those ten rate expression parameters. Very sophisticated experiments and a considerable amount of time would be required. If the goal is simply to find a mathematical form for the rate expression that provides accurate rate predictions at all conditions of interest, then equation (12) is all that is needed. Since the apparent rate coefficients display Arrhenius temperature dependence, only four parameters need to be estimated: two pre-exponential factors and two activation energies.

In fact, it is possible that an even simpler rate expression may be acceptable. If $k^\prime$ is very, very small at all temperatures, the second term in the denominator can be dropped and the rate expression reduces to equation (13). In contrast, the second term in the denominator will equal zero at the start of the reaction if NO is not present. Thus, even if $k^\prime$ is very, very large, the concentration of O~2~ in the denominator must be retained.

$$
r_{NO,1} =  k\left[ O_2 \right]^{\frac{1}{2}}[ N_2 ] \tag{13}
$$

Thus, the proposed mechanism leads to two potential rate expressions, equations (12) and (13). Experimental studies are necessary to establish whether either rate expression is acceptably accurate. It is possible that neither of them, only equation (12), or both of them can accurately predict the rate of the apparent reaction at all temperatures, pressures and compositions of interest.

### Mechanistic Rate Expression from a Mechanism with a Rate-Determining Step {#sec-ch4_ex2}

Suppose that iodopropane disproportionates to produce iodine according to the apparent non-elementary reaction (1). By separately assuming each of the three mechanistic steps in the proposed mechanism, equations (2) through (4), to be rate-determining, generate three possible mechanistic rate expressions for reaction (1) that do not contain concentrations of reactive intermediates.

$$
2 C_3H_5I \rightleftarrows C_6H_{10} + I_2 \tag{1}
$$

$$
C_3H_5I \rightleftarrows C_3H_5 \!\cdot + I \cdot \tag{2}
$$

$$
C_3H_5I + I \cdot \rightleftarrows C_3H_5 \!\cdot + I_2 \tag{3}
$$

$$
2C_3H_5 \cdot \rightleftarrows C_6H_{10} \tag{4}
$$

---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This is a mechanism problem, and in order to begin I need to identify the reactive intermediates and the macroscopically observable reagents. The reactive intermediates are the reagents that appear in the mechanism, but not in the non-elementary reaction. Here I see that C~3~H~5~I, C~6~H~10~ and I~2~ appear in the apparent, non-elementary reaction (1). Looking at the mechanism, I see that it additionally includes C~3~H~5~∙ and I∙, so they are reactive intermediates.

I know that when there is a rate-determining step in the mechanism, the apparent rate of the non-elementary reaction is equal to the rate of the rate-determining step, @eq-rds_rate_expr.

I also know that when one step is rate-determining, quasi-equilibrium expressions, @eq-quasi_equilibrium, can be written for the other steps and used to eliminate the concentrations of the reactive intermediates from the rate expression.

This problem asks me to derive three apparent rate expressions, so I'll have to repeat the process three times.

:::

**Macroscopically Observable Reagents:** C~3~H~5~I, C~6~H~10~ and I~2~

**Reactive Intermediates**: $C_3H_5 \!\cdot\!$ and $I \!\cdot\!$

**For the case where reaction (2) is the rate-determining step**, the apparent rate, $r_1$, of the non-elementary reaction is equal to the rate of reaction (2), because reaction (2) is the rate-determining step.

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - k_{2,r} \left[ C_3H_5 \cdot \right] \left[ I \cdot \right] \tag{5}
$$

The mechanistic steps other than the rate-determining step can be assumed to be quasi-equilibrated. This gives the equilibrium expressions in equations (6) and (7).

$$
K_3 = \frac{\left[ C_3H_5 \cdot \right] \left[ I_2 \right]}{\left[ C_3H_5I \right] \left[ I \cdot \right]} \tag{6}
$$

$$
K_4 = \frac{\left[ C_6H_{10} \right]}{\left[ C_3H_5 \cdot \right]^2} \tag{7}
$$

Equations (6) and (7) can be solved to obtain expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙, equations (8) and (9). Substitution of those equations in equation (5) gives an expression for the apparent rate of reaction (1) if step (2) in the mechanism is rate-determining. The rate expression, equation (10), does not contain concentrations of reactive intermediates.

$$
\left[ C_3H_5 \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}} \tag{8}
$$

$$
\left[ I \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right]}{K_3 \sqrt{K_4}\left[ C_3H_5I \right]} \tag{9}
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - \frac{k_{2,r}}{K_3 K_4} \frac{\left[ C_6H_{10} \right] \left[ I_2 \right]}{\left[ C_3H_5I \right]} \tag{10}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

Start with @eq-rds_rate_expr.

$$
r_{j_{non}} = r_{j_{rds}} = k_{j_{rds},f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j_{rds}}} - k_{j_{rds},r}\prod_{i_p} [ i_p ]^{\nu_{i_p,j_{rds}}}
$$

In this expression $j_{non}$ is the non-elementary reaction (reaction (1) in this problem), $j_{rds}$ is the rate-determining step (step (2) here), $i_r$ indexes the *reactants* in the rate-determining step (here only C~3~H~5~I) and $i_p$ indexes the *products* in the rate determining step (here C~3~H~5~∙  and I∙).

$$
r_1 = r_{2} = k_{2,f} \left[ C_3H_5I \right]^{-\nu_{C_3H_5I,2}} - k_{2,r}\left[ C_3H_5 \cdot \right]^{\nu_{C_3H_5 \cdot,2}}\left[ I \cdot \right]^{\nu_{I \cdot,2}}
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right]^{-(-1)} - k_{2,r}\left[ C_3H_5 \cdot \right]^1\left[ I \cdot \right]^1
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - k_{2,r} \left[ C_3H_5 \cdot \right] \left[ I \cdot \right] \tag{5}
$$

The expressions for the apparent rate of reaction for the two cases that follow (where step (3) is rate-determining and where step (4) is rate-determining) are generated analogously.

To eliminate the concentrations of reactive intermediates, start with @eq-quasi_equilibrium.

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$

In this problem, $j_{nrd}$ denotes a step other than the rate-determining step, in this case, steps (3) and (4), and $i$ indexes *all* reagents present in the system, in this case, C~3~H~5~I, C~6~H~10~, I~2~, C~3~H~5~∙, and I∙.

$$
K_3 = \left[ C_3H_5I \right]^{\nu_{C_3H_5I,3}} \left[ C_6H_{10} \right]^{\nu_{C_6H_{10},3}} \left[ I_2 \right]^{\nu_{I_2,3}} \left[ C_3H_5 \cdot \right]^{\nu_{C_3H_5 \cdot,3}} \left[ I \cdot \right]^{\nu_{I \cdot,3}} 
$$

$$
K_3 = \left[ C_3H_5I \right]^{-1} \left[ C_6H_{10} \right]^0 \left[ I_2 \right]^1 \left[ C_3H_5 \cdot \right]^1 \left[ I \cdot \right]^{-1} 
$$

$$
K_3 = \frac{\left[ C_3H_5 \cdot \right] \left[ I_2 \right]}{\left[ C_3H_5I \right] \left[ I \cdot \right]} \tag{6}
$$

The quasi-equilibrium expression for step (4) is generated analogously, as is the quasi-equilibrium expression for step (2) for the cases where either step (3) or step (4) is rate-determining.

$$
K_4 = \frac{\left[ C_6H_{10} \right]}{\left[ C_3H_5 \cdot \right]^2} \tag{7}
$$

Solve equation (7) for $\left[ C_3H_5 \cdot \right]$, yielding equation (8).

$$
\left[ C_3H_5 \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}} \tag{8}
$$

Substitute equation (8) in equation (6).

$$
K_3 = \frac{ \sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right]}{\sqrt{K_4}\left[ C_3H_5I \right] \left[ I \cdot \right]}
$$

Solve for $\left[ I \cdot \right]$, yielding equation (9).

$$
\left[ I \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right]}{K_3 \sqrt{K_4}\left[ C_3H_5I \right]} \tag{9}
$$

Substitute equations (8) and (9) in equation (5).

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - k_{2,r} \left[ C_3H_5 \cdot \right] \left[ I \cdot \right]
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - k_{2,r}\frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}}\frac{\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right]}{K_3 \sqrt{K_4}\left[ C_3H_5I \right]}
$$

$$
r_1 = k_{2,f} \left[ C_3H_5I \right] - \frac{k_{2,r}}{K_3 K_4} \frac{\left[ C_6H_{10} \right] \left[ I_2 \right]}{\left[ C_3H_5I \right]} \tag{10}
$$

:::

**For the case where reaction (3) is the rate-determining step**, an analogous process shows that the apparent rate of the non-elementary reaction is equal to the rate of step (3) and steps (2) and (4) are quasi-equilibrated leading to equations (11) through (13).

$$
r_1 = k_{3,f} \left[ C_3H_5I \right] \left[ I \cdot \right] - k_{3,r} \left[ C_3H_5 \cdot \right] \left[ I_2 \right] \tag{11}
$$

$$
K_2 = \frac{\left[ C_3H_5 \cdot \right] \left[ I \cdot \right]}{\left[ C_3H_5I \right]} \tag{12}
$$

$$
K_4 = \frac{\left[ C_6H_{10} \right]}{\left[ C_3H_5 \cdot \right]^2} \tag{13}
$$

Solving equations (12) and (13) yields the expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙ shown in equations (14) and (15), and substitution of those equations in equation (11) yields an expression, equation (16), for the apparent rate of reaction (1) if reaction (3) is rate-determining.

$$
\left[ C_3H_5 \cdot \right] = \frac{\sqrt{\left[ C_6H_{10} \right]}}{\sqrt{K_4}} \tag{14}
$$

$$
\left[ I \cdot \right] = \frac{K_2 \sqrt{K_4} \left[ C_3H_5I \right]}{\sqrt{\left[ C_6H_{10} \right]}} \tag{15}
$$

$$
r_1 = k_{3,f} K_2 \sqrt{K_4} \frac{\left[ C_3H_5I \right]^2}{\sqrt{\left[ C_6H_{10} \right]}} - \frac{k_{3,r}}{\sqrt{K_4}}\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right] \tag{16}
$$

**For the case where reaction (4) is the rate-determining step**, an analogous process shows that the apparent rate of the non-elementary reaction is equal to the rate of step (4) and steps (2) and (3) are quasi-equilibrated leading to equations (17) through (19).

$$
r_1 = k_{4,f} \left[ C_3H_5 \cdot \right]^2 - k_{4,r} \left[ C_6H_{10} \right] \tag{17}
$$

$$
K_2 = \frac{\left[ C_3H_5 \cdot \right] \left[ I \cdot \right]}{\left[ C_3H_5I \right]} \tag{18}
$$

$$
K_3 = \frac{\left[ C_3H_5 \cdot \right] \left[ I_2 \right]}{\left[ C_3H_5I \right] \left[ I \cdot \right]} \tag{19}
$$

Solving equations (18) and (19) yields the expressions for the concentrations of the reactive intermediates, C~3~H~5~∙ and I∙ shown in equations (20) and (21), and substitution of those equations in equation (17) yields an expression, equation (22), for the apparent rate of reaction (1) if reaction (4) is rate-determining.

$$
\left[ C_3H_5 \cdot \right] = \sqrt{K_2K_3}  \frac{\left[ C_3H_5I \right]}{\sqrt{\left[ I_2 \right]}} \tag{20}
$$

$$
\left[ I \cdot \right] = \frac{\sqrt{K_2}}{\sqrt{K_3}} \sqrt{\left[ I_2 \right]} \tag{21}
$$

$$
r_1 = \frac{k_{4,f}{K_2K_3}\left[ C_3H_5I \right]^2}{\left[ I_2 \right]} - k_{4,r} \left[ C_6H_{10} \right] \tag{22}
$$

<center>**Discussion**</center>

Each of the three rate expressions contains products of rate coefficients and equilibrium constants. If the equilibrium constants are assumed to display Arrhenius temperature dependence, apparent rate coefficients can be defined as shown in @tbl-ch4_ex2_table. Each apparent rate coefficient in the table will exhibit Arrhenius temperature dependence.

| Rate-Determining Step | $k^\prime_f$ | $k^\prime_r$ |
|:----:|:----:|:----:|
| 2 | $k_{2,f}$ | $\frac{k_{2,r}}{K_3 K_4}$ |
| 3 | $k_{3,f} K_2 \sqrt{K_4}$ | $\frac{k_{3,r}}{\sqrt{K_4}}$ |
| 4 | $k_{4,f}K_2K_3$ | $k_{4,r}$ |

: Apparent rate coefficients. {#tbl-ch4_ex2_table}

Substitution of the apparent rate coefficients into equations (10), (16), and (22) yields the rate expressions shown in equations (23) through (25).This example shows that a single reaction mechanism can yield several different mathematical forms for the rate expression. The mathematical form of the rate expression depends upon the assumptions used to eliminate the concentrations of reactive intermediates from the rate expression.

$$
r_1 = k^\prime_f \left[ C_3H_5I \right] - k^\prime_r \frac{\left[ C_6H_{10} \right] \left[ I_2 \right]}{\left[ C_3H_5I \right]} \tag{23}
$$

$$
r_1 = k^\prime_f \frac{\left[ C_3H_5I \right]^2}{\sqrt{\left[ C_6H_{10} \right]}} - k^\prime_r\sqrt{\left[ C_6H_{10} \right]}\left[ I_2 \right] \tag{24}
$$

$$
r_1 = k^\prime_f\frac{\left[ C_3H_5I \right]^2}{\left[ I_2 \right]} - k^\prime_r \left[ C_6H_{10} \right] \tag{25}
$$

As always, there is no guarantee that any of these rate expressions can accurately describe the dependence of the reaction rate upon composition and temperature. Experimental studies must be undertaken for that purpose. Suppose, as an example, that experimental studies showed that equation (24) provides a highly accurate description of experimental rate data. That does not prove that equations (2), (3), and (4) actually are the reaction mechanism, nor does it prove that step (3) is rate-determining.

### Michaelis-Menten Rate Expression for an Enzymatic Reaction {#sec-ch4_ex3}

Suppose an enzyme, E, catalyzes the conversion of substrate, S, into product, P, as indicated in the apparent, non-elementary reaction (1). If the mechanism consists of reactions (2) and (3), derive a mechanistic rate expression for the apparent generation of P via reaction (1) assuming step (3) is effectively irreversible. The resulting rate expression should be suitable for reaction engineering purposes. That is, it should not contain concentrations of reactive intermediates. 

$$
S \rightleftarrows P \tag{1}
$$

$$
E + S \rightleftarrows E\!\!-\!\!S \tag{2}
$$

$$
E\!\!-\!\!S \rightleftarrows E + P \tag{3}
$$

---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This is a mechanism problem. There isn't a rate-determining step in the mechanism, but it does involve an enzyme. In problems with enzymes (or with homogeneous catalysts), each form of the enzyme is treated the same way reactive intermediates are treated, so for this problem the reactive intermediates are the free (uncomplexed) enzyme and the enzyme-substrate complex. The macroscopically observable reagents are S and P.

Since there isn't a rate-determining step, I will need to choose a reactant or product in the non-elementary reaction and set the apparent rate of generation of that reagent via the non-elementary reaction equal to the sum of the rates at which it is generated in each mechanistic step. In this assignment, I'm asked to generate an expression for the rate of generation of the product, P.

There are two reactive intermediates, but if I wrote the Bodenstein steady state approximation for both of them, the equations would not be mathematically independent because the mechanism includes an enzyme. I know that in this situation I need to write the Bodenstein steady state approximation for all but one of the reactive intermediates and then add an equation for the conservation of catalyst. Those equations can be solved to obtain expressions for the concentrations of the reactive intermediates that can be substituted into the rate expression.

:::

**Macroscopically Observable Reagents:** S and P

**Reactive Intermediates**: E and E-S

Setting the apparent rate of generation of P via reaction (1) equal to the sum of its rates of generation in each of the mechanistic steps, @eq-gen_rate_expr_from_mech, yields the rate expression shown in equation (4). Writing the Bodenstein steady-state approximation for E-S, @eq-bodenstein_ss_approx, yields equation (5) (the expression for E could have been used instead), and the catalyst conservation requirement, @eq-cat_conservation, gives equation (6). Solving equations (5) and (6) yields the expressions for the concentrations of E and E-S shown in equations (7) and (8). Substitution of equation (8) in equation (4) then yields an expression for the rate of generation of P that does not contain concentrations of reactive intermediates, equation (9).

$$
r_{P,1} = k_{3,f} \left[ E\!-\!S \right] \tag{4}
$$

$$
0 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{3,f} \left[ E\!-\!S \right] \tag{5}
$$

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] \tag{6}
$$

$$
\left[ E \right] = \frac{E_0}{1 + \frac{k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]} \tag{7}
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} E_0 \left[ S \right]}{k_{2,r}+ k_{3,f} + k_{2,f}\left[ S \right]} \tag{8}
$$

$$
r_{P,1}  = \frac{k_{2,f} k_{3,f} E_0 \left[ S \right]}{k_{2,r} + k_{3,f} + k_{2,f}\left[ S \right]} \tag{9}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

When using the Bodenstein steady-state approximation, it is useful to write the rate expressions for the mechanistic steps using @eq-rate_mech_step. In the case of step (2), $j = 2$, $i_r$ indexes all of the *reactants* in the reaction and $i_p$ indexes all of the *products* in the reaction, so for reaction (2) $i_r$ includes E and S and $i_p$ includes only E-S.

$$
r_2 = k_{2,f} \left[ E \right]^{-\nu_{E,2}} \left[ S \right]^{-\nu_{S,2}} - k_{2,r}\left[ E\!-\!S \right]^{\nu_{E-S,2}}
$$

$$
r_2 = k_{2,f} \left[ E \right]^{-(-1)} \left[ S \right]^{-(-1)} - k_{2,r}\left[ E\!-\!S \right]^1
$$

$$
r_2 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right]
$$

The expression for the rate of step (3) is generated analogously, *except* the second term is set equal to zero because the problem states that step (3) is effectively irreversible.

$$
r_3 = k_{3,f} \left[ E\!-\!S \right]
$$

Use @eq-gen_rate_from_mech to write an expression for the rate of generation of P.

$$
r_{i,j_{non}} =\sum_{j_{step}}\nu_{i,j_{step}}r_{j_{step}}
$$

Here $i = P$, $j_{non} = 1$, and $j_{step}$ indexes *all* of the steps in the mechanism (2 and 3, here).

$$
r_{P,1} = \nu_{P,2}r_2 + \nu_{P,3}r_3
$$

$$
r_{P,1} = (0)r_2 + (1)r_3
$$

$$
r_{P,1} = r_3
$$

Substitute the expression, above, for the rate of step 3.

$$
r_{P,1} = k_{3,f} \left[ E\!-\!S \right] \tag{4}
$$

There are two reactive intermediates, but only one of the corresponsing Bodenstein steady state approximations can be used because the other will not be mathematically independent. To write the Bodenstein steady-state approximation for E-S, start with @eq-bodenstein_ss_approx.

$$
0 = \sum_{j_{step}}\nu_{i_{RI},j_{step}}r_{j_{step}}
$$

In this equation, $RI$ = E-S, and $j_{step}$ indexes *all* of the steps in the mechanism (reactions (2) and (3) here).

$$
0 = \nu_{E\!-\!S,2}r_2 + \nu_{E\!-\!S,3}r_3
$$

$$
0 = \left( 1 \right) r_2 + \left( -1 \right)r_3
$$

$$
0 = r_2 - r_3
$$

Substitute the expressions, above, for the rates of steps (2) and (3).

$$
0 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{3,f} \left[ E\!-\!S \right] \tag{5}
$$

Since there is an enzyme in the mechanism, write an expression for its conservation, starting with @eq-cat_conservation.

$$
C_{cat,0} = C_{cat,free} + \sum_{i_c}\kappa_{i_c}C_{i_c}
$$

@eq-cat_conservation was written for homogeneous catalysts, so here I've replace the C's with E's. E~0~ represents the total amount of enzyme originally added to the system, expressed as a concentration. It is known and constant, so its appearance in the rate expression is acceptable. The index, $i_c$ includes *all* complexed forms of the enzyme. In this problem, the only complexed form of the enzyme is E-S. That complex contains one original enzyme unit, so $\kappa_{E\!-\!S} = 1$.

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] \tag{6}
$$

To generate expressions for the concentrations of the reactive intermediates, first solve equation (5) for the concentration of E-S.

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} \left[ E \right] \left[ S \right]}{ k_{2,r} +k_{3,f} }
$$

Substitute that result in equation (6) and solve for the concentration of E.

$$
E_0 = \left[ E \right] + \frac{k_{2,f} \left[ E \right] \left[ S \right]}{ k_{2,r} +k_{3,f} }
$$

$$
\left[ E \right] = \frac{E_0}{1 + \frac{k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]} \tag{7}
$$

Substitute equation (7) in equation (5), and solve for the concentration of E-S.

$$
0 = k_{2,f} \frac{E_0}{1 + \frac{k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]} \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{3,f} \left[ E\!-\!S \right]
$$

$$
0 = \frac{k_{2,f} E_0 \left[ S \right]}{\frac{k_{2,r} + k_{3,f} + k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]} - \left(k_{2,r} + k_{3,f} \right)\left[ E\!-\!S \right]
$$

$$
\left[ E\!-\!S \right] = \frac{1}{\left(k_{2,r} + k_{3,f} \right)}\frac{k_{2,f} E_0 \left[ S \right]}{\frac{k_{2,r} + k_{3,f} + k_{2,f}}{k_{2,r} + k_{3,f}} \left[ S \right]}
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} E_0 \left[ S \right]}{k_{2,r}+ k_{3,f} + k_{2,f}\left[ S \right]} \tag{8}
$$

Substitute equation (8) in equation (4).

$$
r_{P,1}  = \frac{k_{2,f} k_{3,f} E_0 \left[ S \right]}{k_{2,r} + k_{3,f} + k_{2,f}\left[ S \right]} \tag{9}
$$

:::

<center>**Discussion**</center>

Before assessing the accuracy of the rate expression shown in equation (9), it is useful to define the minimum number of effective rate coefficients. Michaelis and Menten [-@michaelis_l_kinetik_1913] studied enzymatic conversion of a substrate to product and were the first to propose a mechanistic rate epxression of the form of equation (9). They defined two kinetics parameters, $V_{max}$ and $K_m$, as shown in equations (10) and (11). Substitution of those definitions in equation (9) yields the so-called *Michaelis-Menten rate expression*, equation (12).

$$
V_{max} = k_{3,f} E_0 \tag{10}
$$

$$
K_m = \frac{k_{2,r} + k_{3,f}}{k_{2,f}} \tag{11}
$$

$$
r_{P,1} = \frac{V_{max} \left[ S \right]}{K_m + \left[ S \right]} \tag{12}
$$

The parameters, $V_{max}$ and $K_m$, can be estimated using experimental kinetics data together with software for fitting non-linear models to data. It should be noted that the parameter, $K_m$, includes the sum of two rate coefficients. As such, it will not exhibit Arrhenius temperature dependence. However, enzymes are often only stable over a narrow range of temperatures. As a consequence, assuming Arrhenius temperature dependence may not introduce too much error.

It is also worth noting that the Michaelis-Menten rate expression above is non-linear with respect to the kinetics parameters. However, it can be linearized by taking the reciprocals of the two sides of the equation as shown in equation (13). Specifically, defining $y$ and $x$ as shown in equations (14) and (15), it can be seen that the model has the linear form shown in equation (16) where the slope, $m$, and intercept, $b$, are given in equations (17) and (18). Lineweaver and Burk [-@lineweaver_h_determination_1934] used a plot of $\frac{1}{r_{P,1}}$ *vs*. $\frac{1}{\left[ S \right]}$ to estimate $V_{max}$ and $K_m$, and today plots of the type are commonly called *Lineweaver-Burk* plots.

$$
\frac{1}{r_{P,1}} = \left( \frac{K_m}{V_{max}}  \right) \frac{1}{\left[ S \right]} + \frac{1}{V_{max}} \tag{3}
$$

$$
y = \frac{1}{r_{P,1}} \tag{14}
$$

$$
x = \frac{1}{\left[ S \right]} \tag{15}
$$

$$
y = mx + b \tag{16}
$$

$$
m = \frac{K_m}{V_{max}} \tag{17}
$$

$$
b = \frac{1}{V_{max}} \tag{18}
$$

The Michaelis-Menten rate expression will exhibit asymptotic behavior as the concentration of substrate approaches zero and becomes negligible compared to $K_m$. That is, the rate will asymptotically approach the first order behavior shown in equation (19) when $K_m \gg \left[S\right]$ in the denominator of equation (12). Indeed, if $K_m$ is always very large compared to the substrate concentration, the rate will be first order at all substrate concentrations.

$$
r_{P,1} = \frac{V_{max}}{K_m } \left[ S \right] \tag{21}
$$

The Michaelis-Menten rate expression also will exhibit asymptotic behavior as the concentration of substrate increases. That is, the rate will asymptotically approach $V_{max}$ as $\left[S\right]$ increases so that $\left[S\right] \gg K_m$ in the denominator of equation (12).

### Mechanistic Rate Expression from an Enzymatic Mechanism with an Inhibitor {#sec-ch4_ex4}

Suppose that enzyme E catalyzes the conversion of substrate S to product P, but if the reagent I is present in the system, it inhibits the enzyme. The apparent reaction is shown in equation (1), and the proposed mechanism consists of reactions (2) through (4).

$$
S \rightleftarrows P \tag{1}
$$

$$
E + S \rightleftarrows E\!\!-\!\!S \tag{2}
$$

$$
E + I \rightleftarrows E\!\!-\!\!I \tag{3}
$$

$$
E\!\!-\!\!S \rightleftarrows E + P \tag{4}
$$

Assume that step (4) is effectively irreversible and derive a Michaelis-Menten type of rate expression for this system that is suitable for reaction engineering purposes (i. e. that does not contain concentrations of reactive intermediates). You may assume that the concentration of the free inhibitor can be easily measured, so it is acceptable for its concentration to appear in the rate expression.

---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This is another mechanism problem that includes an enzyme and does not have a rate determining step. The reagents in the apparent reaction, S and P, are always macroscopically observable. The assignment narrative states that uncomplexed I is also macroscopically observable. Species that appear in the mechanistic steps, but not in the apparent reaction, are reactive intermediates. So in this problem, the reactive intermediates are E, E-S and E-I.

Since there isn't a rate-determining step, I will choose a reagent from the apparent reaction and set its apparent rate of generation in the non-elementary reaction equal to the sum of its rates of generation in the mechanistic steps. Here I will do this for P but I could equally well choose S.

To eliminate the concentrations of reactive intermediates from the rate expressions, I'll write the Bodenstein steady state approximation for two of the three reactive intermediates. The Bodenstein steady state approximation for the third reactive intermediate would not be mathematically independent, so I will replace it with an expression for the conservation of catalyst. The resulting set of three equations can be solved to obtain expressions for the concentrations of the three reactive intermediates. Those expressions can then be used to eliminate the concentrations of reactive intermediates from the rate expression.

:::

**Macroscopically Observable Reagents:** S, P, and I.

**Reactive Intermediates**: E, E-S, and E-I.

Setting the apparent rate of generation of P equal to the sum of the rates at which P is generated in each of the mechanistic steps, @eq-gen_rate_expr_from_mech, yields equation (5). Applying the Bodenstein steady-state approximation, @eq-bodenstein_ss_approx, to E-S and E-I yields equations (6) and (7), respectively, and equation (8) requires conservation of enzyme, @eq-cat_conservation.

$$
r_{P,1} = k_{4,f} \left[ E\!-\!S \right] \tag{5}
$$

$$
0 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{4,f} \left[ E\!-\!S \right] \tag{6}
$$

$$
0 = k_{3,f} \left[ E \right] \left[ I \right] - k_{3,r} \left[ E\!-\!I \right] \tag{7}
$$

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] + \left[ E\!-\!I \right] \tag{8}
$$

Solving equations (6) through (8) yields the expressions for the concentrations of E, E-I, and E-S shown in equations (9) through (11). Substitution of equation (11) in equation (5) then yields the rate expression, equation (12).

$$
\left[ E \right] = \frac{k_{3,r} \left( k_{2,r} + k_{4,f} \right) E_0}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{9}
$$

$$
\left[ E\!-\!I \right] = \frac{k_{3,f} \left( k_{2,r} + k_{4,f} \right) E_0 \left[ I \right]}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{10}
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} k_{3,r} E_0 \left[ S \right]}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{11}
$$

$$
r_{P,1} = \frac{k_{4,f} E_0 \left[ S \right]}{\left[ S \right] + \frac{k_{2,r} k_{3,f} + k_{3,f} k_{4,f}}{k_{2,f} k_{3,r}} \left[ I \right] + \frac{k_{2,r} k_{3,r} + k_{3,r} k_{4,f}}{k_{2,f} k_{3,r}}} \tag{12}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

It is useful to write the rate expressions for the mechanistic steps. Start with @eq-rate_mech_step.

$$
r_j = k_{j,f} \prod_{i_r} [ i_r ]^{-\nu_{i_r,j}} - k_{j,r}\prod_{i_p} [ i_p ]^{\nu_{i_p,j}}
$$

To generate an expression for step (2), set $j=2$ and note that $i_r$ indexes all of the *reactants* in the reaction and $i_p$ indexes all of the *products* in the reaction. Thus, $i_r$ includes E and S and $i_p$ includes only E-S.

$$
r_2 = k_{2,f} \left[ E \right]^{-\nu_{E,2}}\left[ S \right]^{-\nu_{S,2}} - k_{2,r}2\left[ E-S \right]^{\nu_{E-S,2}}
$$

$$
r_2 = k_{2,f} \left[ E \right]^{-(-1)}\left[ S \right]^{-(-1)} - k_{2,r}2\left[ E-S \right]^1
$$

$$
r_2 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right]
$$

Expressions for $r_3$ and $r_4$ are generated in analogous manner *except* the second term in the rate expression for step (4) is set equal to zero because the problem states that reaction (4) is effectively irreverisble.

$$
r_3 = k_{3,f} \left[ E \right] \left[ I \right] - k_{3,r} \left[ E\!-\!I \right]
$$

$$
r_4 = k_{4,f} \left[ E\!-\!S \right]
$$

To generate an expression for the rate of generation of P, start with @eq-gen_rate_from_mech. Noting that $j_{step}$ indexes *all* of the steps in the mechanism and setting $i=P$ and $j_{non}=1$ gives the expression for the apparent rate of generation of P via non-elementary reaction (1).

$$
r_{i,j_{non}} =\sum_{j_{step}}\nu_{i,j_{step}}r_{j_{step}}
$$

$$
r_{P,1} = \nu_{P,2}r_2 + \nu_{P,3}r_3 + \nu_{P,4}r_4
$$

$$
r_{P,1} = \left( 0 \right)r_2 + \left( 0 \right)r_3 + \left( 1 \right)r_4
$$

$$
r_{P,1} = r_4
$$

Substituting the expression, above, for the rate of step (4) then gives the rate expression in equation (5).

$$
r_{P,1} = k_{4,f} \left[ E\!-\!S \right] \tag{5}
$$

Next, start with the Bodenstein steady state approximation, @eq-bodenstein_ss_approx.

$$
0 = \sum_{j_{step}}\nu_{i_{RI},j_{step}}r_{j_{step}}
$$

In this equation $j_{step}$ indexes *all* of the steps in the mechanism and $RI$ denotes one of the reactive intermediates. Consequently, in the Bodenstein steady state approximation for E-S, $j_{step}$ includes steps (2), (3), and (4), and $RI$ equals E-S.

$$
0 = \nu_{ES,2} r_2 + \nu_{ES,3} r_3 + \nu_{ES,4} r_4
$$

$$
0 = \left( 1 \right) r_2 \left( 0 \right) r_3 + \left( -1 \right) r_4
$$

$$
0 = r_2 - r_4
$$

Substitution of the rates of steps (2) and (4) yields the expression for E-S. The Bodenstein steady state approximation for E-I is generated analogously.

$$
0 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{4,f} \left[ E\!-\!S \right] \tag{6}
$$

$$
0 = k_{3,f} \left[ E \right] \left[ I \right] - k_{3,r} \left[ E\!-\!I \right] \tag{7}
$$

The catalyst conservation equation, @eq-cat_conservation, was written for homogeneous catalysts, so here I've replace the C's with E's. E~0~ represents the total amount of enzyme originally added to the system, expressed as a concentration. It is known and constant, so its appearance in the rate expression is acceptable. The index, $i_c$ includes *all* complexed forms of the enzyme. In this problem, the complexed forms of the enzyme are E-S and E-I. Both complexes contains one original enzyme unit, so $\kappa_{E\!-\!S} = 1$ and $\kappa_{E\!-\!I} = 1$.

$$
C_{cat,0} = C_{cat,free} + \sum_{i_c}\kappa_{i_c}C_{i_c}
$$

$$
E_0 = \left[ E \right] + \left[ E\!-\!S \right] + \left[ E\!-\!I \right] \tag{8}
$$

To get expressions for the concentrations of the reactive intermediates, first substitute the expression for $r_3$ into equation (7) and solve for $\left[E\!-\!I \right]$.

$$
0 = k_{3,f} \left[ E \right] \left[ I \right] - k_{3,r} \left[ E\!-\!I \right]
$$

$$
\left[ E\!-\!I \right] = \frac{k_{3,f} \left[ E \right] \left[ I \right]}{k_{3,r}} \tag{A}
$$

Next, substitute the expressions, above, for $r_2$ and $r_4$ in equation (6) and solve for $\left[ E\!-\!S \right]$.

$$
0 = k_{2,f} \left[ E \right] \left[ S \right] - k_{2,r} \left[ E\!-\!S \right] - k_{4,f} \left[ E\!-\!S \right]
$$

$$
\left[ E\!-\!S \right] = \frac{k_{2,f} \left[ E \right] \left[ S \right]}{k_{2,r} + k_{4,f}} \tag{B}
$$

Substitute equations (A) and (B) in equation (8) and solve for $\left[ E \right]$.

$$
E_0 = \left[ E \right] + \frac{k_{2,f} \left[ E \right] \left[ S \right]}{k_{2,r} + k_{4,f}} + \frac{k_{3,f} \left[ E \right] \left[ I \right]}{k_{3,r}}
$$

$$
\left[ E \right] = \frac{E_0}{1 + \frac{k_{2,f} \left[ S \right]}{k_{2,r} + k_{4,f}} +\frac{k_{3,f}  \left[ I \right]}{k_{3,r}} }
$$

$$
\left[ E \right] = \frac{k_{3,r} \left( k_{2,r} + k_{4,f} \right) E_0}{k_{2,f} k_{3,r} \left[ S \right] + \left( k_{2,r} k_{3,f} + k_{3,f} k_{4,f} \right)\left[ I \right] + \left( k_{2,r} k_{3,r} + k_{3,r} k_{4,f} \right)} \tag{9}
$$

Substitution of equation (9) in equation (A) yields equation (10), and substitution of equation (9) in equation (B) yields equation (11).

Substitution of equation (11) into equation (5) and division of the numerator and denominator by $k_{2,f} k_{3,r}$ leads to equation (12) for the rate apparent rate of generation of P. (Dividing the numerator and denominator by $k_{2,f} k_{3,r}$ results in a denominator where one term does not contain any rate coefficients and facilitates defining the minimum number of effective rate coefficients.)

$$
r_{P,1} = \frac{k_{4,f} E_0 \left[ S \right]}{\left[ S \right] + \frac{k_{2,r} k_{3,f} + k_{3,f} k_{4,f}}{k_{2,f} k_{3,r}} \left[ I \right] + \frac{k_{2,r} k_{3,r} + k_{3,r} k_{4,f}}{k_{2,f} k_{3,r}}} \tag{12}
$$

:::

The assignment asks for a "Michaelis-Menten type rate expression." In a manner analogous to that described in the discussion for [Example -@sec-ch4_ex3], The kinetics parameters, $V_{max}$, $K_m$, and $K_I$, can be defined as shown in equations (13) through (15). Substitution into equation (15) then yields the Michaelis-Menten type rate expression shown in equation (16).

$$
V_{max} = k_{4,f} E_0 \tag{13}
$$

$$
K_m = \frac{k_{2,r} k_{3,r} + k_{3,r} k_{4,f}}{k_{2,f} k_{3,r}} \tag{14}
$$

$$
K_I = \frac{k_{2,r} k_{3,f} + k_{3,f} k_{4,f}}{k_{2,f} k_{3,r}} \tag{15}
$$

$$
r_{P,1} = \frac{V_{max} \left[ S \right]}{K_m + K_I \left[ I \right] + \left[ S \right]} \tag{16}
$$

Because they contain *sums* of rate coefficients, $K_m$ and $K_I$ in equation (16) are not expected to exhibit Arrhenius temperature dependence over a wide range of temperatures. That said, enzymes often are stable only over a relatively narrow range of temperatures in which case this probably won't cause problems.

Note that if the concentration of inhibitor equals zero, the rate expression is identical to the rate expression in [Example -@sec-ch4_ex3] where there was no inhibitor. As the concentration of inhibitor increases, the denominator gets larger and the rate gets smaller, just as would be expected for an inhibitor.

### Langmuir-Hinshelwood Rate Expression for a Heterogeneous Catalytic Reaction {#sec-ch4_ex5}

Suppose the non-elementary reaction (1) is heterogeneously catalyzed, and the corresponding reaction mechanism is given by equations (2) through (6). Assume step (4) is rate-determining and derive an expression for the apparent rate of reaction (1) that does not include fractional coverages.

$$
A + B \rightleftarrows C + D \tag{1}
$$

$$
A + \ast \rightleftarrows A\!-\!\ast \tag{2}
$$

$$
B + \ast \rightleftarrows B\!-\!\ast \tag{3}
$$

$$
A\!-\!\ast + B\!-\!\ast \rightarrow C\!-\!\ast + D\!-\!\ast \tag{4}
$$

$$
C\!-\!\ast \rightleftarrows C + \ast \tag{5}
$$

$$
D\!-\!\ast \rightleftarrows D + \ast \tag{6}
$$

---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This is a mechanism problem. The macroscopically observable reactants and products in the apparent reaction are A, B, C, and D. All other species appearing in the mechanism, $\ast$, $A\!-\!\ast$, $B\!-\!\ast$, $C\!-\!\ast$, and $D\!-\!\ast$, are treated as reactive intermediates.

This mechanism involves a heterogeneous catalyst, and there is a rate-determining step in the mechanism. Consequently, the apparent rate of the non-elementary reaction is equal to the rate of the rate-determining step as given in @eq-surface_rds.

$$
\begin{align}
r_j &= r_{j_{rds}} \\
&= k_{j_{rds},f}\prod_{i_r}\left[ i_r  \right]^{- \nu_{i_r,j_{rds}}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j_{rds}}} \\
&- k_{j_{rds},r}\prod_{i_p}\left[ i_p \right]^{ \nu_{i_p,j_{rds}} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j_{rds}}}
\end{align}
$$

To make the rate expression useful for reaction engineering purposes, the fractional coverages must be eliminated from it. Because there is a rate determining step, quasi-equilibrium expressions, @eq-quasi_equilibrium, are written for all other steps. (When doing so, if $i$ is a surface species, then $\left[i\right] = \theta_i$.)

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$

An expression for the conservation of sites, @eq-cons_surf_sites, is added to to the quasi-equilibrium expressions.

$$
1 = \sum_{i_{surf}} \theta_{i_{surf}}
$$

The quasi-equilibrium expressions together with the site conservation equation are solved to obtain expressions for the surface coverages. The results are used to eliminate the surface coverages from the expression for the apparent rate of the non-elementary reaction.

:::

**Macroscopically Observable Reagents:** A, B, C, and D.

**Reactive Intermediates**: $\ast$, $A\!-\!\ast$, $B\!-\!\ast$, $C\!-\!\ast$, and $D\!-\!\ast$.

Setting the apparent rate of the non-elementary reaction equal to the rate of the rate-determining step gives equation (7). Assuming steps (2), (3), (5), and (6) are quasi-equilibrated yields equations (8) through (11). An expression for the conservation of sites is given in equation (12).

$$
r_1 = k_{4,f} \theta_A \theta_B - k_{4,r} \theta_C \theta_D \tag{7}
$$

$$
K_2 = \frac{\theta_A}{\left[ A \right] \theta_{\text{vacant}}} \tag{8}
$$

$$
K_3 = \frac{\theta_B}{\left[ B \right] \theta_{\text{vacant}}} \tag{9}
$$

$$
K_5 = \frac{\left[ C \right] \theta_{\text{vacant}}}{\theta_C} \tag{10}
$$

$$
K_6 = \frac{\left[ D \right] \theta_{\text{vacant}}}{\theta_D} \tag{11}
$$

$$
1 = \theta_{\text{vacant}} + \theta_A +\theta_B + \theta_C + \theta_D \tag{12}
$$

Solving equations (8) through (12) for $\theta_{\text{vacant}}$, $\theta_A$, $\theta_B$, $\theta_C$, and $\theta_D$ yields equations (13) through (17). Substitution of equations (13) through (17) into equation (7) yields the requested rate expression, equation (18).

$$
\theta_{\text{vacant}} = \frac{1}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{13}
$$

$$
\theta_A = \frac{K_2 \left[ A \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{14}
$$

$$
\theta_B = \frac{K_3 \left[ B \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{15}
$$

$$
\theta_C = \frac{\frac{1}{K_5} \left[ C \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{16}
$$

$$
\theta_D = \frac{\frac{1}{K_6} \left[ D \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{17}
$$

$$
r_1 =  \frac{k_{4,f}K_2K_3 \left[ A \right]\left[ B \right]- \frac{k_{4,r}}{K_5K_6}\left[ C \right]\left[ D \right]}{\left(1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]\right)^2} \tag{18}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

Start with @eq-surface_rds.

$$
\begin{align}
r_j &= r_{j_{rds}} \\
&= k_{j_{rds},f}\prod_{i_r}\left[ i_r  \right]^{- \nu_{i_r,j_{rds}}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j_{rds}}} \\
&- k_{j_{rds},r}\prod_{i_p}\left[ i_p \right]^{ \nu_{i_p,j_{rds}} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j_{rds}}}
\end{align}
$$

For this problem, $j = 1$, $j_{rds} = 4$, there are no fluid phase reactants or products in the rate-determining step, so $i_r$ and $i_p$ do not index anything, $i_{surf,r}$ indexes the surface reactants in step (4), $A\!-\!\ast$ and $B\!-\!\ast$, and $i_{surf,p}$ indexes the surface products in step (4), $C\!-\!\ast$ and $D\!-\!\ast$.

$$
r_1 = k_{4,f} \theta_A^{-\nu_{A\!-\!\ast,4}} \theta_B^{-\nu_{B\!-\!\ast,4}} - k_{4,r} \theta_C^{\nu_{C\!-\!\ast,4}} \theta_D^{\nu_{D\!-\!\ast,4}}
$$

$$
r_1 = k_{4,f} \theta_A^{-(-1)} \theta_B^{-(-1)} - k_{4,r} \theta_C^1 \theta_D^1
$$

$$
r_1 = k_{4,f} \theta_A \theta_B - k_{4,r} \theta_C \theta_D
$$

To generate quasi-equilibrium expressions, start with @eq-quasi_equilibrium.

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$

In the case of reaction (2), $j_{nrd} = 2$, $i$ indexes all reagents in the system ($A$, $B$, $C$, $D$, $\ast$, $A\!-\!\ast$, $B\!-\!\ast$, $C\!-\!\ast$, and $D\!-\!\ast$), and for the surface species $\left[ i \right] = \theta_i$.

$$
K_2 = \left[A\right]^{\nu_{A,2}}\left[B\right]^{\nu_{B,2}}\left[C\right]^{\nu_{C,2}}\left[D\right]^{\nu_{D,2}}\theta_{\text{vacant}}^{\nu_{\ast,2}}\theta_A^{\nu_{A\!-\!\ast,2}}\theta_B^{\nu_{B\!-\!\ast,2}}\theta_C^{\nu_{C\!-\!\ast,2}}\theta_D^{\nu_{D\!-\!\ast,2}}
$$

$$
K_2 = \left[A\right]^{-1}\left[B\right]^0\left[C\right]^0\left[D\right]^0\theta_{\text{vacant}}^{-1}\theta_A^1\theta_B^0\theta_C^0\theta_D^0
$$

$$
K_2 = \left[A\right]^{-1}\theta_{\text{vacant}}^{-1}\theta_A^1 = \frac{\theta_A}{\left[ A \right] \theta_{\text{vacant}}} \tag{8}
$$

The generation of the expressions for K~3~, K~5~, and K~6~ is analogous.

$$
K_3 = \frac{\theta_B}{\left[ B \right] \theta_{\text{vacant}}} \tag{9}
$$

$$
K_5 = \frac{\left[ C \right] \theta_{\text{vacant}}}{\theta_C} \tag{10}
$$

$$
K_6 = \frac{\left[ D \right] \theta_{\text{vacant}}}{\theta_D} \tag{11}
$$

@eq-cons_surf_sites is the conservation of sites expression where $i_{surf}$ indexes $\ast$ $A\!-\!\ast$, $B\!-\!\ast$, $C\!-\!\ast$, and $D\!-\!\ast$.

$$
1 = \sum_{i_{surf}} \theta_{i_{surf}}
$$

$$
1 = \theta_{\text{vacant}} + \theta_A +\theta_B + \theta_C + \theta_D \tag{12}
$$

Solve equation (8) for $\theta_A$, equation (9) for $\theta_B$, equation (10) for $\theta_C$, equation (11) for $\theta_D$.

$$
\theta_A = K_2 \left[ A \right] \theta_{\text{vacant}} \tag{A}
$$

$$
\theta_B = K_3 \left[ B \right] \theta_{\text{vacant}} \tag{B}
$$

$$
\theta_C = \frac{\left[ C \right] \theta_{\text{vacant}}}{K_5} \tag{C}
$$

$$
\theta_D = \frac{\left[ D \right] \theta_{\text{vacant}}}{K_6} \tag{D}
$$

Substitute equations (A) through (D) in equation (12) and solve for $\theta_{\text{vacant}}$.

$$
1 = \theta_{\text{vacant}} + K_2 \left[ A \right] \theta_{\text{vacant}} + K_3 \left[ B \right] \theta_{\text{vacant}} + \frac{\left[ C \right] \theta_{\text{vacant}}}{K_5} + \frac{\left[ D \right] \theta_{\text{vacant}}}{K_6} 
$$

$$
1 = \theta_{\text{vacant}}\left(1 + K_2 \left[ A \right]  + K_3 \left[ B \right]  + \frac{\left[ C \right] }{K_5} + \frac{\left[ D \right] }{K_6}\right)
$$

$$
\theta_{\text{vacant}} = \frac{1}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{13}
$$

Then substitute the result in equations (A) through (D) to get equations (14) through (17).

$$
\theta_A = \frac{K_2 \left[ A \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{14}
$$

$$
\theta_B = \frac{K_3 \left[ B \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{15}
$$

$$
\theta_C = \frac{\frac{1}{K_5} \left[ C \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{16}
$$

$$
\theta_D = \frac{\frac{1}{K_6} \left[ D \right]}{1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]} \tag{17}
$$

Finally, substitute equations (14) through (17) in equation (7).

$$
r_1 =  \frac{k_{4,f}K_2K_3 \left[ A \right]\left[ B \right]- \frac{k_{4,r}}{K_5K_6}\left[ C \right]\left[ D \right]}{\left(1 + K_2 \left[ A \right] + K_3 \left[ B \right] + \frac{1}{K_5} \left[ C \right] + \frac{1}{K_6} \left[ D \right]\right)^2} \tag{18}
$$

:::

It is convenient to define effective rate coefficients and equilibrium constants as shown in equations (19) through (24), leading to the form of the rate expression shown in equation (25).

$$
k^\prime_f = k_{4,f}K_2K_3 \tag{19}
$$

$$
k^\prime_r = \frac{k_{4,r}}{K_5K_6} \tag{20}
$$

$$
K_A = K_2 \tag{21}
$$

$$
K_B = K_3 \tag{22}
$$

$$
K_C = \frac{1}{K_5} \tag{23}
$$

$$
K_D = \frac{1}{K_6} \tag{24}
$$

$$
r_1 =  \frac{k^\prime_f \left[ A \right]\left[ B \right]- k^\prime_r\left[ C \right]\left[ D \right]}{\left(1 + K_A \left[ A \right] + K_B \left[ B \right] + K_C \left[ C \right] + K_D \left[ D \right]\right)^2} \tag{25}
$$

<center>**Discussion**</center>

The rate expressions for heterogeneous catalytic reactions that result when it is assumed that the adsorption and desorption steps are all equilibrated and a surface reaction step is controlling are known as Langmuir-Hinshelwood rate expressions. They are named for Irving Langmuir, who developed models for adsorption equilibrium [@langmuir_i_adsorption_1918], and Cyril Hinshelwood who used them to develop rate expressions for surface reactions.

Langmuir-Hinshelwood rate expressions for heterogeneous catalytic reactions, Michaelis-Menten rate expressions for enzymatic reactions and general rate expressions for homogeneous catalytic reactions often take the form of a fraction. The numerator is typically a single positive term when the apparent reaction is irreversible or the difference between two terms when the apparent reaction is reversible. The denominator is typically the sum of several terms, each of which is associated with a complexed form of the catalyst. A variety of limiting forms of the rate expression can be generated by assuming one or more terms in the denominator to be insignificantly small compared to the other terms.

### Mechanistic Rate Expression from a Mechanism with a Most Abundant Intermediate {#sec-ch4_ex6}

The oxidation of carbon monoxide, reaction (1) is heterogeneously catalyzed. A proposed reaction mechanism is shown in reactions (2) through (6). Assume that step (6) is rate-limiting and derive an expression for the apparent rate of reaction (1) that contains only partial pressures, rate coefficients and equilibrium constants. How does the apparent rate expression change if $O\!-\!\ast$ is the most abundant surface intermediate?

**Overall Reaction:**

$$
2 CO + O_2 \rightleftarrows 2 CO_2 \tag{1}
$$

**Proposed Mechanism:**
$$
O_2 + \ast \rightleftarrows O_2\!-\!\ast \tag{2}
$$

$$
CO + O_2\!-\!\ast \rightleftarrows CO_3\!-\!\ast \tag{3}
$$

$$
CO_3\!-\!\ast \rightleftarrows CO_2 + O\!-\!\ast \tag{4}
$$

$$
CO + O\!-\!\ast \rightleftarrows CO_2\!-\!\ast \tag{5}
$$

$$
CO_2\!-\!\ast \rightleftarrows CO_2 + \ast \tag{6}
$$

---

:::{.callout-tip collapse="true"}
#### Click Here to See What an Expert Might be Thinking at this Point

This is a mechanism problem. The reactants and product of the apparent reaction, CO, O~2~, and CO~2~ are macroscopically observed. The other reagents appearing in the mechanism, $\ast$, $O_2\!-\!\ast$, $CO_3\!-\!\ast$, $O\!-\!\ast$, and $CO_2\!-\!\ast$, are treated as reactive intermediates.

The mechanism has a rate-determining step and involves a heterogeneous catalyst. In that situation the apparent rate of the non-elementary reaction is equal to the rate of the rate-determining step as given in @eq-surface_rds.

$$
\begin{align}
r_j &= r_{j_{rds}} \\
&= k_{j_{rds},f}\prod_{i_r}\left[ i_r  \right]^{- \nu_{i_r,j_{rds}}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j_{rds}}} \\
&- k_{j_{rds},r}\prod_{i_p}\left[ i_p \right]^{ \nu_{i_p,j_{rds}} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j_{rds}}}
\end{align}
$$

To make the apparent rate expression useful for reaction engineering purposes, all surface coverages must be eliminated from it. When there is a rate-determining step, quasi-equilibrium expressions, @eq-quasi_equilibrium, are used for all other steps.

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$

In this problem there are 4 steps that are *not* rate-determining, and therefore 4 quasi-equilibrium expressions, but there are five surface species ($\ast$, $O_2\!-\!\ast$, $CO_3\!-\!\ast$, $O\!-\!\ast$, and $CO_2\!-\!\ast$). An expression for the conservation of catalyst sites, @eq-cons_surf_sites, provides a fifth equation.

$$
1 = \sum_{i_{surf}} \theta_{i_{surf}}
$$

Those five equations can be solved to get expressions for the surface coverages. Substitution of the surface coverage expressions into the rate expression then eliminates the surface coverages from the rate expression.

In the second part of this problem there is a most abundant surface intermediate. This allows four inequalities of the form given in @eq-surf_mai to be written.

$$
\theta_{i_{ma}} \gg \theta_{i_{nma}}
$$

Substitution of the expressions for the surface coverages into these equalities followed by algebraic simplification may then show that some terms in the expression for the apparent rate of the non-elementary reaction can be eliminated because they are negligible.

:::

**Macroscopically Observable Reagents:** CO, O~2~, and CO~2~.

**Reactive Intermediates**: $\ast$, $O_2\!-\!\ast$, $CO_3\!-\!\ast$, $O\!-\!\ast$, and $CO_2\!-\!\ast$.

**Necessary Equations**

Setting the apparent rate of the non-elementary reaction equal to the rate of the rate-determining step, (6) yields equation (7). Assuming the other steps, reactions (2) through (5), to be at quasi-equilibrium gives equations (8) through (11). Requiring the conservation of catalyst sites yields equation (12).

$$
r_1 = k_{6,f} \theta_{CO_2} - k_{6,r} \left[ CO_2 \right] \theta_{\text{vacant}} \tag{7}
$$

$$
K_2 = \frac{\theta_{O_2}}{ \left[ O_2 \right] \theta_{\text{vacant}}} \tag{8}
$$

$$
K_3 = \frac{\theta_{CO_3}}{ \left[ CO \right] \theta_{O_2}} \tag{9}
$$

$$
K_4 = \frac{ \left[ CO_2 \right] \theta_{O}}{ \theta_{CO_3}} \tag{10}
$$

$$
K_5 = \frac{\theta_{CO_2}}{ \left[ CO \right] \theta_O} \tag{11}
$$

$$
1 = \theta_{\text{vacant}} + \theta_{O_2} + \theta_{CO_3} + \theta_O + \theta_{CO_2} \tag{12}
$$

Equations (8) through (12), can be solved to obtain the expressions for the five surface coverages shown in equations (13) through (17). Substitution into equation (7) then yields the expression for the apparent rate of reaction shown in equation (18).

$$
\theta_{\text{vacant}} = \frac{1}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{13}
$$

$$
\theta_{O_2} = \frac{K_2 \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{14}
$$

$$
\theta_{CO_3} = \frac{K_2 K_3 \left[ CO \right] \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{15}
$$

$$
\theta_O = \frac{\frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{16}
$$

$$
\theta_{CO_2} = \frac{\frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{17}
$$

$$
r_1 = \frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] - k_{6,r} \left[ CO_2 \right]^2}{\begin{pmatrix}\left[ CO_2 \right] + K_2 \left[ O_2 \right]\left[ CO_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right]\left[ CO_2 \right] \\ + K_2K_3K_4 \left[ CO \right] \left[O_2 \right] + K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] \end{pmatrix}} \tag{18}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

Start with @eq-surface_rds.

$$
\begin{align}
r_j &= r_{j_{rds}} \\
&= k_{j_{rds},f}\prod_{i_r}\left[ i_r  \right]^{- \nu_{i_r,j_{rds}}} \prod_{i_{surf,r}}\theta_{i_{surf,r}}^{- \nu_{i_{surf,r},j_{rds}}} \\
&- k_{j_{rds},r}\prod_{i_p}\left[ i_p \right]^{ \nu_{i_p,j_{rds}} }\prod_{i_{surf,p}}\theta_{i_{surf,p}}^{ \nu_{i_{surf,p},j_{rds}}}
\end{align}
$$

For this problem, $j = 1$, $j_{rds} = 6$, there are no fluid phase reactants in the rate-determining step, so $i_r$ does not index anything, $i_p$ indexes the only fluid phase product in the rate-determining step, CO~2~, $i_{surf,r}$ indexes the only surface reactant in the rate-determining step, $CO_2\!-\!\ast$, and $i_{surf,p}$ indexes the only surface product in the rds, $\ast$.

$$
r_1 = k_{6,f} \theta_{CO_2}^{-\nu_{CO_2\!-\!\ast,6}} - k_{6,r} \left[ CO_2 \right]^{\nu_{CO_2,6}} \theta_{\text{vacant}}^{\nu_{\ast,6}}
$$

$$
r_1 = k_{6,f} \theta_{CO_2}^{-(-1)} - k_{6,r} \left[ CO_2 \right]^1 \theta_{\text{vacant}}^1
$$

$$
r_1 = k_{6,f} \theta_{CO_2} - k_{6,r} \left[ CO_2 \right] \theta_{\text{vacant}}
$$

To generate the quasi-equilibrium expressions, start with @eq-quasi_equilibrium.

$$
K_{j_{nrd}} = \prod_i [i]^{\nu_{i,j_{nrd}}}
$$

In the case of step (2), $j_{nrd}$, $i$ indexes every species in the system, and when $i$ is a surface species, $[i] = \theta_i$.

$$
K_2 = \left[ CO \right]^{\nu_{CO,2}} \left[ O_2 \right]^{\nu_{O_2,2}} \left[ CO_2 \right]^{\nu_{CO_2,2}} \theta_{\text{vacant}}^{\nu_{\ast ,2}} \theta_{O_2}^{\nu_{O_2\!-\!\ast ,2}} \theta_{CO_3}^{\nu_{CO_3\!-\!\ast ,2}} \theta_{O}^{\nu_{O\!-\!\ast ,2}} \theta_{CO_2}^{\nu_{CO_2\!-\!\ast ,2}}
$$

$$
K_2 = \left[ CO \right]^0 \left[ O_2 \right]^{-1} \left[ CO_2 \right]^0 \theta_{\text{vacant}}^{-1} \theta_{O_2}^{1} \theta_{CO_3}^0 \theta_{O}^0 \theta_{CO_2}^0
$$

$$
K_2 = \left[ O_2 \right]^{-1} \theta_{\text{vacant}}^{-1} \theta_{O_2}^{1} = \frac{\theta_{O_2}}{ \left[ O_2 \right] \theta_{\text{vacant}}} \tag{8}
$$

The equations for steps (3), (4), and (5) are generated analogously.

$$
K_3 = \frac{\theta_{CO_3}}{ \left[ CO \right] \theta_{O_2}} \tag{9}
$$

$$
K_4 = \frac{ \left[ CO_2 \right] \theta_{O}}{ \theta_{CO_3}} \tag{10}
$$

$$
K_5 = \frac{\theta_{CO_2}}{ \left[ CO \right] \theta_O} \tag{11}
$$

@eq-cons_surf_sites expresses the conservation of surface sites. The index $i_{surf}$ includes $\ast$, $O_2\!-\!\ast$, $CO_3\!-\!\ast$, $O\!-\!\ast$, and $CO_2\!-\!\ast$

$$
1 = \theta_{\text{vacant}} + \sum_{i_{surf}} \theta_{i_{surf}}
$$

$$
1 = \theta_{\text{vacant}} + \theta_{O_2} + \theta_{CO_3} + \theta_O + \theta_{CO_2} \tag{12}
$$

Solve equations (8) through (11) for the coverages of O~2~, CO~3~, O, and O~2~.

$$
\theta_{O_2} = K_2 \left[O_2\right] \theta_{\text{vacant}} \tag{A}
$$

$$
\theta_{CO_3} = K_3 \left[ CO \right] \theta_{O_2} = K_2K_3 \left[O_2\right] \left[ CO \right] \theta_{\text{vacant}} \tag{B}
$$

$$
\theta_{O} = \frac{K_4 \theta_{CO_3}}{\left[CO_2\right]} = \frac{K_2K_3K_4\left[O_2\right] \left[ CO \right] \theta_{\text{vacant}}}{\left[CO_2\right]} \tag{C}
$$

$$
\theta_{CO_2} = K_5\left[ CO \right]\theta_{O} = \frac{K_2K_3K_4K_5\left[O_2\right] \left[ CO \right]^2 \theta_{\text{vacant}}}{\left[CO_2\right]} \tag{D}
$$

Substitute equations (A) through (D) into equation (12), and solve for $\theta_\text{vacant}$ to get equation (13).

$$
\begin{align}
1 &= \theta_{\text{vacant}} + K_2 \left[O_2\right] \theta_{\text{vacant}} \\&+ K_2K_3 \left[O_2\right] \left[ CO \right] \theta_{\text{vacant}} \\&+ \frac{K_2K_3K_4\left[O_2\right] \left[ CO \right] \theta_{\text{vacant}}}{\left[CO_2\right]} \\&+ \frac{K_2K_3K_4K_5\left[O_2\right] \left[ CO \right]^2 \theta_{\text{vacant}}}{\left[CO_2\right]}
\end{align}
$$

$$
\theta_{\text{vacant}} = \frac{1}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{13}
$$

Substitute that result into equations (A) through (D) to get equations (14) through (17). 

$$
\theta_{O_2} = \frac{K_2 \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{14}
$$

$$
\theta_{CO_3} = \frac{K_2 K_3 \left[ CO \right] \left[ O_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{15}
$$

$$
\theta_O = \frac{\frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{16}
$$

$$
\theta_{CO_2} = \frac{\frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \tag{17}
$$


Finally, substitute equatins (13) and (17) into equation (7) and multiply the numerator and denominator by $\left[CO_2\right]$.

$$
r_1 = k_{6,f} \theta_{CO_2} - k_{6,r} \left[ CO_2 \right] \theta_{\text{vacant}}
$$

$$
r_1 =  \frac{\frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]} - k_{6,r} \left[ CO_2 \right]}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}}
$$

$$
r_1 = \frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] - k_{6,r} \left[ CO_2 \right]^2}{\begin{pmatrix}\left[ CO_2 \right] + K_2 \left[ O_2 \right]\left[ CO_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right]\left[ CO_2 \right] \\ + K_2K_3K_4 \left[ CO \right] \left[O_2 \right] + K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] \end{pmatrix}} \tag{18}
$$

:::

Assuming $O\!-\!\ast$ to be the most abundant surface intermediate, @eq-surf_mai, leads to inequalities (19) through (22). 

$$
\theta_{O} \gg \theta_{\text{vacant}} \tag{19}
$$

$$
\theta_{O} \gg \theta_{CO_2} \tag{20}
$$

$$
\theta_{O} \gg \theta_{CO_3} \tag{21}
$$

$$
\theta_{O} \gg \theta_{O_2} \tag{22}
$$

When equations (13) through (17) are substituted into the inequality expressions in equations (19) through (22), simplification leads to the inequalities shown in expressions (23) through (26).

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg \left[ CO_2 \right] \tag{23}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] \tag{24}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2 K_3 \left[ CO \right] \left[ O_2 \right]\left[ CO_2 \right] \tag{25}
$$

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg K_2 \left[ O_2 \right]\left[ CO_2 \right] \tag{26}
$$

:::{.callout-tip collapse="true"}
#### Click Here to See Where That Came From

To generate equation (23), start with equation (19).

$$
\theta_{O} \gg \theta_{\text{vacant}}
$$

Substitute equations (13) and (16).

$$
\begin{align}
&\frac{\frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]}}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}} \\
&\gg \frac{1}{\begin{pmatrix}1 + K_2 \left[ O_2 \right] + K_2 K_3 \left[ CO \right] \left[ O_2 \right] \\ + \frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} + \frac{K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right]}{\left[ CO_2 \right]}\end{pmatrix}}
\end{align}
$$

The denominators on the two sides of the inequality are the same. Multiply each side by the denominator.

$$
\frac{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]}{\left[ CO_2 \right]} \gg 1
$$

Multiply both sides by $\left[ CO_2 \right]$.

$$
K_2K_3K_4 \left[ CO \right] \left[O_2 \right] \gg \left[ CO_2 \right]
$$

The procedure for generating equations (24), (25), and (26) is analogous, but the starting equations are (20), (21), and (22), respectively.

:::

Expression (23) shows that the fourth term in the denominator of equation (18) is much, much greater than the first term. Put differently, expression (23) shows that the first term in the denominator of equation (18) is negligible compared to the fourth term, and so the first term can be set equal to zero. Expression (24) similarly shows that the last term in the denominator is negligible; expression (25) shows that the third term is negligible; and expression (26) shows that the second term is negligible. When all of the negligible terms are set equal to zero, equation (18) simplifies to equation (27).

$$
r_1 = \frac{k_{6,f}K_2K_3K_4K_5\left[ CO \right]^2 \left[ O_2 \right] - k_{6,r} \left[ CO_2 \right]^2}{K_2K_3K_4 \left[ CO \right] \left[O_2 \right]} \tag{27}
$$

This mechanistic rate expression contains multiple rate coefficients and equilibrium constants. Assuming that thermodynamic data are not available for the surface species so that the equilibrium constants are being treated as kinetics parameters, it would challenging and time-consuming to estimate their individual values. However, the rate coefficients and equilbrium constants can be combined as shown in equations (28) and (29), leading to the rate expression shown in equation (30).

$$
k^\prime_f = k_{6,f}K_5 \tag{28}
$$

$$
k^\prime_r = \frac{k_{6,r}}{K_2K_3K_4} \tag{29}
$$

$$
r_1 = k^\prime_f \left[ CO \right]  - k^\prime_r \frac{\left[ CO_2 \right]^2}{\left[ CO \right] \left[O_2 \right]} \tag{30}
$$

It *is* possible to estimate unique values for $k^\prime_f$ and $k^\prime_r$ using experimental data for the apparent rate of reaction (1) at varying concentrations of CO, O~2~, and CO~2~. The estimated apparent rate coefficients, $k^\prime_f$ and $k^\prime_r$, would be expected to exhibit Arrhenius temperature dependence as long as the equilibrium constants do also.

## Symbols Used in @sec-ch4

| Symbol | Meaning |
|:-------|:--------|
| $i$ | Subscript denoting a reagent. |
| | $i_c$ denotes a reagent-catalyst complex. |
| | $i_{ma}$ denotes the most abundant intermediate. |
| | $i_{nma}$ denotes an intermediate that is not most abundant.
| | $i_p$ denotes a fluid phase product. |
| | $i_r$ denotes a fluid phase reactant. |
| | $i_{surf}$ denotes a surface reagent (including vacant sites); an additional $r$ or $p$ denotes a reactant or product, respectively. |
| | $i_{RI}$ denotes a reactive intermediate. |
| | $i_+$ denotes a positively charged reagent. |
| | $i_-$ denotes a negaribely charged reagent. |
| $j$ | Subscript denoting a reaction. |
| | $j_{insig}$ denotes a kinetically insignificant step. |
| | $j_{irrev}$ denotes an effectively irreversible step. |
| | $j_{non}$ denotes a non-elementary reaction. |
| | $j_{nrd}$ denotes a mechanistic step that is not rate-determining. |
| | $j_{rds}$ denotes the rate-determining step. |
| | $j_{step}$ denotes a reaction step in a mechanism. |
| $k$ | Rate coefficient; subscripts identify specific reactions and direction ($f$ indicates forward, $r$ indicates reverse). |
| $q_i$ | Charge of reagent $i$. |
| $r$ | Reaction rate; ; subscripts identify specific reactions and direction ($f$ indicates forward, $r$ indicates reverse). |
| $C_{cat,0}$ | Equivalent concentration of catalyst initially added to the system. |
| $C_{cat,free}$ | Concentration of uncomplexed catalyst. |
| $C_i$ | Concentration of reagent $i$. |
| $C_{sites}$ | Concentration of surface sites. |
| $\theta_i$ | Fractional coverage of the catalyst surface by reagent $i$. |
| $\theta_{\text{vacant}}$ | Fraction of the catalyst surface that is not covered by any reagent. |
| $\kappa_{i_c}$ | Number of catalyst moieties as originally added to the system that are part of catalyst complex $i_c$. |
| $\nu_{i,j}$ | Stoichiometric coefficient of reagent $i$ in reaction $j$. |
| $\sigma_j$ | Stoichiometric number of step $j$. |
| $\Delta G_j$ | Gibbs free energy change for reaction $j$. |
| $\left[\,\,\right]$ | Square brackets indicate the concentration or partial pressure of the reagent they contain. |

: {tbl-colwidths="[20,80]"}
