# Modeling Isolated Ideal Reactors

The first part of *Reaction Engineering Basics* examined reaction rates and rate expressions. It defined reaction rates and noted that rate expressions are equations that give the reaction rate as a function of temperature, pressure and composition. The empirical, theoretical, and mechanistic origins of mathematical forms for rate expressions was presented, and the procedure for assessing the accuracy of a proposed rate expression was detailed. That procedure was shown to involve performing experiments and analyzing the data generated in those experiments. The analysis of experimental kinetics data requires mathematical models for the reactor used. Consequently, the equations used to model ideal BSTRs, SBSTRs, CSTRs, and PFRs were presented and common simplifications of those equations were described. 

In the remainder of *Reaction Engineering Basics* the focus shifts from reaction kinetics to reaction engineering. This fifth section describes the use of reactor models in the analysis of isolated ideal reactors. Specifically it considers problems involving batch stirred tank reactors (BSTRs), semi-batch stirred tank reactors (SBSTRs), continuous stirred tank reactors (CSTRs) and tubular plug flow reactors (PFRs). For each of those ideal reactor types, three kinds of reaction engineering tasks are considered. In reactor response tasks the reactor input is given and the response is calculated or the response is given and the input needed to elicit that response is calculated. In optimization tasks aspects of the reactor response are minimized or maximized with respect to specified inputs. Design tasks are similar to optimization tasks, but reactor specifications and/or inputs are not provided and must be judiciously chosen.

## Chapters in this Section

@sec-response-opt-design Response, Optimization and Design of Reactors

@sec-bstr-analysis BSTR Analysis

@sec-sbstr-analysis SBSTR Analysis

@sec-non-continuous-design Design of Non-continuous Reactors

@sec-cstr-analysis CSTR Analysis

@sec-pfr-analysis PFR Analysis

@sec-continuous-design Design of Continuous Reactors