# Notation and Sign Conventions {#sec-notation}

The last section of each chapter and appendix in *Reaction Engineering Basics* lists the symbols and their meaning as used in that chapter or appendix. This appendix describes notation that is used throughout the book. It also lists the sign convention associated with some quantities.

## Notation

**Dots over variable symbols** are used in *Reaction Engineering Basics* to designate flow variables.

* $n_i$ represents the moles of $i$ whereas $\dot n_i$ represents the molar flow rate of $i$.
* $W$ represents work (energy) whereas $\dot W$ represents the rate of doing work (power).

**A vertical bar with a subscript** is used in *Reaction Engineering Basics* to specify the conditions at which a quantity is evaluated.

* $\Delta H_j^0 \Bigr\rvert_{T=\text{300 K}}$ represents the standard enthalpy change for reaction $j$ *evaluated at* 300 K.
* $n_A \Bigr\rvert_{t=0}$ represents the moles of A *at* $t=0$.

**A summation or continuous product with a single bottom index** is used in *Reaction Engineering Basics* to specify that the summation or continuous product includes *all* possible values of the index.

* $\displaystyle \sum_i \dot n_i$ represents the sum of the molar flow rates of every species, $i$, present in the system.
* $\displaystyle \prod_i a_i^{\nu _{i,j}}$ represents the product of the thermodynamic activity of every species, $i$, present in the system raised to a power equal to its stoichiometric coefficient in reaction $j$.

**A summation or continuous product with top and bottom indices** is used in *Reaction Engineering Basics* to specify that the summation or continuous product includes *specific values* of the index.

* $\displaystyle \sum _{j^\prime=0}^{N_{\text{rxns,ind}}} \nu_{i,j^\prime} \xi_{j^\prime}$ represents the sum of the extents of the *independent reactions* multiplied by their stoichiometric coefficient in reaction $j$. (The extents of reactions other than the independent reactions are *not* included in the sum.)
* $\displaystyle \prod_{i=1}^{N_{\text{Reactants, }j}} C_i^{-\nu_{i,j}}$ represents the continuous product of the concentration of every *reactant* in reaction $j$ raised to a power equal to the negative of its stoichiometric coefficient in reaction $j$. (The concentrations of products of reaction $j$ are *not* included in the continuous product.)

## Sign Conventions

* Stoichiometric coefficients of reactants are **negative**.
* Stoichiometric coefficients of products are **positive**.
* If a reagent is neither a reactant nor a product in a given reaction , its stoichiometric coefficient in that reaction is **zero**.
* Heat *added to* a system is **positive**.
* Work *done by* a system is **positive**.