# Reactor Models

The first section of *Reaction Engineering Basics* reviewed chemical reactions and stoichiometry. The second section defined chemical reaction rates and introduced rate expressions as mathematical models that predict the rate of a reaction as a function of fluid composition, temperature and pressure. It noted that when a rate expression is not available for a reaction, the mathematical form of the rate expression can be proposed empirically, theoretically, or mechanistically, but before it can be used, it must be validated. The validation of a rate expression requires the use and modeling of a chemical reactor. So this section of *Reaction Engineering Basics* offers a short break from rate expressions in order to discuss reactors and reactor models. @sec-modeling-ideal-reactors examines the equations that are needed in order to model the four kinds of ideal chemical reactor that were mentioned in @sec-react-eng-def. Then @sec-struct-response-models describes using those equations to create a computer function that predicts the performance of the reactor.

## Chapters in this Section

@sec-modeling-ideal-reactors Reactor Design Equations

@sec-struct-response-models Reactor Response Functions