# Reactor Analysis {#sec-ch5}

Rate expressions like those considered in @sec-ch3 and @sec-ch4 are used in mathematical models for reactors. This chapter presents an introduction to the modeling of ideal chemical reactors.

## Ideal Reactor Modeling {#sec-ch5_ideal_reactor_analysis}

Equipment within which chemical reactions take place is called a reactor. Mathematical models of reactors are essential for reaction engineering analyses. A reactor model is a set of equations that relates what goes into a reactor to what comes out. Other reactor parameters that affect the relationship between what goes in and what come out appear within the model. 

Reactor models that make certain assumptions about the flow and mixing of fluid are called ideal reactor models. Four ideal reactor models will be considered in subsequent chapters, and their model equations are derived in @sec-apxc. They are continuous stirred tank reactors (CSTRs), batch stirred tank reactors (BSTRs), semibatch stirred tank reactors (SBSTRs), and plug-flow reactors (PFRs). This chapter focuses on general aspects of modeling a single ideal reactor.

In a batch, or closed, reactor, a fluid containing the reactants is put into the reactor before the reaction starts. The fluid is isolated while reaction takes place, then when the processing is complete, the reacted fluid is removed. In a continuous, or open, reactor, fluid containing the reactants continually flows into the reactor. Reaction takes place within the reactor, and reacted fluid continually flows out.

As described next, heat can be added or removed from both batch and continuous reactors. If the rate of heat addition or removal is such that the reacting fluid temperature is constant and the same everywhere, the reactor is isothermal. If the reacting fluid temperature is not constant, the reactor is non-isothermal. If no heat is added or removed from the reacting fluid, the reactor is adiabatic. If the pressure of the reacting fluid is constant and the same everywhere in the reactor, the reactor is isobaric, and if the fluid volume is constant, it is isochoric.

### Reactor Heat Transfer

Supplying or removing heat is an essential aspect of reactor operation, and while there are several ways of doing so, *Reaction Engineering Basics* only considers heat transfer between the reacting fluid and a separate heat exchange fluid as described in [Appendix -@sec-apndx_heat_exch]. The exchange fluid is further assumed to be a pure fluid that either undergoes phase change (exchanges latent heat) or experiences temperature change (exchanges sensible heat), but not both. Consequently, there are two forms of the energy balance on the exchange fluid: one for exchange of latent heat and one for exchange of sensible heat. One of these two equations is among the design equations for each of the ideal reactor types. To avoid duplicating their description in each of the following four chapters, they are considered here.

#### Exchange of Sensible Heat

When the exchange fluid undergoes only temperature change, the energy balance on the exchange fluid is given by @eq-ext_fluid_energy_bal_sens, which is reproduced here as @eq-exchange_energy_bal_sensible. The term on the left side of the equation represents the accumulation of sensible heat in the exchange fluid. The first term on the right side of the equation represents the rate at which heat is transferred from the exchange fluid to the reacting fluid. The last term represents the change in the sensible heat of the exchange fluid as it flows through the reactor. If the reactor operates at steady-state, the time derivative is equal to zero and the energy balance on the exchange fluid reduces to the form shown in @eq-exchange_energy_bal_sensible_ss.

$$
\rho_{ex} V_{ex} \tilde{C}_{p,ex}\frac{dT_{ex}}{dt} = -\dot{Q} - \dot{m}_{ex} \int_{T_{ex,in}}^{T_{ex,out}} \tilde{C}_{p,ex}dT
$$ {#eq-exchange_energy_bal_sensible}

$$
0 = -\dot{Q} - \dot {m}_{ex} \int_{T_{ex,in}}^{T_{ex}} \tilde{C}_{p,ex}dT 
$$ {#eq-exchange_energy_bal_sensible_ss}

In @eq-exchange_energy_bal_sensible and @eq-exchange_energy_bal_sensible_ss the sensible heat terms are written in terms of the gravimetric heat capacity of the exchange fluid, $\tilde{C}_{p,ex}$. It has units of energy per mass of exchange fluid per degree of temperature change. The sensible heat terms could also be written in terms of either the volumetric heat capacity ($\breve{C}_p$, energy per volume of exchange fluid per degree of temperature change) or the molar heat capacity ($\hat{C}_p$, energy per mole of exchange fluid per degree of temperature change). @eq-equivalent_sens_heat_accumulation_terms shows the three equivalent ways of writing the accumulation term and @eq-equivalent_sens_heat_terms shows the three equivalent ways of writing the term for the sensible heat change.

$$
\rho_{ex} V_{ex} \tilde{C}_{p,ex}\frac{dT_{ex}}{dt}\ \Leftrightarrow\ V_{ex} \breve{C}_{p,ex}\frac{dT_{ex}}{dt}\ \Leftrightarrow\ \frac{\rho_{ex} V_{ex} \hat{C}_{p,ex}}{M_{ex}}\frac{dT_{ex}}{dt}
$$ {#eq-equivalent_sens_heat_accumulation_terms}

$$
\dot{m}_{ex} \int_{T_{ex,in}}^{T_{ex}} \tilde{C}_{p,ex}dT\ \Leftrightarrow\ \frac{\dot{m}_{ex}}{\rho_{ex}} \int_{T_{ex,in}}^{T_{ex}} \breve{C}_{p,ex}dT\ \Leftrightarrow\ \frac{\dot{m}_{ex}}{M_{ex}} \int_{T_{ex,in}}^{T_{ex}} \hat {C}_{p,ex}dT
$$ {#eq-equivalent_sens_heat_terms}

#### Exchange of Latent Heat

When the exchange fluid undergoes only phase change, the energy balance on it is given by @eq-ext_fluid_energy_bal_latent, which is reproduced here as @eq-exchange_energy_bal_latent. The term on the left side of the equation represents the accumulation of latent heat in the exchange fluid, the first term on the right side of the equation represents the rate at which heat is transferred from the exchange fluid to the reacting fluid, and the last term represents the change in the latent heat of the exchange fluid as it flows through the reactor. Again, if the reactor operates at steady-state, the time derivative is equal to zero and the energy balance on the exchange fluid reduces to @eq-exchange_energy_bal_latent_ss.

$$
\frac{\rho_{ex} V_{ex} \Delta H_{\text{latent},ex}^0}{M_{ex}} \frac{d \gamma}{dt} = - \dot{Q} - \gamma \dot{m}_{ex} \frac{\Delta H_{\text{latent},ex}^0}{M_{ex}}
$$ {#eq-exchange_energy_bal_latent}

$$
0 = - \dot{Q} - \gamma \dot{m}_{ex} \frac{\Delta H_{\text{latent},ex}^0}{M_{ex}}
$$ {#eq-exchange_energy_bal_latent_ss}


## Quantitative Reactor Analysis {#sec-ch5_quant_analysis}

The purpose of an ideal reactor model is to relate the reactor outputs to the reactor inputs and parameters. Mole balances relate the input molar amounts to the output molar amounts, so they are always included in a reactor model. A mole balance can be written for each reagent present anywhere in the system, whether or not it is present in the reactor input. That includes reagents that are reactants or products in the reactions that are occurring, as well as reagents that are neither reactants nor products in any of the reactions. The reagents that do not participate in any of the reactions can be referred to as "inerts."

Energy balances on the reacting fluid and on the separate heat exchange fluid relate their output temperatures to the reactor inputs and parameters. The energy balance on the reacting fluid also relates any work it performs on the surroundings to the reactor inputs and parameters. The reacting fluid and exchange fluid energy balances also are normally included in the reactor model equations. As discussed below, there are circumstances where a reactor can be modeled without using one or both of the energy balances.

A momentum balance accounts for the conversion of kinetic energy of a flowing fluid to thermal energy. While this energy is negligible with respect to the energy balance, it can have a significant effect upon the pressure of the flowing fluid. Momentum balances are not needed with any of the ideal stirred tank reactors, but they are sometimes necessary when modeling ideal PFRs. When a momentum balance is not needed, the outlet pressure can be calculated from the other output variables using the equation of state (i. e. using the ideal gas law or assuming liquids to have constant density).

Collectively, the mole balances, energy balances, and momentum balance, as needed, are referred to as the design equations for the reactor. In some situations, the mole, energy, and momentum balances are found to contain one too many dependent variables. In these cases a differential form of the ideal gas law must be added to the reactor design equations.

The words "transient" and "steady state" are used to differentiate two modes of reactor operation. When a reactor operates at steady state, one can watch any one point in the reactor and the conditions (temperature, pressure, composition, flow rate, etc.) will not change over time. At a different point in the reactor, the conditions may be different, but they, too, will be constant over time. Putting it another way, when a reactor operates at steady state, the conditions may vary spatially, but they won't vary temporally (i. e. over time). Of the ideal reactors considered in *Reaction Engineering Basics,* only CSTRs and PFRs can operate at steady-state.

In a transient reactor one will observe changes in the conditions over time when watching any one point within the reactor. That is, within a transient reactor the conditions will vary temporally (and possibly spatially, too). The most general form of the design equations are those for transient operation. The steady-state design equations for CSTRs and PFRs represent simplifications of the transient design equations for those reactor types.

### Determining Which Reactor Design Equations are Needed

It is not always necessary to use all of the reactor design equations. For example, in closed systems and in steady-state systems, mole balances do not need to be written for every reagent in the system because the amounts of the reactants and products in the reactions are related through stoichiometry. As such, if $N_{ind}$ mathematically independent reactions are taking place, only $N_{ind}$ reactant or product mole balances are needed, together with a mole balances for each inert.

When sensible heat terms associated with a liquid-phase solution can be expressed in terms of the mass-specific or volume-specific heat capacity of the entire solution, a mole balance for the solvent need not be included among the design equations. However, if the sensible heat terms are written in terms of molar heat capacities of the individual reagents, then the solvent must be included among those reagents, and a mole balance on the solvent does need to be included.

A momentum balance is only needed when the reactor is an ideal PFR. Even then, if it is known that the pressure drop is negligible, the momentum balance is not needed.

If a reactor operates adiabatically there will not be an exchange fluid, and consequently an energy balance on the exchange fluid cannot be included among the design equations. If a reactor operates isothermally at a known temperature, the mole balance equations can be solved separately from the two energy balance equations, and the energy balances may not be needed. (True isothermal operation of an industrial reactor is not very common, but laboratory reactors that are used to generate kinetics data normally do operate isothermally.)

*Reaction Engineering Basics* assumes that heat transfer always involves a prefectly mixed heat exchange fluid. If the outlet temperature of that fluid is known and constant, the other reactor design equations can be solved independently from the energy balance on the exchange fluid, and the latter may not be needed. There are two situations where this can happen. The first is when the exchange fluid undergoes a phase change and exchanges only the latent heat associated with the phase change. Phase changes occur at constant temperature, so, for example, if condensation of saturated steam at 1 atm is being used to supply heat to the reacting fluid, the temperature of the exchange fluid will be constant and equal to 100 °C.

The other situation where all the other reactor design equations can be solved separately from the energy balance on the exchange fluid occurs in assignments from reaction engineering courses or books. It is not uncommon for an assignment to provide only the temperature of the exchange fluid, but not its flow rate or its inlet temperature. In this case the other design equations can be solved independently from the energy balance on the exchange fluid, while the energy balance on the exchange fluid cannot be used because the assignment does not provide sufficient information to use it.

### Quantitative Reaction Engineering Tasks

The reactor design equations establish a quantitative relationship between the reactor inputs, the reactor outputs, and the reactor/process parameters. In any reactor modeling assignment, the reaction engineer is given values for some of the inputs, outputs and parameters and tasked with determining the values of the others. The reactor design equations can be used to accomplish four kinds of tasks: response, optimization, design, and parameter estimation. The difference between these tasks is found not in the equations themselves, but in how they are used. Examples of these tasks are deferred to later chapters, but they are defined here.

**Reactor response tasks**, as defined here, are the most straightforward of the four tasks. In a reactor response assignment the reaction engineer is provided with a sufficient number of reactor variables to allow calculation of all of the quantities of interest. Generally there is a single, correct answer to a reactor response assignment.

Sometimes a reactor response assignment will ask for a graph where a quantity of interest is plotted *versus* some other reactor variable. This is still a reactor response task. The only difference is that the reactor design equations are solved multiple times to generate the data to be plotted. Each time the reactor design equations are solved, there is a single, correct answer, and consequently, there is a single correct graph that completes the task.

In **optimization tasks** the number of reactor variables that are specified or known is not sufficient to allow the reaction engineer to solve the reactor design equations and calculate the quantities of interest. The simplest example would task the engineer to maximize (or minimize) a quantity of interest (the target) with respect to some other reactor variable (the adjusted variable). Neither the value of the target nor the value of the adjusted variable are known. In lieu of knowing the actual value of the adjusted variable, the reaction engineer instead knows that it is the value that maximumizes the target. Typically the engineer is tasked to find both the maximum value of the target and the corresponding value of the adjusted variable. Again, there is a single correct answer to this type of reactor optimization assignment.

Knowing that the reactor design equations will be solved numerically, there are two ways the reaction engineer could approach an optimization task. In the first, a range of values of the adjusted variable is selected and the design equations are solved repeatedly to find the value of the target corresponding to each value of the adjusted variable. Then a table is generated with one column for the target and one column for the adjusted variable. The column for the target is scanned to identify the maximum value, and the corresponding value of the adjusted variable is found in the other column in the same row.

Alternatively the results from solving the reactor design equations are plotted. The maximum in the graph is identified and the maximum value of the target and the corresponding value of the adjusted variable are read from the graph. In this approach, it is possible that a maximum will not be present. In that case, the range of values of the adjusted variable must be increased until a maximum is observed. Once a maximum is observed, the precision of the results can be improved by adding additional values of the adjusted variable between the two points that bracket the maximum.

Many software packages include a function (an optimizer) that performs optimization, that is finds a maximum or minimum. The second approach involves using such an optimizer. In this case, the numerical implementation of the solution would entail writing a reactor model function that receives the adjusted variable as an argument and returns the corresponding quantity of interest. That reactor model function would then be passed to the optimizer. Typically an initial guess for the optimum value of the adjusted variable would also need to be provided.

Optimization tasks can be much more complicated than simply maximizing a quantity of interest with respect to another reactor variable. In addition to specifying multiple adjusted variables, the assignment also could impose constraints on the values of one or more reactor variables (not just the adjusted variables). Constraints are conditions that must be obeyed. An example of a constraint would be that the temperature of the heat exchange fluid cannot exceed some specified value because it would boil or decompose above that temperature. Again, there are software packages that will perform constrained, multi-variable optimization.

**Reactor design tasks** are the most complicated of the tasks considered here. At the same time they can be intellectually stimulating, affording the reaction engineer an opportunity to be creative. A reactor design assignment does not provide sufficient information to solve the reactor design equations. The reaction engineer must choose values for the missing reactor variables. In more extreme cases, the assignment may provide little more than the reagents that are available and the products that are to be produced. The type of reactor to use and how to operate it may be among the choices the reaction engineer needs to make.

Design tasks almost always involve an optimization sub-task. The quantity that needs to be maximized is typically financial in nature. The goal is to maximize the rate of making profit subject to technical, regulatory, and financial constraints. Design at this level is typically taught in chemical engineering courses on plant design, and the system being optimized is typically an entire process, not just an isolated reactor.

That level of design task is well beyond the scope of *Reaction Engineering Basics*. However, simplified design tasks involving only the reactor are considered in @sec-ch10. Instead of optimizing a financial target, reactor variables that are related to the overall economics are used. For example, the cost of operating a process may scale with the temperature of that process, in which case minimizing the temperature minimizes the operating cost. In general, there is not a single correct solution to a reactor design assignment. Design tasks are inherently “open-ended,” and multiple solutions are possible and acceptable.

**Parameter estimation tasks** are inherently different from the three types of tasks described above, but they do use the same reactor design equations and the same solution steps. Briefly, a parameter estimation task involves generating data using a reactor and then using a model for the reactor to estimate the values of parameters appearing in a rate expression. The use of the ideal reactor models to estimate rate expression parameters is examined in @sec-ch11. A similar approach can be used to estimate parameters that appear in empirical models for non-ideal reactors such as those considered in @sec-ch13.

## Qualitative Reactor Analysis {#sec-ch5_qual_analysis}

Qualitative analysis focuses upon how the composition and temperature will vary as the reaction or reactions progress, but not on the magnitude of the variations. In batch reactors the time during which reactions occur is measured using clock time. The reaction time is the difference between the clock time when the reaction started and the clock time when it ended. It is customary to define an elapsed time, $t$, as being equal to zero when the reaction starts, in which case the reaction time is equal to the elapsed time when the reaction stops. 

In continuous flow systems, the time during which reactions occur is equal to the amount of time that the reagents spend in the reactor. One one measure of the time reagents spend in the reactor is the space time, $\tau$, defined in @eq-space_time. Reactions progress over time, so in qualitative analysis, changes in composition and temperature with increasing batch reaction time or flow reactor space time are of interest.

$$
\tau = \frac{V}{\dot{V}_{0}}
$$ {#eq-space_time}

Because the analysis is qualitative, the rate expression is not used directly. Instead, the general behavior of reactions must be used, noting that for a typical reaction

* the rate will increase if the temperature of the reacting system is increased,
* the rate will decrease if the concentration of one or more reactants decreases,
* the rate is not strongly affected by the concentration of the products if the reaction is irreversible,
* the rate decreases as the concentration of the products increases if the reaction is reversible,
* the equilibrium constant decreases as the temperature increases if the reaction is exothermic, and
* the equilibrium constant increases as the temperature increases if the reaction is endothermic.

Of course, not all reactions behave “typically.” The qualitative analysis methodology presented here also can be applied to atypical reactions if the general behavior above is appropriately adjusted. Atypical behavior can often be recognized by examining the rate expression, if it is available. For example, if the rate increases as the concentration of a *product* increases, the reaction is said to be autocatalytic, and the qualitative behavior can be adjusted accordingly. It is important to note, however, that as a reaction approaches thermodynamic equilibrium, it will asymptotically approach "typical" behavior.

The driving force for a chemical reaction is reducing the free energy of the system. Put differently, a chemical reaction always proceeds toward chemical reaction equilibrium. As a consequence, in an isothermal or adiabatic reactor, a single chemical reaction will never change direction spontaneously. To do so, the reaction would have to go beyond equilibrium and then turn around and go back. Since a single reaction will never change directions, the concentrations of the reactants will continually decrease over time and the concentrations of the products will continually increase over time until equilibrium is reached. When equilibrium is reached, the concentrations will stop changing over time.

The other factor to be considered in a qualitative analysis is the extent to which heat is added or removed as the reaction or reactions progress. There are a number of possibilities in this regard. Qualitative analysis is easiest and most reliable when only one reaction is taking place in a reactor that operates either adiabatically or isothermally. When only one exothermic reaction is taking place adiabatically, the temperature will rise continually since the reaction is releasing heat, and that heat is not being removed. Similarly, when only one endothermic reaction takes place adiabatically, the temperature will drop continually. When a reactor operates isothermally, the temperature does not change as the reaction proceeds. When a reactor is neither adiabatic nor isothermal, qualitative analysis can be more difficult with greater uncertainty in the results.

When a reactor operates adiabatically or isothermally with only one or two reactions taking place, the shape of plots of concentration, temperature, rate, selectivity, etc. *versus* reaction time or space time can be predicted qualitatively as follows.

1. Determine the reactor operating procedure (e. g. isothermal or adiabatic).
2. Determine whether the reaction is typical or atypical, establishing the expected behavior as conditions change.
3. Draw sets of axes with the quantity of interest on the y-axis and reaction time or space time on the x-axis.
4. Plot a point on each y-axis representing the initial values of the quantities of interest. (The axes need not have a scale, and as such, plotted values only indicate whether the quantity is initially large, intermediate or small in value.)
5. Determine the initial slope of each graph by considering how the concentrations and temperature will change during a short interval of time and how those changes will affect the quantity of interest being plotted.
6. Determine the initial curvature of each graph by considering whether the changes in the next short interval of time will be greater than, equal to, or less than those in the first interval of time.
7. Determine whether the initial curvature eventually will result in the system approaching equilibrium (i. e. will each graph asymptotically approach a horizontal line?).
8. If the initial curvature will not lead to equilibrium, infer what must happen so that the system eventually will go to equilibrium (i. e. will there be an inflection point or a minimum/maximum?), and qualitatively explain what will cause these changes in the curvature.

In *Reaction Engineering Basics*, qualitative analyses of this type often will be used in the discussion of the results of a quantitative analysis. In that context, qualitative analysis can be used to answer the question, "Do these results make sense?" Additionally, performing a qualitative analysis after the quantitative analysis helps new reaction engineers develop a physical understanding of results that complements the mathematical understanding obtained in quantitative analysis. As a reaction engineer gains experience and develops the necessary skills and understanding, qualitative analysis can often provide insight and guidance before beginning an assignment. This is particularly true for reactor design tasks like those described above.

## Assignment Completion Workflow {#sec-ch5_workflow}

To be added: here for single, isolated ideal reactor analysis, later chapters will add items as they become necessary

* assignment summary
* computational strategy
* reactor model
* numerical implementation
* results and discussion
* assignment fulfillment

## Examples

Qualitative analyses will be used in subsequent chapters to provide a physical interpretation of the results of quantitative analyses. Here two examples are provided. The first illustrates analysis of a single reaction where both compositional and thermal effects are important. The second involves two reactions in series with the assumption that thermal effects are not significant.

### Example with qual analysis of thermal effects

AFCoKaRE Problem 18.1

### Example with qual analysis of composition effects

AFCoKaRE Example 18.3

## Symbols Used in @sec-ch4

| Symbol | Meaning |
|:-------|:--------|
| $i$ | Subscript denoting a reagent. |


: {tbl-colwidths="[20,80]"}
