# Kinetics Data Analysis

The first part of *Reaction Engineering Basics* introduced the field of reaction engineering and reviewed basic facts about chemical reactions. The second part described and defined chemical reaction rates and rate expressions. It presented empirical and theoretical ways to propose the mathematical form of a rate expression.

After the mathematical form of a rate expression has been proposed, it must be validated using experimental kinetics data. That requires mathematical models for the reactors used in the experiments. So the third part of *Reaction Engineering Basics* examined the equations that are used to model four types of ideal reactors.

Having presented that necessary information about modeling reactors, this fourth part of *Reaction Engineering Basics* returns to the subject of rate expressions. Specifically, it explores the generation and analysis of kinetics data. The design of experiments for gathering kinetics data is presented first, followed by three chapters that explain how to analyze data that were generated using ideal BSTRs, PFRs, and CSTRs.

## Chapters in this Part of *Reaction Engineering Basics*

@sec-6_kin_data_gen Generation and Analysis of Kinetics Data

@sec-6_bstr_data_analysis Analysis of Kinetics Data from a BSTR

@sec-6_pfr_data_analysis Analysis of Kinetics Data from a PFR

@sec-6_cstr_data_analysis Analysis of Kinetics Data from a CSTR
