# The Steady-State Axial Dispersion Model {#sec-7_axial_dispersion}

The axial dispersion model for tubular reactors is a plug flow model with mixing in the axial direction. The axial mixing terms contain constants called dispersion coefficients. This chapter considers using the dispersion coefficients as empirical parameters that can be adjusted to create a model that predicts the response of a non-ideal reactor.

## Axial Dispersion

The nearly flat radial velocity profiles associated with plug flow occur when the flow is turbulent. In turbulent flow, swirling flow patterns known as eddies exist. They are similar to whirlpools. As fluid swirls in an eddy, the component of its velocity in the axial direction can become greater and smaller than the mean fluid velocity in the axial direction. This results in axial mixing of the fluid.

One way to account for this type of mixing while retaining the assumption of plug flow, is by adding the term, $-D_{ax} \frac{\pi D^2}{4} \frac{d^2C_i}{dz^2}$, to the plug flow reactor mole balance for each reagent, $i$. This term represents the axial mixing as a non-convective flux. Similarly, the term, $-\lambda_{ax} \frac{\pi D^2}{4} \frac{d^2T}{dz^2}$, can be added to the plug flow reactor energy balance to account for thermal mixing in the axial direction. Again, the thermal mixing is represented as a non-conductive flux.

The representation of axial mixing using non-convective mass and energy fluxes is referred to as axial dispersion.

## Dispersion Coefficients

To those familiar with mass transfer, the term added to the PFR mole balances looks like a mass diffusion term, and the term added to the energy balance looks like a thermal conduction term. Nonetheless, these terms represent axial disperson, not mass diffusion and heat conduction. The constants, $D_{ax}$ and $\lambda_{ax}$ are called dispersion coefficients. They are properties associated with the fluid flow and not the chemical reagents.

The axial dispersion coefficient, $D_{ax}$, is not a molecular property. It is typically found using correlations between the axial Peclet number, @eq-peclet_number and the Reynolds number, @eq-Reynolds_number. The axial termal dispersion coefficient, $\lambda_{ax}$, is similarly found using correlations between the axial Peclet number for heat, @eq-peclet_number_heat and the Reynolds number.

$$
Pe_{ax} = \frac{4\dot{V}L}{\pi D^2 D_{ax}}
$${#eq-peclet_number}

$$
Pe_{ax,h} = \frac{4\rho \tilde{C}_p \dot{V}L}{\pi D^2 \lambda_{ax}}
$${#eq-peclet_number_heat}

It is more common to add axial dispersion when modeling a packed bed. In that case, the catalyst particle diameter is used as the characteristic length, $L$, in the axial Peclet numbers for mass and heat. The invers of the axial Peclet number, $Pe_{ax}$, is also called the dispersion number, and sometimes the Peclet number is referred to as the Bodenstein number.

## The Axial Dispersion Model

The steady-state axial dispersion mole and energy balance, [Equations -@eq-axial_disp_mole_bal_secnd_order] and [-@eq-axial_disp_energy_bal_secnd_order], are derived in @sec-apndx_axial_dispersion. They are second-order ordinary differential equations which means that two boundary conditions must be provided for each concentration and for the temperature. There are different ways to write those boundary conditions.

$$
- D_{ax} \frac{d^2C_i}{dz^2} + \frac{4 \dot{V}}{\pi D^2} \frac{dC_i}{dz} + \frac{4 C_i}{\pi D^2} \frac{d\dot{V}}{dz} = \sum_j \nu_{i,j}r_j
$${#eq-axial_disp_mole_bal_secnd_order}

$$
- \lambda_{ax}\frac{d^2 T}{d z^2} + \frac{4 \dot{V}}{\pi D^2} \left(\sum_i C_i \hat{C}_{p,i}\right) \frac{d T}{d z} = \frac{4U}{D}\left(T_{ex} - T\right) - \sum_j r_j \Delta H_j
$${#eq-axial_disp_energy_bal_secnd_order}

Within the reactor, according to the axial dispersion model, the net flow of a reagent in the axial direction is the sum of two components. One is convective flow and the other is the non-convective mixing flux. The Danckwerts boundary conditions assume that at the reactor inlet, these two terms combined must equal the purely convective flow of the feed to the reactor inlet. An analogus assumption is made regarding the heat flow, leading to the Danckwerts boundary conditions shown in [Equations -@eq-Danckwerts_conc_bc_second_order] and [-@eq-Danckwerts_energy_bc_second_order].

$$
\dot{V}_{feed}C_{i,feed} = \dot{V}_0 C_{i,0} - D_{ax} \frac{\pi D^2}{4} \frac{dC_i}{dz}\Bigg\vert_{z=0}
$${#eq-Danckwerts_conc_bc_second_order}

$$
\dot{V}_{feed}\sum_i\left(C_{i,feed} \hat{C}_{p,i} \right) T_{feed} = \dot{V}_0 \sum_i\left(C_{i,0} \hat{C}_{p,i} \right) T_0 - \lambda_{ax} \frac{\pi D^2}{4} \frac{dT}{dz}\Bigg\vert_{z=0}
$${#eq-Danckwerts_energy_bc_second_order}

Assuming that the concentrations and temperature stop changing when the fluid leaves the reactor yields a second boundary condition, [Equations -@eq-secnd_order_axial_disp_conc_bc_L] and [-@eq-secnd_order_axial_disp_temp_bc_L]. Because one boundary condition is specified at the reactor inlet ($z=0$) and the other at the outlet ($z=L$), the axial dispersion design equations can be referred to as boundary-value ordinary differential equations (BVODEs).

$$
\frac{dC_i}{dz}\Bigg\vert_{z=L} = 0
$${#eq-secnd_order_axial_disp_conc_bc_L}

$$
\frac{dT}{dz}\Bigg\vert_{z=L} = 0
$${#eq-secnd_order_axial_disp_temp_bc_L}

It is known that at industrial conditions, axial dispersion is only significant near the reactor inlet. In packed bed reactors, its effect becomes negligible at a distance into the reactor equal to approximately 50 catalyst particle diameters.

## The Axial Dispersion Model for Non-Ideal Reactors

As just noted, it often is not necessary to include axial dispersion when modeling an ideal tubular reactor with plug flow. However, the axial dispersion model has features that can make it attractive for use as an empirical model for non-ideal reactors. Spedivically, when the dispersion coefficients are equal to zero, it becomes equal to the ideal PFR model. [Example -@sec-example_23_7_1] shows that as the dispersion coefficients become very large, the axial dispersion model approaches the ideal CSTR model.

So, by varying the dispersion coefficients, the axial dispersion model can display behavior that spans the range from an ideal PFR to an ideal CSTR. Consider a real-world reactor that is not accurately described by either the PFR model or the CSTR model. It may be possible to find values for the dispersion coefficients such that the axial dispersion model does provide an accurate description of the non-ideal reactor.

When the volumetric flow rate is not constant, the presence $\frac{d\dot{V}}{dz}$ makes it considerably more involved to solve the axial dispersion design equations. As long as values can be found for the dispersion coefficients that result in an accurate representation of the non-ideal reactor, that term can be dropped from the axial dispersion model for ideal reactors. Doing so results in @eq-axial_disp_mole_bal_secnd_order_const_v. In addition, it is no longer necessary to differentiale between $\dot{V}_0$ and $\dot{V}_{feed}$ in the Danckwerts boundary conditions.

$$
- D_{ax} \frac{d^2C_i}{dz^2} + \frac{4 \dot{V}}{\pi D^2} \frac{dC_i}{dz} = \sum_j \nu_{i,j}r_j
$${#eq-axial_disp_mole_bal_secnd_order_const_v}

Numerical solution of the axial dispersion design equations is facilitated by converting them to an equivalent set of first order ODEs. @sec-apndx_axial_dispersion shows how this is done. Briefly, new variables are defined as being equal to the derivatives of the concentrations and temperature with respect to $z$, yielding [Equations -@eq-ax_disp_new_var_conc] and [-@eq-ax_disp_new_var_temp]. Substitution of those new variables into the axial dispersion mole and energy balances reduces them to first order ODEs with the new variables being the dependent variables, [Equations -@eq-ax_disp_first_order_conc] and [-@eq-ax_disp_first_order_temp]. The boundary conditions can also be expressed in terms of the new variables, [Equations -@eq-Danckwerts_first_order_conc] through [-@eq-first_order_axial_disp_temp_bc_L].

$$
\frac{dC_i}{dz} = \omega_i
$${#eq-ax_disp_new_var_conc}

$$
\frac{dT}{dz} = \omega_T
$${#eq-ax_disp_new_var_temp}

$$
- D_{ax}\frac{d \omega_i}{d z} = - \frac{4 \dot{V}}{\pi D^2}\omega_i + \sum_j \nu_{i,j}r_j
$${#eq-ax_disp_first_order_conc}

$$
- \lambda_{ax}\frac{d \omega_T}{d z} = - \frac{4 \dot{V}}{\pi D^2} \left(\sum_i C_i \hat{C}_{p,i}\right) \omega_T + \frac{4U}{D}\left(T_{ex} - T\right) - \sum_j r_j \Delta H_j
$${#eq-ax_disp_first_order_temp}

$$
C_{i,0} = C_{i,feed} + D_{ax} \frac{\pi D^2}{4} \frac{\omega_{i,0}}{\dot{V}}
$${#eq-Danckwerts_first_order_conc}

$$
T_0 = \frac{\sum_iC_{i,feed} \hat{C}_{p,i}}{\sum_iC_{i,0} \hat{C}_{p,i}}T_{feed} + \lambda_{ax} \frac{\pi D^2}{4} \frac{\omega_{T,0}}{\dot{V} \sum_i\left(C_{i,0} \hat{C}_{p,i} \right)}
$${#eq-Danckwerts_first_order_temp}

$$
\omega_i\Big\vert_{z=L} = \omega_{i,1} = 0
$${#eq-first_order_axial_disp_conc_bc_L}

$$
\omega_T\Big\vert_{z=L} = \omega_{T,1} = 0
$${#eq-first_order_axial_disp_temp_bc_L}

## The Non-Ideal Axial Dispersion Reactor Function

As with other reactor models, it is useful to defin a reactor function that can be used to solve the non-ideal axial dispersion reactor model equations. In this case, those design equations are BVODEs. The numerical solution of BVODEs is described in @sec-apndx_solve_bvodes. Doing so involves calling a BVODE solver from a mathematics software of one's choosing.

The details for using a BVODE solver will depend upon the mathematics software package it comes from. Generally a BVODE solver must be provided with five things. The first two are the values of the independent variables at each of the boundaries. In the axial dispersion model the boundaries are usually $z=0$ and $z=L$. The third is a guess for the values of the dependent variables ($w_i$, $w_T$, $C_i$, and $T$) within the reactor (see @sec-apndx_solve_bvodes).

The fourth thing that must be provided is the name of a function that evaluates the derivatives in the design equations ($\frac{d\omega_i}{dz}$, $\frac{d\omega_T}{dz}$, $\frac{dC_i}{dz}$, and $\frac{dT}{dz}$). The last thing that must be provided to the BVODE solver the the name of a function that evaluates the boundary conditions.

The function that evaluates the derivatives and the function that evaluates the boundary conditions must be written by the engineer. However, since the BVODE solver will call them, the arguments they receive and the quantities they return are specified by the mathematics software package being used. In general, the derivatives function receives values of the independent and dependent variables as arguments and returns the corresponding values of the derivatives The function that evaluates the boundary conditions typically receives the values of the dependent variables at the boundaries (i. e. at the reactor inlet and outlet) and it returns residuals corresponding to the boundary conditions.

The non-ideal axial dispersion reactor function is also written by the engineer performing the analysis. It is not called directly by the BVODE solver, so the engineer can decide what arguments it takes and what quantities it returns. If only one reactor configuration needs to be simulated, the reactor function need not receive any arguments. In *Reaction Engineering Basics* the axial dispersion reactor function always returns the profiles of the dependent variables from the reactor inlet to its outlet.

### Multiplicy of Steady States

Just as was seen with steady-state CSTRs, there can be multiple solutions to the steady-state axial dispersion model design equations. Multiple steady states are a consequence of mixing between the reactor inlet and its outlet. They are not observed in steady-state PFRs because there isn't any axial mixing, but by adding the axial dispersion term, multiple steady states become possible. When multiple steady states are possible, the one that is found by the BVODE solver typically depends upon the guess for the values of the dependent variables provided to it.

## Fitting the Axial Dispersion Model to Reactor Data

If an engineer wants to be able to simulate a non-ideal reactor using the axial dispersion model, it is necessary to find the best values for the dispersion coefficients. The procedure for doing so is effectively the same as the procedure for finding rate expression parameters during the analysis of kinetics data. In the present case, the rate expression parameters are known and the dispersion coefficients are estimated by fitting the axial dispersion model to experimental data.

There can be one very significant difference, however. In kinetics data analysis the engineer can perform many, many experiments using a small laboratory reactor. If an engineer needs to estimate dispersion coefficients for an existing, commercial scale reactor, it is likely that it won't be possible to perform a set of experiments to gather data.

One option in this situation is to measure the age function for the reactor (see @sec-7_seg_flow_models). Often the age function can be measured without disrupting the operation of the reactor, if an appropriate tracer can be identified and added to the feed as an impulse stimulus. The axial dispersion model can be used to calculate a model-predicted age function. Then the model-predicted age function can be fit to age function data from the commercial reactor using the dispersion coefficients as the parameters.

One potential problem with using age function data is that the age function may depend only weakly on the thermal dispersion coefficient. If so, the fit may yield a good estimate for the axial dispersion coefficient, but not for the thermal dispersion coefficient. If the thermal dispersion coefficient is poorly estimated and the engineer feels a better estimate is needed, one option is to measure the temperature profile in the reactor. The temperature profile can usually be measured without disrupting the operation of the reactor. Depending on the degree of instrumentation in the reactor, the capability for measuring the temperature profile may already exist.

If both the age function and the temperature profile are measured, the resulting data set contains multiple responses. The methods used for kinetics data analysis in @sec-6_bstr_data_analysis through [-@sec-6_pfr_data_analysis] apply for single-response data. Software for parameter estimation using mulitple response data will necessary. Parameter estimation using multiple response data goes beyond the scope of *Reaction Engineering Basics.*

## Examples

The first example that follows involves an adiabatic reaction of a liquid feed stream. As such, only the axial dispersion reactor design equations are needed. The second example considers an adiabatic gas phase reaction in a packed bed with a pressure drop. Its solution requires use of the differential ideal gas law and a momentum balance in addition to the axial dispersion reactor design equations.

### Effect of Dispersion Coefficients on the Response Predicted by the Axial Dispersion Model {#sec-example_23_7_1}

to be added

### Effects os the Axial Dispersion Coefficient and the Thermal Dispersion Coefficient upon Reactor Response {#sec-example_23_7_2}

to be added

### Non-Ideal Axial Dispersion Model for a Tubular Reactor with Heat Exchange {#sec-example_23_7_3}

to be added

### Prediction of the Age Function using the Axial Dispersion Model {#sec-example_23_7_4}

to be added

## Symbols Used in @sec-7_axial_dispersion

| Symbol | Meaning |
|:-------|:--------|
| $t$ | Time. |

: {tbl-colwidths="[20,80]"}