# Modeling Isolated Ideal Reactors

The first part of *Reaction Engineering Basics* examined reaction rates and rate expressions. It defined reaction rates and noted that rate expressions are equations that give the reaction rate as a function of temperature, pressure and composition. The empirical, theoretical, and mechanistic origins of mathematical forms for rate expressions were presented, and the procedure for assessing the accuracy of a proposed rate expression was detailed. That procedure was shown to involve performing experiments and analyzing the data generated in those experiments.

The analysis of experimental kinetics data requires mathematical models for the reactor used. Consequently, the reactor design equations used to model ideal batch stirred tank reactors (BSTRs), semi-batch stirred tank reactors (SBSTRs), continuous stirred tank reactors (CSTRs) and tubular plug flow reactors (PFRs) were presented and common simplifications of those equations were described in @sec-3_design_eqns. Their use to create response functions was considered in @sec-3_response_func. Then the analysis of kinetics data analysis to estimate rate expression parameters and the assessment of the accuracy of rate expressions were described in the preceeding section of *Reaction Engineering Basics*.

In the remainder of the book, the focus shifts from reaction kinetics to reaction engineering. This fifth section describes the use of those same reactor design equations and response functions in the analysis of isolated ideal reactors. Here "isolated" means that the analysis considers nothing other than the reactor.

In the chapters of this section, analysis of BSTRs, SBSTRs, CSTRs, and PFRs is described. For each of those ideal reactor types, three kinds of reaction engineering tasks are considered: reactor response tasks, reactor optimization tasks, and reactor design tasks. To begin this section, those three kinds of reaction engineering tasks are described, and differences in the way they are completed are highlighted.

## Chapters in this Section

@sec-5_response_opt_design Response, Optimization and Design of Reactors

@sec-5_bstr_analysis BSTR Analysis

@sec-5_sbstr_analysis SBSTR Analysis

@sec-5_non_continuous_design Design of Non-continuous Reactors

@sec-5_cstr_analysis CSTR Analysis

@sec-5_pfr_analysis PFR Analysis

@sec-5_continuous_design Design of Continuous Reactors