# Reaction Engineering Ethics and Safety {#sec-1_safety_ethics}

Engineers bear significant responsibility in their work, and the public trusts them to do their work accordingly. Codes of ethics serve as guidelines for practicing engineers, and those guidelines touch upon safety. Considering reaction engineering specifically, failure to fully consider safety can result in injury and death to humans and long-lasting damage to the environment. This short chapter emphasizes the criticality of ethics and safety in reaction engineering.

## Ethics {#sec-1_2_a_ethics}

Most engineering professional societies and many engineering schools have set forth **codes of ethics**, and many of the professionals who practice reaction engineering are members of the American Institute of Chemical Engineers (AIChE). The AIChE Code of Ethics [@american_institute_of_chemical_engineers_code_2012] is as follows.

> The Board of Directors of the American Institute of Chemical Engineers adopted this Code of Ethics to which it expects that the professional conduct of its members shall conform, and to which every applicant attests by signing his or her membership application. Members of the American Institute of Chemical Engineers shall uphold and advance the integrity, honor and dignity of the engineering profession by: being honest and impartial and serving with fidelity their employers, their clients, and the public; striving to increase the competence and prestige of the engineering profession; and using their knowledge and skill for the enhancement of human welfare. To achieve these goals, members shall:  
> 1. Hold paramount the safety, health and welfare of the public and protect the environment in performance of their professional duties.  
> 2. Formally advise their employers or clients (and consider further disclosure, if warranted) if they perceive that a consequence of their duties will adversely affect the present or future health or safety of their colleagues or the public.  
> 3. Accept responsibility for their actions, seek and heed critical review of their work and offer objective criticism of the work of others.  
> 4. Issue statements or present information only in an objective and truthful manner.  
> 5. Act in professional matters for each employer or client as faithful agents or trustees, avoiding conflicts of interest and never breaching confidentiality.  
> 6. Treat all colleagues and co-workers fairly and respectfully, recognizing their unique contributions and capabilities by fostering an environment of equity, diversity and inclusion.  
> 7. Perform professional services only in areas of their competence.  
> 8. Build their professional reputations on the merits of their services.  
> 9. Continue their professional development throughout their careers, and provide opportunities for the professional development of those under their supervision.  
> 10. Never tolerate harassment.  
> 11. Conduct themselves in a fair, honorable and respectful manner.

All 11 expectations of the AIChE Code of Ethics are important. A few of them are particularly relevant for reaction engineers. Holding paramount the safety, health and welfare of the public and protecting the environment is discussed later in this chapter. The second tenet, advising employers if you think your work can affect others’ health or safety is essential. As an example, suppose a process you are operating produces an aqueous toxic waste stream. That waste stream is purified, and the resulting purified water is discharged into a stream. If you learn that the purification system has not been operating properly and, consequently, contaminated water has been discharged into the stream, it is essential that you report this to your employer. If your employer takes no action, you should consider further disclosure.

The seventh and ninth expectations can also be relevant. This book presents an *introduction* to reaction engineering. There are many aspects of the field that it does not touch upon. If you intend to pursue reaction engineering as a career, there is much more you need to learn. You should continue to build your reaction engineering competence. Until you have learned more, you should not attempt engage in reaction engineering of systems that do not conform to the assumptions used in this book.

This book is not about ethics, or even reaction engineering ethics. Nonetheless, this chapter has been included because every engineer should be aware of codes of ethics that have been developed for their field. Before you are confronted with an issue of ethics, it is useful to know what you *should* do, and to have thought about and committed to responding in an ethical manner. Establishing personal principles of ethical behavior now, and sticking with them in small matters, will be beneficial should larger ethical issues arise in the future.

## Safety{#sec-1_2_b_safety}

According to the AIChE Code of Ethics the most important ethical responsibilities (the one to be held paramount) are the safety, health and welfare of people and the protection of the environment. Reactive chemical processes present risk with respect to all of these responsibilities. While not intended nor desired, explosions and release of toxic chemicals can occur resulting in deaths, injury, property damage and environmental contamination. Reaction engineers must always be aware of such possibilities and must do all they can to prevent them.

Much can be learned from the U. S. Chemical Safety Board (CSB), a federal agency that investigates industrial chemical accidents [@noauthor_us_nodate]. As an example, “CSB Safety Video: Reactive Hazards” [@u_s_chemical_safety_board_csb_nodate] describes four chemical reaction accidents. In addition to describing how and why the accident occurred, the video offers a number of safety recommendations related to reactive processes.

The first accident was the result of a change in process operation. It involved the highly exothermic polymerization of an acrylic polymer. The company had operated the process safely for years in batches of fixed size. An order was received for an amount of polymer 12% greater than the standard batch size. When the company attempted to manufacture the requested amount in a single batch, the cooling system was unable to remove the generated heat, and the reactor exploded. One person died and 14 others were injured.

A twelve percent increase does not seem excessive. Nonetheless, it **should not have been assumed** that the batch size could be increased by 12% without affecting the process. Ethics would dictate that the consequences of this change should have been thoroughly investigated *before* making a decision to increase the batch size.

The second accident was the indirect result of an equipment failure. A polymerization reactor was used to produce hot polymer being fed to an extruder. During start-up, the extruder failed and the hot polymer was diverted to a storage tank. Too much time was spent trying to fix the extruder, so that the storage tank was overfilled. The excess polymer blocked the pressure gauge and the vent. As a result, workers did not know that the tank was under high pressure, and when they attempted to unbolt the cover, it blew off. As it blew off, the cover broke pipes, resulting in a fire. Three workers were killed.

The third accident was the result of improper scale-up of a chemical reactor. A reaction had been studied and operated safely in a 30 gallon test reactor. When the company scaled up to a 4000 gallon production reactor, they failed to realize that additional cooling was necessary. The production reactor exploded and released toxic chemicals into the air. Two hundred families living nearby had to be evacuated. One hundred fifty-four people had to be treated due to exposure to the chemicals.

The last example involved a leaking valve that the operators believed to be closed. Ultimately this resulted in a explosion that threw a 35 foot section of a tower completely off the chemical site. Another chunk of the tower hit a storage tank setting it ablaze. Shrapnel landed close to nearby tanks, one containing crude oil and the other, anhydrous ammonia. Had any shrapnel hit those tanks, the effects would have been even more dire.

These accidents have been described here to drive home the point that the highest ethical standards must be used when dealing with reactive processes. None of these accidents were desired nor expected. Some were caused by human error and others by a combination of equipment failure and not anticipating and planning for potential disruption of process conditions.

The CSB video [@u_s_chemical_safety_board_csb_nodate] gives a number of recommendations that are worth repeating here. They apply equally to large industrial facilities and to small research laboratories.

* Those responsible for a chemical process must have a thorough understanding of the chemistry under designed operating conditions **and** under all foreseeable abnormal conditions. Multiple sources of information on chemical processes should be consulted and specialized testing should be conducted, if necessary, before operating reactive processes. Indeed, the CSB found that over 90% of serious accidents involve hazards that have already been described in publicly available literature.
* Detailed operating procedures should be developed and training programs to teach those procedures should be implemented. Potential hazards must be communicated to anyone associated with the operation *or maintenance* of reactive processes. Appropriate pressure relief and other safeguards need to be designed into the process.
* The effects of even small changes to process conditions should be thoroughly studied before they are implemented, and the implementation of any changes must be carefully managed.
* Facilities need to plan for possible accidents, including evacuation drills and emergency response exercises. There should be well-rehearsed evacuation plans for facilities where reactive chemical processes operate. There should also be regular emergency response exercises. When appropriate, local law enforcement, firefighters and other first responders should be involved in such exercises.

As with the preceding section on ethics, the safety information presented here barely scratches the surface. Hopefully it is sufficient to have created an awareness of the importance of incorporating safety in every aspect of reaction engineering.