# Reactor Models

The first section of *Reaction Engineering Basics* reviewed chemical reactions and stoichiometry. The second section defined chemical reaction rates and introduced rate expressions as mathematical models that predict the rate of a reaction as a function of fluid composition, temperature and pressure. It noted that when a rate expression is not available for a reaction, the mathematical form of the rate expression can be proposed empirically, theoretically, or mechanistically, but before it can be used, it must be validated. The validation of a rate expression requires the use and modeling of a chemical reactor. So this section of *Reaction Engineering Basics* offers a short break from rate expressions in order to discuss reactors and reactor models.

In *Reaction Engineering Basics*, every assignment that involves a reactor is completed in five basic steps.

1. Summarize the information provided in the assignment.
2. Formulate the solution mathematically.
3. Implement the solution numerically.
4. Execute the solution.
5. Report and comment upon the results.

A mathematical model for the reactor is needed when formulating a solution to an assignment (step 2). So as preparation for completing assignments that involve a reactor, @sec-3_design_eqns examines the equations that are needed in order to model the four kinds of ideal chemical reactor that were mentioned in @sec-1_intro_and_defs. Those equations are called the reactor design equations.

The numerical implementation of a solution (step 3) includes solving the reactor design equations. In *Reaction Engineering Basics* the reactor design equations are solved within a computer function that is referred to as the reactor response function. @sec-3_response_func describes how to use the reactor design equations to create a reactor response function that solves them.

## Chapters in this Section

@sec-3_design_eqns Reactor Design Equations

@sec-3_response_func Reactor Response Functions