<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Reaction Engineering Basics - 11&nbsp; Analysis of Kinetics Data from a CSTR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./section_5_intro.html" rel="next">
<link href="./section_4_pfr_data_analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="http://buffalobadger.github.io" class="navbar-brand navbar-brand-logo">
    <img src="./Graphics/Banner.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="http://buffalobadger.github.io/total_ps.html" rel="" target="">
 <span class="menu-text">ToTaL PS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Reaction Engineering Basics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="http://buffalobadger.github.io/about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./section_4_intro.html">Kinetics Data Analysis</a></li><li class="breadcrumb-item"><a href="./section_4_cstr_data_analysis.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a CSTR</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_1_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic Information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_1_intro_and_defs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reactions, Reactors, and Reaction Engineering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_1_safety_and_ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reaction Engineering Ethics and Safety</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_1_reaction_progress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measures of Reaction Progress</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_2_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rate Expressions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_2_rates_and_expressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reaction Rates and Rate Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_2_mechanisms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reaction Mechanisms and Mechanistic Rate Expressions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_3_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reactor Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_3_design_equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reactor Design Equations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_3_response_function.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reactor Response Functions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_4_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kinetics Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_4_data_generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Generation and Analysis of Kinetics Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_4_bstr_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a BSTR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_4_pfr_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a PFR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_4_cstr_data_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a CSTR</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_5_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling Isolated Ideal Reactors</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_reaction_engineering_tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Response, Optimization and Design of Reactors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_bstr_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">BSTR Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_sbstr_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">SBSTR Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_non_continuous_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Design of Non-continuous Reactors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_cstr_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">CSTR Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_pfr_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">PFR Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_5_continuous_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Design of Continuous Reactors</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_6_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling Ideal Reactor Systems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_6_reactor_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Reactor Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_6_thermally_backmixed_pfr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Thermally Back-mixed PFRs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_6_recycle_pfr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Recycle PFRs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section_7_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling Non-Ideal Reactors</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_7_axial_dispersion_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Axial Dispersion Reactor Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_7_segregated_flow_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Segregated Flow Reactor Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./section_7_zoned_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Zoned Reactor Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_prereq_knowledge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Prerequisite Knowledge</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_nomenclature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Notation and Sign Conventions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_reaction_thermo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Reaction Thermodynamics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_heat_exchange.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Reactor Heat Exchange</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_collision_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Collision Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_transition_state_theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Transition State Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_ideal_reactor_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Ideal Reactor Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_solve_ates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Solving Algebraic Equations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_solve_ivodes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Solving Initial-Value ODEs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_estimate_parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Parameter Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_solve_bvodes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Solving Boundary-Value ODEs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apndx_solve_daes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Solving Differential-Algebraic Equations</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#laboratory-cstrs" id="toc-laboratory-cstrs" class="nav-link active" data-scroll-target="#laboratory-cstrs"><span class="header-section-number">11.1</span> Laboratory CSTRs</a>
  <ul class="collapse">
  <li><a href="#testing-the-ideality-of-a-cstr" id="toc-testing-the-ideality-of-a-cstr" class="nav-link" data-scroll-target="#testing-the-ideality-of-a-cstr"><span class="header-section-number">11.1.1</span> Testing the Ideality of a CSTR</a></li>
  </ul></li>
  <li><a href="#cstr-kinetics-experiments-and-data" id="toc-cstr-kinetics-experiments-and-data" class="nav-link" data-scroll-target="#cstr-kinetics-experiments-and-data"><span class="header-section-number">11.2</span> CSTR Kinetics Experiments and Data</a></li>
  <li><a href="#design-of-cstr-experiments" id="toc-design-of-cstr-experiments" class="nav-link" data-scroll-target="#design-of-cstr-experiments"><span class="header-section-number">11.3</span> Design of CSTR Experiments</a>
  <ul class="collapse">
  <li><a href="#adjusted-experimental-inputs" id="toc-adjusted-experimental-inputs" class="nav-link" data-scroll-target="#adjusted-experimental-inputs"><span class="header-section-number">11.3.1</span> Adjusted Experimental Inputs</a></li>
  <li><a href="#experimental-responses" id="toc-experimental-responses" class="nav-link" data-scroll-target="#experimental-responses"><span class="header-section-number">11.3.2</span> Experimental Responses</a></li>
  </ul></li>
  <li><a href="#cstr-data-analysis" id="toc-cstr-data-analysis" class="nav-link" data-scroll-target="#cstr-data-analysis"><span class="header-section-number">11.4</span> CSTR Data Analysis</a>
  <ul class="collapse">
  <li><a href="#analysis-using-a-response-function" id="toc-analysis-using-a-response-function" class="nav-link" data-scroll-target="#analysis-using-a-response-function"><span class="header-section-number">11.4.1</span> Analysis Using a Response Function</a></li>
  <li><a href="#analysis-using-a-linearized-model" id="toc-analysis-using-a-linearized-model" class="nav-link" data-scroll-target="#analysis-using-a-linearized-model"><span class="header-section-number">11.4.2</span> Analysis Using a Linearized Model</a></li>
  </ul></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"><span class="header-section-number">11.5</span> Examples</a>
  <ul class="collapse">
  <li><a href="#sec-example_11_1" id="toc-sec-example_11_1" class="nav-link" data-scroll-target="#sec-example_11_1"><span class="header-section-number">11.5.1</span> Analysis of Data for Liquid-Phase Reaction</a></li>
  <li><a href="#sec-example_11_2" id="toc-sec-example_11_2" class="nav-link" data-scroll-target="#sec-example_11_2"><span class="header-section-number">11.5.2</span> Analysis of Data for a Gas-Phase Reaction with Change of Total Moles</a></li>
  <li><a href="#sec-example_11_3" id="toc-sec-example_11_3" class="nav-link" data-scroll-target="#sec-example_11_3"><span class="header-section-number">11.5.3</span> Analysis of Data for a Reversible Reaction</a></li>
  </ul></li>
  <li><a href="#symbols-used-in-sec-4_cstr_data_analysis" id="toc-symbols-used-in-sec-4_cstr_data_analysis" class="nav-link" data-scroll-target="#symbols-used-in-sec-4_cstr_data_analysis"><span class="header-section-number">11.6</span> Symbols Used in <span>Chapter&nbsp;11</span></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-4_cstr_data_analysis" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a CSTR</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This section of <em>Reaction Engineering Basics</em> focuses upon the analysis of kinetics data for the purpose of assessing the accuracy of a proposed rate expression. <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a> presented a general introduction to kinetics data analysis and <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> examined the analysis of kinetics data generated using a BSTR. This chapter is like <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> except it is focused on the analysis of kinetics data generated using a CSTR.</p>
<section id="laboratory-cstrs" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="laboratory-cstrs"><span class="header-section-number">11.1</span> Laboratory CSTRs</h2>
<p>There are many similarities between BSTRs and CSTRs. The primary difference is that fluid continually flows in and out of a CSTR. Basically CSTRs are BSTRs with inlet and outlet flow streams. Other than the stopped flow reactor, the BSTRs described in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> could be converted to CSTR simply by adding a flow in and a flow out. In the case of the recirculation loop reactor, <a href="section_4_bstr_data_analysis.html#fig-batch_recirc_reactor">Figure&nbsp;<span>9.2</span></a>, the flow in and out should be small compared to the recirculation flow within the loop. As with the BSTR, one of the most important characteristics of a CSTR is that it is perfectly mixed. As discussed below, when a CSTR is used to generate kinetics data, it is preferable to operate the CSTR at steady state. Consequently, in addition to assessing the mixing before experiments begin, it is also important to verify steady-state operation while conducting the experiments.</p>
<section id="testing-the-ideality-of-a-cstr" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="testing-the-ideality-of-a-cstr"><span class="header-section-number">11.1.1</span> Testing the Ideality of a CSTR</h3>
<p>Given the similarities between BSTRs and CSTRs, most of the discussion in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> applies here, as well. Specifically, one of the most important requirements is that the reactor must be perfectly mixed. Smoke tests and the measurement of the reactor response as the agitation rate is increased again can be used to test for perfect mixing. In addition, a property known as the residence time distribution can be used to assess how well a reactor conforms to the assumptions of an ideal CSTR. Essentially, it provides a necessary, but not sufficient, criterion that the laboratory reactor must satisfy. The measurement and use of the residence time distribution will be presented in <a href="section_7_segregated_flow_model.html"><span>Chapter&nbsp;23</span></a>.</p>
</section>
</section>
<section id="cstr-kinetics-experiments-and-data" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="cstr-kinetics-experiments-and-data"><span class="header-section-number">11.2</span> CSTR Kinetics Experiments and Data</h2>
<p>The nature of kinetics experiments involving a CSTR and the data they generate is different in some respects from a BSTR. To prevent the generally strong temperature dependence of reaction rates from masking weaker composition and pressure effects, experiments should be performed in blocks where all of the experiments in a block are performed at the same temperature. The first two examples in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> showed how each block of data can then be analyzed to estimate the rate coefficient at the temperature used in that block. Then, once all of the blocks have been analyzed, the Arrhenius expression can be fit to the resulting <span class="math inline">\(k\)</span> <em>vs</em>. <span class="math inline">\(T\)</span> data to estimate the pre-exponential factor and the activation energy.</p>
<p>When using a CSTR to generate kinetics data, it should operate at steady state. There are two good reasons for this. First, the temperature of the reacting fluid is likely to change during transient operation, and that prevents the use of same-temperature data blocks. Second, when the reactor operates at steady state, data analysis is greatly simplified. Specifically, the steady-state reactor design equations are algebraic-transcendental equations (ATEs) whereas the transient design equations are initial value ordinary differential equations (IVODEs). Additionally, when the reactor operates at steady state at a known temperature, the mole balance design equations can be solved independently of the energy balances, so only the mole balances are needed when analyzing steady-state CSTR kinetics data.</p>
<p>In a typical CSTR kinetics experiment, the rate of fluid flow into the reactor is set along with the composition of the feed fluid. The pressure and temperature are also adjusted to their desired values for that experiment. Once these inputs have been fixed, the flow rate and composition of the fluid leaving the reactor is monitored. Initially the outlet composition and flow rate may change over time. This indicates that the CSTR has not yet reached steady state. When the outlet flow rate and composition become constant, the CSTR has reached steady state, and the response is measured, and that concludes the experiment. This is very different from BSTR experiments where the response was measured several times during a single experiment. The reason, of course, is that the composition changes during a BSTR experiment wherease nothing changes during a steady-state CSTR experiment. Consequently, the generation of kinetics data using a CSTR typically involves many more experiments compared to when a BSTR is used.</p>
</section>
<section id="design-of-cstr-experiments" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="design-of-cstr-experiments"><span class="header-section-number">11.3</span> Design of CSTR Experiments</h2>
<p>In isothermal BSTR experiments the initial composition and pressure of the reacting fluid and the elapsed time at which the response was measured were the inputs that were adjusted so that the experiments sampled a wide range of compositions. In a sense, the same is true of flow reactor experiments (both CSTR and PFR), but in flow reactors the space time, <a href="section_3_design_equations.html#eq-space_time">Equation&nbsp;<span>6.1</span></a>, determines how long the reaction is allowed to proceed instead of the elapsed wall-clock time (see <a href="section_3_design_equations.html"><span>Chapter&nbsp;6</span></a>). This means that for flow reactors there are more reactor inputs that can be adjusted in order to vary the space time.</p>
<p>As noted in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a>, preliminary studies typically define ranges of interest for temperature, pressure, and composition, and the purpose of kinetics experiments is to generate kinetics data that span those ranges. For each factor (e.g.&nbsp;the temperature, pressure, the concentration of reagent A, the concentration of reagent B, etc.) a set of values (also called levels) are chosen that span its range of interest. Increasing the number of levels improves the resolution of the effect of that factor upon the reaction rate. At the same time, increasing the number of levels increases the number of experiments that must be performed. Once the levels have been chosen for each factor, a factorial design like that described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a> can be used to specify the experiments that will be performed.</p>
<section id="adjusted-experimental-inputs" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="adjusted-experimental-inputs"><span class="header-section-number">11.3.1</span> Adjusted Experimental Inputs</h3>
<p>Temperature is always an important factor, and as previously noted CSTR experiments are conducted in blocks where the steady-state temperature is the same for all experiments in each block. The pressure is constant in CSTR experiments, so if pressure is a factor of interest, the reactor pressure becomes one of the adjusted inputs.</p>
<p>The concentrations (or, for gases, partial pressures) within the reactor are the ones that need to span their range of interest, but unfortunately they cannot be adjusted directly. Instead, the composition and flow rate of the feed entering the reactor are adjusted. Depending upon the configuration of the feed system, the variables that can be adusted include the molar flow rates of the individual reagents or the volumetric flow rate of the feed and the concentrations of the reagents in that feed. Changing these quantities effectively changes the starting composition and the space time. (This assumes that the same reactor will be used in every experiment so the reactor volume cannot be adjusted to vary the space time.)</p>
</section>
<section id="experimental-responses" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="experimental-responses"><span class="header-section-number">11.3.2</span> Experimental Responses</h3>
<p>It was noted in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> that there are many different quantities that can be used as the experimental response. That discussion won’t be repeated here. The response should be a quantity that is directly related to the composition of the fluid leaving the reactor or to the extent of reaction relative to the reactor feed. In other words, after measuring the response and knowing the feed, it should be possible to calculate the concentration of every reagent in the product stream leaving the reactor.</p>
</section>
</section>
<section id="cstr-data-analysis" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="cstr-data-analysis"><span class="header-section-number">11.4</span> CSTR Data Analysis</h2>
<p>The focus of this section is the analysis of a block of experimental CSTR kinetics data where the steady-state reactor temperature was the same in every experiment. Once all blocks have been analyzed as described here, the Arrhenius expression can be fit to resulting rate coefficients for the block temperatures. The fitting of the Arrhenius expression has been discussed and illustrated several times in <a href="section_2_rates_and_expressions.html"><span>Chapter&nbsp;4</span></a>, <a href="section_3_design_equations.html"><span>Chapter&nbsp;6</span></a>, and <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a>, and should be familiar at this point. It won’t be repeated again here, but instead, analysis of a constant-temperture block of CSTR kinetics data using the CSTR reactor design equations is featured.</p>
<p><a href="section_3_design_equations.html"><span>Chapter&nbsp;6</span></a> explained that when a reactor operates at a constant, known temperature, the mole balances for the reactor can be solved independently of the other reactor design equations. Consequently the steady-state form of the ideal CSTR mole balance, <a href="section_3_design_equations.html#eq-cstr_ss_mole_balance">Equation&nbsp;<span>6.30</span></a>, is the only equation needed to model the reactor used to generate CSTR kinetics data. In <em>Reaction Engineering Basics</em> the kinetics data analysis problems are limited to systems where only one reaction is taking place. In that situation, it is not necessary to use an index to differentiate between multiple reactions, and the steady-state mole balance takes the form shown in <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a>.</p>
<p><span id="eq-cstr_mole_bal_one_reaction"><span class="math display">\[
0 = \dot{n}_{i,in} - \dot{n}_i + \nu_i r V
\tag{11.1}\]</span></span></p>
<p>When a rate expression is substituted into <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a> it will introduce the concentration (or possibly for gases, partial pressure) of one or more reagents. In order to solve the mole balances for the outlet molar flow rates of the reagents, the concentration or partial pressure must be expressed in terms of the molar flow rates. Assuming liquids to be incompressible ideal mixtures, the volumetric flow rate is constant and the concentration is related to the molar flow rates as shown in <a href="section_1_intro_and_defs.html#eq-concentration_open">Equation&nbsp;<span>1.15</span></a>.</p>
<p><span class="math display">\[
C_i = \frac{\dot n_i}{\dot V}
\]</span></p>
<p>CSTRs operate at constant pressure, and when used in kinetics experiments, the temperature is also constant. For gas phase systems, however, the volumetric flow rate in <a href="section_1_intro_and_defs.html#eq-concentration_open">Equation&nbsp;<span>1.15</span></a> will change if the reaction causes a change in the total number of moles. Using the ideal gas law to express the volumetric flow rate in terms of the molar flow rates yields the preferred expression for the concentration of a gas phase reagent, <span class="math inline">\(i\)</span>, shown in <a href="#eq-conc_cstr_kinetics">Equation&nbsp;<span>11.2</span></a>.</p>
<p><span id="eq-conc_cstr_kinetics"><span class="math display">\[
C_i = \frac{\dot n_iP}{RT\displaystyle \sum_i\left( \dot{n}_i \right)}
\tag{11.2}\]</span></span></p>
<p>If the rate expression for a gas-phase reaction uses partial pressures instead of concentrations, the partial pressure is related to the molar flow rates as shown in <a href="#eq-partial_pressure_kinetics">Equation&nbsp;<span>11.3</span></a>.</p>
<p><span id="eq-partial_pressure_kinetics"><span class="math display">\[
P_i = y_iP = \frac{\dot{n}_iP}{\displaystyle \sum_i\left( \dot{n}_i \right)}
\tag{11.3}\]</span></span></p>
<section id="analysis-using-a-response-function" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="analysis-using-a-response-function"><span class="header-section-number">11.4.1</span> Analysis Using a Response Function</h3>
<p>The analysis of CSTR kinetics data using a response function is analogous to the analysis of BSTR kinetics data using a response function. The only difference is that the reactor model is a set of ATEs that must be solved numerically instead of a set of IVODEs. Briefly, the procedure is a follows. A response function is created. It is passed the adjusted experimental inputs and values for the rate expression parameters as arguments. Within the response function, the reactor model (the ATEs) is solved for each experiment to find the outlet molar flow rates of all reagents. The results are then used to calculate the model-predicted value of the response that was measured in the experiments. The response function returns the model-predicted responses for all of the experiments.</p>
<p>As noted, the CSTR mole balance design equations are ATEs that will be solved numerically. See <a href="apndx_solve_ates.html"><span>Appendix&nbsp;H</span></a> for a brief overview of the numerical solution of ATEs. A guess for the unknowns is typically needed when solving ATEs numerically. For this reason, it is useful to also make the experimental responses available within the response function. They can be used to make guesses for the unknowns in the mole balances. While the rate expression parameters are being estimated, the response function is called from within the paremeter estimation software. That software <em>may</em> provide a mechanism for additionally passing the experimental responses to the response function as arguments. If it doesn’t, they could be read from a file within the response function. Just as the exact calling and return variables depend upon the parameter estimation software, so does the mechanism for making the experimental responses available within the response function.</p>
<p>The response function is then provided to parameter estimation software along with the adjusted experimental inputs, the experimental responses, and a guess for the parameters. The parameter estimation software returns the estimated values of the kinetics parameters, some measure of the uncertainty in the estimates, and the coefficient of determination, <span class="math inline">\(R^2\)</span>. The estimated parameters can then be used to calculate the model-predicted responses for the experiments. From these, a parity plot and residuals plots can be created as described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a>. If the rate expression is accurate, the following criteria will be satisfied.</p>
<ul>
<li>The coefficient of determination, <span class="math inline">\(R^2\)</span>, will be close to 1.</li>
<li>The uncertainty in each parameter estimate will be small compared to the estimate.</li>
<li>The points in the parity plot will all be close to a diagonal line (<span class="math inline">\(y_{\text{expt}} = y_{\text{model}}\)</span>).</li>
<li>In each residuals plot, the points will scatter randomly about zero (the horizontal axis), and no systematic deviations will be apparent.</li>
</ul>
</section>
<section id="analysis-using-a-linearized-model" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="analysis-using-a-linearized-model"><span class="header-section-number">11.4.2</span> Analysis Using a Linearized Model</h3>
<p>When only one reaction is taking place, as is the case in <em>Reaction Engineering Basics</em> kinetics data analysis problems, the reactor can be modeled using only one mole balance on a reactant or product in the reaction. When this is done, the apparent extent of reaction is used to relate the amounts of all other reagents to the reagent for which the mole balance is written. If that one mole balance can be rearranged into a linear form, the model can be fit to the experimental data using linear least squares. This was described and illustrated in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a> and <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> and won’t be repeated or illustrated in this chapter.</p>
<p>One point to note, however, is that with CSTR kinetics data, the mole balance is already an ATE. It isn’t necessary to integrate an IVODE before linearizing it. Indeed, for a simple rate expression with only one rate coefficient of the form shown in <a href="#eq-simple_rate_expr">Equation&nbsp;<span>11.4</span></a>, the mole balance, <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a>, will already have the linear form shown in <a href="#eq-linear_no_intercept">Equation&nbsp;<span>11.5</span></a> if <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> are defined as shown in <a href="#eq-def_y">Equation&nbsp;<span>11.6</span></a> and <a href="#eq-def_x">Equation&nbsp;<span>11.7</span></a>.</p>
<p><span id="eq-simple_rate_expr"><span class="math display">\[
r = kf\left(\dot{n}_i,P\right)
\tag{11.4}\]</span></span></p>
<p><span id="eq-linear_no_intercept"><span class="math display">\[
y=kx
\tag{11.5}\]</span></span></p>
<p><span id="eq-def_y"><span class="math display">\[
y = \dot{n}_i - \dot{n}_{i,in}
\tag{11.6}\]</span></span></p>
<p><span id="eq-def_x"><span class="math display">\[
x=\nu_i V f\left(\dot{n}_i,P\right)
\tag{11.7}\]</span></span></p>
</section>
</section>
<section id="examples" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="examples"><span class="header-section-number">11.5</span> Examples</h2>
<p>The start of the Examples section of <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> noted that before a reaction engineer can solve a problem, they must identify what type of problem it is. The following callout was provided with the suggestion that the reader mentally insert it at the start of every example in that chapter <em>and</em> in <a href="#sec-4_cstr_data_analysis"><span>Chapter&nbsp;11</span></a> and <a href="section_4_pfr_data_analysis.html"><span>Chapter&nbsp;10</span></a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking after Reading each Problem Statement in this Chapter
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This assignment involves “kinetics data analysis.” I realize that because the problem statement includes 3 distinguishing characteristics of kinetics data analysis assignments.</p>
<ul>
<li>The problem statement describes reactor experiments involving a known reaction.</li>
<li>The data resulting from performing those experiments are provided.</li>
<li>The assignment is to generate a rate expression or estimate the parameters in a proposed rate expression and then assess its accuracy using those data.</li>
</ul>
<p>I know that the preferred way of performing experiments results in sub-sets (or blocks) of the data that each contain a number of experiments all performed at the same temperature. I further know that when this is true, each same-temperature block is first analyzed separately to estimate values of the kinetics parameters at that block’s temperature.</p>
<p>Thus, to begin this assignment I need to do the following things.</p>
<ul>
<li>Separate the experimental data into same temperature blocks.</li>
<li>Identify (a) the reactor inputs that were varied from experiment, (b) the reactor response that was measured in each experiment, and (c) the rate expression parameters that need to be estimated for each block.</li>
<li>Develop a mathematical model that relates the adjusted inputs to the measured response.</li>
<li>Estimate the rate expressions parameters for each block and assess the accuracy of the resulting rate expression for that block.</li>
</ul>
</div>
</div>
</div>
<p>It should also be noted that each of the examples in this chapter present only a single constant-temperature block of data and ask that those data be used to assess the accuracy of a rate expression with respect to the concentration dependence of a rate expression. This is intentional. Two of the four examples in <a href="section_4_bstr_data_analysis.html"><span>Chapter&nbsp;9</span></a> illustrated the second phase of the analysis where the Arrhenius expression was fit to the rate coefficients found by fitting the reactor model to the experimental data. By now, the reader should know how to fit the Arrhenius expression to <span class="math inline">\(k\)</span> <em>vs</em>. <span class="math inline">\(T\)</span> data. The examples here focus exclusively on fitting a CSTR reactor model to CSTR kinetics data with the assumption that the reader already knows how to process the resulting rate coefficients and estimate their pre-exponential factor and activation energy.</p>
<section id="sec-example_11_1" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="sec-example_11_1"><span class="header-section-number">11.5.1</span> Analysis of Data for Liquid-Phase Reaction</h3>
<p>The liquid-phase reaction between reactants A and B, reaction (1), was studied in a 100 cm<sup>3</sup> laboratory CSTR. The reactor operated at steady state, and kinetics data were generated in blocks where the temperature was the same in all of the experiments in any one block. In each block the volumetric flow rate and the inlet concentrations of each of the reagents were adjusted, and the outlet concentration of reagent Y was measured. The data from a block of experiments where the temperature was 35 °C are presented below. Use those data to assess the accuracy with which the rate expression shown in equation (2) describes the composition dependence of the rate of reaction (1).</p>
<p><span class="math display">\[
A + B \rightarrow Y + Z \tag{1}
\]</span></p>
<p><span class="math display">\[
r = kC_AC_B \tag{2}
\]</span></p>
<p>The first few data points are shown in <a href="#tbl-example_11_1_data">Table&nbsp;<span>11.1</span></a>. The full data set is available in the file <a href="./Data/reb_11_1_data.csv">reb_11_1_data.csv</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11_1_data" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.1: First 8 experimental data points.</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\dot{V}\)</span> (cm<sup>3</sup> min<sup>-1</sup>)</th>
<th style="text-align: center;">C<sub>A,in</sub> (M)</th>
<th style="text-align: center;">C<sub>B,in</sub> (M)</th>
<th style="text-align: center;">C<sub>Y,in</sub> (M)</th>
<th style="text-align: center;">C<sub>Z,in</sub> (M)</th>
<th style="text-align: center;">C<sub>Y,out</sub> (M)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0.85</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">0.75</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">5.0</td>
<td style="text-align: center;">0.63</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.39</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">1.24</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">5.0</td>
<td style="text-align: center;">1.13</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is a kinetics data analysis problem. It describes a CSTR and experiments performed using it, provides the data from the experiments and asks me to assess a rate expression proposed for the reaction taking place during the experiments. To solve it I will need to create a response function, and that function will be passed the adjusted inputs and rate expression parameter and return predicted values of the response. To begin, I’ll summarize the information provided in the problem statement, identifying those different groups of variables.</p>
</div>
</div>
</div>
<p><strong>Reactor</strong>: CSTR</p>
<p><strong>Given</strong>: <span class="math inline">\(V=100 \text{ cm}^3\)</span> and <span class="math inline">\(T=\left( 35 + 273.15 \right) \text{ K}\)</span>.</p>
<p><strong>Adjusted Inputs</strong>: <span class="math inline">\(\underline{\dot{V}}\)</span>, <span class="math inline">\(\underline{C}_{A,in}\)</span>, <span class="math inline">\(\underline{C}_{B,in}\)</span>, <span class="math inline">\(\underline{C}_{Y,in}\)</span>, and <span class="math inline">\(\underline{C}_{Z,in}\)</span></p>
<p><strong>Experimental Response</strong>: <span class="math inline">\(\underline{C}_{Y,out}\)</span></p>
<p><strong>Rate Expression Parameter</strong>: <span class="math inline">\(k\)</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I know that in kinetics data analysis problems I need to create a response function, and within that function, I need to solve the reactor model equations. Since the steady-state temperature of the reacting fluid is known, I can model the reactor using only mole balances. There are four reagents, A, B, Y, and Z, so I’ll write the mole balance, <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a>, for each of them.</p>
<p><span class="math display">\[
0 = \dot{n}_{i,in} - \dot{n}_i + \nu_i r V
\]</span></p>
<p>The stoichiometric coefficients of A and B are -1 and the stoichiometric coefficients of Y and Z are +1, leading to equations (3) through (6).</p>
</div>
</div>
</div>
<p><strong>Reactor Model</strong></p>
<p>Mole balances on the four reagents are shown in equations (3) through (6).</p>
<p><span class="math display">\[
0 = \dot{n}_{A,in} - \dot{n}_A - rV \tag{3}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{B,in} - \dot{n}_B - rV \tag{4}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{Y,in} - \dot{n}_Y + rV \tag{5}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{Z,in} - \dot{n}_Z + rV \tag{6}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The reactor design equations are ATEs. Within the response function I will need to solve them numerically for the four outlet molar flow rates, <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. In order to solve those ATEs, I need to go through them and express every quantity that is in them, or that gets substituted into them, in terms of known constants and those 4 unknowns.</p>
<p>The adjusted inputs and the rate expression parameter will be available within the response function. Looking at the design equations, the volume is a known constant. The inlet molar flow rates of each reagent also appear in the design equations, so I’ll need ancillary equations for calculating them from known constants and the four unknowns. When the rate expression is substituted into the design equations it will introduce the concentrations of A and B, so expressions for them will be needed, too. In all cases, I will be able to use the defining equation for concentration in an open system, <a href="section_1_intro_and_defs.html#eq-concentration_open">Equation&nbsp;<span>1.15</span></a>.</p>
<p><span class="math display">\[
C_i = \frac{\dot n_i}{\dot V}
\]</span></p>
</div>
</div>
</div>
<p><strong>Ancillary Equations</strong></p>
<p><span class="math display">\[
\dot{n}_{A,in} = C_{A,in}\dot{V} \tag{7}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{B,in} = C_{B,in}\dot{V} \tag{8}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{Y,in} = C_{Y,in}\dot{V} \tag{9}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{Z,in} = C_{Z,in}\dot{V} \tag{10}
\]</span></p>
<p><span class="math display">\[
C_A = \frac{\dot{n}_A}{\dot{V}} \tag{11}
\]</span></p>
<p><span class="math display">\[
C_B = \frac{\dot{n}_B}{\dot{V}} \tag{12}
\]</span></p>
<p><strong>Response Calculation</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At this point equations (3) through (6) can be solved for the outlet molar flow rates, <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. Within the response function I need to use those results to calculate the model-predicted response. In this problem the response is the outlet concentration of Y, so again <a href="section_1_intro_and_defs.html#eq-concentration_open">Equation&nbsp;<span>1.15</span></a> can be used.</p>
</div>
</div>
</div>
<p><span class="math display">\[
C_Y = \frac{\dot{n}_Y}{\dot{V}} \tag{13}
\]</span></p>
<p><strong>Response Function</strong></p>
<p>The response function is created with the following structure.</p>
<ul>
<li>The adjusted inputs, <span class="math inline">\(\underline{\dot{V}}\)</span>, <span class="math inline">\(\underline{C}_{A,in}\)</span>, <span class="math inline">\(\underline{C}_{B,in}\)</span>, <span class="math inline">\(\underline{C}_{Y,in}\)</span>, and <span class="math inline">\(\underline{C}_{Z,in}\)</span>, and the rate expression parameter, <span class="math inline">\(k\)</span>, are passed to it as arguments.</li>
<li>Variables are defined and assigned the values of all known and given quantities, <span class="math inline">\(V=100 \text{ cm}^3\)</span> and <span class="math inline">\(T=\left( 35 + 273.15 \right) \text{ K}\)</span>.</li>
<li>A function is defined that evaluates the reactor equation residuals (the right-hand sides of equations (3) through (6)), given values of the unknowns, <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. It
<ul>
<li>Calculates <span class="math inline">\(\dot{n}_{A,in}\)</span>, <span class="math inline">\(\dot{n}_{B,in}\)</span>, <span class="math inline">\(\dot{n}_{Y,in}\)</span>, and <span class="math inline">\(\dot{n}_{Z,in}\)</span> using equations (7) through (10).</li>
<li>Calculates <span class="math inline">\(C_A\)</span> and <span class="math inline">\(C_B\)</span> using equations (11) and (12).</li>
<li>Calculated <span class="math inline">\(r\)</span> using equation (2).</li>
<li>Evaluates and returns the residuals, equations (3) through (6).</li>
</ul></li>
<li>For each experiment, the response function
<ul>
<li>Solves the reactor design equations numerically to find <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>.</li>
<li>Calculates <span class="math inline">\(C_Y\)</span> using equation (13).</li>
</ul></li>
<li>The predicted values <span class="math inline">\(C_Y\)</span> for all of the experiments are returned.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Having created the response function, I can now use it to estimate the rate expression parameter, <span class="math inline">\(k\)</span>, at the experimental temperature, 35 °C. To do so I will use parameter estimation software of my choosing. I will write a simple program that passes the adjusted inputs, the measured responses, and a guess for the rate expression parameter to that parameter estimation software. It will return the best estimate for <span class="math inline">\(k\)</span>, some measure of the uncertainty in <span class="math inline">\(k\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</p>
<p>Using the resulting value of <span class="math inline">\(k\)</span>, I can calculate the model-predicted responses for all of the experiments using the response function. Then, knowing the model-predicted responses I can calculate the residual (difference between the measured response and the model-predicted response) for each eperiment. Finally, as described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a>, I can create a parity plot and residuals plots.</p>
</div>
</div>
</div>
<p><strong>Calculations</strong></p>
<ol type="1">
<li>Pass the response function, the adjusted inputs, the experimental responses, and a guess for the rate expression parameter to parameter estimation software to find <span class="math inline">\(k\)</span>, the uncertainty in <span class="math inline">\(k\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</li>
<li>Use the resulting value of <span class="math inline">\(k\)</span> to calculate the model-predicted response, <span class="math inline">\(C_{y,\text{model}}\)</span>, for every experiment.</li>
<li>Create a parity plot (<span class="math inline">\(C_{y,\text{model}}\)</span> <em>vs</em>. <span class="math inline">\(C_{y,\text{expt}}\)</span>) and parity plots (<span class="math inline">\(C_{y,\text{model}} - C_{y,\text{expt}}\)</span> <em>vs</em>. <span class="math inline">\(\dot{V}_{in}\)</span>, <em>vs</em>. <span class="math inline">\(C_{A,in}\)</span>, <em>vs</em>. <span class="math inline">\(C_{B,in}\)</span>, <em>vs</em>. <span class="math inline">\(C_{Y,in}\)</span>, and <em>vs</em>. <span class="math inline">\(C_{Z,in}\)</span>,)</li>
</ol>
<p><strong>Results</strong></p>
<p>To estimate <span class="math inline">\(k\)</span>, the response function described above was passed to parameter estimation software along with the adjusted experimental inputs, the experimental responses and a guess for <span class="math inline">\(k\)</span>. The results returned by that software are shown in <a href="#tbl-example_11-1_results">Table&nbsp;<span>11.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11-1_results" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.2: Parameter estimation results</caption>
<tbody>
<tr class="odd">
<td style="text-align: center;">k</td>
<td style="text-align: center;">796 L mol<sup>-1</sup> min<sup>-1</sup>, 95% CI [743, 854]</td>
</tr>
<tr class="even">
<td style="text-align: center;">R<sup>2</sup></td>
<td style="text-align: center;">0.988</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The estimated rate coefficient was used to calculate the model-predicted response for each experiment, and that was used to calculate the residual for each experiment. The results were then used to generate the parity plot and residuals plots shown in <a href="#fig-example_11_1_plots">Figure&nbsp;<span>11.1</span></a>.</p>
<div id="fig-example_11_1_plots" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_parity.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_VFR_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_CA_residuals.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_CB_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_CY_residuals.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_1_CZ_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.1: Parity and Residuals Plots.</figcaption><p></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 95% confidence interval for <span class="math inline">\(k\)</span>, 743 to 854 L mol<sup>-1</sup> min<sup>-1</sup>, is approximately plus or minus 7% of its estimated value, 796 L mol<sup>-1</sup> min<sup>-1</sup>. There is some scatter apparent in the parity plot, and the coefficient of determination is 0.988. These factors suggest that the rate expression is reasonably accurate. The residuals plots for <span class="math inline">\(\dot{V}\)</span> and <span class="math inline">\(C_Y\)</span> show random deviations of the residuals about zero, too. However, in the residuals plots for <span class="math inline">\(C_A\)</span> and <span class="math inline">\(C_B\)</span> the residuals at low concentration do not scatter equally about zero. The residuals for <span class="math inline">\(C_Z\)</span> show a definite trend, decreasing steadily as <span class="math inline">\(C_Z\)</span> increases. This suggests that the reaction rate may have some functional dependence on the concentration of Z that is not captured in the rate expression.</p>
</div>
</div>
</div>
<p><strong>Assessment</strong></p>
<p>The rate expression is reasonably accurate, but there are indications that the rate expression may not fully capture the dependence of the rate on the concentration of reagent Z. Rate expressions that include a functional dependence on the concentration of Z should be postulated and assessed to determine whether they can represent the experimental results more accurately.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>In this example, the accuracy of the rate expression is reasonable, but the indication that the rate depends on the concentration of Z is a concern. In a real-world study, there would be blocks of data at other temperatures. If the same trends were observed for each data block, the recommendation to try different rate expressions that include functional dependence on Z would be supported. If none of the other temperature blocks showed these trends, it might be recommended that the rate expression was reasonably acceptable.</p>
</div>
</div>
</div>
</section>
<section id="sec-example_11_2" class="level3" data-number="11.5.2">
<h3 data-number="11.5.2" class="anchored" data-anchor-id="sec-example_11_2"><span class="header-section-number">11.5.2</span> Analysis of Data for a Gas-Phase Reaction with Change of Total Moles</h3>
<p>Preliminary experiments have indicated that gas-phase reaction (1) is irreversible and that the rate is not affected by the concentration of the product Z. To generate kinetics data, experiments were performed in blocks where the temperature of every experiment in the block was the same. An ideal CSTR operating at 3 atm was used for all experiments. The feed in every experiment contained only reagents A and B. The space time and the mole fraction of A were varied from experiment to experiment, and the outlet concentration of Z was measured. The block of experiments where the temperature was equal to 450 °C is presented below. Use those data to assess the accuracy of the rate expression shown in equation (2) where the power-law reaction orders, <span class="math inline">\(\alpha_A\)</span> and <span class="math inline">\(\alpha_B\)</span>, must be estimated along with the rate coefficient, <span class="math inline">\(k\)</span>.</p>
<p><span class="math display">\[
A + B \rightarrow Z \tag{1}
\]</span></p>
<p><span class="math display">\[
r = kP_A^{\alpha_A} P_B^{\alpha_B} \tag{2}
\]</span></p>
<p>The first few data points are shown in <a href="#tbl-example_11_2_data">Table&nbsp;<span>11.3</span></a>. The full data set is available in the file <a href="./Data/reb_11_2_data.csv">reb_11_2_data.csv</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11_2_data" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.3: First 6 experimental data points.</caption>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\tau\)</span> (s)</th>
<th style="text-align: center;">y<sub>A,in</sub></th>
<th style="text-align: center;">C<sub>Z,out</sub> (mmol L<sup>-1</sup>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.56</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.94</td>
</tr>
<tr class="odd">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">1.70</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">2.17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">2.87</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">3.33</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This problem describes reactor experiments, provides the data from the experiments, and asks me to assess the accuracy of a rate expression, so it is a kinetics data analysis problem. Knowing that I will be creating a response function, I’ll start by listing the reactor type, constants given in the problem statement, the adjusted experimental inputs, the experimental response, and the rate expression parameters I need to estimate.</p>
</div>
</div>
</div>
<p><strong>Reactor</strong>: CSTR</p>
<p><strong>Given</strong>: <span class="math inline">\(P = 3 \text{ atm}\)</span> and <span class="math inline">\(T = 450 + 273.15 \text{ K}\)</span>.</p>
<p><strong>Adjusted Inputs</strong>: <span class="math inline">\(\underline{\tau}\)</span> and <span class="math inline">\(\underline{y}_{A,in}\)</span>.</p>
<p><strong>Experimental Response</strong>: <span class="math inline">\(\underline{C}_Z\)</span>.</p>
<p><strong>Rate Expression Parameters</strong>: <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I need to generate a response function that predicts the responses using the rate expression. To start, I need a model for the reactor. Referring back to <a href="section_3_design_equations.html"><span>Chapter&nbsp;6</span></a>, I know that when the reactor operates at a known temperature, the mole balances can be solved independently from the other design equations, so all I need here is a set of mole balances for this reactor. The mole balance design equation for a steady-state CSTR with only one reaction taking place is given in <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a>.</p>
<p><span class="math display">\[
0 = \dot{n}_{i,in} - \dot{n}_i + \nu_i r V
\]</span></p>
<p>The stoichiometric coefficients of A, B, and Z are -1, -1 and 1, respectively. The problem also states that the feed contained only reagents A and B, so the inlet molar flow rate of reagent Z is equal to zero. Substitution of those values leads to equations (3) through (5).</p>
</div>
</div>
</div>
<p><strong>Reactor Model</strong></p>
<p>Mole balances on A, B, and Z are shown in equations (3) through (5).</p>
<p><span class="math display">\[
0 = \dot{n}_{A,in} - \dot{n}_A - rV \tag{3}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{B,in} - \dot{n}_B - rV \tag{4}
\]</span></p>
<p><span class="math display">\[
0 = \cancelto{0}{\dot{n}_{Z,in}} - \dot{n}_Z + rV \tag{5}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Within the response function I will need to numerically solve equations (3) through (5) for the outlet molar flow rates of A, B, and Z. To do that, I must provide equations for calculating every other quantity in the equations from those unknowns and known constants. So I’ll go through each of the mole balances, and any equations that will be substituted into them, and write equations for the quantities other than the unknowns and known constants.</p>
<p>At first, looking at the mole balances, it appears that I’m not given sufficient information, but upon careful reading of the problem statement I see that all of the quantities provided are <em>intensive</em> quantities. When that is true, I can choose the value for one <em>extensive</em> quantity and use it as the basis for my calculations. I’m going to choose a reactor volume of 1 L as the basis for my calculations.</p>
<p>The mole balance design equations also contain the inlet molar flow rates of A and B. The problem statement does not provide any flow rates, but having chosen a volume as a basis, I can use the definition of space time, <a href="section_3_design_equations.html#eq-space_time">Equation&nbsp;<span>6.1</span></a>, (which is one of the adjusted inputs) to calculate the inlet volumetric flow rate. Then I can use the ideal gas law to calculate the total inlet molar flow rate and the inlet mole fractions of A and B to calculate their inlet molar flow rates.</p>
<p>When I substitute the rate expression into the mole balances, that will introduce the partial pressures of A and B. Equations for the partial pressures can be written using the unknowns and the defining equation for partial pressure. The rate coefficient and the reaction orders will be passed to the response function as arguments, so I don’t need equations for them.</p>
</div>
</div>
</div>
<p><strong>Ancillary Equations</strong></p>
<p><span class="math display">\[
V = 1 \text{ L }\left( \text{Basis} \right) \tag{6}
\]</span></p>
<p><span class="math display">\[
\dot{V}_{in} = V/\tau \tag{7}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{in,\text{total}} = \frac{P\dot{V}_{in}}{RT} \tag{8}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{A,in} = y_{A,in}\dot{n}_{in,\text{total}} \tag{9}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{B,in} = \left(1 - y_{A,in}\right)\dot{n}_{in,\text{total}} \tag{10}
\]</span></p>
<p><span class="math display">\[
P_A = y_A P = \frac{\dot{n}_A}{\dot{n}_A + \dot{n}_B + \dot{n}_Z}P \tag{11}
\]</span></p>
<p><span class="math display">\[
P_B = y_B P = \frac{\dot{n}_B}{\dot{n}_A + \dot{n}_B + \dot{n}_Z}P \tag{12}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At this point the mole balances can be solved numerically for the outlet molar flow rates of A, B, and Z. This will be done within the response function, and then the results must be used to calculate the response predicted by the model. In this problem the response is the concentration of Z in the stream leaving the reactor. That can be calculated using the ideal gas law, <a href="#eq-conc_cstr_kinetics">Equation&nbsp;<span>11.2</span></a>.</p>
</div>
</div>
</div>
<p><strong>Response Calculation</strong></p>
<p><span class="math display">\[
C_Z = \frac{\dot{n}_Z}{\dot{V}} = \frac{\dot{n}_ZP}{\dot{n}_{\text{total}}RT} = \frac{\dot{n}_ZP}{\left(\dot{n}_A + \dot{n}_B + \dot{n}_Z\right)RT} \tag{13}
\]</span></p>
<p><strong>Response Function</strong></p>
<p>The response function is created with the following structure.</p>
<ul>
<li>The adjusted inputs, <span class="math inline">\(\underline{\tau}\)</span> and <span class="math inline">\(\underline{y}_{A,in}\)</span>, and the rate expression parameters, <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, are passed to it as arguments.</li>
<li>Variables are defined and assigned the values of all known and given quantities, <span class="math inline">\(P = 3 \text{ atm}\)</span> and <span class="math inline">\(T = 450 + 273.15 \text{ K}\)</span>, and the basis, equation (6).</li>
<li>A function is defined that evaluates the reactor equation residuals (the right-hand sides of equations (3) through (5)), given values of the unknowns, <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. It
<ul>
<li>Calculates the inlet volumetric and molar flow rates, equations (7) and (8).</li>
<li>Calculates the inlet molar flow rates of A and B, equations (9) and (10).</li>
<li>Calculates the partial pressures of A and B, equations (11) and (12).</li>
<li>Calculates <span class="math inline">\(r\)</span> using equation (2).</li>
<li>Evaluates and returns the residuals, equations (3) through (5).</li>
</ul></li>
<li>For each experiment, the response function
<ul>
<li>Solves the reactor design equations numerically to find <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_B\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>.</li>
<li>Calculates <span class="math inline">\(C_Z\)</span> using equation (13).</li>
</ul></li>
<li>The predicted values of <span class="math inline">\(C_Z\)</span> for all of the experiments are returned.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Having created the response function, I can now use it to estimate the rate expression parameters, <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, at the experimental temperature, 450 °C. To do so I will use parameter estimation software of my choosing. I will write a simple program that passes the adjusted inputs, the measured responses, and a guess for the rate expression parameters to that parameter estimation software. It will return the best estimate for <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, some measure of the uncertainty in <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</p>
<p>Using the resulting values of <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, I can calculate the model-predicted responses for all of the experiments using the response function. Then, knowing the model-predicted responses I can calculate the residual (difference between the measured response and the model-predicted response) for each eperiment. Finally, as described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a>, I can create a parity plot and residuals plots.</p>
</div>
</div>
</div>
<p><strong>Calculations</strong></p>
<ol type="1">
<li>Pass the response function, the adjusted inputs, the experimental responses, and a guess for the rate expression parameters to parameter estimation software to find <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, the uncertainty in <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</li>
<li>Use the resulting values of <span class="math inline">\(k\)</span>, <span class="math inline">\(\alpha_A\)</span>, and <span class="math inline">\(\alpha_B\)</span> to calculate the model-predicted response, <span class="math inline">\(C_{Z,\text{model}}\)</span>, for every experiment.</li>
<li>Create a parity plot (<span class="math inline">\(C_{Z,\text{model}}\)</span> <em>vs</em>. <span class="math inline">\(C_{Z,\text{expt}}\)</span>) and parity plots (<span class="math inline">\(C_{Z,\text{model}} - C_{Z,\text{expt}}\)</span> <em>vs</em>. <span class="math inline">\(\underline{\tau}\)</span> and <em>vs</em>. <span class="math inline">\(\underline{y}_{A,in}\)</span>.</li>
</ol>
<p><strong>Results</strong></p>
<p>The reactor model described above was fit to the experimental data presented in <a href="#tbl-example_11_2_data">Table&nbsp;<span>11.3</span></a> using parameter estimation software. The results are presented in <a href="#tbl-example_11_2_parameters">Table&nbsp;<span>11.4</span></a>. A parity plot is shown in <a href="#fig-example_11_2_parity">Figure&nbsp;<span>11.2</span></a> and residuals plots are shown in <a href="#fig-example_11_2_residuals_plots">Figure&nbsp;<span>11.3</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11_2_parameters" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.4: Parameter estimation results</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">k</td>
<td style="text-align: center;">4.51 x 10<sup>-5</sup> mol L<sup>-1</sup> s<sup>-1</sup> atm<sup>1.903</sup>, 95% CI [4.36 x 10<sup>-5</sup>, 4.67 x 10<sup>-5</sup>]</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\alpha_A\)</span></td>
<td style="text-align: center;">1.35 , 95% CI [1.27, 1.42]</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\alpha_B\)</span></td>
<td style="text-align: center;">0.558 , 95% CI [0.514, 0.601]</td>
</tr>
<tr class="even">
<td style="text-align: center;">R<sup>2</sup></td>
<td style="text-align: center;">0.995</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="fig-example_11_2_parity" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./Graphics/reb_11_2_parity.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;11.2: Parity plot.</figcaption>
</figure>
</div>
<div id="fig-example_11_2_residuals_plots" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_2_tau_residuals.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_2_yA_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.3: Parity and Residuals Plots.</figcaption><p></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The deviations of the data points from the line in the parity plot are small, the deviations of the residuals about zero are random with no apparent trends, the coefficient of determination is close to 1, and the upper and lower limits of the 95% confidence intervals for all three parameters are close to the estimated parameter value. All of these are indicators of an accurate model.</p>
</div>
</div>
</div>
<p><strong>Assessment</strong></p>
<p>When used with the rate expression parameters shown in <a href="#tbl-example_11_2_parameters">Table&nbsp;<span>11.4</span></a>, the accuracy of the proposed rate expression in describing the concentration dependence of the rate at 450 °C is acceptable.</p>
</section>
<section id="sec-example_11_3" class="level3" data-number="11.5.3">
<h3 data-number="11.5.3" class="anchored" data-anchor-id="sec-example_11_3"><span class="header-section-number">11.5.3</span> Analysis of Data for a Reversible Reaction</h3>
<p>The liquid-phase disproportionation of reagent A, reaction (1), is reversible. Kinetics data were generated in a 3 gal CSTR by varying the volumetric flow rate and the feed concentrations of reagents A, Y, and Z from experiment to experiment. In each experiment the outlet concentration of reagent A was measured. One of the constant temperature blocks of data is presented below; use it to assess the accuracy of the rate expression shown in equation (2). Note that thermodynamic data to calculate the equilibrium constant for reaction (1) are not available, so both the forward and reverse rate coefficients in the rate expression must be estimated from the experimental data.</p>
<p><span class="math display">\[
A \leftrightarrows Y + Z \tag{1}
\]</span></p>
<p><span class="math display">\[
r = k_fC_A^2 - k_rC_YC_Z \tag{2}
\]</span></p>
<p>The first few data points are shown in <a href="#tbl-example_11_3_data">Table&nbsp;<span>11.5</span></a>. The full data set is available in the file <a href="./Data/reb_11_3_data.csv">reb_11_3_data.csv</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11_3_data" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.5: First 6 experimental data points.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\dot{V}\)</span> (gal min<sup>-1</sup>)</th>
<th style="text-align: center;">C<sub>A,in</sub> (lbmol gal<sup>-1</sup>)</th>
<th style="text-align: center;">C<sub>Y,in</sub> (lbmol gal<sup>-1</sup>)</th>
<th style="text-align: center;">C<sub>Z,in</sub> (lbmol gal<sup>-1</sup>)</th>
<th style="text-align: center;">C<sub>A,out</sub> (lbmol gal<sup>-1</sup>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.0068</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.0067</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.0071</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.0074</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">0.0071</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.0082</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is a kinetics data analysis assignment, and to solve it I will need to create a response function. I will begin by summarizing the information provided in the problem statement.</p>
</div>
</div>
</div>
<p><strong>Reactor</strong>: CSTR</p>
<p><strong>Given</strong>: <span class="math inline">\(V = 3 \text{ gal}\)</span>.</p>
<p><strong>Adjusted Inputs</strong>: <span class="math inline">\(\underline{\dot{V}}\)</span>, <span class="math inline">\(\underline{C}_{A,in}\)</span>, <span class="math inline">\(\underline{C}_{Y,in}\)</span>, and <span class="math inline">\(\underline{C}_{Z,in}\)</span>.</p>
<p><strong>Experimental Response</strong>: <span class="math inline">\(\underline{C}_{A,out}\)</span>.</p>
<p><strong>Rate Expression Parameters</strong>: <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I need to create a response function that solves the reactor design equations and predicts the response for each data point. Since the CSTR operated at a known temperature, I only need mole balances to model it. There are 3 reagents in this system, so I’ll write <a href="#eq-cstr_mole_bal_one_reaction">Equation&nbsp;<span>11.1</span></a> for each of them.</p>
<p><span class="math display">\[
0 = \dot{n}_{i,in} - \dot{n}_i + \nu_i r V
\]</span></p>
<p>The stoichiometric coefficients of A, Y, and Z, are -1, 1, and 1, respectively, leading to equations (3) through (5).</p>
</div>
</div>
</div>
<p><strong>Reactor Model</strong></p>
<p>Mole balances on A, Y, and Z are shown in equations (3) through (5).</p>
<p><span class="math display">\[
0 = \dot{n}_{A,in} - \dot{n}_A - rV \tag{3}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{Y,in} - \dot{n}_Y + rV \tag{4}
\]</span></p>
<p><span class="math display">\[
0 = \dot{n}_{Z,in} - \dot{n}_Z + rV \tag{5}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Within the response function I need to solve equations (3) through (5) for <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. The adjusted inputs and the rate expression parameters will be provided to the response function. To solve the reactor design equations, I need to express every other quantity appearing in or substituted into equations (3) through (5) in terms of <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, <span class="math inline">\(\dot{n}_Z\)</span> and known constants. Looking at equations (3) through (5) I can see that I will need expressions for the inlet molar flow rates, <span class="math inline">\(\dot{n}_{A,in}\)</span>, <span class="math inline">\(\dot{n}_{Y,in}\)</span>, and <span class="math inline">\(\dot{n}_{Z,in}\)</span>. I know the volumetric flow rate and the inlet concentrations of the reagents, so those expressions are straightforward.</p>
<p>When the rate expression is substituted into the mole balances it introduces the concentrations of the reagents. This is a steady-state, liquid phase system, so the volumetric flow rate is constant. Knowing that, <a href="section_1_intro_and_defs.html#eq-concentration_open">Equation&nbsp;<span>1.15</span></a> can be used to express the concentrations in terms of the unknowns in terms of their molar flow rates.</p>
<p><span class="math display">\[
C_i = \frac{\dot n_i}{\dot V}
\]</span></p>
</div>
</div>
</div>
<p><strong>Ancillary Equations</strong></p>
<p><span class="math display">\[
\dot{n}_{A,in} = C_{A,in}\dot{V} \tag{6}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{Y,in} = C_{Y,in}\dot{V} \tag{7}
\]</span></p>
<p><span class="math display">\[
\dot{n}_{Z,in} = C_{Z,in}\dot{V} \tag{8}
\]</span></p>
<p><span class="math display">\[
C_A = \frac{\dot{n}_A}{\dot{V}} \tag{9}
\]</span></p>
<p><span class="math display">\[
C_Y = \frac{\dot{n}_Y}{\dot{V}} \tag{10}
\]</span></p>
<p><span class="math display">\[
C_Z = \frac{\dot{n}_Z}{\dot{V}} \tag{11}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Once the reactor design equations have been solved, the resulting values of <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span> must be used to predict the experimental response. In this study, the response was the outlet concentration of A, and that can be calculated using equation (9).</p>
</div>
</div>
</div>
<p><strong>Response Function</strong></p>
<p>The response function is created with the following structure.</p>
<ul>
<li>The adjusted inputs, <span class="math inline">\(\underline{\dot{V}}\)</span>, <span class="math inline">\(\underline{C}_{A,in}\)</span>, <span class="math inline">\(\underline{C}_{Y,in}\)</span>, and <span class="math inline">\(\underline{C}_{Z,in}\)</span>, and the rate expression parameters, <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, are passed to it as arguments.</li>
<li>A variable is defined and assigned the value of the known and given quantity, <span class="math inline">\(V = 3 \text{ gal}\)</span>.</li>
<li>A function is defined that evaluates the reactor equation residuals (the right-hand sides of equations (3) through (5)), given values of the unknowns, <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>. It
<ul>
<li>Calculates the inlet molar flow rates of A, Y, and Z, equations (6), (7), and (8).</li>
<li>Calculates the concentrations of A, Y, and Z, equations (9), (10), and (11).</li>
<li>Calculates <span class="math inline">\(r\)</span> using equation (2).</li>
<li>Evaluates and returns the residuals, equations (3) through (5).</li>
</ul></li>
<li>For each experiment, the response function
<ul>
<li>Solves the reactor design equations numerically to find <span class="math inline">\(\dot{n}_A\)</span>, <span class="math inline">\(\dot{n}_Y\)</span>, and <span class="math inline">\(\dot{n}_Z\)</span>.</li>
<li>Calculates <span class="math inline">\(C_A\)</span> using equation (9).</li>
</ul></li>
<li>The predicted values of <span class="math inline">\(C_A\)</span> for all of the experiments are returned.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Having created the response function, I can now use it to estimate the rate expression parameters, <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, at the experimental temperature. To do so I will use parameter estimation software of my choosing. I will write a simple program that passes the adjusted inputs, the measured responses, and a guess for the rate expression parameters to that parameter estimation software. It will return the best estimates for <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, some measure of the uncertainty in <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</p>
<p>Using the resulting values of <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, I can calculate the model-predicted responses for all of the experiments using the response function. Then, knowing the model-predicted responses I can calculate the residual (difference between the measured response and the model-predicted response) for each eperiment. Finally, as described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a>, I can create a parity plot and residuals plots.</p>
</div>
</div>
</div>
<p><strong>Calculations</strong></p>
<ol type="1">
<li>Pass the response function, the adjusted inputs, the experimental responses, and a guess for the rate expression parameters to parameter estimation software to find <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, the uncertainty in <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span>, and the coefficient of determination, <span class="math inline">\(R^2\)</span>.</li>
<li>Use the resulting values of <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span> to calculate the model-predicted response, <span class="math inline">\(C_{A,\text{model}}\)</span>, for every experiment.</li>
<li>Create a parity plot (<span class="math inline">\(C_{A,\text{model}}\)</span> <em>vs</em>. <span class="math inline">\(C_{ZA,\text{expt}}\)</span>) and residuals plots (<span class="math inline">\(C_{A,\text{model}} - C_{A,\text{expt}}\)</span> <em>vs</em>. <span class="math inline">\(\dot{V}\)</span>, <em>vs</em>. <span class="math inline">\(C_{A,in}\)</span>, <em>vs</em>. <span class="math inline">\(C_{Y,in}\)</span>, and <em>vs</em>. <span class="math inline">\(C_{Z,in}\)</span>.</li>
</ol>
<p><strong>Results</strong></p>
<p>To estimate the kinetics parameters, the response function described above was passed to parameter estimation software along with the adjusted experimental inputs, the experimental responses and a guess for the kinetics parameters. The results returned by that software are shown in <a href="#tbl-example_11_3_results">Table&nbsp;<span>11.6</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example_11_3_results" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11.6: Parameter estimation results</caption>
<tbody>
<tr class="odd">
<td style="text-align: center;">k<sub>f</sub></td>
<td style="text-align: center;">15.8 gal lbmol<sup>-1</sup> min<sup>-1</sup>, 95% CI [15.1, 16.5]</td>
</tr>
<tr class="even">
<td style="text-align: center;">k<sub>r</sub></td>
<td style="text-align: center;">5.02 gal lbmol<sup>-1</sup> min<sup>-1</sup>, 95% CI [4.62, 5.46]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">R<sup>2</sup></td>
<td style="text-align: center;">0.985</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The results from the parameter estimation were then used to create the parity plot shown in <a href="#fig-example_11_3_parity">Figure&nbsp;<span>11.4</span></a> and residuals plots shown in <a href="#fig-example_11_3_residuals_plots">Figure&nbsp;<span>11.5</span></a> as described in <a href="section_4_data_generation.html"><span>Chapter&nbsp;8</span></a>.</p>
<div id="fig-example_11_3_parity" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./Graphics/reb_11_3_parity.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;11.4: Parity plot.</figcaption>
</figure>
</div>
<div id="fig-example_11_3_residuals_plots" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_3_VFR_residuals.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_3_CA_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_3_CY_residuals.png" class="img-fluid figure-img"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="./Graphics/reb_11_3_CZ_residuals.png" class="img-fluid figure-img"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.5: Parity and Residuals Plots.</figcaption><p></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click Here to See What an Expert Might be Thinking at this Point
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The confidence intervals for <span class="math inline">\(k_f\)</span> and <span class="math inline">\(k_r\)</span> form a narrow range of values about the estimates and the coefficient of determination is close to 1.0. Both of these results suggest that the model is accurate. In the parity plot the experimental data all lie close to the line representing the model, and in the residuals plots, the deviations of the experimental residuals from zero appear to be random with no apparent trends. These graphical results also suggest that the model is acceptably accurate.</p>
</div>
</div>
</div>
<p><strong>Assessment</strong></p>
<p>When the rate coefficients in <a href="#tbl-example_11_3_results">Table&nbsp;<span>11.6</span></a> are used in the rate expression, equation (2), it provides an acceptably accurate representation of the experimental results.</p>
</section>
</section>
<section id="symbols-used-in-sec-4_cstr_data_analysis" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="symbols-used-in-sec-4_cstr_data_analysis"><span class="header-section-number">11.6</span> Symbols Used in <a href="#sec-4_cstr_data_analysis"><span>Chapter&nbsp;11</span></a></h2>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Symbol</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(i\)</span></td>
<td style="text-align: left;">index denoting a reagent.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;">Rate coefficient.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(f\left(\right)\)</span></td>
<td style="text-align: left;">A mathematical function of the variables within the parentheses.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\dot{n}_i\)</span></td>
<td style="text-align: left;">Molar flow rate of reagent <span class="math inline">\(i\)</span>, an additional subscripted “in” denotes the flow into the reactor.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(r\)</span></td>
<td style="text-align: left;">Net rate of reaction per unit fluid volume.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x\)</span></td>
<td style="text-align: left;">Independent variable in a linear model.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(y\)</span></td>
<td style="text-align: left;">Dependent variable in a linear model.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(y_i\)</span></td>
<td style="text-align: left;">Mole fraction of reagent <span class="math inline">\(i\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C_i\)</span></td>
<td style="text-align: left;">Concentration of reagent <span class="math inline">\(i\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P\)</span></td>
<td style="text-align: left;">Pressure.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_i\)</span></td>
<td style="text-align: left;">Partial pressure of reagent <span class="math inline">\(i\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R\)</span></td>
<td style="text-align: left;">Ideal gas constant.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(T\)</span></td>
<td style="text-align: left;">Temperature.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(V\)</span></td>
<td style="text-align: left;">Volume of fluid within the reactor.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\dot{V}\)</span></td>
<td style="text-align: left;">Volumetric flow rate.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\nu_i\)</span></td>
<td style="text-align: left;">Stoichiometric coefficient of reagent <span class="math inline">\(i\)</span>.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./section_4_pfr_data_analysis.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Analysis of Kinetics Data from a PFR</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./section_5_intro.html" class="pagination-link">
        <span class="nav-page-text">Modeling Isolated Ideal Reactors</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>