# SBSTR Analysis {#sec-4_sbstr_analysis}

The primary difference between semi-batch stirred tank reactors (SBSTRs) and BSTRs is that fluid flows into *or* out of an SBSTR during some part of the time  when reaction is taking place. This chapter only considers systems where fluid flows into the reactor while reaction is taking place. It describes operation of that type of semi-batch reactor, and examines how flow entering the reactor affects the analysis of an SBSTR. It highlights advantages and disadvantages of SBSTRs, especially in comparison to BSTRs. It illustrates the modeling and optimization of SBSTRs.

SBSTRs where fluid flows out of the reactor while reaction is occurring are described herein. The resulting advantages and disadvantages are identified and discussed. However this chapter *does not* describe the modeling and analysis of this mode of SBSTR operation.

## SBSTR Characteristics

As is the case for the other ideal stirred-tank reactors, one essential characteristic of an SBSTR is that the reacting fluid within it is always perfectly mixed. As discussed in @sec-4_bstr_analysis for batch reactors, it is not essential that the reactor takes the form of a stirred tank; any reactor that is perfectly mixed and that has fluid flowing into or out of the reactor at least some of the time during which reaction is occurring can be modeled as an SBSTR. Nonetheless, actual stirred tanks are most common in commercial practice.

The addition and/or removal of heat from the reacting fluid in a stirred tank is described in @sec-apndx_heat_exch for systems where a separate heat exchange fluid is employed. While other means of heat exchange are sometimes used, *Reaction Engineering Basics* only considers heat exchange between the reacting fluid and a perfectly mixed heat exchange fluid. Mass and energy balances on the exchange fluid are considered in @sec-3_design_eqns and @sec-apndx_heat_exch.

@sec-4_bstr_analysis described three geometries involving a perfectly mixed heat exchange fluid: a shell/jacket, an immersed coil, and an external heat exchanger (see @fig-bstr_heat_exchange_schematics). These three configurations apply equally to SBSTRs.

The characteristic that differentiates between a BSTR and an SBSTR is flow of reagents into or out of the reactor while the reaction is taking place. When reagents flow into the reactor during reaction, the SBSTR is sometimes referred to as a "fed-batch" reactor. A common form of semi-batch operation where reacting fluid leaves the reactor involves simple "reactive separation."

### Batch-Fed SBSTRs

Two advantages can be realized by adding one reagent to an SBSTR over time. One advantage is control of the rate of heat release. An example is the neutralization of a strong acid using a strong base. Such reactions can have very high rates and be highly exothermic. If all of the reagents are added at once, it may not be possible to remove heat fast enough to safely control the temperature. By slowly adding one of the reactants over time, the rate of heat release is limited by the rate of reagent addition and not the rate of reaction. The rate of addition can then be matched to the rate at which heat can be removed. In this way, the temperature can be controlled.

When two or more reactions take place, semi-batch operation with the addition of one reagent can sometimes be used to control selectivity. This happens when the rates of the desired and undesired reactions exhibit different dependence upon the concentrations of the reactants. To illustrate, consider a reaction between reagents A and B. In a BSTR process, the concentrations of A and B would be largest at the start of processing and would remain comparable throughout processing. Suppose instead, that reagent A is present at full concentration at the start of processing, but that reagent B is added to it over time. In this way, the concentration of A can be kept as large as possible while that of B is as low as possible over the course of processing. If the rate of the desired reaction is more favored by high concentration of A and low concentration of B, then semi-batch processing will result in better selectivity than batch processing.

### Reactive Separation SBSTRs

Generally the descriptor, "reactive separation," applies to a wide range of processes wherein reaction and separation occur simultaneously. A number of different types of reactors fall into the category of reactive separation processes. Membrane reactors and reactive distillation columns are reactive separation devices. For present purposes, the term "reactive separation SBSTR" is limited to a two-phase, stirred-tank reactor, for example a reactor where the reacting fluid is boiling and the resulting vapor is removed during processing.

Reactive separation SBSTRs can offer an advantage when a reversible reaction is taking place. Specifically, if one of the products of the reaction is more volatile than the reactants, higher conversion can result in a reactive separation SBSTR than the conversion that would be realized using a BSTR. When using a BSTR, the maximum possible conversion is that where the reaction is becomes equilibrated. When that conversion is reached, the rate equals zero and no further conversion is possible. In contrast, in a reactive separation SBSTR one of the products of the reaction continually boils off and is removed. As a consequence, at a conversion where the BSTR was equilibrated, the SBSTR is not equilibrated because some of the product has been removed. In this way, a reactive separation SBSTR can reach a greater conversion than is possible in a BSTR.

The modeling and analysis of reactive separation SBSTRs is not considered in *Reaction Engineering Basics.* The presence of two phases, and particularly the presence of an interface between the two phases introduces the possibility that neither of the two phases is perfectly mixed. Put differently, it is often found that there are concentration gradients in the fluids near either or both sides of the interface. If such concentration gradients exist, then the fluid is not perfectly mixed, and it is necessary to modify the SBSTR design equations. Reactions at interfaces in multi-phase systems are typically studied in more advanced courses on reaction engineering.

### Other Advantages and Disadvantages of SBSTRs

BSTRs and SBSTRs are both non-continuous reactors, so in comparison to continuous reactors, they have the same advantages and disadvantages. Their advantages include versatility (using the same reactor at different times to run different reactions) and flexibility such as the ability sequentially vary the processing temperature. Their disadvantages are that they are labor intensive and have lower net rates due to turnaround times. Generally SBSTRs and BSTRs are better suited to production of value added products and not commodity products.

Three possible advantages of SBSTRs over BSTRs have already been mentioned: controling selectivity or temperature using the rate of reagent addition and increasing conversion in reversible reactions by removal of products. When one of these three effects can be used to advantage, an SBSTR is preferred. Arguably, operation of an SBSTR is slightly more involved than that of a BSTR, so without one of those advantages, a BSTR is likely preferred.

## SBSTR Operation

The operation of SBSTRs is very much like that of BSTRs, the exception being that during some stages of the operating protocol, reagents are being added to SBSTRs. Operation of SBSTRs includes turnaround time, thereby allowing the definition of a net rate of production of a product like that for BSTRs, @eq-bstr_net_rate. Indeed, some processes begin as fed semi-batch processes, but then, when the reactor becomes full, the feed is stopped and they continue as batch processes.

When a reagent is fed to an SBSTR, the feed rate is often a critical factor. Effectively the feed rate controls the rate of reaction. Early in the process it may be essential to maintain a low feed rate, and thereby a low reaction rate, in order to control temperature rise. As the process progresses, the reaction rate will naturally decrease due to consumption of the reagent initially added to the reactor. There may be a point at which the reaction rate is sufficiently low that it no longer needs to be limited by the feed rate. In other words, the net rate may be larger if a variable feed rate is used. If a fixed and constant feed rate is used, it is important to optimize the net rate or selectivity with respect to the feed rate.

## SBSTR Design Equations

The ideal SBSTR design equations are derived in @sec-apndx_ideal_reactor_models and they are discussed in  @sec-ideal_bstr_eqns. Energy balances on the heat exchange fluid are discussed in @sec-heat_exchange_eqns. The SBSTR mole balance, @eq-sbstr_mol_balance; SBSTR energy balance, @eq-sbstr_energy_balance; exchange fluid sensible heat energy balance, @eq-exchange_energy_bal_sensible; and exchange fluid latent heat energy balance, @eq-exchange_energy_bal_latent; are reproduced below. 

$$
\frac{dn_i}{dt} = \dot n_{i,in} + V \sum_j \nu_{i,j}r_j
$$

$$
\begin{align}
\sum_i \left( n_i \hat C_{p,i}\right) & \frac{dT}{dt} -V\frac{dP}{dt} - P\frac{dV}{dt} = \dot Q - \dot W \\ &- \sum_i \dot n_{i,in} \int_{T_{in}}^T \hat C_{p,i}dT  - V\sum_j r_j \Delta H_j
\end{align}
$$

$$
\rho_{ex} V_{ex} \tilde C_{p,ex}\frac{dT_{ex}}{dt} = -\dot Q - \dot m_{ex} \int_{T_{ex,in}}^{T_{ex}} \tilde C_{p,ex}dT
$$

$$
\frac{\rho_{ex} V_{ex} \Delta H_{\text{latent},ex}^0}{M_{ex}} \frac{d \gamma}{dt} = - \dot Q - \gamma \dot m_{ex} \frac{\Delta H_{\text{latent},ex}^0}{M_{ex}}
$$

Common simplifications of the SBSTR design equations were presented in @sec-3_design_eqns. For convenience, they are summarized below. The sensible heat terms in the mole and energy balances above are written in terms of molar heat capacities. They can also be written in terms of the volumetric or gravimetric heat capacity of the reactiong fluid as a whole.

$$
\left(\sum_i n_i \hat C_{p,i} \right) \frac{dT}{dt}\ \Leftrightarrow\ \rho V \tilde C_p \frac{dT}{dt}\ \Leftrightarrow\ V \breve C_p \frac{dT}{dt}
$$

$$
\sum_i \dot n_{i,in} \int_{T_{in}}^T \hat C_{p,i}dT\ \Leftrightarrow\ \rho \dot V_{in} \int_{T_{in}}^T \tilde C_pdT\ \Leftrightarrow\ \dot V_{in} \int_{T_{in}}^T \breve C_pdT
$$

When the reacting fluid is an ideal gas, the reacting fluid volume, $V$, is constant (assuming rigid reactor walls), and its time derivative is equal to zero. For an incompressible ideal liquid reacting fluid the time derivative of the reacting fluid volume is equal to the volumetric feed rate, and if the feed rate is constant, that expression can be integrated to get an expression for the reacting fluid volume.

$$
\frac{dV}{dt} = \dot V_{in}
$$

$$
V = V_0 + \dot V_{in}t
$$

When heat is added or removed using a heat exchange fluid, the rate of heat removal can be expressed in terms of the heat transfer coefficient and area. When rate expressions are substituted into the mole and energy balances, they may introduce concentration or, for gases, partial pressures. The instantaneous values of those composition variables are found using their defining equations.

$$
\dot Q = UA\left( T_{ex} - T \right)
$$

$$
C_i = \frac{n_i}{V}
$$

$$
P_i = \frac{n_iRT}{V}
$$

## General Approach

The analysis of SBSTRs is very similar to the analysis of BSTRs which was described in @sec-4_bstr_analysis. After identifying the assigment as one involving the analysis of an isolated ideal SBSTR, @sec-4_response_opt_design, the analysis can be completed in four general steps (@sec-3_reactor_model_func): summarize the information provided, formulate the solution mathematically, implement the solution numerically, and present and discuss the results.

Summarizing an SBSTR analysis assignment is essentially the same as summarizing a BSTR analysis assignment. As with BSTRs, the summary should indicate the number of stages in the operating protocol. If the reactor operates as an SBSTR in some stages and as a BSTR in others, that information should be included in the summary.

The mathematical formulation will always entail selecting the reactor design equations needed to model each stage of the operating protocol and simplifying them as appropriate for the manner in which the reactor operates in that stage. When analyzing an SBSTR, the reactor design equations will always be IVODEs with elapsed time as the independent variable. Because the reactor design equations are IVODEs, the mathematical formulation should also specify the initial values and stopping criterion for each stage of the operational protocol.

It is possible that the number of SBSTR design equations will be one less than the number of dependent variables appearing in them. The reason for this is that the energy balance introduces three dependent variables. Assuming the reactor walls to be rigid, the time derivative of the reacting fluid volume will equal zero, but both the time derivative of the temperature and the time derivative of the pressure will be non-zero. This same situation was encountered with BSTRs, and it is handled here in the same way. A differential form of the ideal gas law, @eq-differential_ideal_gas_law and below, is used. It is either added to the SBSTR design equations or it is solved for $\frac{dP}{dt}$ and substituted into the energy balance. Either approach results in the number of IVODEs being equal to the number of dependent variables appearing in them.

$$
RT\left( \sum_i \frac{dn_i}{dt} \right) + R\left( \sum_i n_i \right)\frac{dT}{dt} - V \frac{dP}{dt} = 0
$$

When modeling liquid phase reactions in BSTRs, the number of design equations was always equal to the number of dependent variables because for liquids both $\frac{dP}{dt}$ and $\frac{dV}{dt}$ are equal to zero for an incompressible ideal liquid reacting in a reactor with solid walls. This is **not** true when processing a liquid in an SBSTR. When processing a liquid, $\frac{dP}{dt}$ will equal zero, but the volume will be changing as described above. I this case @eq-sbstr_expansion_term is added to the IVODEs or used to eliminate $\frac{dV}{dt}$ from the reacting fluid energy balance.

$$
\frac{dV}{dt} = \dot V_{in}
$$

The remainder of the mathematical formulation is analogous to BSTRs. It involves writing the ancillary equations that are needed in order to evaluate the derivatives at the start of a numerical integration step (i. e. knowing the values of the independent and dependent variables), writing the ancillary equations needed to calculate the initial and final values, and writing the ancillary equations needed to calculated any other quantities of interest once the design equations have been solved.

Numerical implementation involves writing computer code that performs the calculations described in the mathematical formulation. Presentation and discussion of the results is straightforward.

## Examples

Add a paragraph similar to section 9.6

### Response of an SBSTR for a Hydrolysis Reaction

{{< include ../RE_Basics_Examples/reb_14_1/problem_statement.qmd >}}

:::{.callout-note collapse="false"}
## Note

This problem is loosely based upon the work of Haldar and Rao [-@haldar_experimental_1992; -@haldar_experimental_1992-1], but the rate expression was modified and additional assumptions regarding fluid and reactor properties were introduced. This was done to avoid intricate details from obscuring the basic approach to the analysis of a semi-batch reactor. Therefore, the results presented here should not be used for engineering purposes, but rather the original work should be consulted.

:::

### Yield in an SBSTR

modify 2023 class 18 practice assignment 

### Maximizing the Net Rate in an SBSTR

constrained optimization example

## Symbols Used in @sec-4_sbstr_analysis

| Symbol | Meaning |
|:-------|:--------|
| $i$ | index denoting a reagent. |

: {tbl-colwidths="[20,80]"}