# BSTR Analysis {#sec-5_bstr_analysis}

[advantages, disadvantages and favorable situations for BSTRs.] This chapter examines reaction engineering of a single, isolated BSTR.

## BSTR Operation

## BSTR Optimization Objectives

small volume, short runs, high net rate, high selectivity, minimum heat input
parameters affecting selectivity: initial composition, temperature, reaction time

## Qualitative Analysis of Reaction in a BSTR

## BSTR Design Equations

## General Approach to Modeling Isolated BSTRs

go through chapter 11 approach adding specifics

### BSTR Response

go through use of response function for each of the two varieties of response tasks

### BSTR Optimization

go through use of response function for optimization tasks

## Examples

The examples in this section illustrate the analysis of BSTRs. Examples [-@sec-example_12_1] and [-@sec-example_12_2] are **response problems**. In [Example -@sec-example_12_1] the inputs to the reactor model are all known, and solving the problem involves calculating the response. In contrast, [Example -@sec-example_12_2] provides the response, and solving the problem involves calculating reactor inputs that will result in that response. The numerical approaches used to solve these two types of problems are slightly different. In addition to the computational differences, [Example -@sec-example_12_1] involves a single reaction taking place in an adiabatic BSTR while [Example -@sec-example_12_2] features two reactions taking place in a reactor that is cooled using an exchange fluid. BSTRs. Examples [-@sec-example_12_3] and [-@sec-example_12_4] are **optimization problems**. They identify a reactor variable that must be maximized or minimized by specifying a reactor input. The computational procedure for solving optimization problems differs slightly from the procedures for solving response problems. Like Examples [-@sec-example_12_1] and [-@sec-example_12_2], the BSTR operating protocol in [Example -@sec-example_12_3] consists of a single step. [Example -@sec-example_12_4] illustrates a situation where there are multiple steps in the operating protocol. It also considers turnaround time and the net rate of reaction.

### Adiabatic Reaction with an Unknown Response {#sec-example_12_1}

{{< include ../RE_Basics_Examples/reb_13_1/problem_statement.qmd >}}

### Parallel Reactions with a Specified Response {#sec-example_12_2}

{{< include ../RE_Basics_Examples/reb_13_2/problem_statement.qmd >}}

### Maximum Intermediate Yield in Series Reactions {#sec-example_12_3}

{{< include ../RE_Basics_Examples/reb_13_3/problem_statement.qmd >}}

### Optimization of Net Production Rate {#sec-example_12_4}

{{< include ../RE_Basics_Examples/reb_13_4/problem_statement.qmd >}}

## Symbols Used in @sec-bstr-analysis

| Symbol | Meaning |
|:-------|:--------|
| $i$ | index denoting a reagent. |


: {tbl-colwidths="[20,80]"}
