# Design of Non-Continuous Reactors {#sec-4_non_continuous_design}

@sec-4_response_opt_design describes and differentiates between response, optimization, and design tasks or problems. @sec-4_bstr_analysis and @sec-4_sbstr_analysis examine the modeling of two kinds of non-continuous, ideal reactors: BSTRs and SBSTRs. They illustrate the use of the reactor design equations to complete reaction engineering assignments involving response and optimization tasks. This chapter introduces design tasks for non-continuous ideal reactors.

Reactor design is an advanced aspect of reaction engineering. This chapter is a very basic introduction to reactor design. Its intent is to make the reader aware that many reaction engineering assignments are open-ended and do not have a single "correct" answer like those considered in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis]. Unlike those assignments, reactor design assignments can provide opportunities for a reaction engineer to be very creative and not simply follow some "cookie-cutter" approach to completing assignments. They can lead to discovery of innovative ways to operate reactors and the invention of new kinds of reactors.

## Full Reactive Process Design

Chemical reactors are virtually always one part of a larger process. The highest level of design starts with a decision to build a process from scratch. The decision to do this would be informed by some number of preliminary analyses of the market for the products from the process, the economic potential of the process, the technical feasibility of the process, etc. Full reactive process design will involve a team comprising members with expertise in finance, planning, procurement, law, construction, chemistry, engineering, etc. The members with engineering epertise would include a reaction engineer among other engineering specializations including separations, control, heating and cooling, etc.

There are principles that should guide any reactive process design. Among the more important principles, the process should be safe to operate, it should comply with all governmental regulations, it should not have unfavorable or unjust environmental and societal impacts, and it should be profitable.

Some of the economic factors that must be evaluated as part of the process design are the capital costs (one time expenses to purchase the necessary equipment, etc.), the operating costs (including labor, utilities, feedstock costs, waste disposal, etc.), maintenance costs, licensing costs (e. g. royalties for use of patented technology), income the process will generate and the return on investment. Governmental and legal activities include choosing the site for the process, securing necessary permits, licensing any necessary technology, identifying all regulatory restrictions that apply to the process. Engineers develop equipment specification, and business experts procure the equipment. The engineering team lays out the piping and designs the individual components, making sure that they are all properly and efficiently integrated. Specific tasks that a reaction engineer would be involved in include selecting the type of reactor(s) to be used, sizing the reactor(s) and specifying operational prameters (heating and cooling, feed temperature and composition), specifying turn-around tasks and timing for non-continuous processes, and developing procedures for start-up, operation, shut-down, and various possible emergencies.

## Preliminary Reactor Design

Participation in a full reactive process design of the kind just described requires much deeper knowledge of reaction engineering and much more reaction engineering experience that most readers of this book are likely to possess. Preliminary design involves a more limited scope. A preliminary reactor design might be one of the factors that go into the decision to build the full process. The goals of a preliminary design can include identifying the kind of reactor and the preferred way to operate it for the process under consideration. It might use approximate feed compositions and educated estimates of necessary conversion and selectivity. A detailed economic model is not required, but an awareness of factors that affect both capital and operating costs is important.

Preliminary design starts with an underspecifed reactor process. That is, there isn't enough information about the reactor and its operation to generate reactor design equations and perform an analysis. One way to think about or envision preliminary design is as a process wherein the reaction engineer fills in enough missing information to specify a reaction engineering optimization task and then performs that optimization task. The engineer then might fill in the information differently to specify a different reaction engineering optimization task and complete it. This might be repeated any number of times. The results of one cycle might inspire or inform the specification of a different optimization task. Ultimately, the results from all of the optimizations are compared, and the most promising reactor specifications are selected.

From the reaction engineer's perspective, their starting point is an underspecified reactor. The reaction engineer turns it into a fully specified reactor by choosing the reactor type, setting some of the operating parameters for that reactor type, and optimizing the remaining operating parameters using a reactor model. The reaction engineer may do this for more than one type of reactor, and they may vary which parameters they set and which ones they find by optimizing a reactor model. The different reactor types that the engineer considers and the various combinations of parameters they set versus those they find using modleing can be referred to collectively as the engineer's design strategy. 

Readers who have assimilated the knowledge and skills from Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] are capable of non-continuous reactor analysis. This chapter emphasizes design strategy, not analysis. More specifically, the focus is on choosing the reactor type and specifying operational parameters leading to a fully specified reactor that can be analysed. The design strategy may involve doing this repeatedly with the goal of identifying a fully specified reactor system that meets or exceeds the initial design specifications with the largest possible financial profits.

Almost every preliminary design assignment will have unique aspects. The discussion here begins by identifying the things that might be specified in a preliminary design assignment and the things that might be missing. Next some common kinds of constraints are considered. A full economic analysis and optimization is not warranted at the preliminary design stage. In fact it may not be possible, so this sub-section concludes by identifying reactor performance metrics that might be used as economic indicators when comparing different preliminary designs.

### Preliminary Design Specifications

As already mentioned, reactor design tasks begin with an underspecified reactor. The specifications that are provided in the assignment are called design specifications. Arguably, the reactor type (BSTR, SBSTR, CSTR, PFR, etc) has the greatest effect upon how the reactor performs, but in many (most?) cases, the reactor type is **not** one of the design specifications. Common exceptions to this occur when the design calls for the use of an existing reactor, or when many similar processes have already been designed and they all use the same reactor type. Process parameters including operating temperature and pressure, flow rates, reactor volume, heat exchange area and heat transfer coefficient often are not among the design specifications. 

Very commonly the design specifications **do** identify the feedstock to be used and often its composition/purity, as well. Feed temperatures, flow rates, and other details about how the feed is added are often missing. Steam is often available at one or two temperatures/pressures in a chemical plant, and chilled water at a single temperature. Whatever the steam and chilled water availability, the engineer would typically know what is available. Sometimes heat can be exchanged with other process streams in a chemical plant, but this information may not be known in a preliminary design. The identity of the desired products is usually known, and sometimes the purity and/or production rate are among the design specifications, too. 

### Preliminary Design Constraints

The engineer may not have complete freedom as they add to the design specifications. Other considerations constrain their freedom. For example, there may be temperature limits on various process streams. These might include a maximum allowed reaction temperature (to prevent undesired reactions, phase changes in the reactor, or catalyst deactivation), a maximum outlet temperature on chilled water, or a maximum final temperature for a batch process (so the reactor can be drained safely). Safety can also impose other constraints such as a maximum temperature that feed and product piping can withstand, composition limits to avoid danger of explosion, etc. If anything is being discharged to the atmosphere or into bodies of water, regulations may restrict composition.

Constraints like those just mentioned often do not apply directly to the specifications that the engineer adds to the design specifications. Instead, they limit the choices the engineer can make indirectly. That is, after the engineer adds to the design specifications so the reactor is no longer underspecified, the reactor must be modeled in order to determine whether any of the constraints are violated.

### Reactor Performance Metrics as Economic Indicators

One of the primary goals of process design is to arrive at a set of process specifications that will result in the greatest rate of financial profit, should the process be built. At the preliminary design stage, often there are still too many unknowns for that sort of financial analysis. Instead, reactor performance metrics that are related to profit are used to optimize the reactor system. For example, the operating costs often scale with the volume of the reactor. In that case, one of the goals of the preliminary design would be to minimize the reactor volume for a given production rate.

Similarly, the use of steam or another medium for heating and the use of chilled water or another coolant have associated costs. Minimizing the amount of heating and cooling that uses an exchange fluid then becomes another design objective. If the temperature of available steam or coolant is not known or specified, using lower steam temperatures and higher coolant temperatures similarly reduces costs.

The selling price of the product may depend upon its purity, and production of hazardous wastes can add to operating costs. In both of these cases, selectivity may be an important metric that is related to process profit. Each situation will have key metrics that have a significant impact on process profits. In a preliminary design these metrics can be appropriately minimized or maximized in lieu of an economic analysis.

## Important Design Decisions

A review of the examples in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] will reveal that simply analyzing a reactor requires a relatively shallow level of understanding of reactor performance and a relatively low level of thinking. That is, if one learns how to generate and simplify the reactor design equations for a given system along with some important definitions, modeling the reactor always follows the same general steps. (Write and simplify the design equations, specify the initial and final values, write ancillary equations needed to evaluate the derivatives at the start of an integration step, write ancillary equations to calculate the initial and final values, solve the reactor design equations, write ancillary equations to calculate any other quantities of interest, and calculate the quantities of interest.) When one has that minimum level of knowledge and knows the steps to follow to solve the design equations, response and optimization tasks can be completed without too much additional thought or understanding.

Looking at the discussion that follows many of the examples in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis], and particularly at the qualitative analysis, reveals a deeper level of understanding and a higher level of thinking. At that level, physical explanations for observed phenomena are sought and developed. That is, those discussions seek to explain in physical (not mathematical) terms why a graph has a given shape or passes through a minimum or maximum, or why increasing the inlet temperature or inlet flow rate affects the output in the way that it does. It requires deeper knowledge (e. g. what factors can cause temperature or reaction rate to change) and higher level of thinking (e. g. which of those factors are at play or important at a given point in the process; how will the importance of those factors change over the course of processing; how are those factor related to the reactor inputs).

It can be argued that reactor design requires an even deeper level of understanding of reactor performance and an eveh higher level of thinking. During reactor design the reaction engineer isn't trying to explain an observed reactor response. Rather, the engineer needs to predict how to cause a desired reactor response by altering what goes into the reactor and how it is operated. When a reaction engineer lacks an appropriate level of understanding or has not learned to think at an appropriate level, their design strategy can devolve to the point of trial and error which is at best inefficient and at worst, ineffective.

One of the first decisions the engineer needs to make is whether the process should be **continuous or non-continuous**. This was discussed in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis]. For present purposes it is assumed that the priliminary design involves a non-continuous process. Having settled on a non-continuous process, the next key decision is **whether to use a BSTR or an SBSTR**. @sec-4_sbstr_analysis identified three situations where and SBSTR can offer a clear advantage over a BSTR: highly exothermic reactions, reactions where the selectivity is strongly affected by the relative amounts of the reactants, and reversible reactions where a product can be selectivity removed. If one of these situations clearly pertains, the choice to use an SBSTR is clear.

When the choice between a BSTR and an SBSTR isn't clear, the engineer might initially select a BSTR and begin the design process. The operation of a BSTR is slightly less detailed than an SBSTR because it isn't necessary to start, control and stop flow going into the reactor. As such, using a BSTR simplifies operation and perhaps reduces labor costs compared to an SBSTR. For example at the start of the preliminary design, the engineer may not know whether the reaction rate is so fast and the exothermicity so great that temperature could not be controlled in a BSTR. The engineer could begin by choosing a BSTR. If the rate or extent of temperature rise is always unaccepably large, the use of a BSTR can be abandoned, and replaced with design of an SBSTR. If the engineer initially selects an SBSTR and successfully completed a preliminary design for it, they won't know whether a BSTR could work just as well.

After deciding upon the reactor to use to begin the preliminary design, the engineer will need to add to the design specifications. In the absence of a financial model, the specifications added by the reaction engineer will be of three types: the key reactor metric to be minimized or maximized, the reactor/process parameters that are optimized in order to minimize or maximize the key metric, and the reactor/process parameters that are fixed.

The design process will generate multiple sets of process specifications that ultimately need to be compared. To facilitate that comparison, it is useful to choose one specification as the basis for all calculations. The feed flow rate of the primary reactant or the net rate of production of the primary product are often chosen as the basis. Whatever is chosen as the basis becomes a fixed specification that does not change throughout the preliminary analysis.

There will likely be several reactor metrics that are related to capital or operating cost. They might include reactor size (volume of the reacting fluid) assuming capital and operating costs scale with volume. They might include conversion if recovery of reactant that was not converted is difficult or expensive. They might include selectivity if there is poential to produce multiple products or varying value or with side products that are difficult and/or expensive to remove and dispose of. The engineer must use their experience and judgement to select the most important reactor metric. (It is always possible, and often necessary, to return to this point and select a different key metric.)

At this point the original design specifications, the type of reactor, the basis for the calculations, and the key metric, i. e. the quantity of interest, will have been determined. The engineer can generate the reactor design equations and all necessary ancillary equations needed to calculate the key metric. It won't be possible to perform the calculations yet because the problem will still be underspecified. The engineer can examine the equations and identify which of the quantities appearing in them must be given values so that the key metric can be calculated.

The missing values can be specified in two ways. They can be assigned a fixed value, or they can be used as optimization parameters. Typically fixed values are specified for the quantities that are not expected to strongly affect the key metric while those that are expected to strongly affect the key metric are used as optimization parameters. (Note, the optimization tasks illustrated in Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] involved a single optimization parameter and possibly a single constraint. However computer functions for maximizing or minimizing a the key metric can do so using multiple optimization parameters and multiple constraints.)

As noted previously, the engineer may perform the optimization of the key metric multiple times using different sets of fixed and optimization parameters. Then the engineer might select a second key metric and repeat the process. During the course of these calculations, the engineer may determine that a BSTR cannot meet the design specifications safely (temperature can't be controlled) or that an SBSTR may be a better choice (for selectivity or conversion with a reversible reaction). The whole process would then be repeated, but starting with an SBSTR.

It should be apparent that when a reaction engineer performs a preliminary desigh task, the engineer will make a number of decisions or choices. The choices the engineer makes determined the number of reactor simulations the engineer must perform. A key to efficient and effective design is a deep understanding of reactive processes and an ability to think through the consequences of changing various reactor parameters without performing unnecessary calculations.

## Examples

Performing a preliminary design entails many calculations, and the result, while correct in the sense that it satisfies the design specifications, is not necessarily unique. Readers who have completed Chapters [-@sec-4_bstr_analysis] and [-@sec-4_sbstr_analysis] should already know how to perform the necessary calculations. The new aspect of preliminary design assignments is that the reactor system is underspecified and that the reaction engineer must decide what specifications to add in order to perform the analyses and complete the assignment.

For this reason, the two examples provided here do not include any calculations. Instead, they focus on the engineer's thought processes and the resulting specifications they choose. In essence, the engineer chooses one or more sets of specifications to be analyzed. The sets of specifications the engineer chooses represent that engineer's design strategy. The engineer may revise their design strategy they proceed through the analyses.

So, the following examples describe one engineer's thinking and the design strategy they develop based on that thinking. A different engineer might think differently and develop a different design strategy. Assuming they are competent, both engineers will arrive at a preliminary design that satisfies the design specifications, but their preliminary designs may be different from each other. It is critially important for readers to recognize that **these examples are [not]{.underline} a "cook book" for what [you]{.underline} should be thinking while developing [your]{.underline} design strategy**, but rather an example of what one engineer [might]{.underline} be thinking as they develop [their]{.underline} design strategy. Since the engineer's thinking is the essence of these examples the usual "Click Here to See What an Expert Might be Thinking at this Point" callouts are not used in this chapter's examples.

### Preliminary Reactor Design for an Autocatalytic Reaction

**Background**: One of the processes in a small manufacturing facility generates approximately 20 lb per day of a side product, A. The side product is separated from the primary products and burned because both its volume and its value are small. Recently a homogeneous catalyst that converts A to the much more valuable reagent, B, was discovered. The reaction is mildly exothermic and irreversible, and the catalyst is active at temperatures of the order of 60 °C. The catalyst degrades at temperatures over 90 °C. A rate expression has been developed, and it has been found that the reaction is autocatalytic over a wide range of conversion of A. That is, the reaction rate increases as the concentration of B increases. All thermochemical data needed for a reactor analysis are available.

A market for B will need to be developed, and demand is expected to be intermittent. The company is considering producing B from A and storing the B for later sale when the market is weak. Space is very limited in the manufacturing facility, so the amount of B that can be stored will be limited. If the B reaches that limit, the company will stop making B and revert to burning the A until some of the B has been sold and storage for the B becomes available again.

**Assignment**: Perform a preliminary design of a reactor that can be used as described above.

---

As the engineer who has been given this assignment, here's what I'm thinking:

* The process will only run when there is storage space available for B, so it will be non-continuous.
* Assuming that both capital and operating costs scale with the reactor volume, the reactor volume 
    
Based upon my thinking above, here is my **design strategy**:

### Preliminary Design of a Waste Remediation Reactor

**Background**: A small company makes a specialty halogenated hydrocarbon using a batch reactor. During its production an undesired mono-chloro side product is generated. The side product is separated and stored in a 500 gal tank. Every two weeks a disposal company comes and removes the contents of the tank. The cost for disposal is significant and has been increasing.

Chemists working in the company research labs have found that the mono-chloro side product reacts with 4 M NaOH to remove the Cl as NaCl, replacing it with a hydroxyl group. There may be a market for sale of the hydroxylated product, but even if there isn't, the hydroxylated product can be burned to generate process heat. (Burning the mono-chloro side product is not permitted due to the chlorine it contains.) A pressure of 10 atm is needed for the reaction. A reasonable rate is realized at 90 °C. The heat of reaction is modest, and the hydroxylation reaction is essentially irreversible.

The laboratory results show that the NaOH and the mono-chloro side product also react to form a dichloro waste product. This reaction is slow, so only a small amount of the waste is generated, but the reaction starts at low temperature so the di-chloro waste is generated while the system is being heated to reaction temperature. At temperatures of 90 °C and above, the formation of NaCl is much faster than the rate of formation of dichloro waste. It may still be necessary to store the dichloro waste product and pay for its disposal, but the volume is expected to be much smaller. The reactor must be cooled to 45 °C before the turnaround procedure can begin.

The company is considering building a process for hydroxylation of mono-chloro side product using the chemistry described above. Rate expressions for all reactions and thermochemical data for the reagents are available in company files. On site there is a steam generator that produces saturated steam at one temperature and a small chilled water plant that produces water at a single temperature. The temperatures of the steam and chilled water are suitable for the proposed process.

**Assignment**: Perform a preliminary design of a reactor that can be used to hydroxylate the mono-chloro side product. The results of this preliminary design will inform a decision on whether or not to build the process.

---

As the engineer who has been given this assignment, here's what I'm thinking:

* The mono-chloro side product is not produced continuously, so this process must be non-continuous.
* I don't see any reason for using an SBSTR instead of a BSTR:
    * the heat of reaction is modest, so I don't expect temperature control issues,
    * the reaction is irreversible, so product removal will not increase the conversion, and
    * the selectivity for the dichloro waste does not appear to depend upon composition, so it won't be affected by slowly adding one reactant to the full amount of the other.
* The reactor should operate at its maximum capacity in every batch.
* Essentially complete conversion (say 99.5%) should occur in every batch.
* I'll use two weeks as the basis for my calculations.
* Over a two week period the total volume to be processed is 500 gal plus the volume of a stoichiometrically equivalent amount of NaOH.
    * I'll use stoichiometric amounts of the reactants so I don't need to separate unconverted reactant from the product mixture.
* I can estimate the turnaround time, and I'll assume it is the same for all reactor volumes.
* Picking the number of batches fixes both the volume of the reactor and the time per batch (processing plus turnaround).
    * The volume per batch (the reactor volume) is the total volume to be processed divided by the number of batches.
    * The total time per batch is 2 weeks divided by the number of batches.
    * The *processing* time per batch is the time per batch minus the turnaround time.
* There is a maximum number of batches.
    * Most likely there will be some number of batches for which the time per batch is too small to reach complete conversion.
    * The unlikely limit would be if processing time was negligible compared to the turnaround time, in which case the number of batches would equal 2 weeks divided by the turnaround time.
* If I assume that capital plus operating costs scale with reactor volume, I want to use the maximum number of batches because that will give the smallest volume per batch.
* I can prevent formation of the dichloro waste during heating of the reactants by using a three stage operational protocal:
    * charge the reactor with only the mono-chloro side product and heat to a temperature, $T_1$, at or above 90 °C (No di-chloro waste will form during this stage),
    * when the system reaches temperature, $T_1$, add all of the NaOH and continue heating until the conversion reaches $f_2$,
    * stop heating and cool to 45 °C.
    * The conversion, $f_2$, is a fixed, but unknown, constant. It's value should result in the conversion reaching 99.5% at the end of the cooling stage. (Put differently, the initial value for the third stage, $f_2$, is unknown, but two final values are known: $T$ = 45 °C and $f_3$ = 99.5%. One of the final values can be used to calculate $f_2$ and the other as the stopping criterion - see @sec-apndx_solve_ivodes and [Example -@sec-example_9_6_2]). 
* I can use separate heat exchangers for heating and cooling, each with its own heat transfer area.
* Upon setting the number of batches, the following operational parameters are fixed:
    * the reactor volume
    * the maximum available batch time
    * the maximum available processing time (batch time minus turnaround time)
    * the initial amount of mono-chlor side product in the reactor and its temperature
    * the amount of NaOH to be added to the reactor and its temperature
    * the temperature of the steam in the heating shell (set by the facility steam generator)
    * the chilled water flow rate and inlet temperature (temperature set by the facility water chiller)
    * the final temperature, 45 °C, and conversion, 99.5%.
* Upon setting the number of batches, the following parameters still need to be specified:
    * the final temperature for the first stage of the operational protocol, $T_1$,
    * the heating shell heat transfer area,
    * the cooling shell heat transfer area, and
    * the chilled water flow rate.
    * I can choose values for these parameters that result in the smallest selectivity for the di-chloro waste. That is, I can minimize the selectivity for the di-chloro waste with respect to these four parameters.
* During minimiztion of the selectivity for the di-chloro waste, I must apply constraints:
    * The processing time must be less than or equal to the maximum available processing time.
    * The outlet temperature of the chilled water must not boil, so I'll say the outlet chilled water temperature must be less than 90 °C (this gives me a small margin for error without having the chilled water boil).
    
Based upon my thinking above, here is my **design strategy**:

1. Assume a single BSTR will be used with the three-stage operational protocol describe above.
2. Generate the reactor design equations and use them to create a model that calculates the selectivity for the di-chloro waste given values for the final temperature for the first stage, the two heat transfer areas and the chilled water flow rate.
3. Start with one batch every two weeks and keep increasing the number of batches by one until it isn't possible to achieve 99.5% conversion within the total processing time available for that number of batches.
    a. For each value of the number of batches, calculate the reactor volume and then minimize the selectivity for the di-chloro waste with respect to the final temperature for the first stage, the two heat transfer areas and the chilled water flow rate, and subject to the constraints listed above.
4. The minimum reactor volume and the corresponding selectivity for the di-chloro waste can be identified from the results.
5. It might be interesting to repeat the analysis using a two-step protocol where all of the feed is added at the start to see whether the minimum reactor size or the selectivity for the di-chloro waste changes.

