# Modeling Non-Ideal Reactors

This is the final part of *Reaction Engineering Basics*. The first two parts were primarily focused on reactions and reaction rates. The next four parts involved systems that included *ideal reactors*. This seventh part presents an overview of steady-state, continuous reactor models that can be used when the flow in the reactor does not conform to the assumption of perfect mixing nor to the assumption of plug flow. It begins by examining age distribution functions, which are not reactor models, but can be used to create a non-ideal reactor model or to estimate parameters that appear in non-ideal reactor models. The three model types progress from the segregated flow reactor model which does not contain unknown parameters to the axial dispersion model which has two adjustable parameters to zoned reactor models where there can be a large number of adjustable parameters. The parameters can be adjusted so as to provide the most accurate representation of the actual, non-ideal reactor.

## Chapters in this Part of *Reaction Engineering Basics*

@sec-7_age_function

@sec-7_seg_flow_models

@sec-7_axial_dispersion

@sec-7_zoned_reactor_models