# Reaction Engineering Tasks {#sec-3_react_eng_tasks}

Reactors are typically one component of a larger chemical process. That process might include heat exchangers, other reactors, splitting and mixing of fluid streams, and many other types of equipment. Nonetheless, for analysis purposes it often is possible to draw an imaginary box around only the reactor, and treat it as an isolated system.

Reactor performance can be analyzed qualitatively and quantitatively. The quantitative analysis of an isolated ideal reactor requires a mathematical model of the reactor, and is the primary topic of the next several chapters. Before undertaking a quantitative analysis, it can be useful and insightful to perform a qualitative analysis. A qualitative analysis can also provide insight into the results obtained in a quantitative analysis.

## Qualitative Reactor Analysis {#sec-3_qualitative_analysis}

Qualitative analysis focuses upon how the composition and temperature will vary as the reaction or reactions progress, but not on the magnitude of the variations. @sec-3_react_eng_models noted that in batch reactors the time during which reactions occur is measured using clock time and is equal to the time that has elapsed since the reaction was initiated. It further noted that in continuous flow systems, the time during which reactions occur is equal to the amount of time that the reagents spend in the reactor. It defined the space time, @eq-space_time, as one measure of the time reagents spend in the reactor. Reactions occur over time, so in qualitative analysis, changes in composition and temperature with increasing batch reaction time or flow reactor space time are of interest.

Because the analysis is qualitative, the rate expression is not used directly. Instead, the general behavior of reactions must be used, noting that for a typical reaction

* the rate will increase if the temperature of the reacting system is increased,
* the rate will decrease if the concentration of one or more reactants decreases,
* the rate is not strongly affected by the concentration of the products if the reaction is irreversible,
* the rate decreases as the concentration of the products increases if the reaction is reversible,
* the equilibrium constant decreases as the temperature increases if the reaction is exothermic, and
* the equilibrium constant increases as the temperature increases if the reaction is endothermic.

Of course, not all reactions behave “typically.” The approach to qualitative analysis presented here also can be applied to atypical reactions if the general behavior above is appropriately adjusted. Atypical behavior can often be recognized by examining the rate expression, if it is available. For example, if the rate increases as the concentration of a *product* increases, the reaction is said to be autocatalytic, and the qualitative behavior can be adjusted accordingly.

The driving force for a chemical reaction is reducing the free energy of the system. Put differently, a chemical reaction always proceeds toward chemical reaction equilibrium. As a consequence, in an isothermal or adiabatic reactor, a single chemical reaction will never change direction spontaneously. To do so, the reaction would have to go beyond equilibrium and then turn around and go back. Since a single reaction will never change directions, the concentrations of the reactants will continually decrease over time and the concentrations of the products will continually increase over time until equilibrium is reached. As equilibrium is reached, the concentrations will stop changing over time.

The other factor to be considered in a qualitative analysis is the extent to which heat is added or removed as the reaction or reactions progress. There are a number of possibilities in this regard. Qualitative analysis is easiest and most reliable when only one reaction is taking place in a reactor that operates either adiabatically or isothermally. When only one exothermic reaction is taking place adiabatically, the temperature will rise continually since the reaction is releasing heat, and that heat is not being removed. Similarly, when only one endothermic reaction takes place adiabatically, the temperature will drop continually. When a reactor operates isothermally, the temperature does not change as the reaction proceeds. When a reactor is neither adiabatic nor isothermal, qualitative analysis can be more difficult with greater uncertainty in the results.

When a reactor operates adiabatically or isothermally with only one or two reactions taking place, the shape of plots of concentration, temperature, rate, selectivity, etc. *versus* reaction time or space time can be predicted qualitatively as follows.

1. Determine the reactor operating procedure (e. g. isothermal or adiabatic).
2. Determine whether the reaction is typical or atypical, establishing the expected behavior as conditions change.
3. Draw sets of axes with the quantity of interest on the y-axis and reaction time or space time on the x-axis.
4. Plot a point on each y-axis representing the initial values of the quantities of interest. (The axes need not have a scale, and as such, plotted values only indicate whether the quantity is initially large, intermediate or small in value.)
5. Determine the initial slope of each graph by considering how the concentrations and temperature will change during a short interval of time and how those changes will affect the quantity of interest being plotted.
6. Determine the initial curvature of each graph by considering whether the changes in the next short interval of time will be greater than, equal to, or less than those in the first interval of time.
7. Determine whether the initial curvature eventually will result in the system approaching equilibrium (i. e. will each graph asymptotically approach a horizontal line?).
8. If the initial curvature will not lead to equilibrium, infer what must happen so that the system eventually will go to equilibrium (i. e. will there be an inflection point or a minimum/maximum?), and qualitatively explain what will cause these changes in the curvature.

In *Reaction Engineering Basics*, qualitative analyses of this type often will be used in the discussion of the results of a quantitative analysis. In that context, qualitative analysis can be used to answer the question, "Do these results make sense?" Additionally, performing a qualitative analysis after the quantitative analysis helps new reaction engineers develop a physical understanding of results that complements the mathematical understanding obtained in quantitative analysis. As a reaction engineer gains experience and develops the necessary skills and understanding, qualitative analysis can often provide insight and guidance before beginning an assignment. This is particularly true for design tasks, which are defined later in this chapter.

This chapter does not include examples of qualitative reactor analysis. Qualitative analysis of BSTRs is presented in [Chapter -@sec-4_bstr_qualitative_analysis], that of CSTRs in [Chapter @sec-4_cstr_qualitative_analysis], and of PFRs in [Chapter -@sec-4_pfr_qualitative_analysis].

## Quantitative Reactor Analysis

Models for the quantitative analysis of reactors were introduced in @sec-3_react_eng_models. The reactor design equations establish a quantitative relationship between the reactor inputs, the reactor outputs, and the reactor/process parameters. In any reactor modeling assignment, the reaction engineer is given values for some of the inputs, outputs and parameters and tasked with determining the values of the others. The reactor design equations can be used to accomplish four kinds of tasks: response, optimization, design, and parameter estimation. The difference between these tasks is found not in the equations themselves, but in how they are used. Examples of these tasks are deferred to later chapters, but they are defined here.

### Common Reaction Engineering Tasks

**Reactor response tasks**, as defined here, are the most straightforward of the four tasks. In a reactor response assignment the reaction engineer is provided with a sufficient number of reactor variables to allow calculation of all of the quantities of interest. Generally there is a single, correct answer to a reactor response assignment.

Sometimes a reactor response assignment will ask for a graph where a quantity of interest is plotted *versus* some other reactor variable. This is still a reactor response task. The only difference is that the reactor design equations are solved multiple times to generate the data to be plotted. Each time the reactor design equations are solved, there is a single, correct answer, and consequently, there is a single correct graph that completes the task.

In **optimization tasks** the number of reactor variables that are specified or known is not sufficient to allow the reaction engineer to solve the reactor design equations and calculate the quantities of interest. The simplest example would task the engineer to maximize (or minimize) a quantity of interest (the target) with respect to some other reactor variable (the adjusted variable). Neither the value of the target nor the value of the adjusted variable are known. In lieu of knowing the actual value of the adjusted variable, the reaction engineer instead knows that it is the value that maximumizes the target. Typically the engineer is tasked to find both the maximum value of the target and the corresponding value of the adjusted variable. Again, there is a single correct answer to a reactor optimization assignment.

Knowing that the reactor design equations will be solved numerically, there are three ways the reaction engineer could approach an optimization task. In the first two a range of values of the adjusted variable would be selected and the design equations would be solved repeatedly to find the value of the target corresponding to each value of the adjusted variable. In one approach, a table is generated with one column for the target and one column for the adjusted variable. The column for the target would be scanned to identify the maximum value. The corresponding value of the adjusted variable is found in the other column in the same row.

The second second approach differs in that instead of tabulating the results from solving the reactor design equations, they are plotted. The maximum in the graph is identified and the maximum value of the target and the corresponding value of the adjusted variable are read from the graph. In both of these approaches, it is possible that a maximum will not be present. In that case, the range of values of the adjusted variable must be increased until a maximum is observed. Once a maximum is observed, the precision of the results can be improved by adding additional values of the adjusted variable between the two points that bracket the maximum.

Many software packages include a function (an optimizer) that performs optimization, that is finds a maximum or minimum. The third approach involves using such an optimizer. In this case, the numerical implementation of the solution would entail writing a reactor model function that receives the adjusted variable as an argument and returns the corresponding quantity of interest. That reactor model function would then be passed to the optimizer. Typically an initial guess for the optimum value of the adjusted variable would also need to be provided.

Optimization tasks can be much more complicated than simply maximizing a quantity of interest with respect to another reactor variable. In addition to specifying multiple adjusted variables, the assignment also could impose constraints on the values of one or more reactor variables (not just the adjusted variables). Constraints are conditions that must be obeyed. An example of a constraint would be that the temperature of the heat exchange fluid cannot exceed some specified value because it would boil or decompose above that temperature. Again, there are software packages that will perform constrained, multi-variable optimization.

**Reactor design tasks** are the most complicated of the tasks considered here. At the same time they can be intellectually stimulating, affording the reaction engineer an opportunity to be creative. A reactor design assignment does not provide sufficient information to solve the reactor design equations. The reaction engineer must choose values for the missing reactor variables. In more extreme cases, the assignment may provide little more than the reagents that are available and the products that are to be produced. The type of reactor to use and how to operate it may be among the choices the reaction engineer needs to make.

Design tasks almost always involve an optimization sub-task. The quantity that needs to be maximized is typically financial in nature. The goal is to maximize the rate of making profit subject to technical, regulatory, and financial constraints. Design at this level is typically taught in chemical engineering courses on plant design, and the system being optimized is typically an entire process, not just an isolated reactor.

That level of design task is well beyond the scope of *Reaction Engineering Basics*. However, highly simplified design tasks are presented herein. In general there are reactor variables that are related to the economics of an overall process. For example, the cost of operating a process may scale with the temperature of that process, in which case minimizing the temperature minimizes the operating cost. In general, there is not a single correct solution to a reactor design assignment. Design tasks are inherently “open-ended,” and multiple solutions are possible and acceptable.

**Parameter estimation tasks** are inherently different from the three types of tasks described above, but they do use the same reactor design equations and the same solution steps. Briefly, a parameter estimation task involves generating data using a reactor and then using a model for the reactor to estimate the values of parameters appearing in a rate expression, or for non-ideal reactors, in the reactor model. Parameter estimation tasks are not considered in this section of *Reaction Engineering Basics*, but in Chapters [-@sec-6_kin_data_gen] through [-@sec-6_pfr_data_analysis].