# Generation and Analysis of Kinetics Data {#sec-kin-data-gen}

If the rate of a reaction has been studied previously, an expression for the rate of that reaction may be available. When a rate expression is not available, it is necessary to develop one. In this situation, the mathematical form of the rate expression is not known. Whatever rate expression is eventually developed will contain kinetics parameters that also are unknown. Theory alone cannot provide the mathematical form of the rate expression nor the values of the kinetics parameters that appear in it. For this reason, kinetics data are needed to develop a rate expression.

Reaction rates depend upon temperature, pressure and composition. Temperature can be measured using thermometers or thermocouples. Pressure can be measured using manometers or a wide variety of pressure gauges. Fluid composition can be measured using gas chromatography, mass spectrometry or many other instruments. The same is not true for reaction rates. There isn't a meter, gauge, or instrument that one can put in or attach to a chemical reactor to measure the rate of the reaction or reactions going on within it. 

Since rates cannot be measured directly, changes in composition (or something related to composition) that occur in chemical reactors are measured instead. Those changes are measured experimentally at different reactor temperatures, pressures and compositions, resulting in a set of experimental kinetics data. Three different approaches can be used to analyze those data and develop a rate expression. This brief chapter considers the design of kinetics experiments and presents an overview of the three approaches that can be used to analyze the data generated in those experiments. Before doing so, it is useful to recall the process used to develop rate expressions that was presented in @sec-rates-rate-express.

## Procedure for Developing a Rate Expression

The development of a rate expression for a reaction begins by postulating its mathematical form. As discussed in @sec-rates-rate-express and @sec-mechanisms, the form might be chosen empirically, theoretically or mechanistically. Then a reactor must be chosen for use in kinetics experiments. Chapters [-@sec-bstr-data-analysis], [-@sec-cstr-data-analysis], and [-@sec-pfr-data-analysis] discuss the use of ideal BSTRs, CSTRs, and PFRs, respectively, in the development of rate expressions.

Once a rate expression has been proposed and a reactor has been selected, kinetics experiments can be designed and performed. The resulting experimental data then are used to find the best values for the kinetics parameters appearing in the proposed rate expression and to assess its accuracy. This activity is known as parameter estimation. Parameter estimation requires a model of the reactor that predicts the experimental results for all of the experiments. During parameter estimation, the values of the unknown kinetics parameters are adjusted so as to minimize the differences between the experimental results and those predicted by the model. Parameter estimation is sometimes also referred to as least-squares fitting, curve fitting, or fitting the model to the experimental data.

In addition to the estimates for the values of the kinetics parameters, the software used for parameter estimation will provide statistical measures that can be used to assess the accuracy of the resulting model. Those can be combined with graphical procedures (see [Appendix -@sec-parameter-est]), leading to a recommendation to accept the rate expression, to gather more experimental data and re-assess the rate expression, or to reject the rate expression.

## Design of Kinetics Experiments

The development of a rate expression for a reaction is usually preceded by some preliminary experimental work. That work establishes a range of temperature, pressure and composition that is suitable and appropriate for running the reaction. It may also indicate the reversibility of the reaction being studied The purpose of kinetics experiments is to generate experimental data that span that range of temperature, pressure and composition with sufficient resolution to capture how temperature, pressure, and the reagent concentrations affect the rate. (This chapter and the parts of subsequent chapters discussing experimental design will use the concentrations of the reagents as the measure of composition. It should be noted that for gas-phase reactions, the partial pressures of the reagents could be used instead.)

The nature of kinetics experiments is relatively straightforward. Selected reactor inputs are adjusted to pre-determined values and then an output from the reactor, also called the response, is measured. The first step in designing kinetics experiments is to decide which reactor inputs to adjust so that the experiments will span the desired range of temperature, pressure and reagent concentrations. The inputs that will be adjusted for each of the experiments can be referred to as factors.

The first factor to consider is the temperature. It is preferrable to use blocks of experiments where all of the experiments in each block are run at the same temperature and each block uses a different temperature. The reason is that typically reaction rates are much more sensitive to temperature than to reagent concentrations or partial pressures. The Arrhenius expression indicates an exponential effect of inverse temperature upon the rate. This is much stronger than the concentration dependence found in most rate expressions. Consequently, if concentration and temperature are varied simultaneously, the strong temperature effect may mask weaker concentration effects. The use of temperature blocks allows the composition variables within a block to be varied while the temperature is held constant. Additionally, the analysis of the data is somewhat simplified when temperature blocks are used.

In order to do experiments using temperature blocks, the reactor must operate isothermally. *Reaction Engineering Basics* only considers the analysis of kinetics data that were generated in an isothermal reactor. Additionally, only systems where a single reaction is taking place and a single reactor response is measured. This is sufficient to illustrate the process of developing a rate expression. Systems with more than one reaction taking place require multiple responses, and when done properly, the statistics of parameter estimation using multiple response data are more complicated. Readers interested in the analysis of multiple response kinetics data should consult an intermediate level reaction enginering or statistics textbook.

The second factor to consider is the pressure. For liquid-phase reactions the pressure often does not affect the rate and does not need to be adjusted. For gas-phase reactions it is straightforward to adjust the system pressure from experiment to experiment. Many different reactor inputs can affect the composition of the reacting fluid in the reactor. A list of possible factors include the feed composition, the feed flow rate, the space time, the input molar flow rates of individual reagents, etc.

Once a set of factors has been identified, that is once it has been decided which reactor inputs will be adjusted from experiment to experiment, it is necessary to identify the response that will be used. The response should be some easily measurable quantity that is related to the change in the composition from input to output. Examples include the outlet concentration of a reagent, the conversion of a reactant, the outlet molar amount or flow rate of a reactant or product, the outlet mole fraction of a reagent, etc.

Once the response and the adjusted inputs have been chosen, a set of "levels" must be chosen for each of the inputs. These are the values to which the inputs will be adjusted during the experiments. For example, it might be decided to use four temperature levels of 100, 110, 120 and 130 °C. That means that a set of experiments will be conducted at 100 °C, another set at 110 °C, and so on. Things that must be considered when choosing the levels for each input include the time that is available for doing the experiments and the cost of the experiments (purchase of reagents, salaries for technicians performing the experiments, etc.). Sometimes there can be a trade off between the resolution of the experimental data and the time/cost of the experiments. A design with more levels should capture the effect of changing an adjusted input more fully, but it will require more experimental time and cost more. A design with fewer levels will reduce the experimental time required and cost less, but it may not fully capture the effects of changing temperature, pressure, and reagent concentrations.

The kinetics experiments entail adjusting each of the inputs to one of its levels, measuring the corresponding response, adjusting one or more of the inputs to a different one of it levels, measuring the response, etc. The final decision involved which combinations of levels to use to generate the kinetics data. There are a few ways to do this. A common one, sometimes called a full factorial design simply includes every possible combination of the input levels. [Example -@sec-example_7_1] illustrates factorial design of kinetics experiments.

## Analysis of Kinetics Data

When the reactor operates isothermally and an experimental design with a limited number of temperature levels is used, the kinetics data can be analyzed in two phases. First the data are grouped in blocks where each block includes *all* of the experiments at one of the levels. In the first phase of the analysis, each of these blocks is analyzed separately to assess how accurately the proposed rate expression describes the effect of composition and pressure on the reaction rate. Since all of the experiments in each data block are at a single temperature, the pre-exponential factor and activation energy cannot be estimated. Instead the rate coefficient is treated as the a single kinetics parameter. The same is true of any other kinetics parameters that may vary with temperature. Once the first phase of the analysis is completed, that is, once all of the blocks of data have been analyzed, the Arrhenius expression is fit to the resulting rate coefficients to assess the accuracy of the proposed rate expression in describing the temperature dependence of the rate. Typically the linearized form of the Arrhenius expression is used .

It was noted in @sec-modeling-ideal-reactors that when a reactor operates isothermally at a known temperature, the mole balance design equations can be solved separately from the energy and momentum balance design equations. In fact, when only one reaction is taking place, as is always the case in *Reaction Engineering Basics*, it is possible to use a single mole balance on one reactant or product. The amounts of the other reagents are related to that one reactant or product through the reaction stoichiometry. Three different ways of analyzing each block of experimental data are considered next. 

### Using a Response Function

In this approach to kinetics data analysis, the reactor model is used to write a **response function**. The response function is just that, a computer function or subroutine. It is passed the adjusted inputs data from the experiments as an argument. It is also passed a set of values for the kinetics parameters in the rate expression. Using that information, it calculates the model-predicted responses for all of the experiments and returns them.

In this approach either the full set of mole balances or a single mole balance can be used as the reactor model. **This approach can *always* be used** and it does not introduce any approximations that can affect the accuracy of the results. For this reason, this is the approach used in most examples in *Reaction Engineering Basics*.

Once the response function has been written, it is passed to parameter estimation software along with the adjusted inputs data and the experimental responses data. (In addition, most parameter estimation software also requires that a guess for the values of the kinetics parameters be provided. A number of different computer programs can be used for parameter estimation.) [Appendix -@sec-parameter-est] describes how parameter estimation software works. In essence, it finds values for the kinetics parameters that minimize the difference between the responses predicted by the model and the responses that were measured experimentally.

Typically the parameter estimation software yields (a) the best estimates for the values of the kinetics parameters, (b) some measure of the uncertainty in the parameter estimates, e. g. a 95% confidence interval, and (c) the coefficient of determination, $R^2$.

### Analysis Using a Linearized Reactor Model

In the second approach to analyzing a block of experimental data, a single mole balance on one of the reactants or products is used to model the reactor. If the mole balance is an IVODE, it must be solved analytically in order to use this approach. The model then must be rearranged so that by defining new variables it becomes a linear equation like that shown in @eq-linear_equation, where $y$ and the $x_i$ represent the new variables. The kinetics parameters *do not* appear in the defining equations for the new variables. Additionally, a *unique* combination of the kinetics parameters must appear in the defining equation for each slope, $m_i$, and the intercept, $b$. That means that if there is only one kinetics parameter, the linearized reactor model is of the form, $y=mx$, and if there are two kinetics parameters it has the form $y=mx+b$. Generally, when there are $n+1$ kinetics parameters, the form will be as shown in @eq-linear_equation.

$$
y = m_1x_1 + m_2x_2 + \cdots + m_nx_n + b
$$ {#eq-linear_equation}

The adjusted inputs and the measured responses are then used to calculate the values of the new variables, $y$ and $x_1$ through $x_n$, for each experiment. @eq-linear_equation is then fit to the new variables, e. g. using linear least-squares. If the linearized reactor model has the form $y=mx$ or $y=mx+b$, a spreadsheet can be used to calculate the values of $y$ and $x$, plot the results and fit a linear equation to them. Most spreadsheet programs can be used to estimates for $m$ and $b$, and the coefficient of determination, $R^2$ by adding a trendline to a plot of $y$ *vs*. $x$ and displaying the equation for the trendline on the plot. Additional spreadsheet functions are often available for calculating the uncertainties in the slope and intercept.

If the model is accurate, in other words, if the rate expression is accurate, the value of $R^2$ will be close to 1 and the plotted points will lie close to the fitted line with no systematic trends in their deviations from the line. Uncertainties in the slope and intercept should be small compared to the values of the slope and intercept.

If the model has two or more $x_i$ variables, the results from linear least squares fitting still should provide estimates for the best values of each slope and the intecept, some measure of the uncertainly in the slopes and the intercept, and the coefficient of determination, $R^2$.

It is *not always possible* to analytically solve mole balances that are IVODEs or to linearize the reactor model equation. As such, **this approach cannot always be used**. When it can be used, it offers the advantages of using a spreadsheet to analyze the data and not requiring a guess for the values of the parameters.

### Using an Approximate Reactor Model (Differential Analysis)

The third approach to the analysis of a block of expeimental kinetics data can only be used when the data are from a BSTR or PFR. The mole balances for a BSTR or a steady-state PFR are initial value ODEs (IVODEs). In this approach, a single mole balance on one of the reactants or products again is used. In contrast to the first two approaches that IVODE is not solved directly. Instead, the value of the derivative is approximated, for example using finite differences (see [Appendix -@sec-pre-knowledge]). The resulting approximate mole balance is then fit to the experimental data.

There isn't any real advantage to this approach today, because it is easy to solve the IVODE form of the mole balance numerically using a computer. In the past, however, computers were not as readily available and it was often necessary to solve the mole balance analytically. Generally it is much easier to analytically solve the approximate mole balance than the IVODE mole balance. Under those circumstances, this approach did offer an advantage, but it is not as accurate as solving the IVODE form of the mole balance. Today it is sometimes used for a quick, preliminary analysis of kinetics data, but **the other approaches described in this section are preferred**.

### Analysis of Temperature Dependence

At the end of the first phase of analysis, values for each of the kinetics parameters will have been estimated at every temperature level that was studied. The second phase of the analysis involves modeling the temperature dependence of each of those parameters. This is relatively easy for rate coefficients and for unknown equilibrium constants that are being treated like kinetics parameters. Both of those kinds of parameters are expected to exhibit Arrhenius-like temperature dependence, @eq-arrhenius and @eq-equil_like_arrhenius. [Example -@sec-example_4_4] illustrates the determination of the pre-exponential factor, $k_{0,j}$, and activation energy, $E_j$, using $k$ *vs*. $T$ data. The determination of $K_0,j$ and $\Delta H^0_j$ in @eq-equil_like_arrhenius is analogous.

Modeling the temperature dependence of other types of kinetics parameters such as the exponents in a power-law rate expression is more difficult. Power-law rate expressions are empirical, so there isn't any theory that predicts how the exponents should vary with temperature. Plotting them *versus* temperature may show that they can be treated as constant, vary linearly or exponentially, etc. If an expression for their temperature dependence cannot be developed, it may be necessary to leave them in tabular form and interpolate to find values at temperatures other than the levels studied in the kinetics experiments.

## Assessment of Accuracy and Recommendations

The next step after fitting the reactor model to the data is **assessment of the accuracy of the resulting model**. For linear models with two parameters, this was discussed in @sec-rates-rate-express and illustrated in [Example -@sec-example_4_4]. Briefly, linear least squares can be used find the parameter estimates and confidence intervals and the coefficient of determination, $R^2$. A model plot can then be constructed. The following criteria suggest that the model is accurate.

* In the model plot, the experimental data points will scatter randomly about the line for the predicted results. The deviations from the line will be small and there will not be any systematic deviations about the line.
* The coefficient of determination, $R^2$, will be close to 1.0
* The uncertainty in each parameter will be small relative to its value.

For linear models with more than two parameters and when a response function is used, the estimated parameters can be used to calculate the model-predicted response for each experimental data point. A parity plot of the experimental responses *vs*. the model-predicted responses can be constructed. The difference between each experimental response and the corresponding model-predicted response, i. e. the residuals, can be calculated and plotted against each of the adjusted input variables to get a set of residuals plots. These plots, together with the results from parameter estimation are then used to assess the accuracy of the model. The following criteria suggest that the model is accurate.

* The coefficient of determination, $R^2$, is close to 1.
* The uncertainty in each parameter estimate is small compared to the estimate.
* The points in the parity plot are all close to a diagonal line ($y_{\text{expt}} = y_{\text{model}}$).
* In each residuals plot, the points scatter randomly about zero (the horizontal axis), and no systematic deviations are apparent.

The final step in kinetics data analysis involves **making a recommendation** to accept, reassess with additional data, or reject the rate expression. The intended use of the rate expression, and more importantly the potential consequences of accepting an inaccurate rate expression, can affect the criteria used in making this recommendation. That is, if accepting an inaccurate rate expression might result in severe personal injury, significant property damage or catastrophic financial loss, much more stringent criteria would likely be used than if the model was only going to be used to size a small laboratory reactor.

## Example

### Design of Kinetics Experiments {#sec-example_7_1}

{{< include ../RE_Basics_Examples/reb_7_1/problem_statement.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

I am asked to design kinetics experiments, so I need to decide which variables will be adjusted in the experiments. I further need to decide how many levels to use for each adjusted variable and what those levels should be. The problem states that the rate expression developed using these data will be used to design a new process, so I want to be sure to generate a sizeable data set that spans the expected ranges of the adjusted variables and also captures the effects of each of them upon the response. Based upon the information presented in the problem statement, the experimental response here will be the concentration of A.

Reaction rates can be affected by the temperature and the concentration of each reagent present. Here the problem states that the rate is not affected by the concentration of Z, so the temperature and the concentration of A should vary from one experiment to the next. The reactor is isothermal, so the temperature can be adjusted directly in the experiments. The concentration of A will change as the reaction proceeds. This suggests two ways to vary the concentration of A from experiment to experiment. The first is to adjust the initial concentration of A and the second is to adjust the time at which the response is measured. Longer times will lead to smaller concentrations of A because at longer times more of the A will have reacted. I will use both the initial concentration of A and the reaction time as adjusted variables.

Next I need to decide how many levels to use for each adjusted variable and what those levels should be. Normally I would use levels that span a slightly wider range than the range where the rate expression will be used. Here, however, I'm told that the rate is too low below 65 °C and undesireable reactions occur above 90 °C, so I will choose levels that just span that range. The range only spans 25 °C, so four temperature levels seem reasonable, as does spacing them equally across the range.

I want to span a range of concentrations that is slightly wider than the expected range where the rate expression will be used. Three initial concentration levels of 0.5, 1.0, and 1.5 M will do so. Then, in order to ensure that the data are sensitive to the effect of the concentration of A, I will use six levels of reaction time. Noting that at 80 °C it takes 30 min for the reaction to go to completion, spacing the reaction times 5 minutes apart will lead to samples that span a wide range of conversions.

:::

**Experimental Design**

Three reactor inputs will be adjusted in the experiments: the temperature, $T$, the initial concentration of A, $C_{A,0}$, and the reaction time, $t$. The temperature levels will be 65, 73, 82, and 90 °C; the initial concentration levels will be 0.5, 1.0, and 1.5 M; the reaction time levels will be 5, 10, 15, 20, 25, and 30 min. All possible combinations of these levels will be studied giving a total of 72 experimental data points.

It will not be necessary to perform 72 experiments, however. Using a reactor at 65 °C with an initial concentration of A equal to 0.5 M, six responses can be recorded in the experiment. The number of experiments needed to record all 72 responses is 12. The initial conditions for those 12 experiments are shown in @tbl-example_7_1. Each experiment in the table will yield responses at all six reaction time levels.

| Experiment | T (°C) | C~A,0~ (M) |
|:------:|:-------:|:----------:|
| 1 | 65 | 0.5 |
| 2 | 65 | 1.0 |
| 3 | 65 | 1.5 |
| 4 | 73 | 0.5 |
| 5 | 73 | 1.0 |
| 6 | 73 | 1.5 |
| 7 | 82 | 0.5 |
| 8 | 82 | 1.0 |
| 9 | 82 | 1.5 |
| 10 | 90 | 0.5 |
| 11 | 90 | 1.0 |
| 12 | 90 | 1.5 |

: Initial conditions for kinetics experiments. {#tbl-example_7_1 tbl-colwidths="[30,35,35]"}

:::{.callout-note collapse="false"}
## Note

Some readers might have difficulty with this problem because it relies upon an understanding of how BSTR kinetics experiments are performed and the data they generate, and that information has not been presented yet. BSTR kinetics experiments are considered in @sec-bstr-data-analysis. The important aspects of this example are that it was first necessary to decide which reactor model input variables to adjust, and then it was necessary to decide how many levels of each variable to use and what those levels should be. After doing that, the experimental design simply involves performing an experiment at every combination of the adjusted variable levels.

:::

## Symbols Used in @sec-kin-data-gen

| Symbol | Meaning |
|:-------|:--------|
| $b$ | The intercept, a unique combination of the kinetics parameters, resulting from the linearization of the reactor model. |
| $m_i$ | A slope, some unique combination of the kinetics parameters resulting from the linearization of the reactor model. |
| $x_i$ | Some combination of the experimentally adjusted inputs and the experimental response defined so that the resulting reactor model is a linear equation. |
| $y_{\text{expt}}$ | Experimentally measured response. |
| $y$ | Some combination of the experimentally adjusted inputs and the experimental response defined so that the resulting reactor model is a linear equation. |
| $y_{\text{model}}$ | Model-predicted response. |
| $R^2$ | Coefficient of determination. |

: {tbl-colwidths="[20,80]"}