# CSTR Analysis {#sec-4_cstr_analysis}

Intro, last 3 chapters were non-contin, now start cont with CSTR; properties, adv, disadv, operation, qualit, response and optim

## CSTR Characteristics

similarities and differences between CSTRs and BSTR/SBSTRs, critical assumptions

advantages

disadvantages

## CSTR Operation

start-up, steady-state, shut-down

transient vs. steady state

## Qualitative Analysis of Steady-State Reaction in a CSTR

## CSTR Design Equations

complete

simplifications - ss

simplifications - other

same 4 step analysis approach: summarize, formulate, implement, report/discuss

## Steady-State Multiplicity

description

heat gen vs. heat abs plot

## Steady-State Stability

## Examples

### Response of a SS CSTR {#sec-example_12_7_1}

{{< include ../RE_Basics_Examples/reb_12_7_1/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_1/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: $k_{0,1}$ = 10.2 gal mol^-1^ min^-1^, $k_{0,2}$ = 17.0 gal mol^-1^ min^-1^, $E_1$ = 15.3 kJ mol^-1^, $E_2$ = 23.7 kJ mol^-1^, $C_{A,in}$ = 10 mol gal^-1^, $C_{B,in}$ = 12 mol gal^-1^, $T_{in}$ = 350 K, $V$ = 25 gal, $\dot{V}_{in}$ = 12.5 gal min^-1^, $\Delta H_1 \big\vert_{298 \text{ K}}$ =  -12.0 kJ mol^-1^, $\Delta H_2 \big\vert_{298 \text{ K}}$ = -21.3 kJ mol^-1^, $\hat{C}_{p,A}$ = 85 J mol^-1^ K^-1^, $\hat{C}_{p,B}$ = 125 J mol^-1^ K^-1^, $\hat{C}_{p,D}$ = 200 J mol^-1^ K^-1^, and $\hat{C}_{p,U}$ = 170 J mol^-1^ K^-1^.

**Reactor System**: Adiabatic, steady-state CSTR 

**Quantities of Interest**: $f_A$, $S_{D/U}$, and $T$

#### Mathematical Formulation of the Solution

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
generate design equations as residuals
:::

**Reactor Design Equations**

Mole balance design equations for A, B, D, and U are presented in equations (5) through (8), and an energy balance on the reacting fluid is given in equation (9).

$$
0 = \dot n_{A,in} - \dot n_A + V \left( -r_1 - r_2\right)\tag{5}
$$

$$
0 = \dot n_{B,in} - \dot n_B + V \left( -r_1 - r_2\right)\tag{6}
$$

$$
0 = - \dot n_D + V r_1\tag{7}
$$

$$
0 = - \dot n_U + V r_2\tag{8}
$$

$$
0 = \left( \dot{n}_{A,in}\hat C_{p,A} + \dot{n}_{B,in}\hat C_{p,B}\right) \left(T - T_{in}\right)  + V\left( r_1 \Delta H_1 + r_2 \Delta H_2\right)\tag{9}
$$

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point

In order to solve the ATEs numerically I'll need to do two things: calculate the values of the residuals for each guess and provide an initial guess.

Starting with evaluating the residuals, I'll need to evaluate them each time a new guess for the solution is generated. At that point, guesses for each of the unknowns will be available along with the given and known constants. I will need to calculate any other quantities that appear in the residuals expressions.
:::

**Ancillary Equations for Evaluating the Residuals**

$$
\dot n_{A,in} = \dot C_{A,in} \dot{V}_{in} \tag{10}
$$

$$
\dot n_{B,in} = \dot C_{B,in} \dot{V}_{in} \tag{11}
$$

$$
k_1 = k_{0,1} \exp{\frac{-E_1}{RT}}\tag{12}
$$

$$
k_2 = k_{0,2} \exp{\frac{-E_2}{RT}}\tag{13}
$$

$$
C_A = \frac{\dot{n}_A}{\dot{V}_{in}}\tag{14}
$$

$$
C_B = \frac{\dot{n}_B}{\dot{V}_{in}}\tag{15}
$$

$$
\Delta H_1 = \Delta H_1 \big\vert_{298 \text{ K}} + \left( \hat{C}_{p,D} - \hat{C}_{p,A} - \hat{C}_{p,B} \right)\left(T - 298\right) \tag{16}
$$

$$
\Delta H_2 = \Delta H_2 \big\vert_{298 \text{ K}} + \left( \hat{C}_{p,U} - \hat{C}_{p,A} - \hat{C}_{p,B} \right)\left(T - 298\right) \tag{17}
$$

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
When I solve the ATEs numerically, I'll also need to provide an initial guess for the solution....
:::

**Ancillary Equations for Calculating the Initial Guess**

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
develop equations needed to calculate quantities of interest
:::

**Ancillary Equations for Calculating the Quantities of Interest**

Solving the reactor design equations yields [list unknowns]. 

$$
f_A = \frac{\dot{n}_{A,in} - \dot{n}_A}{\dot{n}_{A,in}} \tag{16}
$$

$$
S_{D/U} = \frac{\dot{n}_D}{\dot{n}_U} \tag{17}
$$

**Calculations Summary**

1. Substitute given and known constants into all equations.
2. When it is necessary to evaluate the residuals
	a. [list of variables] will be available.
	b. 
3. When it is necessary to calculate the quantities of interest, [list]
	a. [list of variables] will be available.
	b. 

#### Numerical implementation of the Solution

1. Make the given and known constants available for use in all functions.
2. Write a residuals function that
	a. receives guess values for [list of variable],
	b. evaluates the residuals as described in step 2 of the calculations summary, and
	c. returns the values of the residuals.
3. Write a reactor model function that
	a. ...
	b. defines an initial guess for the unknowns, [list of variables],
	c. gets a set of values of the unknowns that solve the ATEs by calling an ATE solver and passing the following information to it
		i. the initial guess and
		ii. the name of the residuals function from step 2 above,
	d, checks that the solver converged, and
	e. returns the values returned by the ATE solver.
6. Perform the analysis by
	a. ...
	b. getting [list of variables] by calling the reactor model function from step 3 above,
	c. calculates the quantities of interest as described in step 3 of the calculations summary,
	d. ....

#### Results and Discussion

The calculations were performed as described above.


<!--
::: {.callout-note appearance="simple"}
## [SC]{style="color:blue"}o[RE]{style="color:red"} Connection
Videos showing how to complete this assignment using either Matlab or Python, along with the Matlab and Python code, are available in [SCoRE](URL).
:::
-->


### Selectivity in a SS CSTR{#sec-example_12_7_2}

{{< include ../RE_Basics_Examples/reb_12_7_2/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_2/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: 

**Reactor System**: 

**Quantities of Interest**: 


### Cell Growth and Washout in a CSTR{#sec-example_12_7_3}

{{< include ../RE_Basics_Examples/reb_12_7_3/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_3/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: 

**Reactor System**: 

**Quantities of Interest**: 


### Multiple SSs in a CSTR{#sec-example_12_7_4}

{{< include ../RE_Basics_Examples/reb_12_7_4/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_4/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: 

**Reactor System**: 

**Quantities of Interest**: 


### Start-Up of a CSTR{#sec-example_12_7_5}

{{< include ../RE_Basics_Examples/reb_12_7_5/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_5/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: 

**Reactor System**: 

**Quantities of Interest**: 


### Transient Responses in a CSTR{#sec-example_12_7_6}

{{< include ../RE_Basics_Examples/reb_12_7_6/narrative.qmd >}}

{{< include ../RE_Basics_Examples/reb_12_7_6/equations.qmd >}}

---

:::{.callout-tip collapse="true"}
## Click Here to See What an Expert Might be Thinking at this Point
identify problem type, describe variable naming
:::

#### Assignment Summary

**Given and Known Constants**: 

**Reactor System**: 

**Quantities of Interest**: 


## Symbols Used in [Chapter -@sec-4_cstr_analysis]

