# Design of Continuous Reactors {#sec-4_continuous_design}

Effectively, this chapter is a continuation of @sec-4_non_continuous_design. That chapter only considered the design of non-continuous reactor processes. It presented important design principles and described different levels of design before identifying preliminary design as being an appropriate level of design for the purposes of *Reaction Engineering Basics*.

Briefly, preliminary design begins with an underspecified reactor process to which the design engineer adds sufficient specifications to enable modeling and analysis of the process. It uses reactor performance metrics as indicators of process economics. Often a single key reactor performance metric is minimized or maximized with respect to one or more reactor process parameters to be specified by the design engineer. Some process parameters or reactor outputs may be subject to constraints imposed by safety, operability, or regulatory considerations.

All of the discussion in @sec-4_non_continuous_design applies equally in the present chapter, but it won't be duplicated here. Chapters 12 and 13 illustrated the modeling and analysis of two types of continuous reactors, namely the CSTR and the PFR. With that knowledge as background, this chapter considers two additional aspects of preliminary design. Specifically this chapter builds upon @sec-4_non_continuous_design by adding sections on the choice between non-continuous and continuous processes and on the choice bewteen CSTRs and PFRs in continuous processes.

## The Choice Between Non-Continuous and Continuous Processes

Most of the criteria used when choosing between a continuous process and a non-continuus process have already been mentioned in previous chapters. This section simply gathers them together in one place. The most important criterion, perhaps, is the anticipated amount of the product to be produced anually. If the product is a commodity that is going to be produced and sold in large volumes, a continuous process is most likely preferred. The profit margin on commodity chemicals is often small, and production costs need to be minimized because they cannot be passed on to the consumer easily. Generally the additional labor and logistics of a non-continuous process lead to a larger production cost per pound of product compared to a continuous process.

In contrast, when a small annual production is anticipated, but the profit margin is large, a non-continuous process may be preferred. A non-continuous process allows production of value-added products on demand. This can reduce the costs associated with storing the products during seasons of low demand while allowing for ramping up production when demand is greater.

Another important factor is the number of different reactor operating conditions required to produce the product. If the "recipe" for making the product involves multiple reactive steps at different temperatures and of different durations, a non-continuous process will likely be preferred. For example if the reactive processing requires holding at one temperature for some period of time, then adding a reagent and holding at a different temperature for a different amount of time, a non-continuous process would probably be preferred. It is simply easier to follow this kind of recipe using a non-continuous process.

Similarly, if the reaction must be run at conditions where the reaction rate is very low, a non-continuous process may be the better choice. For processes where the rate is much faster, where additional reagents do not need to be added part way through the reaction process, and where multiple reaction temperatures are not required, a continuous process can be advantageous.

Flexibility is another consideration when deciding between a continuous and a non-continuous process. A non-continuous process may be more suitable if the same reactor will be used to produce different products at different times. That is, it may be more challenging to use the same feed and product piping to conduct one chemical processes part of the time and a different reaction at other times in a continuous reactor system. Generally continuous processes are best when they can be started up and allowed to operate at steady state for extended periods of time.

In the final analysis, though, none of these criteria are definitive. Ultimately the choice between using a non-continuous process or a continuous process comes down to economics.

## The Choice Between CSTRs and PFRs in Continuous Processes

In some instances the choice between a CSTR and a PFR is an easy one, but under other circumstances it is not clear at all. The most significant difference between the two reactor types is how the temperature and composition vary during the reaction time. In continuous reactors, the reaction time is the length of time that the reacting fluid spends in the reactor.

The choice between a CSTR and a PFR is easiest when only one reaction is taking place and the reactor is **isothermal**. For typical reaction kinetics a high rate is favored by large reactant concentrations and, if the reaction is reversible, by small product concentrations. In an isothermal CSTR the concentrations are the outlet values and they do not vary during the reaction time. The reactant concentrations are smaller than in the feed, the product concentrations are larger than in the feed, and the reaction rate does not change during the reaction time.

In an isothermal PFR the concentrations change monotonically during the reaction time. The reactant concentrations start at their feed values and decrease steadily to their outlet values during the reaction time. The product concentrations start at their feed values and increase steadily to their outlet values. Based on those variations the rate of a typical reaction decreases steadily during the reaction time in a PFR.

Comparing equal feeds at equal conversions, the rate will be constant during the reaction time in a CSTR. When comparing at equal conversions, the outlet composition from a PFR will equal the CSTR composition. Therefore rate in a PFR will become equal to the CSTR rate at the end of the reaction time. Except at the very end of the reaction time, the rate in the PFR will be greater than the rate in the CSTR, so a PFR volume smaller than the CSTR volume is needed to reach the same final conversion.

Comparing equal feeds at equal space times means the reaction times for the reactors are the same, but the conversions differ. Again, the CSTR rate will be constant during the reaction time. Because the initial rate in the PFR is higher, the PFR will reach the same conversion as the CSTR in less reaction time than the CSTR. the PFR fluid will continue to react for the remainder of the reaction time, so its final conversion will be greater than the CSTR conversion.

Thus the choice between a CSTR and a PFR for a slngle, isothermal reaction is quite straightforward, but few commercial reactors operate isothermally. When the reactors are **adiabatic**, the composition effects are the same as in isothermal reactors, but temperature effects must also be considered. In a CSTR, the temperature does not change during the reaction time. The temperature and composition in the CSTR are constant and equal to their outlet values.

The temperature will change during the reaction time in a PFR, and the effect of that change can either reinforce the effect of composition change or it can oppose it. If the reaction is **endothermic** the temperature decreases steadily during the reaction time. Taken alone, this change decreases the rate and so it reinforces the effect of decreasing reactant concentration. If the reaction is exothermic, the temperature increases during the reaction time. Taken alone, this increases the rate, so for an exothermic reaction the effect of changing temperature during the reaction time opposes the effect of composition. This results in three possible rate behaviors in an adiabatic PFR with an **exothermic** reaction.

* The rate increases steadily during the reaction time as would happen if the temperature effect was stronger than the composition effect over the reactor's entire conversion range.
* The rate increases, passes through a maximum, and then decreases during the reaction time as would happen if the temperature effect predominated at early reaction times and the concentration effect predominated at later reaction times.
* The rate decreases steadily during the reaction time as would happen if the concentration effect was stronger than the temperature effect over the reactor's entire conversion range. (As noted above, this rate behavior also occurs when the reaction is endothermic.)

Comparing equal feeds at equil conversions as above, the rate will not change during the reaction time in a CSTR, and because the conversions are equal, the rate in a PFR will become equal to the CSTR rate at the end of the PFR reaction time. If the rate in the PFR increases steadily during the reaction time (first rate behavior above) the required PFR volume will be larger than the CSTR. This is because the rate only become equal to the CSTR rate at the very end of the reaction time; prior to that the PFR rate is lower than the CSTR rate so the required volume is larger. Conversely, if the rate in the PFR decreases steadily (third rate behavior above) the required PFR volume will be smaller than the CSTR. If the PFR rate increases, passes through a maximum, and then decreases during the reaction time, the required PFR volume could be smaller or larger than the CSTR volume.

Comparing equal feeds at equil space times for a single reaction in adiabatic reactors, the rate again will not change during the reaction time in the CSTR. The reaction time in the PFR will equal the reaction time in the CSTR. If the PFR rate increases steadily during the reaction time, the conversion will be smaller in the PFR than in the CSTR. If the PFR rate decreases steadily during the reaction time, the conversion will be larger in the PFR than in the CSTR. Not surprisingly, if the PFR rate increases, passes through a maximum, and then decreases during the reaction time, the conversion in the PFR could be either larger or smaller than that in the CSTR.

Some reactors are neither isothermal nor adiabatic, and in these cases the variation of the rate during the reaction time will differ from the rate behaviors described above. When more than one reaction is taking place the selectivity may be just as important as the reaction rate. The effects of temperature and composition upon the selectivity may be different from their effects upon the rate. This can lead to trade-offs between conversion and selectivity.

In summary, for a single reaction in an isothermal reactor the choice between a CSTR and a PFR is straightforward. For single reactions in adiabatic reactors it is straighforward if the reaction is endothermic. When the reaction is exothermic it won't be known which of the three rate behaviors applies without performing at least a few preliminary calculations.

Furthermore, all of the preceding qualitative analysis assumed typical kinetics. For atypical kinetics (autocatalytic reactions, reactant-inhibitie reactions, etc.) a similar analysis can be used. As was found for typical kinetics, in some cases the choice between a CSTR and a PFR will be straightforward while in others it won't.

In the simplest of situations it may be possible to make a choice between a CSTR and a PFR on the basis of a qualitative analysis. In many other situations preliminary modeling of both reactor types may be needed to inform the choice of which reactor type to use. Finally, CSTRs are not well-suited to reactions that require a solid catalyst, in which case the use of a PFR is obvious.

## Examples

The example presented in @sec-4_non_continuous_design describes possible design strategies an engineer might use when tasked with designing a non-continuous reactor for an auto-catalytic reaction. It focuses more upon selecting a key metric (the reactor volume) and identifying the operating parameters that can be varied to minimize that metric than on choosing the type of reactor to use.

The examples presented here focus upon initially choosing to use a CSTR, to use a PFR, or to analyze both reactor types before choosing one of them. Once that choice is made, design strategies analogous to the one presented in [Example -@sec-example_11] can be developed for the chosen reactor type(s). As was the case in @sec-4_non_continuous_design, these examples describe one possible design strategy, but they do not include any analysis. The reader should have learned how to model and analyze CSTRs and PFRs in @sec-4_cstr_analysis and @sec-4_pfr_analysis.

As was true in @sec-4_non_continuous_design, the engineer's thinking is the essence of these examples, the usual "Click Here T\to See What an Expert Might be Thinking" callouts are not used.

### Preliminary Design of a Continuous Reactor for an Exothermic Autocatalytic Reaction {#sec-example_14_3_1}

**Background**: A chemical company is considering construction of a new plant to produce 15 million pounds of reagent Z per year. This will be the first time the company will produce Z. It is produced from reagent A in an irreversible, autocatalytic, exothermic reaction, equation (1). The rate expression is shown in equation (2) where the rate coefficient $k_2$ is much, much smaller than $k_1$. Kinetics and thermodynamic data are available for the system. The product, Z, must be at least 95% pure, and the reacting fluid temperature cannot exceed 115 °C. A small steam generator and a chilled water plant will be built to support the process. 

$$
A \rightarrow Z \tag{1}
$$

$$
r_1 = k_1C_AC_Z + k_2C_A \tag{2}
$$

**Assignment**: Perform a preliminary design for the reactor to be used in the new plant.

#### Design Strategy

The annual production is large, so the process will be continuous. There isn't an existing plant that I can use for reference, so I'll need to decide whether to use a CSTR or a PFR. Some qualitative reasoning may help me make that choice. 
If I use a CSTR, it will operate at the final conditions where the temperature will be as high as allowed and the composition will consist of 95% Z and 5% A. Both of these factors favor a high rate, and consequently a small volume. (The reaction is auto-catalytic, so the rate remians high despite a lower reactant concentration and higher product concentration.) If I use a PFR, near the inlet the composition will be almost all A and the temperature will be low. This will lead to a very low rate near the inlet, a lower average rate, and consequently a large reactor. Based on this reasoning, it seems clear that a CSTR should be used.

I'd like the reactor to be as small as possible which means I'd like the rate to be as large as possible. I can't exceed 115 °C, so to provide a margin of safety, I'll set the outlet temperature to be 100 °C. For the rate to be as large as possible, and knowing the conversion must equal 95%, that fixes the outlet composition and temperature. 

I'll assume two weeks of down time per year, which fixes the outlet flow rate of Z at 1.5 x 10^6^ lb per 50 weeks. I can convert that to a molar outlet flow rate, then, knowing the conversion, I can calculate the inlet molar flow rate of A. Then, knowing the rate and the inlet flow rates, I can calculate the reactor volume.

I'm not sure whether the heat of reaction is sufficiently high to operate adiabatically. I might need to add heat or I might need to remove it so that the outlet temperature is 100 °C. I'll need to calculate the necessary heat transfer area and exchange fluid temperature. I'll assume that steam and cooling water will be available at the same temperatures as in other plants the company operations for the purposes of this preliminary design. If the design proceeds to a larger scale, the design of the steam and chilled water plants will need to be integrated into the reactor design.

Since the reactor volume is essentially fixed by the specified production rate, the costs that scale with the reactor volume are also fixed. I expect that the steam and/or chilled water will be the next most significant contributors to the operating costs. If I need cooling, I can minimize the amount of coolant used by adjusting the heat transfer area.

Even if I don't need steam for steady-state operation, I will likely want to supply heat during process start-up. I'll need to devise a start-up procedure and calculate its heat exchange requirements. If the steady-state process also requires steam, I'll need to design the reactor for the more demanding of the two operating modes. I'll assume that any steam used will be saturated, and adjust the heat transfer area to minimize the steam flow rate. I'll assume that only 85% of the steam condenses to provide a margin of error.

#### Discussion

In this assignment, the choice between a CSTR and a PFR was quite easy. The kinetics were such that high product concentration favors a high rate, and the reaction was exothermic, so adiabatic operation would give a high temperature, which also favors a high rate. The choice of a CSTR could be made on the basis of a qualitative analysis without requiring any computational analysis of a PFR.

In [Example -@sec-example_11], the reactor volume was used as the key metric affecting the operating costs for the process. Here the reactor volume was effectively established by the specified production rate, product purity, and maximum temperature. Thus, the coolant and steam flow rates could be used as the key metrics affecting operating costs. Further, if both cooling (during steady-state operation) and heating (during start-up) were required, they could both be minimized because they would not be used simultaneously. The cooling could be minimized for steady-state operation and the heating for start-up.

### Preliminary Design of a Continuous Reactor for an Endothermic Reaction {#sec-example_14_3_2}

**Background**: Z is the monomer used to produce a commodity polymer. Typically Z is produced from A via the endothermic, irreversible dehydrogenation reaction (1). The gas-phase dehydrogenation reaction is second order in A. A company wants to build a process to produce 10,000 tons of Z per year. The feed A will be avialable at 200 °C and 10 atm. The reactor must operate at 98% conversion, and its temperature must be kept below 800 °C.

$$
A \rightarrow Z + H_2 \tag{1}
$$

**Assignment**: Perform a preliminary design of a reactor for use in this process.

#### Design Strategy

The amount of Z to be produced per year is very large, so I'll design a continuous reactor. It is likely that I'll need to heat the reactor whichever type I choose. If I choose a CSTR, it will operate at the outlet composition where the concentration of A will be very small, leading to a low rate of reaction, and therefore requiring a large reactor. Additionally, because the reacting fluid is a gas, it might be challenging to design the agitation so that mixing is perfect. So, it seems clear that I need to use a PFR.

Having chosen the reactor, most of the operational details are fixed. The conversion and outlet flow rates are set by the given process specifications, and knowing the conversion, I can calculate the feed flow rate. I want the reactor to be as small as possible because I expect operating costs to scale with the reactor volume. I could simply design the reactor to operate close to the maximum allowed temperature, leaving an appropriate margin of error.

However, I don't really know whether it is necessary to operate right at the limit. The rate may be sufficiently large at lower temperatures. Clearly there will be a trade-off between reactor volume and heating demand where using less heat will result in a larger volume. I also don't know what the heat exchange fluid is going to be. It might be saturated steam, but depending upon the temperature, a molten salt might be preferred.

For the purposes of this preliminary design, I'll assume that the temperature of the heat exchange fluid will be constant, and I'll create a graph showing the reactor volume as a function of the heat exchange fluid temperature. That may prove helpful for choosing what to use as a heat exchange fluid as the design moves forward. That is, for a given volume it will show the necessary exchange fluid temperature, and that can be used to estimate the associated costs for various heat exchange fluids.

#### Discussion

In this example, the choice of the type of reactor to use was unequivocal. The remaining available specifications were insufficient to go too far with the preliminary design. In situations like this it can be useful to explore the trade-offs between different operating parameters instead of choosing a key metric and minimizing it. In this way, preliminary choices can be made to more fully specify the nature of the system, after which a preliminary optimization can be performed.

For this system, the engineer would really need more details about the metals to be used for the reactor (what temperatures can it withstand, at what temperature might hydrogen embrittlement become an issue) and its compatibility with different heat exchange fluids. A very preliminary calculation of reactor volume versus heat exchange temperature like the one described above can inform decisions about the metallurgy, heat transfer medium, etc. Then a slightly improved preliminary design can be undertaken.

### Preliminary Design of a Continuous Reactor for an Exothermic Reaction {#sec-example_14_3_3}

**Background**: The liquid-phase, exothermic reactions of A and B, equations (1) and (2), are exothermic, irreversible, first order in A and first order in B. D is the desired product because its value is significantly greater than U. The activation energy for reaction (1) is smaller than the activation energy for reaction (2) while their pre-exponential factors are comparable. The kinetics and thermodynamics of the reactions are well-documented.

$$
A + B \rightarrow D + Z \tag{1}
$$

$$
A + B \rightarrow U + Z \tag{2}
$$

**Assignment**: For a proposed process to manufacture D, separate streams of A and B will br available at 30 °C where they will react at a modest rate when combined. The adiabatic temperature rise for the reactions at these feed conditions is approximately 60 °C. Chilled water will also be available at 25 °C. Perform a preliminary design of a continuous reactor for the conversion of A and B.

#### Design Strategy

The assignment doesn't specify a production rate, so I'll choose a feed rate as a basis in my analysis. There are two important performance metrics in this system, the reactor volume and the yield of D. Based upon the information given in the assignment, the reactor could operate adiabatically, but it might be preferrable to cool it because lower temperature will favor the production of D (because the activation energy is smaller).

The choice of reactor is not clear-cut. If a CSTR is used, it will operate at higher temperature and lower reactant concentrations. Those factors have opposing effects upon the reaction rates, and by extension the reactor volume. If a PFR is used, the temperature at the inlet will be smaller, and the concentrations of the reactants will be larger. As the fluid progresses through the reactor, the temperature will rise, tending to increase the rate, while the reactant concentrations will decrease, tending to decrease the rate. Depending upon the conversion, it is possible that the average rate in the PFR will be close to the rate in the CSTR, and consequently, their volumes will be comparable. Because the temperature will vary in the PFR, it also isn't clear which reactor will offer the better selectivity.

Given those uncertainties, it would not be prudent to choose the reactor type without performing any analysis. Instead, I will evaluate both reactor types and, if possible, choose the preferred reactor based upon a comparison of their performance. For either reactor type, I'm also not sure which of the performance metrics is most important, the reactor volume or the yield of D. That is, it might result that when the reactor volume is minimized, the yield of D is very small, or vice versa.

In light of the uncertainties described above, my design strategy for each of the two reactors will be as follows:

1. Choose a range of reactor volumes.
    a. for each volume, maximize the yield of D with respect to the coolant flow rate and heat transfer area.
    b. plot the maximum yield of D as a function of the reactor volume.
2. Choose a range of values of the yield of D.
    a. for each yield of D, minimize the reactor volume with respect to the coolant flow rate and heat transfer area.
    b. plot the minimum reactor volume as a function of the yield of D.

This will generate four graphs, two for the CSTR and two for the PFR. These graphs should make any trade-offs between reactor volume and yield apparent, and they may also show that one of the two reactor types is clearly superior. In any case, these graphs should be useful for refining the the design specifications.

#### Discussion

In this assignment it wasn't possible to select the reactor type on the basis of a qualitative analysis. This is often the case, especially if the reactor is being heated or cooled. It is better to do at least an initial computational analysis of both reactors and use the results to inform future design decisions.
