# Modeling Isolated Ideal Reactors

The first part of *Reaction Engineering Basics* examined reaction rates and rate expressions. It defined reaction rates and noted that rate expressions are equations that give the reaction rate as a function of temperature, pressure and composition. The empirical, theoretical, and mechanistic origins of mathematical forms for rate expressions were presented, and the procedure for assessing the accuracy of a proposed rate expression was detailed. That procedure was shown to involve performing experiments and analyzing the data generated in those experiments.

The analysis of experimental kinetics data requires mathematical models for the reactor used. Consequently, the reactor design equations used to model ideal BSTRs, SBSTRs, CSTRs, and PFRs were presented and common simplifications of those equations were described in @sec-3_design_eqns, and their use to create response functions was presented in @sec-3_response_func. 

The use of response functions in the analysis of kinetics data analysis to estimate rate expression parameters was considered in the preceeding section of *Reaction Engineering Basics*. In the remainder of the book, the focus shifts from reaction kinetics to reaction engineering. This fifth section describes the use of those same reactor design equations and response functions in the analysis of isolated ideal reactors. Here "isolated" means that the analysis considers nothing other than the reactor.

In the chapters of this section, analysis of batch stirred tank reactors (BSTRs), semi-batch stirred tank reactors (SBSTRs), continuous stirred tank reactors (CSTRs) and tubular plug flow reactors (PFRs) is described. For each of those ideal reactor types, three kinds of reaction engineering tasks are considered: reactor response tasks, reactor optimization tasks, and reactor design tasks. In reactor response tasks the reactor input is given and the response is calculated or the response is given and the input needed to elicit that response is calculated. In optimization tasks aspects of the reactor response are minimized or maximized with respect to specified reactor parameters. Design tasks are similar to optimization tasks, but reactor specifications and/or inputs are not provided and must be judiciously chosen.

## Chapters in this Section

@sec-5_response_opt_design Response, Optimization and Design of Reactors

@sec-5_bstr_analysis BSTR Analysis

@sec-5_sbstr_analysis SBSTR Analysis

@sec-5_non_continuous_design Design of Non-continuous Reactors

@sec-5_cstr_analysis CSTR Analysis

@sec-5_pfr_analysis PFR Analysis

@sec-5_continuous_design Design of Continuous Reactors