rule example_23_7_2:
    input:
        "Calculations/example_23_7_2/cum_age_dist_fcn.csv",
        "Calculations/example_23_7_2/results.csv"
        
rule example_23_7_2_data:
    input:
        "Calculations/example_23_7_2/example_23_7_2_data_gen.m"
    output:
        "Calculations/example_23_7_2/cum_age_dist_fcn.csv"
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_23_7_2');example_23_7_2_data_gen;exit"
        """

rule example_23_7_2_matlab:
    input:
        "Calculations/example_23_7_2/cum_age_dist_fcn.csv",
        "Calculations/example_23_7_2/example_23_7_2.m"
    output:
        "Calculations/example_23_7_2/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_23_7_2');example_23_7_2;exit"
        """
