rule example_25_3_2:
    input:
        

rule example_25_3_2_matlab:
    input:
        
    output:
        
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_25_3_2');exit"
        """
