rule example_22_5_1:
    input:
        "Calculations/example_22_5_1/cum_age_dist_fcn.csv",
        "Calculations/example_22_5_1/cum_age_dist_comp.png",
        "Calculations/example_22_5_1/cum_age_dist.png",
        "Calculations/example_22_5_1/response.png",
        "Calculations/example_22_5_1/results.csv"

rule example_22_5_1_matlab:
    input:
        "Calculations/example_22_5_1/example_22_5_1.m",
        "Calculations/example_22_5_1/data.csv",
        "Calculations/example_22_5_1/example_22_5_1_discussion.m"
    output:
        "Calculations/example_22_5_1/cum_age_dist_fcn.csv",
        "Calculations/example_22_5_1/cum_age_dist.png",
        "Calculations/example_22_5_1/response.png",
        "Calculations/example_22_5_1/results.csv",
        "Calculations/example_22_5_1/cum_age_dist_comp.png"
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_22_5_1');example_22_5_1;exit"
        matlab -nodisplay -r "cd('Calculations/example_22_5_1');example_22_5_1_discussion;exit"
        """
