rule example_M_4_1:
    input:
        "Calculations/example_M_4_1/results.png"
        
rule example_M_4_1_calculations:
    input:
        "Calculations/example_M_4_1/example_M_4_1.py"
    output:
        "Calculations/example_M_4_1/results.png"
    shell:
        """
        python3 Calculations/example_M_4_1/example_M_4_1.py
        """
