rule example_25_3_1:
    input:
        

rule example_25_3_1_matlab:
    input:
        
    output:
        
    shell:
        """
        matlab -nodisplay -r "cd('Calculations/example_25_3_1');exit"
        """
